### ISSUE TITLE
[shape] Volunteer program

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1001]
## Acceptance

- [x] Do a shaping on a volunteer program **✅2024-02-21 80% Shaping complete. See https://github.com/life-itself/comms/blob/main/shaping/Volunteers%20Get%20Involved%20program%20v0.1. Follow up #1046**

## Tasks from 2024-01-17

- [x] Get back to volunteer email ✅ _follow up again once below is completed_
  - [x] Write the how to introduce yourself on Github discussion - https://github.com/orgs/life-itself/discussions/1000
    - [x] screenshot the above - walk people through with screengrabs
- [ ] FUTURE: create list of volunteer tasks - this can be part of shaping issue
- [ ] Identify tasks we can hire people to do ⏭️ discuss with Rufus
- [ ] 👉 **🚧2024-02-20 brainstorm and updates captured in this ~~[gdoc](https://docs.google.com/document/d/1FDETuGOJnMynkOMB4vxMA_4NVur_h7S9BM-F5igKSqo/edit?usp=sharing)~~ shaping doc in comms**

**Comment by laurenwigmore** [comment]
@rufuspollock I've invited you to a meeting tomorrow (Wed 21st), and I've created a document with information you might want to review before the call [here](https://docs.google.com/document/d/1FDETuGOJnMynkOMB4vxMA_4NVur_h7S9BM-F5igKSqo/edit?usp=sharing), I've added this link above in the main body as well

**Comment by rufuspollock** [comment]
FIXED.
