### ISSUE TITLE
Ordinary People podcast: publish Simon Longstaff

### ISSUE THREAD

**Issue by shiweiart** [life-itself/community#1002]
_Update_ : to be completed by 8th February 4pm CET (via upworker task) - [Page link](https://lifeitself.org/podcast/simon-longstaff-ordinary-people)

### Tasks
- [ ] Add a draft title or issue reference here

Conversation published on Youtube & Anchor.
- [x]  Episode page added to the website. 🚧 2024-02-13 drafted awaiting YouTube video and SRC to publish - SRC takes up to 24hours to be available_
- [ ]  Guest informed that the episode is out and has been sent the links. Sylvie actioning
- [ ]  The new episode has been announced on Twitter. @moonimmisch
- [ ]   Email announcing a new episode has been sent to mailing list. _wiil add in to #1033_ 

**Tasks:**

- [x] edit the video
- [x] upload video from zoom to youtube 🚧 _will ask the upworker to complete the amends to the video as per Sylvie's feedback and upload directly to our YouTube channel_ ❌ _uploaded as per upworkers original edit_
- [x] create canvas template
- [ ] create jingle
- [x]  write short summary about this specific podcast and simon
- [x]  upload on spotify

**Comment by moonimmisch** [comment]
@shiweiart would you like me to takeover some of these tasks? :)

**Comment by shiweiart** [comment]
BLURB: Dr Simon Longstaff is the  Executive Director of The Ethics Centre, co-founder of the Festival of Dangerous Ideas, and has been named one of the True Leaders of the 21st century by Australian Financial Review BOSS magazine.  He shares with us his journey into ethics, from the choice of his mother between the life of her child and her own, his path of working as a cleaner, to studying the law, to the influence the aboriginal people had on his life to his work of strengthening Australia’s ethical infrastructure.
