### ISSUE TITLE
[Shape] Weekly Community Hangout Planning

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1003]
We want to have a space where our community can hang out together regularly, have conversations around things that matter (to us and the community), create conscious connections, nurture existing members and give new members a place to join that is more active than the whatsapp chat and the community calls (which are more Q&A/sharing on a specific topic). 

The idea is to create a weekly(or biweekly) community hangout online.

https://github.com/orgs/life-itself/discussions/1039 - discussion topic related to the Hangouts themes and any key insights or points.

## Acceptance
- [x] First community hangout is scheduled ✅ _Thursday 8th Feb 5pm CET_
- [x] First community hangout has been announced in the whatsapp chats (general & event)
- [x] First Community hangout takes place

## Task
- [x] Decide on if these will take place weekly or biweekly _will trial weekly in February with a break on the weeks we have a community call - idea is to have one community call a month_
- [x] Decide on the day and time
- [x] Decide on the first theme for the call
- [x] Announce the calls in the newsletter
- [x] Announce the calls in the whatsapp chats
- [x] Announce on IG
- [x] Announce on linkedin 
- [ ] Announce on twitter
- [x] Set up first call - link
- [x] Add calls and links into the LI events calendar: Community Hangout Video call link: https://meet.google.com/xeq-tttq-yjp

## Notes
- Aim: for this to become self managing i.e. Lauren doesn't always need to be present, they could still happen once established enough without a LI member
- We would supply the link, and 'advertise' it to the community
- It should be low investment in terms of resources - time, energy/management

- Pro for weekly: it is consistent: everyone knows it is at DAY/TIME
- Con for weekly: people become complacent when something is always available 
- We could align some topics of conversation around the theme(s) from the research group 
- Good days for hangouts: Wednesdays or Thursdays, but Friday could add a bit of variety
- Cons for a Friday: LI hosts the research call and the core meeting on a Friday - we could all get a bit 'meeting'ed out'. Those who work more tradition M-f working weeks will often end their days earlier on a Friday for the weekend or take the day off.
- Cons for a Wednesday: most popular day for online events - so likely come competition
- Cons for Thursday: Attendance at Community Calls isn't that great - is this the lack of interest or the day/time?
- Time wise: hosting at a time where Rufus and Sylvie (and Hub members) could also join would be best suggested 4pm CET

### Promo Blurbs
- use in whatsapp, linkedin, IG, (condense for twitter)

**Calling all those seeking more connection with fellow Life Itself community member!**

Ready to deepen your sense of belonging, connect, chat, and make new friends? Join us for our brand new online community hangout happening every Thursday at 5pm CET!

This is your chance to:

Mingle and make friends: Expand your social circle and connect with like-minded community members from diverse backgrounds.
Engage in stimulating conversations: Each week we will discuss interesting topics, share our stories, successes and passions, and learn from each other's perspectives.
Build a sense of belonging: Actively be a part of a welcoming and supportive community where you feel valued and heard.
Have fun: Enjoy a relaxed and enjoyable atmosphere.

Everyone is welcome!

Here's what you need to know:

When: Thursdays at 5pm CET (time zone converter: https://www.worldtimebuddy.com/)
Where: Online via Googlemeets: https://meet.google.com/xeq-tttq-yjp
Who: You and other amazing community members!

How does this differ from the Community Calls? The Community Hangout is an informal opportunity for us to get together and have a chat. No-one is leading the dialogue or presenting as with the Community Calls. The Hangout is like gathering around the bonfire, or grabbing a coffee off the cuff. We invite you to come regularly and simply as you are.

Don't miss out on this exciting opportunity to connect, have fun, and be part of something special! ✨

Spread the word and invite your friends!

See you there!

P.S. Add this to your calendar here: https://calendar.google.com/calendar/event?action=TEMPLATE&tmeid=N21vbXMwaDBoMm5wanYwdmg5bzFrY2p0N25fMjAyNDAyMDhUMTYwMDAwWiBjX2QwNjQ2M2JjOGJmZThhZWU2MjU5OTIxMGY0MjdjMzE3NjRiOGQyMWViZGFlZjkwOGU1MGEwZjJlYTRhMzU4NWVAZw&tmsrc=c_d06463bc8bfe8aee62599210f427c31764b8d21ebdaef908e50a0f2ea4a3585e%40group.calendar.google.com&scp=ALL

**Comment by laurenwigmore** [comment]
FIXED. First hangout took place, subsequent 2 in progress. https://github.com/orgs/life-itself/discussions/1039 - as a tracker of themes.
