### ISSUE TITLE
[Shape] Life Itself Brand Style Conversation with Sylvie

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1005]
To ensure consistency of brand, Lauren will have a conversation with Sylvie to align design and brand elements moving forward for 2024.

Intention: Clear understanding of the branding of LI, the document to refer to and what to use / when

## Acceptance
- [x] Call completed between Lauren and Sylvie
- [ ] Reference document / update to Tao created for everyone to refer to as needed
- [ ] Announced to team (in strategy meeting w/c 22nd?)

## Tasks
- [x] Lauren to arrange call with Sylvie
- [x] Call completed
- [x] Clear points to include in the 2024 brand document agreed on ✅ [_document containing notes and to-dos_](https://docs.google.com/document/d/1Uo266gfC2FwADhjgxJ0hLzg3CvVYmdNxZT5lfEI48c8/edit)
- [ ] Appropriate document update (i.e. Life Itself Design System)
- [ ] Tao updated
- [x] Discussion on whether items already live should be amended ❌ _no_
  - [ ] If so which ones
  - [ ] List created
  - [ ] Issue created to action these  

**Sylvie** @shiweiart 
- [ ] Examine what is working and not working in the current design branding
  - [ ] Review typography
  - [ ] Review natural form and look for other shapes/forms that can be used to punctuate 
  - [ ] Create different strength of the lines for the grid so it’s stronger and in colors of black, white and yellow
  - [ ] Arrange another meeting with S+L for 2 weeks (2nd Feb)

**Comment by laurenwigmore** [comment]
@shiweiart just detailing a note here for the deadline for you to look at the typography: Tues 30th January

**Comment by rufuspollock** [comment]
WONTFIX. Not important for now and we can leave.
