### ISSUE TITLE
January 2024 Newsletter

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1024]
## Acceptance
 - [x] Newsletter is sent _✅ scheduled to go out 10am CET Monday 5th Feb_
## Tasks
- [x] Write newsletter in Brevo
- [x] Info from Hub/Residencies received and included
- [x] Tenzo note published
- [x] Test Newsletter
- [x] Newsletter is scheduled

## Notes of items to include
- [x] Community call #947 
- [x] New community hangouts
- [x] Conflict course
- [x] study group
- [x] 2R course pilot group - want to be part of the new group?
- [ ] Team member announcements?

### Reference
Lauren, we could focus the newsletter on fewer things. 

1. Extension of open residency at hub until may. Might be nice to feature a picture of a current or recent  resident or two with short bio. 

2. Second renaissance page - may want some polishing still.

Would be nice to have some people sign up to the course ...

3. Advertising the drop in opportunities on Thursday (assuming we go with that time.)

4. Advertising the gathering.

(Now got to more than two!)

**Comment by laurenwigmore** [comment]
FIXED. Newsletter scheduled and included all 4 suggestions in Reference.
