### ISSUE TITLE
Scholars Videos Release - w/c 2nd Sept 2024

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1026]
Shaping related to #790  

Scholars videos are available, which have yet to be released or announced. We are now 5 months after the date of filming.

## Acceptance
- [x] Video series is live on YouTube
- [x] Video series has been promoted to community
- [x] Video series has been shared with all the scholars 

## Tasks
- [x] Meeting with Rufus
- [x] Decide on key message of this series: unveiling the wisdom of the second renaissace: a contemplative interview series
- [x] Copy for each person/video added to YouTube [use summary descriptions provided
- [ ]  from John](https://docs.google.com/document/d/13E1_moe2EHwUPMDOXVzbnNwiVekbaWJKqz99e6gcga4/edit#heading=h.rahy0acc2jg4)
  - [x] Condensed version added to Substack announcement 
- [x] Write promotional text for webpage ✅ _draft below_
- [x] YouTube checklist met for each video and playlist series
- [x] Have a landing page/webpage for videos 🚧 _draft on substack_
- [x] Embed videos 🚧 _once live on Youtube_
- [ ] Announce in newsletter
- [x] Announce on socials
  - [x] IG
  - [x] X
  - [x] LinkedIn
  - [x] Whatsapp channels 
  - [x] FB

# Website copy draft

Title of series: Unveiling the Wisdom of the Second Renaissance: A Contemplative Interview Series 

Embark on a profound journey with us as we delve into the contemplative insights and wisdom of seven influential thought leaders: Francios Demange, Gregg Henriques, John Vervaeke, Nicholas Janni, Rainer v Leopretching, Ria Baeck, and Thomas Steininger.

Join us on our Contemplative Interview series as we explore the minds of these intellectual architects working towards a unique and transformative cultural movement, dedicated to addressing the challenges of the Second Renaissance. Captured during the Elder Gathering at the Praxis Hub in Bergerac, France from August 7th to September 3rd, 2023, this series presents their profound reflections and insights.

This 13 video series invites you to embark on a voyage of discovery, enquiry and reflection as you immerse yourself in the wisdom and vision of these seven renowned thought leaders.

A brief note on each leader:

1. Francios Demange: Renowned philosopher and visionary thinker, exploring the intersections of consciousness and societal transformation.
2. Gregg Henriques: Psychologist and author pioneering integrative approaches to psychology, bridging science and spirituality.
3. John Vervaeke: Cognitive scientist and professor delving into the depths of meaning, wisdom, and the nature of human cognition.
4. Nicholas Janni: Leadership coach and embodiment expert, guiding individuals and organizations toward authentic and embodied leadership.
5. Rainer v Leopretching: Philosopher and futurist, shaping narratives on the future of technology, ethics, and humanity.
6. Ria Baeck: Facilitator and systems thinker, facilitating transformative dialogues and fostering collective intelligence.
7. Thomas Steininger: Scholar and practitioner of integral philosophy, exploring the evolution of consciousness and its implications for society.

### Meeting notes 2024-03-26 

Present: John, Rufus, Lauren

- [ ] Everyone filmed has been edited
- [ ] Action - copy over LI members
  - [ ] Don't publish Marc's for now
- [ ] Scholarchs notes as good to open with - 
  - [ ] Gregg - straight in to his UTOK theme - strong on formal content, less personal
  - [ ] Thomas - had both personal and formal work of last 10 years in dialogue
  - [ ] Ria - personal story of her immediate experience of the weeks retreat
- [ ] John could give us bullets for each conversation as an overview of what they spoke about
- [ ] Rufus - want all videos up, maybe with a highlight reel of the elders in silence/portraits
  - [ ] If release in sequence would need info to decide sequencing and for promo (fixed with bullets)
- [ ] Boaz and Liam greenlight to go out
  - [ ] John followed up directly to see if they wanted more edits done for individual personal project/use
  - [ ] Minor edits done to all videos
- [ ] John's reflections on opening sequence: John, Gregg, then Nicholas 
- [ ] Subtitles (srt) - depends what platform this will be published on
- [ ] Need to give John correct logo for future ✅ 
- [ ] For future introductions at the beginning (e.g. with John V) of the video - we would like to write the copy. 
  - [ ] Happy to do smaller edits for introductions but likely over a few weeks.
  - [ ] Rufus to confirm if needed after speaking with Sylvie
- [ ] John away w/c 1st April
- [ ] Aim for 2nd half of April to release
  - [ ] to add filmed by John Oliver
  - [ ] John active on LindedIn and can help share
- [ ] All scholarchs consented to the release

**Actions**
- [x] Add an entry in the content log (clog 👞!)
- [x] Review existing issues
  - [x] Epic: https://github.com/life-itself/community/issues/790 **✅2024-03-26 updated. This will be our MASTER/MISTRESS issue**
  - [x] Other one about published **✅2024-03-26 DELETE and merged with epic**
- [x] Publish one video on YouTube - Unlisted video on YouTube - https://www.youtube.com/watch?v=6wW1hvUgpog
- [x] John to jot down a few bullet points on each video [doc](https://docs.google.com/document/d/13E1_moe2EHwUPMDOXVzbnNwiVekbaWJKqz99e6gcga4/edit#heading=h.fgg68kt80mcd)
- [x] John to include emails for each Scholarch with the bullet points
- [ ] Descript to write a 3 sentence summary for each as well
- [ ] Lauren to copy over the other lightly edited videos from John of the LI members
- [x] Lauren to send John the correct logo for future use (and brand doc?) ✅ _sent_
- [ ] John to share the Descript link to John V for us to see what features we have access to

## Inbox

- [ ] What about B&W, srt and thumbnails etc ... that John Oliver has in his raw folders but we don't ...
- [ ] https://www.interiortruth.com/lifeitself - can we get links to Life Itself and Bergerac Hub 😉
  - [ ] Fix logo
  - [ ] Can we have them in one place e.g. life itself youtube etc?
- [ ] John Oliver folder of color edits: https://drive.google.com/drive/folders/1rN7o8DTDvsHt-mxYu2FUOVwlmKBiFNhj 🚩 can remove now (we have copies)

**Comment by laurenwigmore** [comment]
Update: This is in progress and I will look to release the first week of September

**Comment by laurenwigmore** [comment]
Update:

- Substack post completed and all videos on YouTube with descriptions.
- Updating best video to link to at end of each to be completed once live.
- Touching base with John re if we can tie promo together into his next/current project.
- Socials still to be done.

**Comment by laurenwigmore** [comment]
FIXED! Released 2024-09-10. To be announced in September newsletter.
