### ISSUE TITLE
Automate archiving of zoom to drive (improvements to Comms workflows Jan 2024)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1029]
Standardize and automate zoom content: we want every zoom recording auto-archived in a standard locations

### Tasks
- [x] Enable audio transcription for zoom calls automatically so we don't have to do this separately https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0064927 **✅2025-02-12 believe this is done**
- [x] Create standard folder for zoom raw content **✅2024-01-31 https://drive.google.com/drive/folders/166EM0QDS8b_JbTVih_Yl8_vY85eSN8VD**
- [ ] Research if we can automate this **🚧2024-01-31 see section in notes** **💬2025-02-12 this video with make.com (like zapier) shows this is definitely possible https://www.youtube.com/watch?v=mBk4g2O7ZGM**
- [ ] Automate this if possible

### Automation options to transfer zoom recordings to gdrive

- Zapier - https://zapier.com/blog/upload-zoom-recordings-google-drive/ (can upload and also send an email notification to team)
- Bardeen - https://www.bardeen.ai/playbooks/upload-zoom-recording-to-drive
- zBackup.app - https://marketplace.zoom.us/apps/hmLqgaSsSxGxzRMKIkt4aw
- Splain.io - Rufus tried this in past (not sure this is working anymore)

### What can we use for collecting analytics

- https://funnel.io - Free plan. But only 3 sources. $X per month for Y. TODO

**Comment by laurenwigmore** [comment]
Video recommends Make - https://www.make.com - $9 pcm for simple, lowest plan
NTS: Aaron Delz YT - multiple tutorials on using Make for automations
- zoom automated download only available within 24hrs of recording and needs approval to start automation process

**Comment by rufuspollock** [comment]
WONTFIX. For now we continue by hand.

**Comment by rufuspollock** [comment]
@seankessinger check this out

Also see https://comparethe.co/Workflow+Automation for list of tools. BTW a 🏆 bonus item on this task is to update that comparethe with more info from real experience.

**Comment by seankessinger** [comment]
**Shaping: Zoom → Google Drive Automation Research**
https://docs.google.com/document/d/1hAdt0gLCi43p_kJFYDt7Fwk-UApJSM5hs04hZgMSJ9U/edit?usp=sharing
