### ISSUE TITLE
Intro to Second Renaissance v2 - better produced

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1030]
## Redesign 2nd renaissance

- Say the motivation early i.e. first episode
- Have personal shares each episode ... (maybe start with that ...)
- Have vivid shares e.g. the duel story

https://link.excalidraw.com/l/9u8crB2ZmUo/3aqZa7eLIIT

## Tasks

- [ ] write out current sequence as a big bullet list or mermaid diagram
  - [x] Choose bullet list or mermaid diagram **✅2024-02-01 bullet list as easier to start with**
  - [x] Find current sequence sources **✅2024-02-01 first episodes e.g. 1-3 were in the google doc, plus slides. Then for last episodes we ad-libbed more**
    - [x] What are the raw sources? **✅2024-02-01 a) https://link.excalidraw.com/l/9u8crB2ZmUo/3aqZa7eLIIT with its overview b) [gdoc course draft][xxx] c) live recordings for last 1-2 episodes**
- [ ] ...

[xxx]: https://docs.google.com/document/d/1roBFoP2o7li3Rn3fDyLICHFc_HrjCpDw1s7HjAo67U4/edit
