### ISSUE TITLE
February 2024 Newsletter

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1033]
## Acceptance
 - [x] Newsletter is sent
  
## Tasks
- [x] Write newsletter in Brevo
- [x] Info from Hub/Residencies received and included
- [x] Tenzo note published
- [x] Test Newsletter
- [x] Newsletter is scheduled

## Notes of items to include
- [x] Community call update #947 
- [x] Next community call - #1038 
- [x] Promo of #1035 
- [x] Next community hangouts - now changed to Community Get Involved
- [x] #1002 
- [x] Sylvie's call out for a Graphic Designer - notes in google doc
- [x] Hub call out for 2 positions - Ops Manager x2
- [x] research report announcement https://github.com/life-itself/labs/issues/222#issuecomment-1968596731
- [x] watch this space - up and coming talk at Limicon

### Reference

**Comment by laurenwigmore** [comment]
FIXED. Scheduled for 1130am 2024-03-05.
