### ISSUE TITLE
Hub Comms Status Update Feb 2024 and Last Actions for Alexia

### ISSUE THREAD

**Issue by alexianetcu** [life-itself/community#1034]
Meeting Notes: 

# 2024-02-06 - Alexia and Lauren Debrief and Connect

- [x] Intention: debrief on the position of the Hubs comms status to allow for a fluid transition on Alexia's departure for us (Lauren and comms team) to move forward clearly 

## Part I Briefing

- [x] update on hub-related comms
  - New list of potential places to advertise residencies moving forward https://docs.google.com/spreadsheets/d/1EKnEgJ5PjfVUiFEOb6nE6vZ9NyPEsA5Ov_vT4gDbK1g/edit#gid=207124184 
  - Total of 3 video testimonies - link to folder: https://drive.google.com/drive/folders/1TSdynu0BwOPdbbDdrmUjH0z6Xb0kZdx5
  - use of post-residency questionnaire for written testimonies 
    - what is sent: https://forms.gle/6vApeLvcjaVYohFp6
    - to view answers: https://docs.google.com/forms/d/1sGoD4F_wCFCDBypo5EsWHihVOlj5DaM39-dO-MTnFwI/edit#response=ACYDBNhfHAH4ZIS5H9UJJZgilgtp4iPjr7LqaEhas8ek7APVnrcmrezPf4nRrSdP_8KUFWI
    - Total of 20
- [x] handbook for passing on info **notes for Alexia to include below**
  - intention: 1. clear on where we are at and 2. useful info to support onboarding of next guardian
  - current strategy situation and context
  - include links to past conversations
  - reflections with hind-sight
  - roles and responsibilities 
- [x] Previous issue resulting from a conversation with Nathen related to Hub Comms https://github.com/life-itself/barbacane/issues/112

### Summary of current comms in place

- Only comms being done for the Hub at present is advertising in the newsletter, and WhatsApp groups occasionally
- Website updates
- Process for participants interested in joining the Hub: interview with Valerie (unsure of what is shared exactly related to expectations and T&Cs shared)
- Post-questionnaire sent

## Notes

 - The effectiveness of posting in groups on social media was raised. This should not be the only relied upon way of advertising.
 - Issue life-itself/barbacane#112 - the outcome of the conversation around this issue is related to the strategy of the Hub needing to be defined before any action taken
    - 2024-02-06 no action taken. Hub Comms Shaping would have created concrete actions but with Alexia's decision to leave this has not been done yet
 - Testimonies were not completed because of a feeling of a lack of clarity over whether this was needed, and a lack of self-agency to do. Felt overwhelmed with all the task types.
   - Not clearly defined as a SHOULD DO
   - And no clear understanding of their use and how they would be used
   - Felt more comfortable/useful using feedback questionnaire - as a qualitative capture to use more widely in i.e. grants etc., and quotes used in newsletter but not more widely than this
 - ⏭️ Stating the use of a feedback form and request for simple video testimonies should be added clearly to the initial/welcome conversation of each participant into the space (to avoid a sense of feeling like you are 'burdening' participants at the end)

### Actions

- [x] Alexia to add all the testimonies to the Residencies Video Testimonies folder - clearly labelled by Name and Month Year i.e. Rob Hardy February 2024 https://drive.google.com/drive/folders/1TSdynu0BwOPdbbDdrmUjH0z6Xb0kZdx5
- [x] Bergerac Hub folder to be tidied to be better labelled https://drive.google.com/drive/folders/1G50zAmtVsAN8UneLjYxIiAckUb_zvLq5 
- [ ] Put update on comms startegy issues https://github.com/life-itself/barbacane/issues/112 

## Part II Connect

- [ ] Brainstorm on how things could go re hub comms from now on **:fast_forward: Alexia's thoughts added into Handover document clearly labelled**
  - [x] Lauren to gain understanding of the Hub situation more widely and how it relates to Comms team
  - [x] Alexia to be confident with how to write handover document and what to include
- [x] Update from Alexia's on her next personal steps

**Comment by laurenwigmore** [comment]
Hi @alexianetcu just touching base to see where you are at with things?

**Comment by laurenwigmore** [comment]
FIXED.
