### ISSUE TITLE
Promotion for Relational Embodiment Residency June 2024

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1035]
[2-WEEK RELATIONAL EMBODIMENT RESIDENCY](https://neurosystemics.org/simple-event/relational-embodiment-residency/) taking place in J16-30 June 2024.

Agreed actions from on the meeting with Boaz and Lauren on 2024-02-06

## Acceptance
- [x] Community Call hosted
- [x] Newsletter sent in February _scheduled for 5pm CET 2024-02-19_
- [x] LI residency page for event live

## Tasks
- [x] Information and Google form sent to Boaz regarding the Community Call
- [x] Issue set up for Community Call #1038 
- [x] A short addition to the Feb and March newsletters to promote the free 4 week online training 
  - [x] Added to February and March newsletter issues
- [x] A separate focused newsletter announcement to go out to LI members
- [x] Event added to LI residency page (as with previous residencies) **To do w/c 18th March**
- [ ] Promote on LinkedIn and tag Boaz
- [ ] Promote on IG and tag @ NeuroSystemics_care 
- [x] Boaz to draft special announcement newsletter
  - [x] Lauren to send previous example to Boaz for reference

NB - Boaz asked to create the posts for us to share on social media

### Notes

- previous residency in 2023
- Marc did a lot of word of mouth promo in 2023
- This years structure: 4 weeks online (1 meeting per week), 2 week in-person at Hub, 2 weeks online (1 meeting per week)
- A number of attendees already coming from Boaz's network, from a number of countries
- Currently the only external person organizing a residency
	- proto-trustees likely to extend the long-term hub residency across summer period
	- individuals who stay in the Hub could therefore either attend the event or not
	- people attending the event could stay externally
- Minimum 6 people per group, min. of 2 groups ideally more
- importance to promote and attract people
- Boaz's IG account has a large following and so will repost LI content related to the event

**Comment by laurenwigmore** [comment]
FIXED. Main agreed promotional actions done.
