### ISSUE TITLE
Community Call: Boaz Feldman 28/03/2024

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1038]
Boaz Feldman | 28/03/2024 | 630pm CET | Multi-Level Resilience

## Acceptance

- [x] Community call hosted and recorded 
- [x] Uploaded to Youtube and blog post 

## Tasks

Pre-event

- [x] Confirm speaker
- [x] Confirm details with google form https://forms.gle/gfZfKEATSmusp5AW7
- [x] Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [x] Create Canva graphic using template 
- [x] Create registration using Zoom - https://us02web.zoom.us/meeting/register/tZEkd-6grzkrH91zE6A2X2h-h9Oe24tHB6oI
- [x] [Create the blog post](lifeitself.org/blog/practicing-flexibility-in-deliberately-developmental-spaces) 
  - [x] Include image, registration link, biography of speaker or description of the event
- [ ] Promotion
  - [ ] Emails
    - [x] Initial announcement (main group) on if newsletter was more than a week ago 
    - [ ] Day before announcement (main group) only if initial announcement was more than a week ago
    - [ ] Email reminder (recipients)
    - [ ] Plus in newsletter (if applicable)
  - [ ] Whatsapp
    - [x] Initial announcement
    - [ ] 3 days before
    - [ ] Day before
    - [ ] 1-2 hours 
  - [ ] Twitter
    - [ ] Thread for initial announcement
    - [ ] 3 days
    - [ ] Day before
  - [ ] Instagram
    - [ ]  Stories
      - [ ] Story template or resharing post
      - [ ] Initial
      - [ ] 3 days before
      - [ ] Day before
  - [ ] Post for initial announcement 
  - [ ] Linkedin Event created 

### Post-event

- [x] Make the youtube video
- [x] Update original blog post with youtube video plus information 
- [x]  Title: Should include name of person, plus keywords/topic
- [x] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [x] Copy of zoom recording [saved here in Raw Content log
- [x] Update CRM with links etc. 
- [x] Let the speaker know and make it easily shareable 

### Socials text

Thursday 28th March 630pm CET is the date for our March community call: Multi-level resilience with Boaz Feldman.
This call is a teaser, ahead of the up and upcoming residency Boaz is leading in June 16-30 at the Bergerac Hub

As multi-dimensional beings, it takes an ecology of practices to build resiliency in the face of all the different ways we suffer. In this community call Boaz will be collectively exploring a multi-level resiliency-building approach that is practiced at NeuroSystemics, a somatically and relationally-centred clinical method for trauma healing.

In particular, he will guide participants through some self-regulation, co-regulation and perspectival abilities that will help us to be more embodied and more present in relationships.

Sign up for the call via our website.
---
Twitter

📢Register now for our March Community Call!

Thurs 28th March 630pm CET 
@ ?? / Ahead of the June Relational Embodiment residency at the Bergerac Hub, Boaz Feldman will be sharing practices to build multi-level resilience against all the ways we can suffer in today's world. 

Register here: https://bit.ly/3Tn2NnB

Read more 👇 (add on residency)

**Comment by laurenwigmore** [comment]
FIXED.
