### ISSUE TITLE
Podcast Downloads

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1042]
Spotify for podcasters is changing its set up and after June 2024 our uploaded episodes and jingles will not be available to access, combine or download as needed. This will need to be done via Riverside.

# Acceptance
- [ ] All required jingles and edited episodes downloaded

# Tasks
- [ ] Check if we have the audio files in our Gdrive (original or edited)
- [ ] Download the 2x intro jingles
  - [ ] Ordinary People
  - [ ] General Podcast
- [ ] Download other episodes
- [ ] Set up Riverside account
