### ISSUE TITLE
Implement shaped proposal 202401: Presenting our Strategy

### ISSUE THREAD

**Issue by elisapaka** [life-itself/community#1048]
An issue for implementing the shaped proposal 202401 "[Presenting our Strategy](https://github.com/life-itself/comms/blob/main/pitch/2401%20Presenting%20our%20Strategy%20v3%20in%20its%20current%20form.md)". 

## Summary of shaped proposal

- Appetite: 3d (reduced by 1d given we spent 1.5d in shaping and work we did in shaping will help)
- Problem: lot of strategy-related materials but they aren't woven together or consolidated which creates a sense of overwhelm and confusion and prevents them being published and used.
- Solution: inventory materials, create framework to organize them, create roadmap for publication. If we can, start on consolidated strategy.

## Acceptance

- [x] A complete inventory of existing materials related to Life Itself strategy (V2 and V3) in the strategy repo **✅2024-02-23 this got complete.**
- [x] A framework for organising materials **✅2024-02-25 we kind of have that in the structure**
- [x] Most important materials are organised according to the framework in a visual map or similar **✅2024-02-25 have that in excalidraw image**
- [ ] A roadmap for publishing the consolidated strategy (e.g. in the form of a DAG of recommended outputs with estimates)
- [ ] Bonus: Sketch of long-form consolidated v3 strategy
- [ ] Bonus: Consolidated v2 strategy

## Tasks

- [x] Complete the inventory of strategy materials in the Strategy repo **🚧 2024-02-23 90% complete**
  - [x] Add all materials in the excalidraw (https://app.excalidraw.com/l/9u8crB2ZmUo/3EkbCxN8qBi) to the `strategy/materials` vault **✅ 2024-02-22 See here for complete list: https://github.com/life-itself/strategy/tree/main/materials**
  - [x] Create Dataview layout
  - [x] After 1-2 entries, assess what frontmatter/metadata to add **Proposal for frontmatter properties to include (in no particular order): https://github.com/life-itself/strategy/blob/main/Framework.md**
  - [ ]  Add all materials from list "Oct 2021 Consolidated List of Materials"
  - [ ] Go through strategy folder on drive and check for anything we may have missed https://drive.google.com/drive/folders/1Vf3yL9xSgbaMSJ5bxpCfXqPG7Bq6-36a
- [ ] Develop framework for organising the most important materials
- [ ] Organise materials in inventory according to the framework
- [ ] Create a roadmap for publishing the consolidated strategy

### Misc

- [x] Have we included the brand documents **Yes - we have brand narrative 2020, and brand narrative 2022)**
- [x] More generally have we gone through entire strategy v3 folder in drive and processed everything (either decided it's worthy of inclusion or not - probably worth having that checklist somewhere with brief notes either way e.g. Inbox page in strategy repo or similar. BONUS: deleting / archiving / deprecating stuff in that folder)
  - [x] Is this (+going through everything in drive) crossing into a rabbit hole of looking for materials we ever produced on this? **this isn't everything, just that specific folder**
- [x] Strategy wiki: what is the 'Oct 2021 Consolidated List of Materials'? **✅2024-02-27 explained this.**
  - [x] What do the 3rd and 4th columns represent? **Hypothesis: 4th column is notes - 3rd column I don't have a guess for!**
- [x] What is "Multiple why levels issue 36 Sep 2021"?
