### ISSUE TITLE
Publish Karl + Rufus DDS 2023-12-21 Q&A video

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1051]
## Acceptance

- [x] Live on youtube
- [ ] Advertised on ...
  - [ ] conscious coliving
  - [ ] ...

## Tasks

- [x] Download from zoom and archive in drive
- [x] Upload full video recording to YouTube 🚧 _Upworker will be posting the version completed as a task onto our account by 2024-03.01_
- [ ] Chop off first 1 min 10 seconds or so of video recording (Rufus waffles).
- [x] Add timestamps in video description for each question segment.
- [ ] Tag zettelkasten atom for this item for potential future splitting
- [ ] Where to share?
   - [ ] LI Conscious Coliving whatsapp
     
Maybe

- [x] ? Get transcript of video recording

[Folder with items](https://drive.google.com/drive/folders/1lkPBE4tQAgvXRkPyWvOxze8BEnHJl7oI)

**Comment by laurenwigmore** [comment]
FIXED. Published - https://www.youtube.com/channel/UCmBq3VO9w_MLTKD_CHsYN-Q
Shared in Whatsapp and Feb newsletter.
