### ISSUE TITLE
Contemplative Activism book (what happened)

### ISSUE THREAD

**Issue by theo-cox** [life-itself/community#1052]
Liam and Valerie were contributing to a contemplative activism book in Aut 2021. What happened to this? Are there outputs (even from Liam and Valerie) that we can share?

## Acceptance

- [ ] Blog post about contemplative activism book idea and/or outputs
- [ ] Outputs posted on blog / site connected with collective activism initiative

## Tasks

- [x] Find out from Liam and Valerie what happened ✅ **2 areas to explore: [the CA pieces and arts](https://drive.google.com/drive/folders/1xjHIDRrXL9OzELJCsjFHM51Sz0ENrYoL?usp=sharing) and [The residency testimonials](https://drive.google.com/drive/folders/1fUSX1mNOLf1uRu85lwQB6DVnklm81bCK?usp=share_link)**
- [ ] Look through material sent my Valerie and see what we can share

**Comment by rufuspollock** [comment]
Short answer i think is that nothing ultimately happened. No book was produced.
