### ISSUE TITLE
Community Call: Danielle Johnson 15/04/2024 9pm CET

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1061]
Danielle Johnson | 15/04/24 | 9pm CET | From Field Study to Limicon 2024

## Acceptance

- [x] Community call hosted and recorded 
- [x] Uploaded to Youtube and blog post 

## Tasks

Pre-event

- [x] Confirm speaker
- [x] Confirm details with google form https://forms.gle/gfZfKEATSmusp5AW7
- [x] Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [x] Create Canva graphic using template 
- [x] Create registration using Zoom - https://us02web.zoom.us/meeting/register/tZIlcumgqDgpHNCJXkgrbVZLcZyMjEaqBskc
- [x] [Create the blog post](lifeitself.org/blog/practicing-flexibility-in-deliberately-developmental-spaces) 🚧 _awaiting different image_ ❌ _none available_
  - [ ] Include image, registration link, biography of speaker or description of the event
- [ ] Promotion
  - [ ] Emails
    - [ ] Initial announcement (main group) on if newsletter was more than a week ago 
    - [ ] Day before announcement (main group) only if initial announcement was more than a week ago
    - [ ] Email reminder (recipients)
    - [ ] Plus in newsletter (if applicable)
  - [ ] Whatsapp
    - [x] Initial announcement
    - [ ] 3 days before
    - [ ] Day before
    - [ ] 1-2 hours 
  - [ ] Twitter
    - [x] Thread for initial announcement
    - [ ] 3 days
    - [ ] Day before
  - [ ] Instagram
    - [ ]  Stories
      - [x] Story template or resharing post
      - [x] Initial
      - [ ] 3 days before
      - [ ] Day before
  - [ ] Post for initial announcement 
  - [ ] Linkedin Event created 

### Post-event

- [x] Make the youtube video
- [x] Update original blog post with youtube video plus information 
- [x]  Title: Should include name of person, plus keywords/topic
- [x] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [ ] Copy of zoom recording [saved here in its own folder](https://drive.google.com/drive/folders/1cKyu2A4FjTKMk-5YOuqhFpu9Er6o2jy4)
- [x] Update CRM with links etc. 
- [x] Let the speaker know and make it easily shareable 

### Socials Text
**IG**
Danielle Johnson, PhD is a generalist currently working in the liminal web ecosystem.

In a series of essays framing the Emerge Austin 2022 conference, Jonathan Rowson, put forth a rousing call to action: Let's build a field. This idea ignited a passion within Danielle which prompted her to begin working on a study of the field. That work brought up the question: Who is in this field? As a way to find answers, Danielle volunteered to take the lead on organizing Limicon 2024 (https://www.limicon2024.com/); a field nurturing, online event, that took place across March 2024.

In this call, Danielle will share a little about her journey, some insights she gained along the way, how Limicon 2024 fits into this work, and how she might further collaborate on the project with the Life Itself community.

Sign up for the call via our website.

**Twitter**
Register now for our next Community Call 

Monday 15th April 9pm CET with Danielle Johnson

From Field Study to Limicon 2024
Danielle will share her journey, insights gained along the way, how Limicon 2024 fits into this work and future collaborations related to liminal space ecosystems.

Register here 👉 https://bit.ly/3PSRtPp

**Comment by laurenwigmore** [comment]
FIXED.
