### ISSUE TITLE
March 2024 Newsletter

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1062]
## Acceptance
 - [ ] Newsletter is sent
  
## Tasks
- [x] Write newsletter in Brevo
- [x] Info from Hub/Residencies received and included
- [ ] Tenzo note published - and reference x2
- [x] Test Newsletter
- [x] Newsletter is scheduled

## Notes of items to include
- [x] Community call updates - #1038 and #1061 
- [ ] Next community call - TBC
- [x] Limicon update
- [x] New CC website
- [x] 2R project team update - new website
- [x] Sylvie - any updates?

### Reference
- [ ] 2x Tenzo notes (from Feb and March)

**Comment by laurenwigmore** [comment]
FIXED. Scheduled to go out 2024-04-08.
