### ISSUE TITLE
[epic] Consolidation and Marketing of Conscious Coliving

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1063]
- **Appetite**: 3 person weeks (ship by 15th march)
- **Problem**: We have our courses and information related to CC scattered in multiple places, with 2 different brands alluding to similar things - CC and DDS. This makes them hard to find and market. Plus though our courses are good, we aren't getting many signups as we do no marketing.
- **Solution**: New site consciouscoliving.org with a good accessible landing page(s) that highlight exactly what we offer. Consolidate our material into that. Our audience is a bit beyond basic coliving and with a spectrum from there to DDS. Then given this single funnel point, design and launch a first marketing campaign.

Background shaping: https://github.com/life-itself/comms/blob/main/pitch/2408%20Practical%20Action%20Course%20Release.md

https://link.excalidraw.com/l/9u8crB2ZmUo/47ErL1keHFy

## Acceptance

```[tasklist]
### Audience / brand and sketch of hero section
- [x] Bad alternatives analysis to get some copy
- [x] First sketch of hero
- [x] Do a poll on our own community
- [x] Finalize target user ... **✅2024-03-12**
- [x] Finalize hero copy **✅2024-03-12 came up with 3 good options. Shared with community for feedback**
- [x] Resolve conscious coliving vs conscious collectives vs conscious communities as default way of speaking (note have domains for first 2 but not the last one)
- [x] Update domain url and set up redirect in cloudflare 🚧 to consciouscollectives.org **needs fixing - see comment below**
```

```[tasklist]
### ConsciousColiving.org Landing Page
- [x] Choose hosting platform **✅2024-03-14 going for simple canva option for now**
- [x] Sketch page including hero, offers e.g. courses, events
- [x] Do complete page (even if rough) **✅2024-03-14 https://consciouscoliving.org**
- [x] Add analytics (google analytics?) (Canva insights are built in)
- [x] MINOR/SECONDARY Newsletter sign up (*just for this* - and just random/irregular updates) ✅ **section on substack newsletter**
```

```[tasklist]
### First marketing campaign
- [ ] Identify audience channels ... (use Traction books as a starting point ...)
- [ ] What material ...
- [ ] Launch event ...
- [ ] Copy for front page ...
- [ ] Sketching hero section and content out for front/landing page
- [x] [10 day marketing plan created](https://docs.google.com/spreadsheets/d/1E23T7dXDkA6POR_8IgUtSub7aIhChxus92D0nnDzs0E/edit#gid=1640337796)
- [x] Copy for campaign written 🚧
- [x] Graphics created 🚧
- [x] Social Media channels to focus on decided
- [x] Course Signup Aims by Fri 29th March  - CC101: 26 new sign ups - 300 in total
- [x] TC: 13 new sign ups - 75 in total
- [ ] PA: 47 new sign ups - 50 in total
- [x] Launch blog post added to LI website
- [ ] https://github.com/life-itself/community/issues/1069
```

```[tasklist]
### Unscoped
- [ ] Consoldiate material into it
- [ ] BONUS: A launch event / effort (or at least one planned for later?)
```

```[tasklist]
### Misc
- [x] Create issue on Github for implementation
- [x] Lauren - register consciouscollectives.org
- [x] Trial page on substack
- [x] Trial page on Ghost
- [x] Sketch out how we want the page to look - https://app.excalidraw.com/l/9u8crB2ZmUo/47ErL1keHFy
- [x] Decide on platform 🔑 originally Ghost **update 2024-03-13 published via canva**
```

#### Substack

- Not very customizable: when it comes to your substack's theme and layout, your options are limited to how you want your posts to be displayed (grid, list...) and changing colors, fonts...
- The welcome page, which is what first-time visitors would see, has an email subscription form that adds subscribers to the substack itself...this is because the platform is designed for building an audience on Substack (there is an option to import emails from other platforms that only makes sense if you're trying to make substack your primary content provider)
- In the posts themselves, the editor allows you to add elements from top to bottom, so you cannot have two elemets side by side (e.g. video with a subscription button next to it), so that renders the initial sketch (inspired by startwritingonline) impossible to do
- https://consciouscoliving.substack.com/
- This is what I was able to set up: it has one post which has a link to sign up to the course, and could potentially include links to the other courses, but as I mentioned before, customizability is very limited and it would look nothing like the intial sketch.

#### Ghost
- https://conscious-coliving.ghost.io/
- Not sure I can layout the page sequentially - if we want to follow the design of the mock up 
  - Ordered to oldest first for this mockup
- Can change theme so layout can be better
  - Need to play around with which could give us what we want
  - Possible themes: Caspar, Edge, Headliner

### Aim of the landing page

- CC page is showcasing: what it is, why do it and how to do it
  - they dance together the conscious supports the coliving and the coliving supports the conscious
  
🤔 
- When I visit consciouscoliving.org I want to know clearly what the page is about, what I can get from it that is useful to me and why I should trust it as a resource
  - How will I know it is useful for me? :key: a clear statement of who this is for

#### Ranking of WhatsApp Poll Answers 2024-03-11 (16 out of 123 voted)
- [ ] 1- I want a day-to-day environment that supports sustained practice towards inner growth (11 votes) :sunflower: 
- [ ] 2- I want a place where I have to grow i.e. in community (9 votes) :sunflower: 
- [ ] 3- I want to build a community (9 votes) :sunflower:
- [ ] 4- I want an environment where I get to practice IRL (i.e. not reading a book or doing a course) (8 votes)
- [ ] 5- I want to dedicate my life to inner growth withought having to become a traditional monk (7 votes) :sunflower: 
- [ ] 6- I DO want to live in a hippie commune (4 votes) :house_with_garden:
- [ ] 7- I want to go beyond classic coliving (e.g. flatshare coliving for cheaper rent) (4 votes) :house_with_garden: 
- [ ] 8- I don't want to live on my own anymore (3 votes) :house_with_garden:
- [ ] 9- I want something more than a retreat i.e. longer-term and on-going (2 votes)  :sunflower: 
- [ ] 10, 11, 12- I've had bad experiences, I don't want to accidentally join a cult, I don't want to live in a hippie commune (0 votes) :house_with_garden:  
- **NB unable to post on twitter as options are limited to only 25 characters**

**Comment by laurenwigmore** [comment]
[Ref] potentially useful link related to the Ghost theme we have - https://github.com/TryGhost/Casper

**Comment by rufuspollock** [comment]
@laurenwigmore ok i've setup a redirect in page rules and turned on proxy (which we need for redirects to work). This should work but may take a bit of time for cache to reset.

**Comment by laurenwigmore** [comment]
FIXED. consciouscollectives.org has been set up, and an initial, relatively, unsuccessful marketing campaign was run with an upworker. We haven't done any more promotion of the website or courses since.
