### ISSUE TITLE
CoCo Practical Action Course Published

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1065]
Set the course up and have the email automation available and live.

## Acceptance

- [x] Course in markdown **✅2024-03-11**
- [x] Course is proofed **✅2024-03-12**
- [x] All graphics/images have been created
- [x] Course automation is live in Brevo

```[tasklist]
## Tasks
- [x] Design header graphics for course
- [x] **Bonus** Source suitable images to break up the text in the body of the course
- [x] Review and tidy final text in the .md forms
- [x] Move images up a level to `img` folder **✅2024-03-14 ❌ don't bother!**
- [x] Correct image names to be lower case with dashes (not spaces) **✅2024-03-14 ❌ let's not bother**
- [x] Fix image links to be to raw github location
- [x] Input course days into individual templates
- [x] Link templates into an automation
- [x] Make automation live
```

**Comment by laurenwigmore** [comment]
@rufuspollock do you have capacity to run the script this week, so we can make this course live before we start a new cycle?

**Comment by laurenwigmore** [comment]
FIXED live and working.
