### ISSUE TITLE
[ship] Limicon 2024 Talks

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1066]
We plan to provide three talks in the Limicon 2024 space. 

## Acceptance
- [ ] Three talks scheduled
- [ ] Three talks hosted

## Tasks

**Before the event**
- [ ] Decide on the three talk topics and who will present
  - [ ] Introduction to the Second Renaissance - Rufus
  - [ ] Ecosystems Mapping - Catherine
  - [ ] DDS Presentation - Matthew
- [ ] Agree on dates and times for the talks - all to hosted in the same week **weeks would be off-cycle weeks of w/c 18th or 25th March - recommended w/c 25th so w/c 18th they could be prepared**
- [ ] Add talks - title, details to Limicon events board
- [ ] Write a blog post on our website
- [ ] Promo talks to LI community 
  - [ ] Whatsapp
  - [ ] IG
  - [ ] Twitter
  - [ ] LinkedIn

**After the events**
- [ ] Add update after the talks to the March or April newsletter
- [ ] Follow up with useful contacts made in the space

**Comment by laurenwigmore** [comment]
@rufuspollock @catherinet1 @matthewmccarthy11 issue and comments related to the best week I see for the calls

here are two screenshots of events currently taking place with Limicon across these 2 weeks

<img width="894" alt="image" src="https://github.com/life-itself/community/assets/132304704/73912ff8-35fc-4971-a2fc-9466cd1b24be">

<img width="922" alt="image" src="https://github.com/life-itself/community/assets/132304704/0ea80c30-7aa2-4b9a-afd9-eaf6a5e2cf20">

**Comment by laurenwigmore** [comment]
Moving from whatsapp: 

@Rufus Pollock @Catherine LI The Limicon Newsletter will go out over the weekend promoting next weeks talks. I'll be contacting Lauren (from Limicon) to share our presence. Could you both view the event item descriptions and let me know of any edits you would like made this week (edits can still be done next week). and I will email Lauren later today. Info below ⬇️ 

**Many terms, one space?** 
Host: Life Itself

Date: Tuesday 26th March 
Time: 2pm - 330pm EST (7-830pm CET)

Description: Reporting from a 4 year project mapping an emerging ecosystem.

Since 2020 Life Itself and collaborators have been "mapping for emergence" - looking at the emerging set of actors in this "liminal space" searching for similarities - and differences.

In this talk we look mainly at the various names and tribes that seem to be converging as well as current and previous efforts to map and make sense of what is happening.


Category: (select one or a few from the following list, and delete the remainder) Speaker/Presentation, Eco-system Building

Vibe of Session: 

Specifications: 
-Process: 
-Spectators Welcome?: Yes
-Cameras On or Off?: On
-Recorded?: Yes
-Kid Friendly?: No

Website: [https://ecosystem.lifeitself.org/](https://www.google.com/url?q=https://ecosystem.lifeitself.org/&sa=D&source=calendar&ust=1711544464481463&usg=AOvVaw3eCwF6OK2h_J-dv40vKgVx)

Link to Event:  [https://us02web.zoom.us/j/82647867579?pwd=NExyS0hUN3JocHhQOVRubXE4WDBTUT09](https://www.google.com/url?q=https://us02web.zoom.us/j/82647867579?pwd%3DNExyS0hUN3JocHhQOVRubXE4WDBTUT09&sa=D&source=calendar&ust=1711544464481463&usg=AOvVaw0mRfFb-0Xl1oZ7aqje2Xir)

**The Second Renaissance: a time between worlds**
Host: Rufus Pollock - Life Itself

Date: Wednesday 27th March
Time: 12pm - 130pm ET / 5pm - 630pm CET

Description: How do we present what is happening and some of the key ideas of "this space" in a way that is succinct and accessible - including to people not yet "in the space"?

We present one framing of this "time between worlds" to set the stage for structured dialog about different approaches and their resonance.

Register here to join the call: [https://us02web.zoom.us/meeting/register/tZUof-2qrT4qG9wCRqshBOY90v9zpSp5ylpv](https://www.google.com/url?q=https://us02web.zoom.us/meeting/register/tZUof-2qrT4qG9wCRqshBOY90v9zpSp5ylpv&sa=D&source=calendar&ust=1711544464481463&usg=AOvVaw0_MPxfWirajrRkN69ImELr)

Category: (select one or a few from the following list, and delete the remainder) Speaker/Presentation

Vibe of Session: 

Specifications: 
-Process: 
-Spectators Welcome?: 
-Cameras On or Off?: On
-Recorded?: Yes
-Kid Friendly?: No

Website: [https://lifeitself.org/second-renaissance](https://www.google.com/url?q=https://lifeitself.org/second-renaissance&sa=D&source=calendar&ust=1711544464481463&usg=AOvVaw2mFUOExwzs3ns3qI8WB27L)

Link to Event:   [https://us02web.zoom.us/j/81584235018?pwd=S0kzR0c2cElOaDJvalRuZnZyT25Ndz09](https://www.google.com/url?q=https://us02web.zoom.us/j/81584235018?pwd%3DS0kzR0c2cElOaDJvalRuZnZyT25Ndz09&sa=D&source=calendar&ust=1711544464481463&usg=AOvVaw1Vl1jR_vqKJWcyq52XXSXj)
