### ISSUE TITLE
Tracking CoCo website launch metrics

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1069]
## Acceptance

- [ ] Targets met after 2 week campaign
- [ ] Analysis to understand better which posts / platforms performed best - _deadline agreed 11am CET 2024-04-15_

## Tasks

- [ ] Insights / metrics checked and added to our metrics spreadsheet
  - [x] beginning
  - [x] middle
  - [x] end 
- [ ] Sheet added to spreadsheet for tracking of social platforms
- [ ] Updated analysis of the campaign to include:
  - [ ] An overview of the campaign period in graphs to support the metrics and easier to visually understand - TODO
  - [ ] Which platform was the most successful / useful? - TODO 
  - [ ] Based on the above analysis - what are the conclusions/recommendations for the next campaign? - TODO
- [ ] Set up canva analytics for website ?
  - [ ] and future campaigns?
 - [ ] Add Google analytics to the CoCo website @laurenwigmore 
 - [ ] Consider setting up analytics software for future campaigns is it worth it? 🔑 **trial for a month once we have the next campaign agreed**

### Targets

- [x] CC101: 26 new sign ups - 300 in total ✅ 
- [ ] TC: 13 new sign ups - 75 in total ✅ 
- [ ] PA: 47 new sign ups - 50 in total ❌ _extremely far off target_

---
## Notes 
- [ ] What is your analysis of the campaign overall?
  - [ ] Individual metrics are fine _if_ there is a summary of this e.g. from IG metrics we can see that carousel posts do best, or it seems that posting at 8pm has a stronger reach or this isn't a long enough campaign to draw conclusions but my sense from these metrics are xxx - this can be added here for reference
  - [ ] Adding post type details to the spreadsheet might also have been useful when scanning - static / video / carousel etc.
- [ ] An overview of the campaign period in graphs would also work to support the metrics on the right hand side - TODO
- [ ] Which platform was the most successful / useful? - TODO
- [ ] Based on the above analysis - what are the conclusions/recommendations for the next campaign? - TODO
  - [ ]  NB: It's OK if it is 'inconclusive'  but a sense of guidance - what we should start with, focus on, or consider for the next campaign would be useful. For example
    - [ ] Should we even do one? It is cost-effective/useful?
    - [ ] Is it better to focus only on forums /groups?
    - [ ] Should we consider moving to a new/different platform?
    - [ ] Why has CC101, and TC done so much better than PA in this campaign? 
 - [ ] You mentioned canva does analytics - is that available for this campaign and/or our website?
   - [ ] If not, can we set this (canva analytics) up? TODO
 - [ ] TODO add Google analytics to the CoCo website @laurenwigmore 
 - [ ] TODO? set up analytics software for future campaigns? (notes on potentials added to #1007)

**Comment by laurenwigmore** [comment]
The notes from 2024-04-11 Lauren/Akram meeting - to review the first campaign have been added to our Comms meeting log.

**Comment by laurenwigmore** [comment]
FIXED.
