### ISSUE TITLE
April 2024 Newsletter

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1071]
## Acceptance
 - [x] Newsletter is released
 - [x] Newsletter is sent as an email
  
## Tasks
- [x] Write newsletter in Substack (April trial)
- [x] Info from Hub/Residencies received and included via their substack
- [x] Tenzo note published on Hub's substack
- [x] Test Newsletter
- [x] Newsletter is scheduled 

## Notes of items to include
- [x] The Gathering (-no.1)
- [x] Boaz's 1. second info call in May and 2. practice session - May 22 5:15-6:15pm CEST on this link https://us02web.zoom.us/j/5607901945 
- [x] Danielle's community call
- [x] Next community call - Richard Flyer
- [x] Research update
  - [x] Research calls - Tom & DDS update 
  - [x] Hackathon
- [x] Impermanence exhibition update

Boaz's info for no.2
Great here it is: May 31st 6-7:30pm CEST.
It’ll be with : Boaz Feldman, Rebekka Haas & Bugu Turkogul
We’ll be: co-creating a welcoming and regulating space, and then share details and answer questions about the upcoming Relational Embodiment Residency: https://neurosystemics.org/simple-event/relational-embodiment-residency/

**Comment by laurenwigmore** [comment]
FIXED. Trialed April's newsletter via Substack. Scheduled for release as a post and email at 9am CEST 7th May.
