### ISSUE TITLE
Switching to substack for newsletter and blog

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1073]
We have created a substack for Life Itself to test out its capabilities to host our newsletter and blog moving forward. 

# Acceptance

- [x] Test out Substacks capabilities ✅ **Video walk-through here https://drive.google.com/file/d/17U5X9iDrEEnMv4R7UYOxgeV9sj31oe37/view**
- [x] Complete a shaped pitch 🚧 https://github.com/life-itself/comms/blob/main/pitch/2420%20moving%20lifeitself%20blog%20to%20substack.md

**Video walkthrough most useful sections** 
- [ ]  Start - 2:52 - Intro of front page
- [ ] 4:56 - 6:57 - Writing a post
- [ ] 11:00 - 11:41 - Subscriber settings

# Tasks

- [x] Compare Substack vs Ghost vs Medium **see below**
- [x] Test out Substack for our needs **see pitch for extensive testing notes**
- [x] Write up longer analysis of why substack **see below**
- [ ] update the subscribe button on the life itself website to the new substack link/button on - @rufuspollock **I'm unable to locate these on Github to update.** The new link to embed: `<iframe src="https://news.lifeitself.org/embed" width="480" height="320" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no"></iframe>`
    - [ ] main front page https://lifeitself.org/
    - [ ] footer
 - [ ] Remove or link the Blog section that is featured near the the bottom of the LI home page (as the posts won't update automatically now we are on substack)
 - [ ] Introduce Sylvie and walk through Substack for Ordinary People publications specifically

## Substack Summary

Substack meets our current needs quite comprehensively.

- **Ease of Use**: a user-friendly interface without much technical expertise required.
- **Newsletter-centric Platform**: which focuses on building a subscriber base and fostering a direct connection between writers and readers, facilitating engagement and loyalty.
- **Flexibility**: Prescheduling posts, multiple authors per post, and the option to segment subscribers, can provide flexibility in content delivery and audience management.
- **Podcast Integration**: is available with automatically generating transcripts from uploaded files and allowing import/sync of episodes from platforms like Spotify.
- **Automated Features**: of social sharing after publishing, makes it more convenient (we still need to write the copy for the posts).
- **Subsections**: Division of the newsletter is possible if we wanted to do this
- **Customization**: Not as extensive as self-hosted platforms like Ghost, there are still some (albeit minimal) customization and branding options.
- **Cost Structure**: Substack offers a free-paid subscription tier should we ever need it (although paid % taken is higher than Ghost), a monthly, yearly, or founding basis. If we don't charge, it doesn't cost us anything to use.

Main win: Simplicity, with a focus on publishing newsletters/posts, (and the option of integrated monetization features later if wanted).

### Substack vs Ghost vs Medium Notes

This was partly done in https://github.com/life-itself/community/issues/1063.

| Platform | Uses | Notes | Monetization |
| -------- | -----| ----- | -------- |
| Substack  | newsletter-based platform that allows writers to build a subscriber base and monetize their content | user-friendly interface =  easy for writers to set up and manage their newsletters | Subscription based model |
| Medium | publishing platform that focuses on creating a community of readers and writers | complex system that requires users to navigate through tags, publications, and social features | Subscription based model |
| Ghost | self-hosted platform that offers complete control and customization over the website. | technical knowledge to set up, but it offers complete control over the website’s design and functionality |Set up own payment system |

### You an create subsections! Yay

<img width="643" alt="image" src="https://github.com/life-itself/community/assets/180658/57d0215a-0560-4cb1-afbb-46eb312f8714">

**Comment by asimong** [comment]
Why Substack?

**Comment by rufuspollock** [comment]
> Why Substack?

We narrowed choice to ghost vs substack and in our testing substack was easier, quicker etc and somewhat cheaper. It also seemed easy to switch from if we didn't like it.

We'll also post a longer analysis in the above issue soon. But basically we want blog/news, we wanted simplicity, we want newsletter integration if we could get it (but don't need charging etc).

**Comment by asimong** [comment]
My interest might be expressed in the question: "which services are (or are not) fully paid up subscribers to modernity?" (And how do you tell? How do you discern? How much are people aware of this dimension? How much of modernity just comes down to convenience?)

**Comment by rufuspollock** [comment]
> My interest might be expressed in the question: "which services are (or are not) fully paid up subscribers to modernity?" (And how do you tell? How do you discern? How much are people aware of this dimension? How much of modernity just comes down to convenience?)

Every since OKF days i've had a tendency to pragmatism and "pick your battles". e.g. we used skype at OKF etc. For me here the tool choice is largely about "what works", "ease of use", "cost" etc and not so much a particular alignment with our ideology (though pragmatism is one part of that ideology). That's my 2c 🪙

**Comment by laurenwigmore** [comment]
@rufuspollock is it possible to update the subscribe button on the LI website so that people who subscribe will now do so via Substack (and not Brevo).

**Comment by rufuspollock** [comment]
@laurenwigmore i suspect we need to embed the substack iframe.

**Comment by laurenwigmore** [comment]
@rufuspollock a reminder you still need to change the sign-up on the LI website. Here is the information that is in the main issue for your reference:

- [ ] update the subscribe button on the life itself website to the new substack link/button on - @rufuspollock I'm unable to locate these on Github to update. The new link to embed: <iframe src="https://news.lifeitself.org/embed" width="480" height="320" style="border:1px solid #EEE; background:white;" frameborder="0" scrolling="no"></iframe>
 - [ ] main front page https://lifeitself.org/
 - [ ] footer

**Comment by laurenwigmore** [comment]
@rufuspollock we are still receiving sign-ups to our newsletter going into Brevo. Is it possible to amend the above to substack?

**Comment by laurenwigmore** [comment]
FIXED. Closing this with the note that the website sign up is still linked to Brevo (so manually requires updating the subscribers on substack) - should be fixed with the update on the website https://github.com/life-itself/comms/issues/118
