### ISSUE TITLE
Community Call: Richard Flyer 21/05/2024 9pm CET

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1074]
Boaz Feldman | 28/03/2024 | 630pm CET | Multi-Level Resilience

## Acceptance

- [x] Community call hosted and recorded 
- [x] Uploaded to Youtube and blog post 

## Tasks

Pre-event

- [x] Confirm speaker
- [x] Confirm details with google form https://forms.gle/gfZfKEATSmusp5AW7
- [x] Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [x] Create Canva graphic using template 
- [x] Create registration using Zoom - https://us02web.zoom.us/meeting/register/tZEkd-6grzkrH91zE6A2X2h-h9Oe24tHB6oI
- [x] Create the blog post](lifeitself.org/blog/practicing-flexibility-in-deliberately-developmental-spaces) 
  - [x] Include image, registration link, biography of speaker or description of the event
- [ ] Promotion
  - [ ] Emails
    - [ ] Initial announcement (main group) on if newsletter was more than a week ago 
    - [ ] Day before announcement (main group) only if initial announcement was more than a week ago
    - [ ] Email reminder (recipients)
    - [x] Plus in newsletter (if applicable)
  - [ ] Whatsapp
    - [x] Initial announcement
    - [x] 3 days before
    - [x] Day before
    - [ ] 1-2 hours 
  - [ ] Twitter
    - [x] Thread for initial announcement
    - [ ] 3 days
    - [ ] Day before
  - [ ] Instagram
    - [ ]  Stories
      - [ ] Story template or resharing post
      - [x] Initial
      - [ ] 3 days before
      - [ ] Day before
  - [ ] Post for initial announcement 
  - [x] Linkedin Event created 

### Post-event

- [x] Make the youtube video
- [x] Update original blog post with youtube video plus information 
- [ ] Title: Should include name of person, plus keywords/topic
- [x] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [x] Copy of zoom recording [saved here in Raw Content log
- [x] Update CRM with links etc. 
- [x] Let the speaker know and make it easily shareable 

### Socials text

**IG**
Our next Community Call is on Tuesday 21st May 9pm CEST and we welcome Richard Flyer - a pioneer and author in the field of community connection and development.

In this community call Richard shares principles for building a global symbiotic culture, by starting with yourself in your local community. Sharing knowledge from his work across five decades of experiments and explorations across different nations, wisdom traditions, and organizational structures, to support the cultivation of a global shift from a Culture of Separation to a Culture of Connection. 

Link to register in our bio.

#SymbioticCulture #CommunityBuilding #SocialChange

**Twitter**
Register now for our next community call!
Richard Flyer joins us on Tuesday 21st May 9pm CEST to share his principles, learnings, and practical know how on building community. Register here - https://bit.ly/3wiluBB
Or read more below.

From five decades of experiments and explorations across different nations, wisdom traditions, and organizational structures. Join us on this call if you too are seeking a shift from a Culture of Separation to a Culture of Connection.

#SymbioticCulture #CommunityBuilding #SocialChange

**Comment by laurenwigmore** [comment]
FIXED - recorded and now live.
