### ISSUE TITLE
New website setup using substack and static site in combination

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1075]
```[tasklist]
### Tasks
- [x] Cloudflare worker revert proxy script **🚧2024-04-27 https://dash.cloudflare.com/2e945b31b891a1119d506f82b065df2c/workers/services/edit/lifeitself-dotorg-proxy/production**
- [x] Analyse pages we have on the site so we can work if we need to proxy all of them **🚧2024-04-28 https://docs.google.com/spreadsheets/d/1UYz-oZooKO5e2Smh6CSEBBT8dBLVoDgr_hHaY47EBJo/edit#gid=0**
- [ ] New cloudflare worker https://dash.cloudflare.com/2e945b31b891a1119d506f82b065df2c/workers/services/edit/dotorg-proxy/production
```

## v3

Idea is ...

- substack urls go to substack
- everything else to flowershow
- and bonus: substack landing page at /blog/ or `/news/`

```[tasklist]
### Tasks
- [x] What are substack urls? **✅2024-04-28 see below. think i have everything**
- [x] Create and test proxy
- [x] Can we disable the signup prompts on most pages? **💬2024-04-29  there's no way to disable generally afaict and several online reports confirm it can't be disable.**  See also www.citationneeded.news/substack-to-self-hosted-ghost/**
- [x] Get it working **✅2024-07-02 ❌ we never got this working because of subtle issues and no way to proxy substack landing page somewhere else. So we gave up**
```

### Substack pages

```
/
/about
/p/ for pages,
/t/ for tags
/s/ for sections
/archive # for post archive page ...
```

## 2nd Effort: ...

Sources

- Substack: lifeitselfnews.substack.com
- Flowershow powered site: 
- Clouldfare for DNS and reverse proxy

Important facts

- substack only supports cname so you have to give it a www domain

Plan

```mermaid
graph LR

flowershow[Flowershow]

request --> proxy[Cloudflare]
proxy --default--> substack[Our Substack]
proxy --"if /"--> flowershow
```

- [x] Setup new `flowershow.lifeitself.org` subdomain 
- [ ] Create reverse proxy that proxies home page on www.lifeitself.org to flowershow
- [ ] Redirect lifeitself.org to www.lifeitself.org

---

## v1: substack at suburl ❌

This failed because it turns out  setting up substack at a suburl is **really painful** and perhaps impossible.

This documents where we got to ...

- We created a worker

```mermaid
graph LR

request --> proxy[Proxy]
proxy --if /blog--> substack[Our Substack]
proxy --"otherwise"--> donothing[do nothing i.e. render our current site]
```

This failed because it turns out substack calls `/api/v1/...` stuff and expects that to be there.

Proxying `/api/v1` worked pretty well ...

**Comment by rufuspollock** [comment]
NTS about how to handle the reverse proxy

- One option is to route everything through worker and send everything onwards if for substack and route everything else
  - 👎 because no caching (??)
  - 👎 b/c costly (?? not very expensive)
- add worker routes for everything in cloudflare dashboard
  - 👍 it will work
  - 👎 have to add a route for every new page (unless we do a subdomain)
  - 👎 painful to do manually
- best option would be reverse proxy to substack ❌ however no way i can see to get this working because substack urls have to be on main site as fqdn is hardcoded into urls i think ...)

**Comment by rufuspollock** [comment]
FIXED / WONTFIX. We have site setup but only with substack at a subdomain for now.
