### ISSUE TITLE
[epic] LifeItself.org revamp with substack april 2024

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1076]
This revamp covers both technical re-architecture plus content reshaping to implement conclusion of #196 

For motivation and context see the shaping below ...

## Acceptance

```[tasklist]
### Technical
- [ ] https://github.com/life-itself/community/issues/1077
- [x] Remove popup to sign up to CoCo course **✅2024-04-27 in 3f88974a7955273f3d22f9db8d39c942567ce8de**
- [x] BONUS: ❓#1089 **✅2024-06-01**
- [x] Move out tao? **✅2024-06-01 ❌ not worth it for now. no good reason and a hassle to do.**
- [ ] https://github.com/life-itself/community/issues/1075
- [ ] Work out how to do bulk redirects again (can we still use `_redirects` or do we have to use cloudflare dashboard stuff)
```

```[tasklist]
### Content
- [ ] Redo front page with ToC and three areas
```

# Shaping

## Hypothesis

Technical side

- Combine simple tools to get website with best of both worlds: substack for lots of content
  - Accept some disjunction in look and feel across segments
- ...

Principles

- Use subdomain more for specific subprojects rather than have everything in one site ...
  - little benefits of synergies e.g. no real benefit of tao and rest of site being in one
  - ?? can achieve SEO by cloudflare proxy approach (hard with `_next` subfolder stuff but not impossible)
  - cost of complexity and slow builds etc

**Comment by rufuspollock** [comment]
FIXED. We moved to substack and this is now superseded by #1136
