### ISSUE TITLE
Unmerge sutras from this repo (reverses #125)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1077]
```[tasklist]
### Tasks
- [x] Reboot sutras repo https://github.com/life-itself/sutras **✅2024-04-26 done and deployed at https://github.com/life-itself/sutras using [DataHub Cloud](https://datahub.io/)**
- [x] Add redirect
- [x] Remove from this repo
- [x] Migrate issues etc back **✅2024-04-27 found one issue and merged back https://github.com/orgs/life-itself/discussions/164**
```

**Comment by rufuspollock** [comment]
Redirect done

<img width="1089" alt="image" src="https://github.com/life-itself/community/assets/180658/dc535f6f-5182-49ad-998d-6bde0cabd7be">

**Comment by rufuspollock** [comment]
FIXED.
