### ISSUE TITLE
May 2024 Newsletter

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1080]
## Acceptance
 - [x] Newsletter is released
 - [x] Newsletter is sent as an email
  
## Tasks
- [ ] Write newsletter in Substack 
- [ ] Info from Hub/Residencies published via their Substack
- [ ] Test Newsletter
- [ ] Newsletter is scheduled 

## Notes of items to include
- [x] 2R Net
- [x] Richard Flyers Community Call
- [x] Hackathon update
- [x] Daniel Thorson
- [x] Valerie OP (& Liam if released before newsletter goes out)
- [x] Liana's CBI update
- [x] webinar update
- [x] stoa announce

**Comment by laurenwigmore** [comment]
FIXED. Sent.
