### ISSUE TITLE
Publish Ordinary People - Liam Kavanagh episode - 29 May

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1081]
## Acceptance

- [x] Episode live on Youtube
- [x] Episode live on Spotify
- [x] Podcast page on substack done
- [ ] Announcement post live 

## Tasks

- [x] add video to clog
- [x] edit the video
- [x] add to Youtube
- [x] create canvas template
- [ ] create jingle
- [x] write short summary about this specific podcast and person
- [x] upload on spotify and release 
- [x] upload on youtube and release 🚧 _scheduled for 5 June_
- [x] Add to substack as a post and tagged as OP 🚧 _scheduled for 5 June_
- [x] Guest informed that the episode is out and has been sent the links.
- [x] The new episode has been announced on Twitter and other socials

**Comment by laurenwigmore** [comment]
FIXED.
