### ISSUE TITLE
Publish Ordinary People - Rainer v Leopretching Episode

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1083]
## Acceptance

- [x] Episode live on Youtube
- [x] Episode live on Spotify
- [x] Podcast page on website done
- [x] Announcement post live 

## Tasks

- [x] add video to clog
- [x] edit the video
- [x] add to Youtube
- [ ] create canvas templates
- [ ] create jingle
- [x] write short summary about this specific podcast and person
- [x] upload on spotify and release
- [x] upload on youtube and release
- [x] Add to substack as a post and tagged as OP
- [ ] Episode page created and added to the website podcast page. 
- [x] Guest informed that the episode is out and has been sent the links.
- [x] The new episode has been announced on Twitter and other socials

**Comment by laurenwigmore** [comment]
FIXED.
