### ISSUE TITLE
Publish Ordinary People - Natalia Lombardo episode

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1084]
## Acceptance

- [ ] Episode live on Youtube
- [ ] Episode live on Spotify
- [ ] Podcast page on website done
- [ ] Announcement post live 

## Tasks

- [x] add video to clog
- [x] edit the video
- [x] add to Youtube
- [ ] create canvas templates
- [ ] create jingle
- [ ] write short summary about this specific podcast and person
- [ ] upload on spotify and release
- [ ] upload on youtube and release
- [ ] Add to substack as a post and tagged as OP
- [ ] Episode page created and added to the website podcast page. 
- [ ] Guest informed that the episode is out and has been sent the links.
- [ ] The new episode has been announced on Twitter and other socials

**Comment by laurenwigmore** [comment]
FIXED.
