### ISSUE TITLE
Prep for Research Hackathon May 2024

### ISSUE THREAD

**Issue by catherinet1** [life-itself/community#1085]
## Acceptance

- [x] Announcement published **Done: https://lifeitself.org/blog/research-hackathon-may-2024**
- [x] Announcement shared **Shared in Whatsapp groups, Twitter, LinkedIn and with Cohere+ team.**
- [x] 10+ sign-ups **2024-05-07 13 sign-ups so far 🎉  (+ Catherine, Rufus, and Lauren). Sign-ups [spreadsheet](https://docs.google.com/spreadsheets/d/1Mon8fvjHlp7HO20oxeS-fPDAMZynbRq3nL563u6MEwY/edit?resourcekey#gid=1373988679).**
- [x] Zoom or Google Meet link sent to all registered participants **Tracking sending of confirmation emails and calendar invites in sign-ups spreadsheet: https://docs.google.com/spreadsheets/d/1Mon8fvjHlp7HO20oxeS-fPDAMZynbRq3nL563u6MEwY/edit#gid=1373988679**

## Tasks

- [x] Publish announcement
  - [x] Find last year's announce post **https://lifeitself.org/blog/2023/05/17/research-hackathon-june-2023#what-is-a-hackathon**
  - [x] Write post, inc some form of sign-up so we know roughly who to expect
  - [x] Create new sign-up form **https://docs.google.com/forms/d/18IRs1n-thNECXPpgVy8-SG11CpUDAjdxTzf8oAOCjGo/edit**
  - [x] Add Cohere+ logo and EU logo
- [x] Share
  - [x] Cohere+ team
  - [x] LI research community
  - [x] Events board WA
  - [x] Get Involved chat
  - [x] Tweet
  - [x] LinkedIn?
- [x] Share again ~1 week before **Shared details and sign-up form again in General Chat and LI Research chat at beginning of Hackathon week**

## Notes

- Life Itself Research hackathon: 
- Friday: internal
- Kick-off meeting of hackathon at 5pm European on the Friday

Friday 5pm to Saturday 7pm (though US folks can work later)

- Friday 11am-5pm: pre coworking. Come and get involved and cowork virtually.
- **Friday 5-6pm kickoff**
- Saturday 11-12pm (check-in, new joiners)
- Saturday 6-7pm closing
- People "self-organise" in between

We'll have pre coworking on Friday from 11am European if you want to get together early. Formal kick-off of hackathon will be happening at 5pm.

Intentions:

- Research collective opportunity to work together
- Allow new folks to engage
- Ship stuff ...
