### ISSUE TITLE
Publish Ordinary People - Daniel Thorson - Thurs 16 May

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1086]
## Acceptance

- [x] Episode live on Youtube 🚧 _scheduled for 2024-05-21_
- [x] Episode live on Substack/Spotify 🚧  _scheduled for 2024-05-21_
- [x] Shorts completed and used for promo 🚧 

## Tasks

- [x] add video to clog
- [ ] edit the video ❌ _not editing_
- [x] add to Youtube
- [x] Identify sections for shorts 
- [x] Create shorts 🚧 
- [x] create canvas templates
- [x] create jingle
- [x] write short summary about this specific podcast and person
- [x] upload on spotify and release 🚧 
- [x] upload on youtube and release 🚧 
- [x] Add to substack as a post and tagged as OP 🚧 
- [ ] Episode page created and added to the website podcast page. ❌ _not applicable now on substack_
- [x] Guest informed that the episode is out and has been sent the links.
- [x] The new episode has been announced on Twitter and other socials
  - [x] Prelaunch video teaser promoted on all channels

### Announcement text

Whatsapp / Instagram / LinkedIn - use 2nd short and the below text 

Tweet 1
Daniel Thorson speaks with Rufus Pollock in our latest episode of Ordinary People.  LINK

In this episode Daniel dives into Daniel his unique journeys of finding faith, meaning, and personal growth through unexpected avenues of meditation, living at a Goenka center, and participating in the Occupy Wall Street movement.  

Tweet 2 
They delve into the critical roles of trust, courage, and support in navigating life's uncertainties and explore the intersection of Buddhism and technology, pondering the potential for online spaces to foster contemplative practices, and sustaining personal and societal transformation through commitment and deep inquiry.

Tweet 3
#monastic #emerge #buddhism #friendship #inquiry #technology #socialtransformation #courage #faith #meditation #suffering For the full conversation click here ➡️ LINK

Tweet 4 -
Preview from a recent conversation with Daniel Thorson - SHORT LINK

**Comment by laurenwigmore** [comment]
FIXED.
