### ISSUE TITLE
Move website out of community and have this be wiki / planning space

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1089]
Summary: Migrate lifeitself.org website content and build to a separate repo (and out of community) so that `community` repo becomes a community notebook / wiki / planning / playground space.

## For team: 🚩 Important - edit in new repo going forward

> [!warning]
>  Going forward please edit lifeitself.org website at https://github.com/life-itself/lifeitself.org

## Why do this?

Situation:

- lifeitself.org currently built off markdown content and flowershow nextjs app here in community repo
- we also have "notes" stuff that is the germ of an a notebook / wiki / planning space

Problem:

- in short having an informal wiki like area and main website together does not work in terms of cognitive frame, UX, permissions or actual tech build
- To give a few examples:
  - difficult to access/edit notes: no-one (even rufus) edits notes stuff because its kind of hidden, plus overwhelmed with rest of site
 - permissions: risky to give everyone access to website as they can accidentally break build etc. But you want lots of people to add to notebooks
  - tech build: lifeitself.org needs a custom flowershow app which therefore means a load of JS stuff in repo (plus its big). But notebook would not need that so could be built from simple datahub/flowershow cloud
 
### More whys

Why not start a new repo for the wiki / notebook etc: because all the issues and discussions are here and migrating them is a massive pain.

Why move the website out: website is large and slow to build. Also most people shouldn't really be interested in or touching the main website.

Why not keep the wiki / playground here with the website: because then it gets lost in main website. plus notebook gets bogged down in site build. With site out we can use datahub cloud to build without need for self build (btw we tried this in our last iteration and have the `/notes/` section).

## Tasks

```[tasklist]
### Tasks
- [x] Mirror the repo **✅2024-05-10 during hackathon https://github.com/life-itself/lifeitself.org**
- [x] Set up a cloudflare pages build and test it **✅2024-06-01 it's live here and looks good https://lifeitself-org-5z4.pages.dev**
- [x] Move lifeitself.org domain to run off new pages build **✅2024-06-01, this community repo is no longer the source for building lifeitself.org instead it is https://github.com/life-itself/lifeitself.org**
- [x] Need to sync again as a couple of commits since then (but nothing significant) - see https://github.com/life-itself/community/commits/main/ **✅2024-06-01 synced across the 2 v minor commits https://github.com/life-itself/lifeitself.org/commit/4bf0897f9ac5cd7290a52dfe60489b0922abb057 and https://github.com/life-itself/lifeitself.org/commit/b6a00a84df25548bfefcec633b50008ecf7be342**
- [x] Remove build from cloudflare pages **✅2024-06-01**
- [x] Remove all the lifeitself.org site content here and make this a simple markdown-based PKM / wiki repo **✅2024-06-02 see https://github.com/life-itself/community/commit/36355bce05b0494084ba3930c14035fed4577396**
- [x] Deploy it to notes.lifeitself.org using datahub cloud **✅2024-06-02 see https://notes.lifeitself.org**
```

```[tasklist]
### Future
- [ ] BONUS (FUTURE): clean git history and remove all the git lfs stuff so that cloning is fast (plus )get it purged by github so it does not count to our quota
- [ ] Remove notes stuff on lifeitself.org site (this requires checking what pages reference notes atm e.g. some stuff in tao - i recommend we copy those items *back* into tao so tao is self-complete)
```

**Comment by rufuspollock** [comment]
FIXED. All done. Some follow up i've left in future for now as won't do for the moment.

**Comment by davidgasquez** [comment]
Looks awesome @rufuspollock! :heart_eyes:
