### ISSUE TITLE
Write up Wilber integral psychology book and post

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#109]
## Acceptance

* [ ] Book notes on integral psychology are published online either in LI blog or community site

## Tasks

* [ ] Rough and ready: basic tidy up my notes
  * [ ] Extract the youtube comment (maybe post somewhere)
* [ ] Push that
* [ ] More tidying e.g. better headings, add a summary
  * [ ] Add a summary
* [ ] Extract all the images at the end about development pathways
0/3
  * [ ] pandoc it to markdown folder
  * [ ] pull the images from the folder
  * [ ] store them and re reference them from summary
* [ ] Convert the developmental pathways into one big spreadsheet and embed / publish that
