### ISSUE TITLE
June 2024 Newsletter

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1090]
## Acceptance
 - [x] Newsletter is released
 - [x] Newsletter is sent as an email
  
## Tasks
- [ ] Write newsletter in Substack 
- [ ] Info from Hub/Residencies published via their Substack
- [ ] Test Newsletter
- [ ] Add any new signups on old newsletter subscribe form to Substack
- [ ] Newsletter is scheduled 

## Notes of items to include
- [ ] The Stoa call update
- [ ] The Gathering update
- [ ] Research updates
- [ ] Community calls _unlikely to have hosted any_
- [ ] Ordinary People episodes - Liam, Natalia
- [ ] Promo Slowww synthesizer course (see email for access)
- [ ] Ivo's emerge event in Ukraine (more details required)
- [ ] Connection call for 2R

**Comment by laurenwigmore** [comment]
FIXED. Newsletter sent.
