### ISSUE TITLE
Publish Ordinary People - Roberto Unger episode - mid July 2024

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1093]
## Acceptance

- [ ] Episode live on Youtube
- [ ] Episode live on Spotify
- [ ] Podcast page on substack done

## Tasks

- [ ] add video entry to clog
- [ ] edit the video if needed
- [ ] add to Youtube
- [ ] create canvas templates
- [ ] create/add jingle to podcast
- [ ] write short summary about this specific podcast and person
- [ ] upload on spotify and release
- [ ] upload on youtube and release
- [ ] Add to substack as a post and tagged as OP
- [ ] Guest informed that the episode is out and has been sent the links.
- [ ] The new episode has been announced on Twitter and other socials

**Comment by laurenwigmore** [comment]
WON'T FIX - not to be published as per conversation with Rufus
