### ISSUE TITLE
Publish Ordinary People - Bonnita Roy episode

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1094]
To touch base with Bonnitta before releasing this episode in early August to check she is happy timings wise, based on the release of an earlier podcast in June featuring her.

## Acceptance

- [x] Re-set up LI podcast page and push through to main LI podcast
- [x] Episode live on Youtube
- [x] Episode live on Spotify
- [x] Podcast page on substack completed and sent as a mailout

## Tasks

- [x] add video entry to clog
- [ ] edit the video if needed
- [x] add to Youtube 
- [ ] optimise video using checklist
- [x] create canvas templates 
- [ ] create/add jingle to podcast
- [x] write short summary about this specific podcast and person
- [x] upload on spotify and release
- [x] upload on youtube and release
- [x] Add to substack as a post and tagged as OP
- [ ] Guest informed that the episode is out and has been sent the links.
- [x] The new episode has been announced on Twitter and other socials
- [ ] Shorts created for promotion and released
  - [x] Teaser
  - [x] 2nd short

# 2024-08-13 Quick Review of Podcast and changes to implement before posting BR's episode

Choice: have one podcast called "Life Itself Podcast"

On YT etc we can have playlists and can always curate "sub playlists" by hand on our site if needed.

Suggested steps

- Create new podcast on substack at https://news.lifeitself.org/s/podcast
- Connect to *existing* and *main* spotify podcast system (which i believe automatically pushes to other places)
- Publish one back episode of ordinary people (with the back date if possible) to test ...
  - If that is good we can give radha task of back-posting rest ...
- ...

Future:

- how to deal with the backlog?? we'll work that out one day ...

**Update 2024-08-15**

See #1120 - Bonnitta Roy's will be published via old process and substack pages / sections updated and amended accordingly.

**Comment by laurenwigmore** [comment]
In progress - releasing this week.

**Comment by laurenwigmore** [comment]
@RadhaHarilal tomorrow (13th Aug) can you create 2 reels - 1 to use as a teaser and short and 1 to use as a short from this interview.
We have a [spreadsheet](https://docs.google.com/spreadsheets/d/1edrCk4saByUFAlffx1pSRk01QPjQSj6P4Xr5pgFF3sU/edit?gid=0#gid=0) where one of our community members volunteered and identifed specific sections that could be good for reels (some to be combined). 
In the reels we want to have captions please.

Also in YouTube I have a vidQI score of 92 for this unreleased video. I need to look at a few more of the optimisation points (add cards for example) and to do a short trim of the end.

**Comment by RadhaHarilal** [comment]
@laurenwigmore There is something wrong with the video. When I downloaded it, the quality was very low, and when I tried to fit it to reel format, and blew the image, it spoilt the video quality.

**Comment by laurenwigmore** [comment]
> @RadhaHarilal could you ask Bijesh how he created reels from our past videos, as they have all been on the same platform (recorded via zoom). If needs be I will pass this task to Bijesh to complete as I want to ideally release this today, the latest Thursday. You could also download from our YouTube channel or from our Raw content folder.

**Comment by RadhaHarilal** [comment]
@laurenwigmore Yes you may ask Bijesh to work on these.

**Comment by laurenwigmore** [comment]
FIXED - released on 2024-08-15
