### ISSUE TITLE
[epic] Karl + Rufus Interviews re ECT and DDPs in general

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1097]
2-5 interviews re ECT and DDPs in general.

Notes from 2023-05-24 chat.

- Scripting / topic brainstorming
- Do this simply
- Life Itself would cover publishing/processing efforts

```[tasklist]
### Tasks
- [x] Episode 1: recorded and published
- [x] Episode 2: recorded and published
- [ ] Shape up the rest of this or decide this is complete ...
```
