### ISSUE TITLE
[Epic] T1 Comms Drive

### ISSUE THREAD

**Issue by theo-cox** [life-itself/community#110]
## Description

We are aiming to supercharge our comms in 2022. This requires a bunch of actions to fulfill on our targets. Lets bang em out.

## Acceptance

- [ ]  All comms infrastructure up and running as required
- [ ] We have a full content plan for the year including resources
- [ ] Everyone is clear on what they need to do to support comms efforts

## Tasks

- [ ] T1 planning **Theo proposal: We devote a good couple hours of T1 planning session to the below tasks**
     - [ ] Group session to bulk out the yearly calendar for 2022 (including days of relevance, e.g World Rewilding Day).
     - [ ] Group brainstorming session to begin planning online summit for 2022
     - [ ] Team effort to add short quotes, reflection questions and excerpts to the [LI Content Mastersheet](https://docs.google.com/spreadsheets/u/0/d/1M3nqhszdQDYZeSHPttAevfsr0u9x_irLit9S-oUSzO0/edit).
     - [ ] A team effort to collect more content (photos, videos, testimonials, etc.), ask @nathenf  for guidance: he can create a shot list 
       for specific events.
     - [ ] Group brainstorming session to begin planning online summit for 2022
- [ ] Mailchimp to be upgraded for a/b testing and email journeys. **@rufuspollock I think $21/month is worth it if we can significantly increase our functionality. Tagging here for visibility and to give opportunity for veto before I pull the trigger in Jan**
- [ ] Brainstorm and implement a valuable lead magnet for newsletter sign-ups (a free offer in exchange for name and email). **There's discussion about whether this can be the contemplative activism book, or some collection of essays from the residency**
- [ ] Newsletter sign-up should be on every page of the website and must include at least first name and email. An unobtrusive pop-up form when people go to exit the website would also be great. **@rufuspollock can we get Khalil to do this when onboarded?**  
- [ ] Newsletter template with correct formatting for ease of use. **@nathenf assigning you here**
- [ ] Welcome email journey created for new subscribers @nathenf 
- [ ] Youtube video thumbnail template created @nathenf 
- [ ] Youtube profile and video captions optimised @nathenf 
- [ ] Create a call to action to add to each Youtube video from now on @nathenf 
- [ ] Create a SOP (standard operating procedure for new Youtube videos) @nathenf 
* [Recurring] Writers of new articles to complete the blog summary section in the [LI Content Mastersheet](https://docs.google.com/spreadsheets/u/0/d/1M3nqhszdQDYZeSHPttAevfsr0u9x_irLit9S-oUSzO0/edit) from now on. **@rufuspollock @lkavanagh30 @IljaMaiber to take note**

**Comment by theo-cox** [comment]
@rufuspollock @lkavanagh30 @IljaMaiber These are the immediate actions from the comms plan which we need to push forward at the start of 2022. Please review (and then re-review in the new year)

**Comment by rufuspollock** [comment]
@theo-cox this is great. For me, it would be easier to have a short dedicated session to review the high level goals and then let you guys decide how you want to implement.

Small comment on mailchimp as you specially asked: i don't think we have a large enough list to justify a/b testing (we won't get statistical significant i think at this point). I also (have long) wondered about switching to sendinblue - i've preferred it in my experience and much cheaper (we just went with mailchimp at start b/c someone chose that fairly randomly i think). In general though that spend seems small so i think it is in your discretion.

**Comment by theo-cox** [comment]
@rufuspollock happy with that. To be honest (summit aside, which Nathen and I can probably plan ourselves and then just come to you for your contacts as and when) I have put the calendar, excerpts and content curation as a group activity because I know it's something that won't get done unless I pin everyone down on a call to do it. If you have a more optimistic estimation or have an alternative approach then I'm open...

P.s. good to know on mailchimp. We'll hold off and look into sendinblue in the new year

**Comment by rufuspollock** [comment]
I agree about having a call - especially to present the high level strategy.

**Comment by rufuspollock** [comment]
@theo-cox flagging that i think this should include the strategy which i know we have a doc for.

And adding that as per comment in that doc:  I imagine we want some kind of meeting to feel this is really "signed off" e.g. I imagine it would be good to really link this to the overall goals of other circles and have some conception of how the strategy relates to the overall engagement pathway for people.

**Comment by nathenf** [comment]
@rufuspollock I added links to key documents in this issue.
