### ISSUE TITLE
Conscious Food Course

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1101]

**Comment by rufuspollock** [comment]
**[Original Post]** by **@jenniferchan8** on **2025-10-17 at 08:53:26 UTC** (from `life-itself/practicum#12`)

---

**Title:** Conscious Food Learning Resource

## Acceptance Criteria

- [x] Shaping complete - **all info here: https://docs.google.com/document/d/1Wtp-I105Fkar9JVhn1ve_nMKiFw0i1u47LqmPezLIO0/edit?tab=t.0#heading=h.al8qygidfntc**
- [x] Have a finished ~20 page book; digital edition
- [ ] Landing page for book established
- [ ] Posted on Substack/instagram/etc

## Tasks
- [ ] Illustrate the book—probably aiming to do ~10 big illustrations, a few small ones
- [x] Interviews 1-3 have been transcribed, cleaned, + synthesized into a 7 page script
- [ ] Finish, transcribe, integrate interview 4
- [ ] Get feedback from Valerie about book script
- [ ] Clean + digitize illustrations and text into a book
- [ ] Figure out how to ship a book–digital publication on Life Itself website? A substack post/instagram post? Creating a landing page?
- [ ] Converge with Rufus on a general structure for the Praxis Academy, especially around filming norms, clip structure, editing videos, + hosting site
- [x] Interview Valerie about course needs--Wednesday at 2:30 PM or 3 PM
- [x] Flesh out ideas for curricula (e.g., video series, Coursera-esque platforms to host a course, an online module with free and paid components, model based on the Artist's Way) - 
- [x] Research platforms for hosting course - **recommend Mighty Networks, Kajabi, or Skillshare**
- [x] Research 18R cooking offerings - **not relevant**
- [x] Create SCQA/first hypothesis
- [x] Interview Rufus for 10 min
- [x] Interview other people at the hub--ask them what their hope/pain points/needs are
- [x] Analyze for justice--are foods culturally sustaining/income accessible?

## Notes

- Goal is to ship by end of practicum
- Might want to do a 1 week product sprint with The Design Sprint--Google Ventures
- Demo with friends/others!
- Ask people what topics they'd be interested in (e.g., how to meal prep as someone working 40 hours a week, mindful eating, etc.)
- Ideas: personalized coaching? accountability buddies/getting matched to a random person to chat about outcomes?
- Comparative tasting?
- Better Living through Bittermelon as inspo?

**Comment by rufuspollock** [comment]
**[Original Post]** by **@rufuspollock** on **2025-12-23 at 08:15:47 UTC** (from `life-itself/practicum#12`)

---

@jenniferchan8 if you get a chance you update this with a final status 😄🙏
