### ISSUE TITLE
July 2024 Newsletter

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1103]
## Acceptance
 - [x] Newsletter is released
 - [x] Newsletter is sent as an email
  
## Tasks
- [x] Write newsletter in Substack 
- [x] Info from Hub/Residencies published via their Substack
- [x] Test Newsletter
- [ ] Add any new signups on old newsletter subscribe form to Substack
- [ ] Newsletter is scheduled 

## Notes of items to include
- [x] Rainers OP
- [x] 2R Zoom course - in Aug/Sept? (earlybird)
- [x] 2R connection calls
- [x] Jasons community call
- [ ] 2R video - launched ❌ _will not be completed in time for this newsletter carried over to Aug_

**Comment by laurenwigmore** [comment]
FIXED. Newsletter sent.
