### ISSUE TITLE
August 2024 Newsletter

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1104]
## Acceptance
 - [x] Newsletter is released
 - [x] Newsletter is sent as an email
  
## Tasks
- [ ] Write newsletter in Substack 
- [ ] Info from Hub/Residencies published via their Substack (october)
- [ ] Test Newsletter
- [ ] Add any new signups on old newsletter subscribe form to Substack
- [ ] Newsletter is scheduled 

## Notes of items to include
- [ ] 2R video - launched
- [x] update on explorer course - success and next one in October
- [x] 2R connection calls & workspace calls
- [ ] DDS website launched & ECT event
- [ ] Scholars Series launch
- [x] Sylvie's podcast  with Jonathan - https://www.youtube.com/watch?v=RpDVQYEqqwI
- [x] Announce next Dark Renaissance Resilience call
- [x] Bonnitta Roy - OP podcast

**Comment by laurenwigmore** [comment]
FIXED. Sent on 2024-09-03.
