### ISSUE TITLE
Hire a Bergerac Hub Manager

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1108]
## Acceptance

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

## Tasks

```[tasklist]
### Tasks
- [ ] Identify need
- [ ] Write job description
- [ ] Post job description ...
```

**Comment by laurenwigmore** [comment]
@rufuspollock I have had an enquiry from someone who stayed at the Hub over summer, initially about the social media role, but I'm wondering if this might be suitable. Is fluency in French a necesscity or a nice to have? They aren't fluent.
