### ISSUE TITLE
Create a checklist for YT channel

### ISSUE THREAD

**Issue by RadhaHarilal** [life-itself/community#1112]
Conduct market research, competitor research, and create a checklist for the team to use moving forward, to enable organic audience growth and better use of our main social media tool - YouTube.

## Acceptance

- [ ] Create a Complete checklist for YouTube channel

## Tasks
- [x]  Examine YouTube Studio Analytics
- [x] Assess video performance 
    - [x] Identify gaps
    - [x] Evaluate video quality
- [x] Scrutinize channel's visual elements
     - [x] banner
     - [x] Logo
     - [x] Thumbnail
     - [x] Title
     - [x] channel description
     - [x] tags
     - [x] playlists 
- [x]  Market Research
     - [x] Check Google Trends
     - [x] Social listening
     - [x] Look for content gap
- [x] Competitor Research
     - [x] Analyze their top-performing videos
     - [x] engagement metrics
     - [x] posting frequency
- [x] Keyword Research
     - [x] Use VidIQ to research keywords
- [x] Sharing
     - [x] Check if the videos are shared
- [x] Suggestions
     - [x] Create a content calendar
   

```[tasklist]
### Link to Spreadsheet
- [x] YouTube Checklist (https://docs.google.com/spreadsheets/d/1eCPhYwumTPZarchG7PhYbKdGWzRDjX62msxAudbe3Xw/edit?usp=sharing)
```

```[tasklist]
### Tasks
```

**Comment by laurenwigmore** [comment]
@RadhaHarilal please add a link to where the checklist is located to this issue in the main body 🙏

**Comment by RadhaHarilal** [comment]
@laurenwigmore I have added the link to the checklist

**Comment by laurenwigmore** [comment]
FIXED
