### ISSUE TITLE
Jason Sears Villageco - Community Call 16.09.24

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1114]
Jason Sears | Creating Space for Connection | 16.09.2024 9pm

## Acceptance

- [x] Community call hosted and recorded 
- [x] Uploaded to Youtube and blog post 

## Tasks

Pre-event

- [x] Confirm speaker
- [x] Confirm details with google form https://forms.gle/gfZfKEATSmusp5AW7
- [x] Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [x] Create Canva graphic using template 
- [x] Create registration using Zoom / lu.ma: https://lu.ma/8obzza6h
- [x] Create the blog post
  - [x] Include image, registration link, biography of speaker or description of the event
- [ ] Promotion
  - [ ] Emails
    - [ ] Initial announcement (main group) on if newsletter was more than a week ago 
    - [ ] Day before announcement (main group) only if initial announcement was more than a week ago
    - [ ] Email reminder (recipients)
- [ ] Plus in newsletter (if applicable)
  - [ ] Whatsapp
  - [x] Initial announcement
    - [ ] 3 days before
    - [ ] Day before
    - [ ] 1-2 hours 
  - [ ] Twitter
    - [x] Thread for initial announcement
    - [ ] 3 days
    - [ ] Day before
  - [ ] Instagram
    - [ ]  Stories
      - [ ] Story template or resharing post
      - [x] Initial
      - [ ] 3 days before
      - [ ] Day before
  - [x] Post for initial announcement 
  - [x] Linkedin Event created 

Post-event

- [x] Make the youtube video
- [x] Update original blog post with youtube video plus information 
- [x] Title: Should include name of person, plus keywords/topic
- [x] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [x] Copy of zoom recording [saved here in Raw Content log
- [ ] Update CRM with links etc. 
- [x] Let the speaker know and make it easily shareable 

### Socials text
to be completed

**Comment by laurenwigmore** [comment]
FIXED
