### ISSUE TITLE
Ontological Politics recordings 2022 - publish the material

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1115]
Consolidate and publish the ontological politics materials.

Have beginnings of a course outline (audio)

https://drive.google.com/drive/u/0/folders/103I49U0O6EevceK8uVA49QP5UETrB2r1

## Status 2023-08-23 (when Jake finished)

- Transcript Write Ups for first 3: https://hackmd.io/@dXA5rhguQmebRR8TmcSQtw/ByJ_HWlj2/edit **This looks like an otter summary rewritten and expanded**
- Section titled write up of first three on HackMd listed above - contains detailed write up of recordings as well as links to edited Otter AI transcriptions ✅ 
- Issues: Recording quality very poor and relatively frequent interruptions --> Otter AI really struggled with transcribing the text accurately.
- Learned: During future recordings, prioritise environment with no background noise and proper access to microphone.

## Acceptance

- [ ] ...

## Tasks

- [x] Check access to recording **2023-06-30 Can't get access** **✅2023-06-30 have access**
- [x] Upload no 1 and no 2 to otter and get rough transcript
  - [x] check quality given background noise
- [ ] Tidy a bit (in otter or markdown/obsidian)
- [ ] Create sections / summary (can use otter ones and improve)
- [ ] What's view on the material so far?

## Links to Otter Transcripts

- [ ] Audio 1: https://otter.ai/u/85LsnSgQiCd1XlxcD4pGrIDEznA?utm_source=copy_url **length, quality of transcript, copy/paste the otter summary below**
- [ ] Audio 2: https://otter.ai/u/pDP5EwuDiPQSjabzQQlWlY-zF1A?utm_source=copy_url
- [ ] Audio 3: https://otter.ai/u/Uvk2D_BxLO-9ZnQGuITDKeTK5Q0?utm_source=copy_url

Radha's Observation

- [ ] The audio quality is bad, I edited roughly 10-12 mins of each audio file on otter.
- [ ] Otter transcripts are good, there are a few words which needs to be fixed.
- [ ] **Suggestion:** It would be a great idea to do some keyword research and transform this transcript to an SEO rich blog.
- [ ] **Hackmd:** This transcript looks much better for each audio **Is this actually transcript or a rewritten version of the text?**

### Recording 1 ...

...

**Comment by rufuspollock** [comment]
@RadhaHarilal when doing comments can you provide a bit more info. See e.g. https://lifeitself.org/tao/issues#completing-tasks for more background.

As just discussed you are also now going to update as per bolded stuff here ...

<img width="845" alt="image" src="https://github.com/user-attachments/assets/2d98bdd8-30ca-4e91-8c69-18667fcd547f">

**Comment by RadhaHarilal** [comment]
@rufuspollock Thank you for your feedback. I have updated the length, quality and summary of transcripts. I have also updated your query about Hackmd. Let me know if this is good to go.

**Comment by rufuspollock** [comment]
@RadhaHarilal can you upload the rest of the recordings now to otter from the drive folder and add links to them (both to drive version and the otter version) like you have for existing ones (with just otter links)

**Comment by RadhaHarilal** [comment]
@rufuspollock I have uploaded all the recordings to otter and updated both the links to the otter and the drive. Feel free to let me know if you need any more assistance.
