### ISSUE TITLE
Ordinary People: Kyle Kowalski - Slowww Podcast Publish End of Aug

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1117]
Note: OP episode

## Acceptance

- [ ] Podcast page on substack completed and released w/c 2024-08-26
- [ ] Episode live on Youtube
- [ ] Episode live on Spotify & Apple
- [ ] Promotional tie-in completed 

## Tasks

- [x] add video entry to clog
- [ ] edit the video if needed ❌ _not needed_
- [x] add to Youtube 
- [x] optimise video using checklist 🚧 
- [x] create canvas templates 
- [ ] create/add jingle to podcast
- [x] write short summary about this specific podcast ✅ and person 🚧 _asked Kyle if has a bio he wants to supply_
- [x] Add to substack as a post 🚧 _saved as draft_
- [x] Pushed through to all podcast hosts (spotify and apple)
- [x] Upload on youtube and release
- [x] Guest informed that the episode is out and has been sent the links
- [x] The new episode has been announced on Twitter and other socials
- [ ] Shorts created for promotion and released ❓ _based on time constraints and our other focuses this/next week I'm not sure this will be done as a short ahead of release but could be completed after for our YT optimisation or podcast divided up_
- [x] Promotional tie in - Kyle promoting via newsletter
  - [x] Contacted Kyle
  - [x] copy provided

**Comment by laurenwigmore** [comment]
Fixed. Released and Kyle notified 2024-08-29.

**Comment by laurenwigmore** [comment]
Fixed. Released and Kyle notified 2024-08-29.
