### ISSUE TITLE
Conscious Communities Connection Call - 11 Sept 24

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1122]
## Acceptance
 
- [x] Announcement live
- [x]  First Conscious Communities Connection Call takes place 11 Sept 24 6pm CET
- [x]  Following calls scheduled and advertised

## Tasks
 
- [x] Post annoucement
- [x] Write purpose statement
- [x] Future dates for future calls to be added to lu.ma and set up
- [x] Add to Life Itself event calendar
- [x] lu.ma event set up - https://lu.ma/4pd4n6k6
- [x] Promote on social media
  - [ ] Whatsapp
  - [ ] IG
  - [ ] Twitter
  - [ ] LinkedIn 

### Document reference
[Connection Calls Plan](https://docs.google.com/document/d/11qQtWnOyuQcbMrpSQkQvWJLE2nhqi_PBuF6U6-6efQk/edit)
[Conscious Coliving program vision Aug 2024](https://docs.google.com/document/d/1wSdjmQgllX8JYAP-ku5fReHJ8a77ps0RBDvOZujwcMc/edit#heading=h.1b6lni5129h8)

**Comment by laurenwigmore** [comment]
FIXED. First call held - with 11 attendees (18 registered), next call scheduled for October 16th.
