### ISSUE TITLE
September 2024 Newsletter

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1123]
## Acceptance
 - [ ] Newsletter is released
 - [ ] Newsletter is sent as an email
  
## Tasks
- [x] Write newsletter in Substack 
- [x] Info from Hub/Residencies published via their Substack (october)
- [x] Test Newsletter
- [x] Add any new signups on old newsletter subscribe form to Substack
- [x] Newsletter is scheduled 

## Notes of items to include
- [ ] 2R video - launched ❌ 
- [ ] update on explorer course - next one in October ❌ 
- [x] Events calendar - workspace, deep resilience, connection, coco
- [ ] ~DDS website launched &~ ECT event ?? - _postpone to Oct newsletter_
- [x] Scholars Series launch
- [x] Rufus and Sylvie with on podcast: https://alistairlanger.de/podcast/50-cultural-evolution-life-itselfs-blueprint-for-a-second-renaissance/
- [x] Wall-E film night
- [x] Promo Bonnitta Roys course - https://www.endemic.org/divinityschool 
- [x] Hub manager & Autumn residency
- [x] Stephen Deluge release
- [x] Impermenance magazine launch & art manifesto
- [x] 2R & tech post

**Comment by laurenwigmore** [comment]
FIXED.
