### ISSUE TITLE
September 2024

### ISSUE THREAD

**Issue by RadhaHarilal** [life-itself/community#1124]
Radha's Work in the month of September

```[tasklist]
### Tasks
- [ ] Acceptance
```
:
Prepare the tasks for the month of September. 
Mention week-wise hours for the tasks

```[tasklist]
### Tasks
- [ ] **Week:** 12-13th Sep
- [ ] **Hours:** 8 
- [ ] Identify facebook groups 
- [ ] Content Creation (creatives/infographics/reels/shorts)
- [ ] **Week:** 16-20th Sep
- [ ] **Hours:** 30
- [ ] Identify facebook groups 
- [ ] Content Creation
- [ ] Edit YouTube videos
- [ ] **Week:** 23-27th Sep
- [ ] **Hours:** 30
- [ ] Identify facebook groups 
- [ ] Content Creation
- [ ] Edit YouTube videos

 
```

**Comment by laurenwigmore** [comment]
Hi Radha, I've made a few amends - you don't need to use the table layout for this necessarily. I would also allocate next to each task the division of the time and more detail e.g. Content Creation for X - 5 hours etc.
