### ISSUE TITLE
October 2024 Newsletter

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1128]
## Acceptance
 - [x] Newsletter is released
 - [x] Newsletter is sent as an email
  
## Tasks
- [x] Write newsletter in Substack 
- [x] Info from Hub/Residencies published via their Substack (october)
- [x] Test Newsletter
- [x] Add any new signups on old newsletter subscribe form to Substack
- [x] Newsletter is scheduled 

## Notes of items to include
- [x] ECT report and webinar
- [ ] Map and Directory Announcement

**Comment by laurenwigmore** [comment]
FIXED.

**Comment by laurenwigmore** [comment]
FIXED.
