### ISSUE TITLE
Zak Stein Podcast Episode Release & Promotion

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1129]
## Acceptance

- [x] Episode live on Youtube
- [x] Episode live on Spotify
- [x] Podcast page on substack completed and sent as a mailout
- [ ] Social media promotion done - goal 200 views in 1 week (by Friday 11th Oct)
- [ ] Featured in October Newsletter

## Tasks

- [x] add video entry to clog
- [ ] edit the video if needed
- [x] add to Youtube 
- [x] optimise video using checklist
- [x] create canvas templates 
- [ ] create/add jingle to podcast
- [x]  write short summary about this specific podcast and person
- [x] upload on spotify and release
- [x] upload on youtube and release
- [x] Add to substack as a post
- [x] Guest informed that the episode is out and has been sent the links.
- [x] The new episode has been announced on Twitter and other socials
- [ ] Shorts created for promotion and released
  - [ ] [Section identified](https://docs.google.com/spreadsheets/d/1J4ixo60zZ3u_r0-I24lM8KGS3MpB_JpZwqeTvW-pyw4/edit?gid=0#gid=0) 
  - [x] Teaser
  - [ ] 2nd short
  
 **Social Media / Promotion Tasks**
 @RadhaHarilal to add details
 
```[tasklist]
### Tasks
- [ ] **Promote Video on FB groups**
- [ ] Daily join 10-15 fb groups (search using relevant keywords - in this case metacrisis etc.)
- [ ] While search the groups, read the 'about' section of the group
- [ ] Check if there is engagement in the group
- [ ] Check if relevant topics are posted in the group
- [ ] Check if promotion is allowed
- [ ] Only if the group is relevant, there is engagement, and promotion is allowed, join the group
- [ ] At times, the groups do not allow to join using the Company Page. But if the group is very good, you may join using your personal account (optional)
- [ ] Once you are added to the group, you may promote your video.
- [ ] Everyday the upper limit to post on groups is around 15-20 groups, after which FB will block your account for 24 hours (you wont be able to post on groups) to prevent spamming.
- [ ] **Promote video on LinkedIn groups to get more views**
- [ ] Similar to FB groups, check for LinkedIn groups and send request
- [ ] At any given point of time, your account cannot have more than 20 pending requests for groups on LinkedIn. So, join only 5 groups on daily basis, and keep a tab of pending requests.
- [ ] Delete the requests on daily basis to avoid more pending requests
- [ ] Audit the group before joining
- [ ] Check if there is engagement
- [ ] Check if the group is relevant to our topic
- [ ] Once request is accepted, you may promote in 10-15 groups per day
- [ ] **Promote link on Twitter**
- [ ] Groups in Twitter are called as communities
- [ ] It is difficult to find communities for our target audience on Twitter
- [ ] We can upload reels, and post links to YT video
- [ ] The edit option on Twitter is available only for paid members, so if there is an error while uploading, you need to delete the post and upload again
- [ ] Page analytics has been moved to paid members as well
- [ ] While Promoting on Twitter, add two tweets, 1. Upload the reel directly, and in the description add the tiny url of the YT video link. 2. Post the tiny url link on the tweet.
```

```[tasklist]
### FB groups and checklist for FB and LinkedIn promotion
- [ ] https://docs.google.com/spreadsheets/d/1sL_pUUjpWqpa2myVlcBVyOr0pm0iBuaUeaKcCQH3j9k/edit?usp=sharing
```

**Comment by laurenwigmore** [comment]
Notes on items to address in future:
- YT title and description was changed - which meant it didn't align with the graphic, mailout and podcast description. Q: How much does this really matter? 🔑 work around was to include title in top part of YT description
- Wrong logo used on end screen of reels
- incorrect key word not amended on a reel that was shared and had to be deleted from all platforms

**Comment by laurenwigmore** [comment]
@RadhaHarilal can you extend on your tasks please for example: 
- Promote video daily in facebook groups: 1-3 groups per day from X list (and link to a spreadsheet of the groups you are posting in)
- Promote on twitter every other day  using a minimum 3 post thread 
etc

**Comment by RadhaHarilal** [comment]
@laurenwigmore 

- I have not kept a tab of groups, most of the groups doesn't allow to join using the fb page, so I join using my personal account and post on daily basis. Today onwards I will note down the links of groups and provide the link here.
- I have been posting once on Twitter. Today onwards I will add 3 posts.
- We can run this for one more week.
- I will create this checklist tomorrow first thing.

**Comment by laurenwigmore** [comment]
Hi @RadhaHarilal can you update the tasks in this issue and include the above items from your comment in the appropriate spreadsheet please.

**Comment by RadhaHarilal** [comment]
@laurenwigmore Please check and let me know if this is what you are looking for and need anything else on this issue.

**Comment by laurenwigmore** [comment]
FIXED and [Radha's task notes moved to our Gdrive for future reference](https://docs.google.com/document/d/1nxwe7NcwKLJ9wPwgrE08TauXMOMy5FHQEQSJa_ZarqY/edit?tab=t.0)
