### ISSUE TITLE
Publish 2R Tech Talk

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1130]
Talk given as part of Stephen Reid's community sharing on Sept 17th 2024.

## Acceptance

- [x] Talk and slides are live on Substack
- [x] Talk is live on YouTube

## Tasks

- [x] [Download talk](https://drive.google.com/drive/folders/1Aj4GY6vntE-zXg38y0bCIBfetJLYP0pV)
- [x] Slides (add link)
- [x] Add to clog
- [x] Review thread and [notes](https://docs.google.com/document/d/1a3xYCTvdNcmEgtjeSavCuAehrVmDN_RhJTqoRZ-ZzlM/edit#heading=h.1nerbpmt7ejj)
- [x] Upload to YouTube
- [x] Source appropriate image / create in canva
- [x] Check with Stephen if OK to include full Q&A
  - [ ] If no, edit video recording to include only actual presentation (and maybe response to Q&A - that’s just bonus)

**Comment by laurenwigmore** [comment]
FIXED.
