### ISSUE TITLE
Life Itself Branding and Website Relaunch Phase I

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1133]
Phase I of the updates and strategy from the extensive work done with Hannah.

[See this document for notes, outputs and other links](https://docs.google.com/document/d/1rLBPmwE6CjknoUDaxu1SKT6D9u5HNv5jMFYOeTbsO_s/edit?usp=sharing)

Phase I: Inner Development Goals Conference is taking place on 16-18 Oct. Catherine will be at the conference. We want to:
a) have merchandise to take to the conference
b) have our website updated following on from the output from Hannah
c) have our Comms SCQH completed - with a Phase II detailed

### Good, Better, Best Outcomes:

- **Good:** Website is live with core content updated and functional
- **Better:** Website is live with new content, restructuring, user engagement features (search bars etc), and resources available (e.g., learn resources, project info)
- **Best:** Website is fully updated with new branding, resources, and social media campaign ready, with launch post and announcements published

**Appetite:** 8-14 Oct (5 calendar days) - 12 person days? TBC

**Availability:** 

- Lauren: 25-30hrs focused solely on this across the 5 days

## Acceptance

- [ ] Catherine attends conference with merchandise
- [ ] Website is updated and live

## Tasks

- [ ] Assign Project Manager ✅ _Lauren_
- [ ] Pull items from Comms SCQH doc into Coggle question tree ✅ _top focuses noted with 🔥 _
- [ ] Decide objectives of phase I : 🔑 _To have a fully functioning website with a clear communication strategy ready for the upcoming conference_
- [ ] Map out plan of work

**IDG**
- [ ] Decide on merchandise - quantity, budget, quick turn-around and delivery to Sweden
- [ ] Order merchandise
- [ ] Copies of Impermenance Magazine and ?? printed and lamenated for on-stand reference
- [ ] Decide main CTA to direct people to (website? map?)
- [ ] Links: [Marketing Brainstorm](https://docs.google.com/presentation/d/16QwboUMrh3wstFNwfKf3ApSdMHgZE3s3Nueq4VOuVKQ/edit#slide=id.g309bf86ea6b_0_0) & [Plan of work}(https://docs.google.com/document/d/12uoVM6_NodZ-EFEMXij6TPkd9Nly48kVqMxusY-z9PI/edit#heading=h.e03mh4l3v38a)

**Website**
- [ ] Define what copy needs to be written
  - [ ] Home page 
  - [ ] Media/learn 🔥🔥 
  - [ ] About
  - [ ] Residency 🔥
  - [ ] Studio 🔥🔥
  - [ ] CoCo
  - [ ] 2R 
- [ ] Draft copy
  - [ ] Home page 
  - [ ] Media/learn 🔥🔥 
  - [ ] About
  - [ ] Residency 🔥
  - [ ] Studio 🔥🔥
  - [ ] CoCo
  - [ ] 2R 
- [ ] [Audience online engagement channels](https://docs.google.com/spreadsheets/d/1-LC0fk8cSJwHvyoDBYXbzODlqGgoMVltYObpmhdnyzQ/edit?gid=988896312#gid=988896312)
- [ ] Where will we host the website
  - [ ]  Do we need a developer to help set up?
- [ ] Graphics and branding update _would suggest this is paused until Phase II_  
- [ ] Review website layout (see excalidraw for 5 main pages)
  - [ ] How do we order all of our pages / content
  - [ ] What can be archived? 
  - [ ] Is the blog staying on substack?
    - [ ] Impacts our sign-up options (still currently Brevo) 
- [ ] Test website functionality
- [ ] Draft launch post _phase II?_
- [ ] Announce the new website via email and social media _phase II??_
- [ ] Write up plan for Phase II
- [ ] Comms SCQH finalised

**Comment by laurenwigmore** [comment]
Figma drawing's and copy linked to Strategy Meetings doc
