### ISSUE TITLE
Migration of Hub substack over to LI substack

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1137]
## Acceptance

- [x] Pitch completed
- [ ] Substack migrated

## Tasks

- [x] Conduct shaping 
- [x] Add identied tasks from the shaping
- [ ] Export all data (posts and subscribers), 
- [ ] Import it into LI substack. 
- [ ] Add and amend the section headings to include a Residencies section (as this is the main CTA that the Hub/LI wants - attendance at residencies). 
- [ ] Update the tags on the site to include the ones appropriate to the Hub. 
- [ ] Moving forward write the newsletter updates directly into the LI newsletter. 
- [ ] Keep a record of the metrics/statistics on the Googledrive, if they aren't transfered across to the LI substack
- [ ] Close the Praxis Hub substack
- [ ] Update the links to the Praxis Hub substack on the LI website
  - [ ] Residency
  - [ ] Hub
- [ ] Check with Valerie if any other links need to be updated e.g. on whatsapp

---
## Shaping

- Appetite: 4-6 hours including shaping and migrating
- Situation: We want to move the Praxis Hub substack across to be a part of the LI substack.
- Problem: We aren't sure how to do this, and how to adapt the LI substack to include the Hub.
- Solution: Use the export and import option for the posts and subscribers, and have one subheading - Residencies. Update external links to the LI substack. Close the Praxis Hub substack.

#### Situation

- We recently had a marketing and strategy review completed.
- It was suggested that we have too many 'entry' points for people trying to find and join us.
- Migrating the Praxis Hub substack into the LI substack was discussed.

#### Complication

- We do not know how to or if we can migrate the substacks.
- The LI main website is being redesigned.
- We do not know if the blog will move and be included in the redesign or stay on Substack.
- We do not know when the website redesign will be completed.
- Will the Hub continue to do it's own Newsletter or will we write it directly on to the LI newsletter moving forward?

#### Hypothesis

- Use the import/export method for both posts and subscribers
- Set up a Praxis Hub section - decide what to call it: Residencies, Praxis Hub?
- Add tags of: Contemplative Activism, Residencies, Testimonials
- Update 'About' to include information on the Hub
- Keep a record of the metrics/statistics on the Gdrive, if not automatically updated on to the LI substack in the import

#### Notes

- Research on forums and substack if substacks can be merged: _:x no they can't but they can be [exported](https://support.substack.com/hc/en-us/articles/360037466012-How-do-I-export-my-posts) and [imported](https://support.substack.com/hc/en-us/articles/360037830351-How-do-I-import-my-posts-from-another-platform-such-as-Mailchimp-WordPress-Medium-or-Ghost). Note the import doesn't refer to exported posts from substacks but it seems highly likely it would be exactly the same_
- Duplicate subscribers are not added

#### Rabbitholes

- Do not get sidetracked redesigning/amending posts once they have been moved across
- Do not start analysing the metrics

**Comment by laurenwigmore** [comment]
@rufuspollock the shaped pitch is above for the migration of the Hub substack to the LI substack. If this is fine, I'll add this to the calendar plan for November (which I'll share soon).

**Comment by rufuspollock** [comment]
@laurenwigmore i've reviewed and well done on a clear, thorough pitch. Some thoughts that came up as i read it:

- 🚩🔥⛔ An important situation and complication point that should happen *before* we do implementation
  - Valerie is currently main user of praxis substack. Is she happy/onboard with the consolidation? She didn't really get to speak to hannah to hear the strong argument for consolidation. We should check Valerie is ok with this ...
  - Thus, it would be key to check with Valerie about this (and Liam too). **This may require Rufus to have a quick chat**
  - Would also be nice to flag to proto-trustees. However, that can just be whatsapp update on proto-trustees channel. And Catherine can do this as she is on that group!
  - One could flag that this is reversible - we can leave existing substa
- You mention uncertainty about what the section is called. This raises the broader question of what the hub should be called. Again, Hannah had a recommendation that we use simple consistent naming e.g. Bergerac Hub (see line 51 in https://docs.google.com/spreadsheets/d/1-LC0fk8cSJwHvyoDBYXbzODlqGgoMVltYObpmhdnyzQ/edit?gid=27157188#gid=27157188)
- As i understand subsections in substack, they can have a separate email list. However, when you mail that list you always mail that list *plus* the "default" list. If we want to be able to email specific Residencies/Praxis list we need to move newsletter subscriptions to a separate substack list/subsection called newsletter (this would, in fact, make sense anyway). Then newsletter only folks would not get random residency updates.
  - NB: we would *not* need to do this for people who have subscribed specifically to substack since its creation since those people were implicitly/explicitly signing up for everything. It would just be the people coming from the newsletter source on Life Itself 
  - You would want to do this change *before* we import the user list so that we didn't incorrectly "deduplicate" (we would only want to deduplicate with pure substack signups now with newsletter signups)
- There's no info in hypothesis what we do with praxishub.substack.com once we have "shut it down". If we delete it, we can't set up redirects. Thus, i imagine we want to put a big featured post on it saying "MOVED TO XXX" or similar.
  - 🚩 (another action i then thought of) we also want to remove praxishub from our recommended list on life itself news ...
- Lastly, given substack will stay around i would see archiving stats info as relatively minor item (we can always login later and get stuff)

**Comment by laurenwigmore** [comment]
@rufuspollock I've touched base with Valerie on this in the Team Meeting today. It was suggested that

- Mid November time (if this works re the baby) for you, Valerie and Liam to meet. I'm happy to attend as well if deemed useful. 
- Meeting to discuss keeping the current Hub substack open and tranisitioning it into use for Post Secular Praxis Hub residencies moving forward.
- The section on the LI substack to be called The Bergerac Hub. ✅ 
- To use this section to detail all info related to news, and residencies at the Hub, with appropriate sign-posting to external websites for more information and residency sign up where applicable.
- I will hold off taking any action on the migration until a conversation has been had on this.

**Comment by Postnormalval** [comment]
hello 
A quick comment just to ask to move with that in January if possible.as I have no time but feel very concerned by the move and Liam too.  Please wait to all be agreed on the best way to do that with Liam and myself when circumstances will allow. It is not just Rufus and Lauren's  decision  I feel as most residencies were under Praxis culture which under  life itself  banner yet  it should been  specific within all residencies general landscape  to  build on that work properly as other specific residencies .

**Comment by rufuspollock** [comment]
WONTFIX. For now we won't do this and we'll leave praxis in existence.
