### ISSUE TITLE
November 2024 Newsletter

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1138]
## Acceptance

- [x] Newsletter is released
- [x] Newsletter is sent as an email

## Tasks

- [x] Write newsletter in Substack
- [x] Info from Hub/Residencies published via their Substack (october)
- [x] Test Newsletter
- [ ] Add any new signups on old newsletter subscribe form to Substack
- [x] Newsletter is scheduled

## Notes of items to include

- [x] Bonnitta Roy podcast II
- [x] Barnraising - 3rd Dec
- [ ] Blogs - 
- [ ] Map and Directory Announcement (carried over from Oct - not added by Catherine in last month's)
- [x] Can you be a Multiplier? - Woman´s leadership programme for NGOs/CSO, academia and public institutions - Vienna Jan 2025 (see email from Catherine 18.11.24)

**Comment by laurenwigmore** [comment]
FIXED.
