### ISSUE TITLE
Bonnitta Roy Podcast Episode 2 Release and Promo

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1139]
Release podcast no.2 of Bonnitta Roy

## Acceptance
 
- [x] Episode live on Youtube
- [x] Episode live on Spotify
- [x] Podcast page on substack completed and sent as a mailout
- [x] Social media promotion done
- [ ] Featured in November Newsletter

## Tasks

- [x] add video entry to clog
- [x]  edit the video if needed 🚧 _waiting for descript access to trial removal of ums etc_
- [x]  add to Youtube
- [x]  optimise video using checklist
- [x]  create canvas templates
- [ ]  create/add jingle to podcast
- [x]  write short summary about this specific podcast and person
- [x]  upload on spotify and release
- [x]  upload on youtube and release
- [x]  Add to substack as a post 🚧 _draft done_
- [x]  Guest informed that the episode is out and has been sent the links.
- [x]  The new episode has been announced on Twitter and other socials

## Social Media / Promotion Tasks
- [x] Sections identified for shorts creation 
- [x] Shorts created for promotion and released 🚧 _completed 1/2 to be tried via Descript_

**Comment by laurenwigmore** [comment]
FIXED.
