### ISSUE TITLE
Follow up / tidying following split of notes.lifeitself.org and lifeitself.org in #1089

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1142]
Follow up to #1089

```[tasklist]
### Tasks
- [ ] BONUS (FUTURE): clean git history and remove all the git lfs stuff so that cloning is fast (plus )get it purged by github so it does not count to our quota
- [ ] Remove notes stuff on lifeitself.org site (this requires checking what pages reference notes atm e.g. some stuff in tao - i recommend we copy those items *back* into tao so tao is self-complete)
- [ ] Redirect lifeitself.org/notes to notes.lifeitself.org and remove all the notes stuff from the repo 5-30m
```

**Comment by rufuspollock** [comment]
FIXED.
