### ISSUE TITLE
Publish Research Call - Nicholas Wilkinson

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1143]
## Acceptance

- [x] Recording is published
- [x] Post on substack is published

## Task

- [x] Description of call provided
- [ ] Description of series (?)
- [x] Canva image done
- [x] Recording saved on shared drive Raw Content folder
- [x] Added to clog
- [x] Uploaded to YouTube
- [x] Added to Substack
- [x] Shared in whatsapp group

**Comment by laurenwigmore** [comment]
FIXED.
