### ISSUE TITLE
[epic] Plant trees and permaculture at Farmhouse Hub Winter 2024

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1144]
We want to do some tree planting and come up with something of a (permaculture) plan for the land at the PBM hub.

🔗 https://notes.lifeitself.org/Tree+planting+and+wild+garden+design+at+farmhouse+hub

### First day on the land 2024-11-25

- [x] Calendar invite
- [x] Chat with Lucy
- [x] Walk the land
- [x] Next steps **✅2024-11-25 in excalidraw atm**

### Prep background info

- [x] Create an overview map for people to orient themselves **✅2024-11-25 https://link.excalidraw.com/l/9u8crB2ZmUo/2b2Zq1UhuVq**
  - [x] Google maps etc layout of land.
  - [x] ⏭️ Videos of the land linked into overview
    - [x] Edit the video flyovers
    - [x] Post flyovers somewhere (instagram and/or youtube)
    - [x] Link them to the map
- [x] Soil analysis (old)
  - [x] Find old one in drive and share it **✅2024-11-25**
    - [x] Find it
    - [x] Link it **✅2024-11-25 added to excalidraw and linked to full version in drive**
  - [x] Do pH etc analysis
    - [x] buy pH measuring system **✅2024-11-21 ordered on amazon https://www.amazon.fr/dp/B0BBGH5BM6?ref=ppx_yo2ov_dt_b_fed_asin_title**
    - [x] Do analysis and add somewhere e.g. to the plan **🚧2024-11-23 did a first test**
- [x] Research permaculture etc
  - [x] Ask for suggestions **✅2024-11-18 **
  - [x] Collate suggestions **✅2024-11-20 here https://notes.lifeitself.org/Tree+planting+and+wild+garden+design+at+farmhouse+hub**
  - [x] Pick a book to read **✅2024-11-22 [[whitefield-2004-earth-care-manual]]**
  - [x] Read it and summarize **🚧2024-11-22 told S about some of it. Read about 100 pages**

### Create a todo list and track the items

- [x] Choose the system **✅2024-11-25 let's just use github**
  - [x] Options **github, notion, excalidraw, ...**
  - [x] Criteria
  - [x] Evaluation
- [x] Extract existing items and add them
  - [x] From Lucy's whatsapp post
  - [x] My list above

### Setup coordination mechanism

- [x] Have a whatsapp group? **Yes**
- [x] Set it up and have an invite link **✅2024-11-20**

```[tasklist]
### Plan of planting and ordering
- [x] Get planting plan
- [x] Identify tree nurseries **✅2025-01-28 we have 2 options that are good (see below)**
- [x] Schedule time to go **✅2025-01-28 going on sunday 2nd feb**
- [ ] Call Desmartins Pepiniere (ciel)
- [ ] Get manure ... **🚧2025-01-28 have confirmed price of around €100 for delivery (with donation). Lucy will schedule for w/c 2025-02-03**
- [ ] Research grants for walnut trees (call mayor?)
- [ ] Schedule planting day(s)
```

```[tasklist]
### Buy mycorrhizal fungi
- [x] How much? 4kg for 70 trees
- [x] Where to buy? **✅2025-01-28 https://www.amazon.fr/s?k=mycorrhizal+fungi&crid=3FY572RSTPKF0&sprefix=mychorr%2Caps%2C148&ref=nb_sb_ss_sc_3_6 estimate about €25/kg**
- [ ] Order them ...
```

### Where to buy plants

- Proflora Bergerac - https://www.google.com/maps/place/Proflora/@44.8254522,0.4685293,1774m
- Pepinieres Desmartis at Bergerac https://www.pepinieres-desmartis.fr/ - https://maps.app.goo.gl/dQTnCdd5uW2J7Ljn7

![Image](https://github.com/user-attachments/assets/57e085d7-ede0-41a6-9c89-0915f9f3eafd)

![Image](https://github.com/user-attachments/assets/08d45ca3-0fa9-4fa0-9a9c-9b1638eecfd6)

**Comment by rufuspollock** [comment]
We have done all the prep. Now need to get advice on trees and plant them in Jan. Pausing until then.

**Comment by rufuspollock** [comment]
FIXED.  (for now).

We achieved a lot:

- Have overview info including flyovers
- Got lake permission
- Made good contacts
- Have a detailed plan
- Identified where i can buy stuff

What we didn't achieve: actually planting anything 🌳🤣

What i posted on whatsapp

@⁨Lucy Vignola⁩ @⁨Jo Vignola⁩ @⁨Paul (Poogly)⁩ @⁨Karen Pollock⁩  It seems like spring is already here and it is quite warm e.g. daffodils are coming out, i see buds on trees …

I assume that means it is is a bit too late for tree planting this year? (❓)

also there is the idea we should create a berm / swale and that requires some pre-preparation — thus if we were to do anything this year it would not be until early / mid March (which i imagine is really too late).

Even so we have made immense progress this year …

•⁠  ⁠📝 we have a detailed info on the land and what we should do
•⁠  ⁠🗺️ we have a clear plan
•⁠  ⁠⁠🌳 thanks to detailed help especially from @⁨Jo Vignola⁩  we know what to plant and where we can get it ...
