### ISSUE TITLE
January 2025 Newsletter

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1145]
## Acceptance

- [ ] Newsletter is released
- [ ] Newsletter is sent as an email
- [ ] Newsletter is shared in whatsapp chat

## Tasks

- [x] Write newsletter in Substack
- [x] Info from Hub/Residencies published via their Substack (october)
- [x] Test Newsletter
- [x] Add any new signups on old newsletter subscribe form to Substack
- [x] Newsletter is scheduled

## Notes of items to include

- [x] Hub / residency update? 🚧 _awaiting to be published_
- [ ] 2R Con? ❌ _next month_
- [x] 2R Newsletter launch
- [x] Impermanence Magazine Launch success 🚧 
- [x] Gathering March/April at Hub (Catherine's announce)
- [x] Promo Forum 🚧 _to publish post first_
- [ ] Research community update ❌ _next month_
- [x] Interactive map update

**Comment by catherinet1** [comment]
Hi @laurenwigmore, cc @JonahWilberg  -- a suggestion for this month's newsletter -- include a research community update, sharing the research community 2R research agenda/plan (+ how people can get involved)?

**Comment by catherinet1** [comment]
Hi @laurenwigmore - an item for this newsletter: announce new interactive version of 2R ecosystem map.

Text for it is drafted in this doc: https://docs.google.com/document/d/13u7Q3a46yEENXBjok0XyuM5mmhr0e7W6Q9zxvOmxrHg/edit?tab=t.0

**Comment by laurenwigmore** [comment]
Hi @alexandrageorges I hope you're feeling better! Will you be able to draft and post an article on the Bergerac substack today or tomorrow so I can link it in to the newsletter going out this week (on Tuesday or Wednesday)

**Comment by laurenwigmore** [comment]
FIXED.
