### ISSUE TITLE
[epic] 3 New Learn Pages (Lauren Dec 2024) (Obsolete)

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1147]
Sub part of

- #568 

## Acceptance

- [ ] Shaping signed off
- [ ] 3 learn pages live
- [ ] Landing page for Learn Pages resource live

## Tasks

- [ ] Submit shaping (see below)
- [ ] Select topics for learn pages
- [ ] Compile resources for each learn page and create pages for
  - [ ] Bonnitta Roy 
  - [ ] Conscious Parenting - https://github.com/life-itself/community/issues/94
  - [ ] Christopher Alexander / Conscious Architecture
- [ ] Create a landing page for the Learn Pages beacons 

## Promotion / socials

- [ ] https://github.com/life-itself/community/issues/1079
- [ ] plan for promotion created

## Shaping of the Learn Pages

**Appetite:** 1-1.5 person days to create 2-3 learn pages & landing page
**Situation:** We have a few learn pages on our website, and we have more that can be added, to help share our material.
**Problem:** There is no central landing page for the learn pages resource to be found. The LI website has been under review and there has been a suggested redesign, and there a number of topics we could choose for our learn pages to start implementing.
**Solution:** Focus on adding 3 new learn pages on Bonnitta Roy, Conscious Parenting and Christopher Alexander / Conscious Architecture (using the previously listed layout and guidelines) and create a main landing page to list and hyperlink these resources too.

### Situation

- We currently have 3 learns pages on our website
  - https://lifeitself.org/learn/fundamental-wellbeing
  - https://lifeitself.org/learn/cultural-evolution
  - https://lifeitself.org/learn/praxis-ecology
- We want to add more learning pages and have a list on Github of potential ones
- We have a previously drafted SCHQ on https://github.com/life-itself/community/issues/568 which highlights that we already have a fair amount of material on specific topics/ideas e.g. fundamental wellbeing (waking up), second renaissance, great grasping/shadows of enlightenment, web3 (analysis of tech utopian aspirations) etc
- Learn Pages are quick win resources hosted on our website, that offer a brief overview of the topic, the person, principle and include embedded associated resources from Life Itself e.g. podcast episode / YT video

### Complication

- There is no central point, such as a landing page with links, for people to navigate and find these learning pages easily
- We aren’t sure which learning pages to add first from our list
  - Conscious coliving - course, blog posts, podcast, community calls
  - Conscious parenting - podcasts, course
  - Diginomics
  - Web3
  - Once upon a time podcast series
  - Exploring Social Transformation podcast series
  - Integral Theory
  - Collective Wisdom
  - Collective Intelligence
  - Contemplative Activism
  - Ontological Politics
  - Bonnitta Roy
  - Second Renaissance
  - Christopher Alexander / Conscious Architecture
- The website is currently being updated, and the structure will change from the current set up. Although this has not been started yet. The Learn Pages could be added/referenced on our Resources page. When this may happen is tbc.
- There is a wider consideration related to how do these learn pages as a resource fit into the bigger picture and how can we use them to support our strategy moving forward
- Items that could be included for individual learn pages might be scattered in different places - podcasts, YT videos, Github discussions/issues, documents
- Our resources and offerings are often scattered and not well organized and therefore, often not shared

### Question

- How can we efficiently add useful resources, with an easy access point, for our community to use and find them?

### Hypothesis

- Create a simple landing page called Learn Pages - adding each learn page into an alphabetical hyperlinked list. Create 3 new learn pages on Bonnitta Roy, Conscious Parenting and Christopher Alexander / Conscious Architecture, using the outline/requirements as already listed in this issue https://github.com/life-itself/community/issues/568. 
- Notes
- To do separately: review the longer-term strategy and create a shaping to continue to build the learn pages as a strong easy win beacon to attract community members.
- Lauren is currently unsure how to create linked chapters on a page outside of Obsidian

### Rabbitholes

- Focusing on the redesign and structure of the website
- Overcomplicating the addition of a few pages
- Creating extra resources off of these
- Focusing too much on the 2025 strategy without implementing 3 more learn pages

**Comment by laurenwigmore** [comment]
@rufuspollock if you're able to look at this tomorrow (Wednesday) and sign off, I can start implementing at the end of this week.

**Comment by rufuspollock** [comment]
My view would be: conscious parenting, conscious coliving and web3.

Please can we do one "fat marker sketch" of one page and the learn landing page.

**Comment by laurenwigmore** [comment]
![Image](https://github.com/user-attachments/assets/2243960e-0522-48d6-951a-c324d47d459b)

**Comment by rufuspollock** [comment]
@laurenwigmore the fat marker needs more detail on the content. In this case we are content focused so the layout of the page is useful but only a part of the "fat marker"
