### ISSUE TITLE
December 2024 Highlights Newsletter

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1153]
## Acceptance

- [x] Newsletter is released
- [x] Newsletter is sent as an email

## Tasks

- [x] Write newsletter in Substack
- [ ] Info from Hub/Residencies published via their Substack
- [x] Test Newsletter
- [ ] Add any new signups on old newsletter subscribe form to Substack
- [x] Newsletter is scheduled

## Notes of items to include

- [x] Highlights of 2024: 2R, Hub, Featured
- [x] What's next 2025
- [x] Get involved/support us CTA
- [x] Merry Christmas!

**Comment by laurenwigmore** [comment]
FIXED.
