### ISSUE TITLE
Review 2021: how did we do against plan, learnings etc

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#116]
When 2021 completes we want to review what happened against our 2021 plan so that we are we complete, we get insights, we can learn and adjust/improve  going into 2022

## Acceptance

* [ ] We have an internal written review of 2021
* [ ] Key points added to tao (public)
* [ ] Summary blog post

## Tasks

Prelim:

* [ ] Identify sources for 2021 planning (including OKRs etc) **Our plan was here https://tao.lifeitself.us/plans/2021/** **Tracker/OKRs here: https://docs.google.com/spreadsheets/d/14ssxMsQbB4yAx-j6aKYrIsPcfcPTQKyEdvKIaqirQIM/edit#gid=166132929**
  * [ ] Check that this plan is up to date with the gdoc
  * [ ] ? put a note about revision in Jul-Sep 2021
* [ ] Schedule team meeting

Review

* [ ] Reflections: esp in comparison to plan
* [ ] Analysis: Time spent vs time planned and insight from that
* [ ] Retrospective
  * [ ] What worked
  * [ ] What did not work (as well as I would like)
  * [ ] Learnings
* [ ] Acknowledgements

Comms

* [ ] Blog this
* [ ] Link from Tao to the blog
