### ISSUE TITLE
Plan for 2022

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#117]
When conducting our work (especially as a highly distributed, agile, small organization) we want an overall year plan 2022 so that we have a vision of what we are up to, what needs to be done by who, and how it fits together and connects to our broader vision/plan

## Acceptance

* [x] #121 **Chose circle => stream => project**
* [x] Draft plan prepared with key workstreams and OKRs **IN PROGRESS 90% https://docs.google.com/document/d/1YFqmMPMJ4Dyx1P-yzOXWS_NODfQ6EjvRv388Ql1PMNY/edit#**
* [x] Budget against those **https://docs.google.com/spreadsheets/d/1lua4wuE2ZwB0IlYZ7gK0KSj4GFDc5F_efNkh6Umm9n0/edit#gid=1311442204**

## Tasks

Review

* [x] Review overall strategy and long-term plan **TODO: we need to finalize and release the revision of our overall strategy. Main insight is prioritizing "Pioneering a Culture" and deliberately developmental spaces near-term**
	* [x] https://tao.lifeitself.us/scqh/ **TODO: needs an update**
	* [x] https://tao.lifeitself.us/plans/ **TODO: needs an update**
* [x] Review pillars and programs that support that

Draft

* [x] Create possibility and intention for the year **Building on Bridgeheads. Solidifying, grounding, developing**
* [x] Identify any key accountabilities and constraints (e.g. time, budget, etc)
* [ ] Select from pillars/programs/products and create workstreams with OKRs and initiatives **We now have key circles and streams established, OKRs TODO**
* [x] Budgeting (mainly time) against initiatives **Done: https://docs.google.com/spreadsheets/d/1lua4wuE2ZwB0IlYZ7gK0KSj4GFDc5F_efNkh6Umm9n0/edit#gid=995046412**

Agreement

* [ ] Discuss with team
* [ ] Finalize

Sharing

* [ ] Tidy
* [ ] Publish (e.g. to tao)

**Comment by rufuspollock** [comment]
We did quite a bit of work on this in Nov-Dec here: https://docs.google.com/document/d/1YFqmMPMJ4Dyx1P-yzOXWS_NODfQ6EjvRv388Ql1PMNY/edit#

**Comment by rufuspollock** [comment]
We did more work yesterday getting a (more) detailed workplan for the 2 main workstreams.

**Comment by rufuspollock** [comment]
Draft Plan is now 90% done. All that remains there is to add key results and migrate to spreadsheet. After that team meeting.

- [ ] tidy, transfer relevant content to spreadsheet and leave space for addition (e.g. revised OKRs) @theo-cox
- [ ] schedule all team meeting, discuss with team, cocreate OKRs @theo-cox

**Comment by rufuspollock** [comment]
FIXED. See acceptance. We had a plan. 😉

**Comment by rufuspollock** [comment]
UPDATE: posted the plan to the tao https://lifeitself.org/tao/plan-2022
