### ISSUE TITLE
Second Renaissance Online Introduction Course - 5 Sept

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#1170]
2nd Explorer course - condensed into one 3 hour session on 5 Sept 6pm-9pm CET

Secondrenaissance.net is a new accessible resource for newcomers to the Second Renaissance space. A co-created discussion/presentation was recently piloted in-person at a Hub Residency in June 2024. Given the focus on the 2R movement and a recent backlog review, creating a 2R Zoom course to further engage newcomers is a prioritized next step. Why? To share and bring to life the essence of the Second Renaissance in an inspiring way so that attendees receive inspiring information, and co-sense-make with others providing an opportunity to be interactive and connect with people and leave the course with a sense of empowerment and personal and collective resonance of why it is important to be involved in creating this paradigm shift.

## Acceptance

- [ ] Sign up target met - 20 people 
- [ ] Course hosted

## Tasks

- [x] Set up on lu.ma _use copy from first course and amend accordingly_ - https://lu.ma/4tzj9o9r
- [ ] Announcement made in Connection Calls on 20th Aug & 3rd Sept
- [x] Set up zoom link for lu.ma confirmation emails _done automatically via lu.ma_
- [ ] Announcement on 2R substack
- [x] Design/create announcement images
- [ ] Initial Announcements made on Socials and Discord _posted on whatsapp, discord, IG, twitter and event on LinkedIn._
- [ ] Schedule of posting / announcing made 🚧 _Radha to link in her social media shorts to this as the main CTA in August_
- [ ] Regular posting to promote
  - [ ] Facebook groups to be used as a targetted promotional means 
- [ ] Added to Second Renaissance website 
- [ ] Included in Aug Newsletter
- [ ] Add to LI Events Calendar
- [ ] Mailout one week prior to the event
- [ ] Draft copy to share with others in our network to include in their newsletters
- [ ] Plan content and requirements for each session _Rufus and Sylvie to schedule sessions in calendars ahead of 5th Sept_
- [ ] Design / check slides if required
- [ ] Invite people directly - personal messages / emails etc
- [x] Send reminder emails ahead of sessions (schedule on lu.ma)  _scheduled to go out via lu.ma_
  - [ ] 1 day
  - [ ] 1 hours
  - [ ] 15 mins
- [ ] Host sessions
- [x] Cover for Lauren (as traveling) sourced ✅ _Radha kindly agreed_
- [ ] Send a thank you email
  - [ ] Resend feedback link (in case) 
- [ ] Offer next steps
- [ ] Pre-sign up for next Intro link for next course to share with friends - October ??
- [ ] Debrief meeting
- [ ] Next steps agreed

## Notes

2024-07-31 2R Course Sync Meeting carried across for reference

Present: Lauren, Rufus, Sylvie
Intention: To ensure we are fully prepared and ready for the course tonight and all tasks have been done

Key Responsibilities in call of producer:

- welcome/admit attendees and emergency contact shared in reminder emails
- open breakout rooms - ensure people are paired with different people for each breakout room
- Any late arrivals, take to one side (in a seperate room) and provide an update of where we have got to and where we are now, so they can enter with confidence
- recap sent at the end of course and zoom link for recording sent
- See document above for more notes

## Socials

**Whatsapp (sent 2024-08-19)**

📣 We are hosting our next Second Renaissance: A first exploration together course in September

_"It was a wonderful opportunity to hear the unique experiences and perspectives of individuals from different pockets of the world, all brought together by our curiosity or drive to bring about a wiser and better human society."_

**📆 5th September 
🕐 6pm-9pm CEST / 12pm-3pm ET
📍 Online
🎟 10€ Standard (discounts available)
🔗 https://lu.ma/4tzj9o9r**

​In this short one session course, we will explore together the following areas:

​ 🤔 **Awareness:** Exploring our paths to the second renaissance. How did you come to be interested in this? If and when did you start noticing “cracks” in the foundations? 

​🌅 **Renaissance:** Exploring what we see can arise? What kind of views and values do you think are needed going forward? 

​🌱 **Seeds:** What are the seeds of the second renaissance? Where should we plant and cultivate them? What kinds of greenhouses? What kinds of pockets of emergence are there?

​The course focuses on supporting your own exploration and discovery using small group discussion and sharing amongst the wider group.

​This format makes it suitable whether you’re a complete newcomer or already have deep knowledge of the area.

🤗 Join us and help us spread the word by sharing with your communitie

**Comment by rufuspollock** [comment]
OBSOLETE / INVALID. This got postponed.
