### ISSUE TITLE
Switch to to discourse from discord for 2R forum (and as general "landing point")?

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1175]
Hypothesis: Switch to using discourse (and deprecate discord?) as our main place for participation and discussion.

S: have both both this discord and a discourse (web) forum setup. For now, we are using discord and wanted "one place" so kept the discourse invisible.

```[tasklist]
### Tasks
- [x] Analyse pros/cons of moving to discourse for forum (and in general as replacement for discord)
- [x] Discuss this hypothesis **🚧2024-06-30 in chat and with curator group**
- [x] Set up discourse **✅2024-06-28 already done back in May**
```

```[tasklist]
### Migrate
- [ ] Switch instructions on secondrenaissance.net to go to discourse forum rather than discord chat
- [ ] transfer required content from discord to discourse (what content?)
```

```[tasklist]
### Better Onboarding
- [ ] Research how to do onboarding on discourse **🚧2024-06-28 have not found that much from 20m of googling - will list below as we find it**
- [ ] Implement onboarding on discourse
```

# Shaping

## Situation

- Want a place for people to go who want to "engage / participate / go deeper" on Second Renaissance project and specifically from secondrenaissance.net
  - Say hello
  - Engage in discussion and q&a
  - Share information
  - Find out where they can contribute
- Had set up discord and discourse prior to launch
- At launch decided to only show one of these to keep things simple and went with discord as using discord for the team
- Some activity on discord though reasonably limited
- Synchronous chat is limited importance relatively and could use whatsapp etc if needed
- Voice chat features of discord are not needed (we have hangouts or zoom)

## Problem

- Discord is a poor match to need in terms e.g.
  - post length limited
  - can't paste images
  - not internet discoverable
- Want to avoid duplication so we only really want to use one of discord or discourse
- Discourse has some nice features for forums e.g. turning posts into wiki posts, better categorization etc
- Essentially discord is comms for gamers with some attempt to bolt on other features ... whilst discourse is designed as a forum 
-  Discord "vibe/brand" is for gamers which isn't our focus (Simon: "The logo says a lot: Discord is designed for gamers and gaming")

## Hypothesis

Switch to discourse and deprecate discord ...

- Discourse is better for our core needs
- Discord is a barrier to some of our uses / needs in key areas e.g. use as forum
- It's early on so no great switching cost ...

Simon (on discord thread  - thread id 1255828195916255254): "Constitutionally I prefer Discourse mainly as it is Open Source, and I think it shows as in your comparison. Being open source it is (AFAIK) free of ads but one needs to pay for hosting. Discord has ads and is proprietary..."

### Comparison

- **Ease of access**: Discord requires sign in and is somewhat geeky. Discourse is web so anyone can browse. General experience is likely a bit more familiar. **Discourse the winner?**
- **Editing**: Discord has annoying limitations e.g. 2k character limit, can't have images inline, etc. Discourse is really designed for posting etc. **Discourse is the winner**
- **Onboarding**: seems a bit mixed. Discord now has welcome flow. Discourse has discobot and things. **No clear winner**
- **Discoverability (e.g. by search)**: discord is basically a closed space. Discourse is web and well indexed by google etc. Some may say they want more of a private space. That said our goal is making things more accessible. **Winner: Discourse**
- **Cost**: discord is free but closed. Discourse costs ~$20/month (or more)
- **Opens source**: discord is closed and proprietary. Discourse is open source. **Winner: discourse**
- **Real-time chat**: Discord is built for this. Also has video etc. Discourse really has this a kind of add-on and does not really compare **Discord is clearly the winner**

More discussion in https://discord.com/channels/1230798369337643030/1255828195916255254

### How to do onboarding on discourse

- https://meta.discourse.org/t/welcome-message/225465 this indicates that some custom messaging from discobot is possible
- have a banner encourage signup https://meta.discourse.org/t/how-can-i-add-a-banner-asking-new-users-to-register/172467 - i wonder if one can adjust this to have any content you want ...
- https://meta.discourse.org/t/welcome-message-at-the-top/129246 this also has some stuff about creating a banner ...

Here's an example from openrefine forum that shows a custom welcome message at the top

They also have categories on the home page which i achieved via instructions on https://meta.discourse.org/t/displaying-categories-on-the-homepage/275874/2

![image](https://github.com/life-itself/community/assets/180658/a4694e59-a44f-4fb9-985e-7a43101fb24f)

## Discussion

- Also discussion on https://forum.lifeitself.org/t/which-platforms-are-best-for-what-exactly/20
- Also long thread on discord thread id 1255828195916255254

**Comment by rufuspollock** [comment]
Relates to (or even is now duplicate of) #1164

**Comment by rufuspollock** [comment]
FIXED. This happened. We are now using discourse https://forum.secondrenaissance.net/
