### ISSUE TITLE
[epic] Strategy Revision 2021 and Transition Plan

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#118]
State as of 8 Jan 2022: In #36 we worked on a new high level SCQH plus there is work in #98. An SCQH is basically a strategy so this is a new high level strategy.

We now need to do the following ...

## Acceptance

* [ ] New strategy (SCQH) published in tao
* [ ] New strategy (SCQH) published in a blog post
* [ ] Transition roadmap written and signed off

## Tasks

- [x] draft our new strategy - see #36 **DONE**
- [ ] finalize our new strategy …
  - [x] The Bjorkman SCQH <= this has more detail
  	- [ ] The new SCQH => the longer, contextual version …
  - [ ] Integrate the new strategy discussion (that’s more internal …)
	- [ ] What happens with Labs vs Guild vs …
- [ ] Publish the strategy (note some of this is duplicated with #36)
	- [ ] blog post of SCQH
	- [ ] blog post of details
	- [ ] Update the tao
- [ ] Create transition roadmap
	- [ ] Where are we going?
	- [ ] What are the interim checkpoints? 
	- [ ] What are the timelines? 
	- [ ] What are the needs, and processes to fulfil them?
	- [ ] Who is accountable for what?

**Comment by nathenf** [comment]
MERGED with #196

**Comment by rufuspollock** [comment]
@nathenf great to see the tidying. One small thing: when closing as merged could you comment a bit on what you actually merged. e.g. here i don't think we've merged much of the actual tasks - more that this is a duplicate of other item (??)
