### ISSUE TITLE
Nomenclature is clarified for pillar/program/product/project

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#121]
What do labels do we use for the different ‘types’ which comprise Life Itself’s work?

## Solution

DECISION: Circles => Streams => Projects

* Circle: Highest level coherent area of activity with own strategy, budget, roles etc with some degree of decision making autonomy. May even correspond to its own mini-org. Examples: Labs, Spaces, AETRE etc
* Stream: Ongoing area of activity within a circle which: has a defined offer and associated standards, and encompasses a number of projects. E.g. ecosystem mapping, residencies or comms
* Project: A discrete, defined outcome being worked towards i.e. we have achieved X E.g. Visualisation design for the ecosystem map

## Motivation

At the moment we have a somewhat bewildering list which we don't just consistently e.g. https://tao.lifeitself.us/plans/ talks about workstreams and pillars whilst on website we have "initiatives" etc

![image](https://user-images.githubusercontent.com/180658/149326967-8491e613-f353-4043-a76c-3683ab789596.png)

![image](https://user-images.githubusercontent.com/180658/149327409-06f12b01-fe6e-425b-9089-9da6a74ebe85.png)

## Job Stories

When I’m talking about Life Itself work with colleagues I want to have a shared language we can use so we understand each other easily and don’t speak across purposes. Ex: “When presenting our strategy to colleagues, we might talk about distributing resource across programmes [insert label here] - implications very different depending on how this work understood, and we don’t want to have to define it at outset every time”

When I’m navigating the Life Itself shared drive I want to intuitively be able to find where things are store to save me time and avoid missing important information due to unclarity around location. E.g. currently I have to judge whether I think something will count as a program or project to try and find it in the shared drive (and go back if I get this judgement wrong). Further, some things which one might think of as projects (e.g, Sympoiesis series) are stored within a program folder rather than in the projects folder.

When I’m undertaking project management within Life Itself I want a clear picture of how different levels of work fit together so I can make PM decisions with the full context in mind

* When we decide to do something or not we want to know how it fits into the strategy. Specifically we should normally be able to say “activity/project/initiative X” is part of “stream/xxx” Y which is part of our “pillar/major workstream/…” Z

## Acceptance

* [x] We have a nomenclature with definitions **DONE. See Solution above**
* [x] We have an action plan to implement **DONE. See Next Actions below**

## Tasks

* [x] Collect examples
* [x] Summarize job stories
* [x] Do research
* [x] Options
* [x] Solution

### Next Actions

Next actions around nomenclature:

* Update team
* Update key resources (e.g. templates etc)
* Inventory of:
    * Existing work (to categorise)
    * Shared drive (to categorise)
* Reorganise shared drive accordingly 

What are the implications of our decision for 1) our content and 2) our shared drive?

1. **We implement changes in plan going forward, change standard template docs and others which are still regularly used (ie don’t retroactively change all content)**
2. **Options: Change titles and leave everything else the same OR restructure shared drive to reflect some alternative nesting arrangement based on above decision (Theo’s pitch would be the latter)**

## Analysis

Rufus notes

- Magic number 7 +/- 2
- People think hierarchically
- People want some coherence
- People want to be able to find things relatively quickly
- MECE: mutually exclusively, collectively exhaustive => no multiple parents (e.g. a project is part of a single product). tree not a DAG
- Does the project, program distinction matter really for us at this point? 
- PARA = projects + areas

![image](https://user-images.githubusercontent.com/180658/149328797-68d65f92-33d5-4957-8655-fd7b5dae681a.png)

Theo Notes

* The overall areas work fits into: **Options: Pillars, Programs, Workstreams, Buckets, Circles…**
* Specific initiatives/projects in a given area: **Options: Projects, Initiatives, Products, Activities**
* Actions etc within this: **Tasks, Issues**
* Are there others?: **Might be worth distinguishing activities from offerings e.g. we have projects which we undertake, but a number of products which we offer more generally**

### Hypothesis

Hyp: we want a tree with labels for the levels of that tree …

* Project: defined endpoint and goals
    * Aliases: Initiatives
* Streams: ongoing workstream with a defined offer/purpose/mission
    * Alias: initiatives e.g. see our website
    * Alias: Product (deprecate as has this aspect that gets shipped) 
    * Alias: Program
* For internal understanding
    * High level product => Medium Level Product => Product?
    * My answer: Pillars => Streams
        * We can add another layer one long day in the future if we need it.
    * Theo answer: Streams => Projects
* Every project comes under a stream
    * => nesting for gdrive, website etc.
    * Resources will be attached to a specific project, and nested in shared drive accordingly

**Comment by rufuspollock** [comment]
FIXED. See Solution above.

DECISION: Circles => Streams => Projects

* Circle: Highest level coherent area of activity with own strategy, budget, roles etc with some degree of decision making autonomy. May even correspond to its own mini-org. Examples: Labs, Spaces, AETRE etc
* Stream: Ongoing area of activity within a circle which: has a defined offer and associated standards, and encompasses a number of projects. E.g. ecosystem mapping, residencies or comms
* Project: A discrete, defined outcome being worked towards i.e. we have achieved X E.g. Visualisation design for the ecosystem map
