### ISSUE TITLE
Collecting Key Thought Pieces that are worth (re)sharing

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#124]
We want to collect all the key thought pieces and articles that Life Itself et al has created so that we can highlight them on the website #170 and reshare them more widely with our audience. 

## Acceptance

- [ ] Key articles, etc compiled in one place ✅  **Good number of articles now ready [Website update spreadsheet](https://docs.google.com/spreadsheets/d/13RVMrZ02Rw6a1BtftIUO4v7R7rXt5_phQLR4rHa343M/edit#gid=609489402)**
- [ ] Key articles organised by categories 🚧 **Zaib created, Nathen to Review**
- [ ] List of key articles presented on the website 🚧 pull request created

## Tasks

- [x] Determine sources for key articles ✅ **Blog, Google Docs (if unpublished), Rufus' Website**
- [x] List all key articles in [website migration spreadsheet](https://docs.google.com/spreadsheets/d/13RVMrZ02Rw6a1BtftIUO4v7R7rXt5_phQLR4rHa343M/edit#gid=609489402) ✅ 
- [x] Fill in necessary information (categorise, is it about Life Itself or more externally focussed?) ✅ 
- [x] Add page to website listing key readings
  - [ ] Create page home/key-readings/
  - [ ] List articles chronologically for now

## Inbox (add to spreadsheet) 

* [ ] https://lifeitself.us/2017/09/10/four-types-of-problem/ - could easily be turn into an instagram story or twitter story ✅ added to Key Thought Pieces
* [ ] https://lifeitself.us/2017/09/18/techno-solutionism/ - needs maybe extending ✅ added to key thought pieces
* [ ] see more material in https://github.com/life-itself/community/blob/main/abc/techno-solutionism.md (some of which could be reposted) 🔴  link not working

**Comment by rufuspollock** [comment]
@ZybN how are we doing on this? And can update time spent plus the acceptance criteria with progress so far 🙏😄

**Comment by nathenf** [comment]
@rufuspollock I've added to next iteration and set due date for the 6th. We fixed Zaibs conflicts this morning so she will upload the page tomorrow for review

**Comment by ZybN** [comment]
I have created the pull request for the key thought pieces [Pull Request](https://github.com/life-itself/community/pull/418)
