### ISSUE TITLE
Merge sutras into this repo

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#125]
Situation: have sutras ("curated wisdom teachings") repo https://github.com/life-itself/sutras and site https://sutras.lifeitself.us

Complication: currently separate repo from here with its own site and we think "monorepo" approach (i.e. all here in this repo) is the way to go atm (and only split later) because:  it is simpler (KISS), better for SEO (one site to start with), better for attention/critical mass. Note that other repo is done using nuxt.js and this will probably be nextjs so need to convert a bit.

Thesis: merge sutras into this repo at `/sutras/` subdirectory for content

## Acceptance

* [x] sutras repo merged here **✅2022-12-14 merged into https://github.com/life-itself/community/tree/main/vault/sutras**
* [x] sutras repo deleted or archived as read only with pointer here **✅2022-12-14 archived and left pointer**

## Tasks

* [x] Review sutras repo and decide what needs to be done (MVP to migrate) **✅2022-12-14 just migrate the main texts. Added a simple index page. Migrate issues**
* [x] Migrate texts
* [x] Add index page
* [x] Migrate issues **✅2022-12-14 migrated couple of issues to forums here. Nothing **
* [x] Make read-only and mark as moved **✅2022-12-14 **

**Comment by rufuspollock** [comment]
@Liyubov are you interested in this perchance? 😄

**Comment by Liyubov** [comment]
So let me ask, since I am not really sure: in tasks it says:

- [ ] Review sutras repo and decide what needs to be done (MVP to migrate)

For me it is hard to say how it should be merged with any repos in community-repo. This is the question in fact @rufuspollock ?

**Comment by rufuspollock** [comment]
@Liyubov the idea would be to take a look through that repo and the content in it and propose how to merge here. All the content is here: https://github.com/life-itself/sutras/tree/main/content/sutras so that would be the main thing to merge over I think.

The next question would be how to create a space on this site for that.

Also feel free to focus on other issues - this was just a suggestion.

**Comment by Liyubov** [comment]
Ok if I understood well one can:

1. merge sutras [folder ](https://github.com/life-itself/sutras/tree/main/content/sutras )to the folder of life-itself community here https://github.com/life-itself/community 
2. merge or link it with other existing subfolders of community (but here I cannot help since I was not the one who created them so I would need to talk to anyone of you first)

If it is 1., I can do that by PR. If 2. then it is probably for creators of other folders.
Thanks.

**Comment by rufuspollock** [comment]
@nathenf this is so small i can do this myself directly and we don't need to analyse.

**Comment by rufuspollock** [comment]
FIXED. All done.
