### ISSUE TITLE
Migrate primers into normal structure

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#126]
Currently have a bunch of old stuff in the primers folder

Primer stuff could just become notes e.g. in `/abc/`.

## Acceptance

* [ ] `/primers/` folder no longer exists and all content migrated into other parts of the repo

## Tasks

* [ ] Assess primers folder for what we want to manage / migrate (e.g. i think the main primer pdf ArtEarthTechPrimers.pdf can go away etc)
  * [ ] Also good to check what we actually posted on the blog (e.g. i think we posted mindfulness and non-attachment ??) 
* [ ] Migrate relevant stuff to `/abc/` etc
