### ISSUE TITLE
Summary essays of key traditions/movements/philosophies in the metamodern ecosystem

### ISSUE THREAD

**Issue by theo-cox** [life-itself/community#128]
This tab has a list of key traditions in the ecosystem: https://docs.google.com/spreadsheets/d/1sotA3Cm79B1te4ooMQvPk6OHdaxZwnDB2VRLtfQAuRE/edit#gid=1105141571

When I'm promoting the ecosystem mapping project I want to have useful content to boost the utility of the site and get people interested so that we get more engagement around the project as a whole.

These summaries should be max 5 pages (ideally less) and cover a bit of the history/lineage of these traditions, their key ideas/claims, major figures etc

These are what @juliedayot has already done to avoid repetition (although I have yet to find time to review them properly): https://docs.google.com/document/d/1quwlbfMHaGjKsFwIUHWqELhSeCPBn2GA_zkqmNinohs/edit?usp=sharing

## Acceptance

- [x] Summary essays for each topic in the list done ✅ summaries made from original list of topics
- [x] Essays blogged
- [x] Essays added to the site **all articles begin with Mapping Metamodern: followed by topic**

## Tasks

- [X] [Mapping Metamodern: What is Metamodernism?](https://lifeitself.org/2022/03/11/mapping-metamodern-what-is-metamodernism/) **Published**
- [X] [Mapping Metamodern: Zen](https://lifeitself.org/2022/03/18/mapping-metamodern-zen/) **Published**
- [X] [Mapping Metamodern: Permaculture](https://lifeitself.org/2022/03/25/mapping-metamodern-permaculture/) **Published**
- [X] [Mapping Metamodern: Alternative Economics](https://lifeitself.org/2022/04/01/mapping-metamodern-alternative-economics/) **Published**
- [X] [Mapping Metamodern: Alternative Governance](https://lifeitself.org/2022/04/08/mapping-metamodern-alternative-governance/) **Published**
- [X] [Mapping Metamodern: Psychotherapy](https://lifeitself.org/2022/04/22/mapping-metamodern-psychotherapy/) **Published**
- [x] [Mapping Metamodern: Buddhism ](https://docs.google.com/document/d/1mAg6Juy0C4RKsnOErdMyHkA450xdAFyyhdL1w0ma7t4/edit?usp=sharing) **Published**
- [x] [Mapping Metamodern: Integral] see also #123 (https://docs.google.com/document/d/1tXR6SaGfStFKX31yfWoZLF2XRpSscHsaoD37grESoSU/edit) **Written but not published** TODO back-publish this when others are #347

**Comment by theo-cox** [comment]
@juliedayot can you link the ones you've already done please?

**Comment by theo-cox** [comment]
Ignore, found it

**Comment by catherinet1** [comment]
Hi @EilidhRoss1, we are cleaning up ecosystem-related issues. Please could you update this issue? e.g. are we still doing this/is this still in progress? (maybe not and then close) Let me know if you have any qs.

**Comment by EilidhRoss1** [comment]
I think @theo-cox and I agreed to pause this issue for the moment. So am happy for this issue to be closed and can reopen if we decide to loop back to it.

**Comment by nathenf** [comment]
FIXED - All article summaries add to the blog
