### ISSUE TITLE
Publish Untitled issue tree material (Big Vision issue tree) from Autumn 2020

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#132]
With Roope and others at Demos Helsinki we co-created a narrative for the Untitled project in Autumn 2020 using the SCQA methodology. We mean to publish this as the time but didn't get to. Would like to back-publish this so referenceable.

NB this SCQA was v similar to Life Itself's general "Big Vision / Transforming the narrative" SCQA.

```[tasklist]
### Tasks
- [x] Find the doc **✅2024-07-04 https://docs.google.com/document/d/1lYRtKwAsDh8WwKlC141nsI5ZMeZxjPtbqRP8eEpqi0Y/edit**
- [ ] Convert to markdown and back-post to the blog
- [ ] Add to list of SCQAs (e.g. in digital garden)
```
