### ISSUE TITLE
Briefing re using Obsidian

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#133]
Obsidian is becoming our tool of choice for editing markdown files and especially markdown wikis - which we use in several initiatives such as web3, ecosystem and this repo.

## Acceptance

* [ ] Document exists with brief intro plus
  * [ ] links to longer intro/background
  * [ ] tutorial(s)
* [ ] Recorded 10-30m session walkthrough

## Tasks

- [ ] Why => you want to edit markdown. Plus you want to edit a bunch of notes which are linked together aka a second brain / zettelkasten / digital garden / (markdown) wiki etc.
   - [ ] Bonus: Zettelkasten, backlink revolution etc
- [ ] What => obsidian is an editor for second brain etc
- How => ...

**Comment by rufuspollock** [comment]
DUPLICATE now of #379 which is the main issue now.
