### ISSUE TITLE
Gathering March 2022 (Spring) - Delivery

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#134]
## Acceptance

- [x] We have a fun and fruitful and well organised gathering 

## Tasks

**Programme/frame**
- [ ] Create schedule on paper and put it upon wall with post-its for suggested activities to add to the schedule 

**Logistics**
- [x] Email participants with key info and update + to ask for arrival/departure details, dietary requirements, and phone number N.B. you can do this through Tito) **Email sent on 9/3 to all participants registered on Tito with info on: Food; Getting to the hub; Things to bring and asking for: arrival and departure times; dietary requirements; contact phone number.**
- [ ] Schedule room allocations
- [ ] Check all rooms are clean before guests arrive
- [ ] Create a whatsapp group with all participants

**Comms**
- [ ] Decide who will be content/comms lead e.g. responsible for taking photos/recording testimonials etc. during the gathering
- [ ] Write a blog post at end of gathering 
- [ ] Gather media content that Nathen can use during gathering e.g. photos, video testimonials, etc. To be uploaded in this [folder](https://drive.google.com/drive/u/0/folders/1I0KDUpLR876sXhyFORg2RqXKLkMMSiY_)

**Evaluation & Feedback**

- [ ] ...

**Comment by rufuspollock** [comment]
@catherinet1 do you want to close this one - now it is done.

**Comment by catherinet1** [comment]
FIXED. We held the Spring Gathering 17-23 March 2022.

**Comment by rufuspollock** [comment]
@catherinet1 did we write a blog post at the end of the gathering? Ditto on the other comms task. Either way can we update the task list as per https://tao.lifeitself.us/issues/#completing-tasks 🙂🙏

**Comment by catherinet1** [comment]
Hello @EilidhRoss1 was just looking for photos from the gathering for one to perhaps accompany my newsletter contribution. Are the photos and videos etc. from the Gathering on the Drive somewhere? Please could you upload them to this folder - https://drive.google.com/drive/folders/1jiEJrgysZLtKKN6_spys33HRunIMeRJa - or let me know where they are so I can move them over? Thanks : )

**Comment by EilidhRoss1** [comment]
@catherinet1 done https://drive.google.com/drive/folders/1-3YQwNU_zQdSe0v5YAEqDYqO-5YLl_UO?usp=sharing

**Comment by catherinet1** [comment]
awesome, thanks, @EilidhRoss1 ! beautiful photos! :)

**Comment by catherinet1** [comment]
Comms and Evaluation/feedback tasks updated = all tasks updated.
