### ISSUE TITLE
Gatherings 2022 planning

### ISSUE THREAD

**Issue by catherinet1** [life-itself/community#135]
### Tasks

- [ ] schedule next 2 gatherings
  - [X] Propose dates and check with team **Proposed 28/5-4/6 for sprint; 5/7-12/7 for summer community gathering**
- [ ] Create Tito page for next gatherings 
- [ ] Update old sprint page? https://lifeitself.us/sprints/#hfaq-post-3752
- [x] Update old gathering page https://lifeitself.us/gathering/. **Updated to say dates tbc for summer 2022**
  - [ ] edit this page when confirmed format of next gathering having integrated learnings from march gathering + make it more visible on website
- [ ] Publish webpages/blogposts for next sprints/gatherings

**Comment by nathenf** [comment]
@catherinet1 this is assigned to you, but I assume no longer useful. May we close?

**Comment by rufuspollock** [comment]
FIXED / INVALID. We didn't do other gatherings than the march one in the end.
