### ISSUE TITLE
Add ORA material to (2R) ecosystem mapping

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#1351]
## Job Story 

We want to add the list of polycrisis response orgs we worked on as part of the ORA project. - https://lifeitself.org/blog/2023/01/19/polycrisis-mapping-ORA-project

## Acceptance

- [ ] ORA Material is integrated into the Life Itself Ecosystem 

## Tasks

- [x] Create sheet in the cohere+ database for ORA material ✅ **12/21/2023 titled ORA MATERIAL https://docs.google.com/spreadsheets/d/1YcIQP_CGYhpMTzEQU_f46j159UalqLVfGt2chhsoQxw/edit#gid=298172192**
- [ ] Identify which organizations are already apart of ecosystem in the database sheet
- [ ] Identify which organizations  fit criteria to include in the ecosystem **should we use cohere+ criteria other than the EU focus**?

## Analysis

- [ ] ORA Airtable: https://airtable.com/invite/l?inviteId=invpq2bWCgihkrL8g&inviteToken=ec4f08596ad5086effb1dd4f0441d20d386dd8dc33bb5cf5d4070f352f715b12&utm_medium=email&utm_source=product_team&utm_content=transactional-alerts

**Comment by rufuspollock** [comment]
And i found another ORA related spreadsheet (also includes project planning but also a db): https://docs.google.com/spreadsheets/d/1YcIQP_CGYhpMTzEQU_f46j159UalqLVfGt2chhsoQxw/edit?gid=298172192#gid=298172192 (which seems to have more info).

@catherinet1 any insight on the differences between these spreadsheet

**Comment by c4ss1uslab** [comment]
i'm trying to get access! i requested it with my email - cassius.carv@gmail.com.

**Comment by catherinet1** [comment]
> And i found another ORA related spreadsheet (also includes project planning but also a db): https://docs.google.com/spreadsheets/d/1YcIQP_CGYhpMTzEQU_f46j159UalqLVfGt2chhsoQxw/edit?gid=298172192#gid=298172192 (which seems to have more info).
> 
> [@catherinet1](https://github.com/catherinet1) any insight on the differences between these spreadsheet

I'm not sure what the two spreadsheets you're comparing are. 

Iirc Airtable was the main spreadsheet for ORA research.

The tab you indicated in the spreadsheet linked here (which is the internal spreadsheet for the Cohere+ mapping project, not the ORA project) was I believe a copy-paste of orgs we had mapped in the ORA Airtable, here to be evaluated for inclusion in the Cohere+ database or not. 

hope that helps

**Comment by rufuspollock** [comment]
FIXED. This is live at https://ecosystem.secondrenaissance.net/ora/directory/

<img width="1418" height="1024" alt="Image" src="https://github.com/user-attachments/assets/cd5917c4-1a7f-418b-9aa8-6157f924d993" />
