### ISSUE TITLE
Switch to lifeitself.org from lifeitself.us

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#137]
We have now (2022-04-06) registered lifeitself.org (finally available yay!).

Wanted to switch from lifeitself.us as has "US" connotations and the "us" part does not come across.

## Acceptance

* [ ] lifeitself.us => lifeitself.org
	* [ ] website
	* [ ] email and google app
	* [ ] redirect from lifeitself.us
* [ ] labs.lifeitself.us => lifeitself.org
* [ ] web3.us => web3.org
* [ ] ecosystem.us => ecosystem.org
* [ ] possibilitynow => possibilitynow.org

## Tasks

* [ ] ...
