### ISSUE TITLE
Codifying our Governance Structure

### ISSUE THREAD

**Issue by theo-cox** [life-itself/community#139]
When I work at Life Itself I want a clear way to understand what my roles and accountabilities are, what I can expect of others, how decisions get made and who can make them.

When I work at Life Itself I want a clear understanding of what our commitment to being a Teal org means in the day to day so that I can show up in the best way possible in this context.

## Acceptance

- [ ] First set of roles Life Itself team codified and signed off, covering the work we do as a team on a daily basis (that are at least "safe enough to try")
- [ ] Major decisions and points of decision-making authority are captured explicitly by either roles or policies signed off by the team (that are safe enough to try) 
- [ ] Governance process for the future (e.g. how we will address how the org runs going forward) is signed off and implemented
- [ ] Agreed tool to use for governance functions such as clearly displaying and navigate roes and policies (e.g. GDoc, GitHub, GlassFrog)

## Tasks

- [ ] Draft initial roles and policies **In progress: https://docs.google.com/document/d/1SMwdkE-H8lQMF3OTxJkKDlWhtkR5qWTO31YnsPBLRbo/edit?usp=sharing**
- [ ] Finalise with team
- [ ] Discuss and research tool(s)
- [ ] Implement new structure
