### ISSUE TITLE
[epic] Annual Gathering 2022

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#146]
The annual gathering is a chance to explore and engage. It's a particular focus to get to know others and widen the “fellowship for a radically wiser, weller world”.

## Tasks

Content

* [ ] outline
* [x] web page
* [x] update /gathering/ with content of blog post so they are in sync @catherinet1 
  * [ ] Bonus: find a nice short video from past gatherings 	
  * [x] Archive current gathering page to 2019 @catherinet1 **Page created here https://lifeitself.us/gathering-2019/**
  * [ ] Aside: find material from previous gathering @rufuspollock 

Invitations

* [x] Setup invitee spreadsheet and consolidate material into it @rufuspollock 
* [x]  Set up Tito for gathering (inc. 5% fees) @catherinet1 **Tito page here: https://ti.to/art-earth-tech/life-itself-summer-gathering-2022**
  * [x] draft standard email with payment instructions inc. info on registering on Tito if paying via bank transfer **Email is [here](https://docs.google.com/document/d/1ja8sPlsKvsg2vnxKOaNhUGscGL2VN6RPP_n5ADrTwxE/edit) and I've scheduled a reminder to myself to check on 15th July that correct payment has been received via bank transfer for Tito registrations made using discount code for those paying via bank transfer.**

Production

* [ ] Liase with producer @rufuspollock

**Comment by catherinet1** [comment]
updated Tito task

**Comment by catherinet1** [comment]
Updated payment info email task

**Comment by rufuspollock** [comment]
WONTFIX. In the end we had a more informal gathering.
