### ISSUE TITLE
Design and share questionnaire to gauge needs re curated content

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#148]
When creating curated content I want to understand potential audience views and needs so that we can speak to that (and understand if this is useful) e.g.

* What things are not working e.g. climate crisis, political system
  * Why are they not working? Eg. seeing the interconnectedness?
* Of these X things what would be most useful to you
  * A careers guide
  * A guide to coliving
  * ...

**Key Documents**

- [Questionnaire Planning Doc](https://docs.google.com/document/d/1nhMcE6p3-YsQOnalXDgUUbRjKnMC5GO_y989mCVinU4/edit#heading=h.2vsv1vop4b88)

## Acceptance

* [X] Questionnaire created -https://docs.google.com/forms/d/1e9vT4cNbQY62O2VruhyMAcaCusv3gwO1lAdUTvfKvZ0/edit
* [X] Questionnaire shared and at least 50 responses - we reached 46 in total
* [x] Results analyze and executive summary created with insights - [Executive summary](https://docs.google.com/document/d/1VLEeByF5mPNkvSJxJgBQOK6qkd-VagTpTwFRhEdwtWE/edit?usp=share_link) is in 👀 review

## Tasks

* [X] Draft questionnaire (google docs) - **https://docs.google.com/document/d/1nhMcE6p3-YsQOnalXDgUUbRjKnMC5GO_y989mCVinU4/edit#heading=h.2vsv1vop4b88**
  * [X] Clearly define intention/audience/goal
  * [X] Sections plus 2-3 questions on each for review by others to confirm direction
  * [X] Review
  * [X] Finalize

* [X] Transfer to questionnaire system
  * [X] Select questionnaire system @nathenf - We used google forms
    * [X] Review tally.so and google forms
    * [X] Select

  * [x] Test Questionnaire
    * [X] Test the questionnaire within the team 1. to test usability 2. feedback on questions - We did this in all team meeting on 30/09
    * [X] Do wider test on 5-10 people we know who can give feedback - We did not do this because we felt pretty happy with the survey after the team meeting. - We did not do this in the end as feedback from the team was enough

* [X] Share
  * [X] Consider an incentive option => Free Collective Wisdom Paperback & a LI t-shirt, or something - Decided against incentivising as we felt in this case it would not really provide value
  * [X] Send via our mailing list 2 weeks in a row (cross reference emails to make sure those who complete it do not receive it again
  * [X] Send email specifically to Alumni who know Life Itself more
  * [X] Post on Socials

* [X] Analysis
 * [X] Collate and summarise responses
 * [ ] Meeting to determine what we have learned and what that means for the project

**Comment by rufuspollock** [comment]
@nathenf i've done a first review and left a substantive commentary at top re direction. Once that's synced we can focus on questions.

**Comment by nathenf** [comment]
@rufuspollock I've gone through your inputs, thanks very much for that. There are a few replies.

**Comment by EilidhRoss1** [comment]
FIXED survey sent out and [responses analysed](https://docs.google.com/document/d/1VLEeByF5mPNkvSJxJgBQOK6qkd-VagTpTwFRhEdwtWE/edit)
