### ISSUE TITLE
[epic] Life Itself Website Revision - Summer 2022

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#149]
**Job Story**

When people come to our website they want to be able to easily navigate to our most recent work and initiatives. They want to be taken on a journey which encourages them to explore the whole website or at least find a number of things that they are interested in. From the homepage they should instantly get a feel for what Life Itself is and what it can offer. They also want to easily be able to return and find new content and news.

**Hypothesis**

What we would be aiming to observe is an increased number of returning users (because the usability of the website encourages more people to return), a decrease in bounce rate, an increase in session duration and number of pages per session. This should steadily increase our number of users as we gain more returning users. 

We want to bring new clarity and focus to Life Itself site reflecting the clearer focus we have. Also content has expanded quite a bit and could be consolidated and more accessible.

**Key Documents**

- Context in [this PA10](https://docs.google.com/document/d/1X9NebAIhxtQMIa4dYcD7KO3BWcMg9AfSs_lKyputA0k/edit#)
- Working on copy & structure in [this doc](https://docs.google.com/document/d/1y_CG4rdWO7IvCEsMux9lVRO_ko_BTHWAZetTe9-CD9I/edit?usp=sharing)
- [Mainpage Excalidraw](https://app.excalidraw.com/s/9u8crB2ZmUo/3HFKSwsU9zH)
- [Website Structure in Coggle](https://coggle.it/diagram/YsUYJmqIBdEcOuNM/t/wiser-2022)

## Acceptance

* [ ] New landing page
* [ ] Ecosystem integrated
* [ ] Ecosystem expanded

### Landing Page

* [ ] Copy
* [ ] Design
* [ ] Implement 

### Other pages to create

* [ ] Guide Pages (Landing pages for each section of the ecosystem map)
* [ ] Volunteer/Contribute Page

### Pages in need of an update

* [ ] Main blog page for better content display
   * [ ] Categories clearly defined and assigned
* [ ] Optimise Residencies page for people to apply
   * [ ] Testimonials
   * [ ] Intro Video

### Ecosystem Integration

* [ ] Transfer Pages
* [ ] Fix Links
   * [ ] Links on own website
   * [ ] Ask backlinks to be revised

**Comment by nathenf** [comment]
@rufuspollock @EilidhRoss1 I've made a document and made a first pass on website structure and copy, would appreciate feedback before moving forward to image and design style. [Doc is here.](https://docs.google.com/document/d/1y_CG4rdWO7IvCEsMux9lVRO_ko_BTHWAZetTe9-CD9I/edit#)

**Comment by EilidhRoss1** [comment]
Have gone through the doc Nathen, I think it's really really great - very clearly set out and effectively conveys what we are wanting to do. Have left a couple of comments but all small things.

**Comment by rufuspollock** [comment]
@nathenf great work Nathen. Doc is thorough and excellent start. Will add comments there.

**Comment by nathenf** [comment]
DUPLICATE - merged with #170
