### ISSUE TITLE
[epic] Wiser Initiative - pathways to a wiser, weller world

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#150]
**Key Documents**
[Wiser 2022 A10](https://docs.google.com/document/d/1X9NebAIhxtQMIa4dYcD7KO3BWcMg9AfSs_lKyputA0k/edit#)
[Wiser Job Stories](https://docs.google.com/document/d/1NcuslX2GEFzBPmS1X4_VfhHCKp9tRRD6GI_ezoOfWL4/edit)
[Wiser SCQH](https://docs.google.com/document/d/1YZqeHYvAtJcQdIJqYWShpMzjQd09XeB1bivHm4c-KTI/edit#heading=h.wdicmfuaa0oh)

## Acceptance

* [X] PA10 for the initiative - see key documents above
* [ ] Updated brand for Life Itself #162 
* [ ] Website updated #170 
* [ ] Comms strategy around Wiser determined and in action
* [ ] Budget defined

### Market Research
   - [X] Questionnaire (see #148)
   - [ ] Once we have an MVP, do 5 deeper interviews to corroborate our ideas (see #166)

###  Develop Guides
   - [ ] Set-up for content curation see #152 
   - [ ] Create Template for guides
   - [ ] Test template for SEO 
   - [ ] Do keyword research + Answer the public to see what answers to include in guides
   - [ ] Link Orgs to correct guides

### Comms Strategy
   - [ ] Decide on content creation/curation
      - [ ] Find ways to automate curation of content
   - [ ] Podcast
      - [ ] Create A10
      - [ ] Identify key guests 
   - [ ] Email Marketing

### Membership
- [ ] Decide on membership model
- [ ] Research best tools to use for membership management

### Wiser 2022 Launch
- [ ] Ask orgs on the map to share with their networks
- [ ] Press release
- [ ] Get Interviewed on several podcasts

**Comment by nathenf** [comment]
WONT FIX - in the last year we have moved away from the wiser initiative. This has been iterated into the current #814 and development of beacons #826
