### ISSUE TITLE
Wiser 2022 - Content Curation Set-Up

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#152]
I want a place to store and find key readings from different areas of social transformation, so that I can use them in guides or create reading lists for the guides. 

## Acceptance

- [ ] Content curation system set-up
- [ ] Organization is clear and easy for us to use

##Tasks

- [ ] Set-up Zotero
   - [ ] Make lists for each area of social transformation

**Comment by nathenf** [comment]
WONT FIX - For now not a priority or within our direct interest
