### ISSUE TITLE
Look into if we can x-post (or merge) Life Itself hubcasts with main podcasts

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#153]
I want to merge the old podcast with the new podcast for consistency and back history

## Context 

Came across the (old) hubcase when searching for "life itself podcast": https://podcasts.apple.com/us/podcast/the-life-itself-hubcast/id1548190164?uo=4

here's the "official" podcast:

https://podcasts.apple.com/ie/podcast/the-life-itself-podcast/id1618247766

## Acceptance

- [ ] Life Itself Hubcast episodes merged into main podcast
- [ ] Hubcast updated to redirect to current podcast 

## Tasks

- [X] Reach out to Sen to get details of the hubcast - **Sen agreed to give us the interviews with Sylvie and Liam which are now stored [here](https://drive.google.com/drive/folders/1_TvdZk2Hh_1weBI7SkV_N3nC2N0360hC?usp=share_link)**
- [ ] Create episodes from hubcast content
- [ ] Backdate in the current podcast 
- [ ] Link to current podcast from hubcast with update text about the migration

**Comment by rufuspollock** [comment]
@EilidhRoss1 flagging FYI 👆

**Comment by nathenf** [comment]
@EilidhRoss1 we could back publish the hubcast episodes on the Life Itself Podcast and then close/redirect the old podcast. I think in total we could create 3-4 episodes, merging what was previously chapters into the full interview.

**Comment by rufuspollock** [comment]
@nathenf @EilidhRoss1 you'd need to get in touch with Sen from the Berlin Hub (you probably already have her contacts).

**Comment by EilidhRoss1** [comment]
I contacted Sen to enquire about merging the hubcast in with the Life Itself podcast. She responded asking how the work she puts into the hubcast could be valued/acknowledged if the hubcast were to be merged with the Life Itself podcast:

Sen 16/11/22

"I’d be glad to discuss sharing my content, but it would be important for me to first have a conversation about how the work that has gone into the research, preparation, production, and hosting of this podcast will be recognized and valued. 

To give you an idea of the work this has entailed, approximately 130 hours of my own time has gone into this. This includes 5 published episodes, as well as 5 upcoming ones. 

Let me know if this is something you would be open to discussing"

Eilidh 16/11/22

"Thanks so much for getting back to me and for flagging this. Absolutely we should figure out how we can acknowledge all the work you have put into this. I wonder if you have any requests or suggestions of how to move forward?"

Sen 17/11/22

"Hi Eilidh,
I appreciate your question - here are some initial thoughts: 
When I created The HubCast, my vision was to represent the stories of the people who live here, as well as those who pass through our doors as visitors, guests, event hosts, and speakers. Additionally, I wanted to share stories of the events that happen in the Hub, or those associated with values shared by the community members here (for example the Climate March). 

As a multi-podcaster and radio correspondent, it's important for me to tell a good story, so plenty of research, preparation, sound adjustment, editing, and post-production goes into each episode. The themes that are ongoing in the HubCast are community skills, conflict navigation, authentic relating, climate action, and more. To produce work like this of course takes  interest, willingness, time, and skill. 

One of my preferred situations would be to continue to produce the HubCast as a broadcast for Berlin-based Hub activities, and to be financially compensated to do so, eventually involving additional team members in production to leverage different skill sets. This has been proposed multiple times in the past to Rufus, but it seems the timing hasn't been right to take this on yet. Furthermore, as LI has created its own podcast, this would perhaps not fit strategically into its content planning. 

Thus, I could imagine another situation where I merge the content of the 5 published episodes, as well as the 5 upcoming episodes with the LI podcast in exchange for a lump sum of how much time this endeavour has taken. I'd be curious if LI would make me an offer for these 10 episodes. 

The upcoming episodes (30-45' each) to be released are: 
#6 Laird Schaub, co-founder of the Foundation for Intentional Communities
#7 Diana Leafe Christian, author of Creating a Life Together
#8 Maria Silvia, community facilitator
#9 Karl Steyaert, Cultural Catalyst Network 
#10 Dr. Rosemarie Soucy, psychiatrist on personality disorders in communities 

I'd be curious to hear what you'd think"

In order to proceed with this issue I would need input from @rufuspollock

**Comment by rufuspollock** [comment]
@EilidhRoss1 can you cc me into the email thread.

**Comment by EilidhRoss1** [comment]
@rufuspollock done

**Comment by EilidhRoss1** [comment]
Just following up on this @rufuspollock

**Comment by rufuspollock** [comment]
Have emailed ~10d ago and just followed up.

**Comment by nathenf** [comment]
I downloaded the files Sen sent and added them to drive https://drive.google.com/drive/folders/1_TvdZk2Hh_1weBI7SkV_N3nC2N0360hC?usp=share_link

**Comment by EilidhRoss1** [comment]
FIXED we have permission from Sen to publish her interviews with Liam and Sylvie on the Life Itself podcast. Issues for these tasks are [here](https://github.com/life-itself/community/issues/268) and [here](https://github.com/life-itself/community/issues/267) respectively.
