### ISSUE TITLE
Conscious Parenting Pilot Material

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#156]
First interview / webinar material for pilot series / seminar on conscious parenting

Part of #94 

## Acceptance

- [x] Published first series of interviews / tutorials to youtube / podcast **✅2023-03-04 see 3 podcasts linked on https://lifeitself.org/projects/conscious-parenting**
- [x] Conscious Parenting project / page on site e.g. at `/consious-parenting/` or `/projects/conscious-parenting/` ✅ **see https://lifeitself.org/projects/conscious-parenting**
  - [x] short intro
  - [x] includes links/embed to videos/recordings

### Record material

* [x] Create a list of topics
* [x] First series of interviews with Esther **✅2022-10-01 - see below**
* [ ] (BONUS) Review and make notes of specific topics that come up (and the start and end timestamps) along with any key points. **✅2023-03-04 ❌ wontfix and moved back up to #94**

### Publish: Edit and post to youtube / podcast (e.g. some recordings could split into two)

- [x] Prep
  - [x] quickly review recordings and note how we could split **✅2023-02-05 did not split in the end.**
  - [x] decide if we publish one by one or all in one go (probably doesn't really matter along as we have separate episodes)
- [x] ... everything else to get it up ... **✅2023-02-05 see #282 #283 #284**
- [x] Promotion **✅2023-02-05 ❌ wontfix. we wanted to get out but not promoting specifically. will have an initiative page for this - see #97**

### Landing page for project

Note this could follow from #97 which may have a standard project page structure

- [x] key content 
  - [x] title
  - [x] tagline
  - [x] description
  - [x] episodes content
  - [x] people
  - [x] links to associated blog posts
- [x] publish ✅ see [https://lifeitself.org/projects/conscious-parenting](https://lifeitself.org/projects/conscious-parenting)
- [x] announce briefly some way ... ✅ Announced in the latest newsletter

## Notes

Conscious Parenting with Esther Montmany
Creating a wiser, weller world starts with great parenting. Join us in discovering conscious parenting to create the stewards of the future.
Jan 2021 - Present

What
Our conscious parenting project is a series of offerings from conscious parenting pioneer Esther Montmany. The offerings shed light on the impact of parents behaviours on the child, how to positively transform the role of the parents, and pragmatic tools for all elements of parenting.

Esther has worked with Mauricio and Rebecca Wild at their legendary school in Ecuador and led the children's program at Plum Village summer retreats as well as starting several initiatives of her own. Over the past 20 years she has been exploring how to relate with children through her own experiences as a mother and as a coach for other parents.

Why **Leave this out for now**
The next generation of humans are being born into and will live through some of the most turbulent times in human history. According to the NHS, [18% of children in the UK aged 7 to 16 have a probable mental disorder in 2022](https://digital.nhs.uk/data-and-information/publications/statistical/mental-health-of-children-and-young-people-in-england/2022-follow-up-to-the-2017-survey#:~:text=In%202022%2C%2018.0%25%20of%20children,between%202020%2C%202021%20and%202022.) and this number is steadily on the rise. Children need conscious parents more than ever, to help them navigate the modern world.

Conscious parenting opens up the possibility of raising healthy children with deep awareness and groundedness who can go on to become brilliant adults.

include links to podcasts, hangout and blog post.

### Raw recordings on zoom (public access for initial sharing until on youtube)

Esther Montmany conscious parenting recording 1 (45m): https://us02web.zoom.us/rec/share/MQHZ3d1lVE4euxIRPTqenUKBdYmiogZ8tTvYPOar-ltq3_D3bBHFUd0LTazbLUhR.0LV8_zSwITy34Upc

Esther Montmany conscious parenting recording 2 (1h12m): https://us02web.zoom.us/rec/share/qaM7ftwVs7_Srz2KcYO2GUG5uabaOx0U0VEyuy0DpIioeJt5Hl_tNqoO_t7z2dIR.gU9Y2sZSKk5vxH1D

Esther Montmany conscious parenting recording 3 (53m): https://us02web.zoom.us/rec/share/cqikwYbhsiS7OrHEpVNCC65R38kLtEcr082pluwE5WmKmtvDClUZ3-OQuwOom9GC.v3sdKVeHXfROD-Mq?startTime=1661336997000

Esther Montmany conscious parenting recording 4 (1h26m): https://us02web.zoom.us/rec/share/cqikwYbhsiS7OrHEpVNCC65R38kLtEcr082pluwE5WmKmtvDClUZ3-OQuwOom9GC.v3sdKVeHXfROD-Mq?startTime=1661341173000

**Comment by EilidhRoss1** [comment]
Seen, will add to the todo list to get done before the end of the month.

**Comment by EilidhRoss1** [comment]
Working on this today. I've got access to recordings 1-3 however I'm confused about recording 4 as it doesn't seem to have ever existed. When I was [cataloguing](https://docs.google.com/spreadsheets/d/140ZSrXYjSdhU_nBBZAMBgzTx9oo-C-wad4ikJYNrwvM/edit?pli=1#gid=0) all the zoom recordings earlier this month, there were only 3 conscious parenting episodes filmed with Esther in August 2022. The length of these 3 recordings match up with the lengths of recordings 1-3 as given in this issue. That only 3 episodes were recorded is corroborated by the emails we received from zoom - only 3 emails were received notifying us of recordings being saved to zoom on the days 22 and 24 of August 2022 for the calls named 'Esther Montmany on Conscious Parenting'. We have received no other emails regarding the saving of any other recordings using Esther's name on any other day. We received no other emails regarding any other cloud recordings under any name in between Esther Montmany on Conscious Parenting recording 3 on the 24/08/22 and the next saved recording on 02/09/22 with Peter Lipman. 

We have 3 other conversations with Esther saved to the drive, however none of the lengths of these videos match that of recording 4 as given here. 

@rufuspollock can you let me know if you think recording 4 might have been saved anywhere other than the Life Itself zoom cloud. 

In the meantime, I will begin processing recordings 1-3.

**Comment by rufuspollock** [comment]
@EilidhRoss1 my *vague* recollection now was that recording "3" had two parts (as the entire session lasted a long time). Did we have two parts to recording 3 (or any of the other ones)?

The other thing is i've found a 4th recording *in my personal zoom* though i'm not sure we would publish this one. In any case i will download and add to the folder for this project.

**Comment by EilidhRoss1** [comment]
Recordings 1 and 2 were two parts and a separate email was sent for both. Whereas for recording 3 only one email was sent with one recording.

**Comment by rufuspollock** [comment]
@EilidhRoss1 just so you know you can find a bio and headshot for esther on this post: https://lifeitself.org/blog/2021/11/30/community-hangout-december-2021

**Comment by EilidhRoss1** [comment]
Series published, landing page task still outstanding

**Comment by rufuspollock** [comment]
@nathenf one issue i noticed is that we have published the "hangout" content (see #91) as a podcast which was never my intention. Can we remove the hangout from our podcasts both on the relevant channels and on the podcast page. The only intention for the hangout was we publish it to youtube and embed in the hangout post for that event (from dec 2021)

**Comment by rufuspollock** [comment]
@nathenf assigning this to you for remaining item which is creating a "project" page for this. Could be a good initial try-out (as new) for getting our standard "project" page right (cf #97).

**Comment by nathenf** [comment]
@rufuspollock only task left open here is time stamping for specific topics. Perhaps something for Zaib to practice on?

**Comment by rufuspollock** [comment]
@nathenf there's a whole chunk for the landing page? (or is that a separate issue?)

**Comment by nathenf** [comment]
@rufuspollock I'm not sure what you mean here. I've not seen any other text, but happy to add it in.

**Comment by rufuspollock** [comment]
@nathenf in the issue description ...

<img width="805" alt="image" src="https://user-images.githubusercontent.com/180658/222469233-00ef45bf-a002-4678-9d9d-a156a03cb4c2.png">

**Comment by nathenf** [comment]
@rufuspollock I understand now, by chunk you were talking about open tasks not a piece of content to add to the page. Thanks for clarifying, I've now updated the issue

**Comment by rufuspollock** [comment]
@nathenf great job on the page.

One small comment is to check the material either after go-live or before (if a PR with a preview) as a small number of formatting issues (i've fixed these both): e.g.

![image](https://user-images.githubusercontent.com/180658/222886296-1e9e63fb-90f1-4b8c-aa6e-c3d5bac96415.png)

**Comment by rufuspollock** [comment]
FIXED. All done - see especially https://lifeitself.org/projects/conscious-parenting 👏. 

I moved out the one future item into the parent issue #94
