### ISSUE TITLE
[epic] Life Itself Branding and Style Major Revision 2022

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#162]
To update brand (narrative) and associated design guidelines and have these published and known by all relevant stakeholders.

**Resources**
- [Brand 2022 A10](https://docs.google.com/document/d/1edZUkd3O3nxIBCeX8xb-Yvra3Q_xmStunNYHwarKogA/edit#heading=h.9jh0gkl15o07)
- [High Level Mission Statements Excalidraw](https://excalidraw.com/#room=e46b905c3d5981cb6275,sTqBvg1Gdf8UySMibsdiDw)
- [Issue Tree](https://docs.google.com/spreadsheets/d/18PawidoZU2omOa1q8xpEXhQobtK4g8m3vlTIgyzlfZ4/edit#gid=857074362)
- [Asset Templates](https://docs.google.com/spreadsheets/u/0/d/1M7Sfvkrg0q5XmFvGRDJSf9E_sEHMfw1rB0p2xTCuYEU/edit)

## Acceptance

- [x] Preparatory
  - [x] Complete A10 **✅2022-07-19 [A10 done](https://docs.google.com/document/d/1edZUkd3O3nxIBCeX8xb-Yvra3Q_xmStunNYHwarKogA/edit)**
  - [x] Complete SCQH and Issue tree **✅2022-09-15 [SCQH in A10](https://docs.google.com/document/d/1edZUkd3O3nxIBCeX8xb-Yvra3Q_xmStunNYHwarKogA/edit) and [issue tree](https://docs.google.com/spreadsheets/d/1NDkT_bRVHs16Hr9BiCrr5XlyBErAz7iqK4g2cPC4I3U/edit#gid=501497498)**
- [ ] [Brand Narrative for Life Itself Overall Completed 🚧 90% ](https://docs.google.com/document/d/1aiN0XS9z_h0bOt4ssN6bTBDCs8pcwctoz5V0CSsXdTE/edit#heading=h.a74zrqdvzj3k)
- [ ] TODO: Style Guide complete and finalised
- [ ] Rollout of complete branding across comms channels & website

### Initial

- [x] Complete A10
- [x] Complete SCQH
- [x] Iterate issue tree
- [x] Do market research

### November 2022 Onwards

- [x] Create poster for the hub about Life Itself ✅ **Poster created and published in Evolve magazine, additional posters made for the hub #611**
- [x] Write copy for poster 🚧 [Writing copy here](https://docs.google.com/document/d/1vb7rjwWdhh1xNnUaFcbhfFMU2IfFHtFrkZinrbGfSlU/edit#heading=h.g3zk809lcaot)
- [x] Mockup homepage ideas for website ❌ **Did not complete and not sure if relevant now**

### Comms

 ~~* [ ] Blog post announcing the process (use scqh?)
  * [ ] Why (do this)?~~
* [ ] Back publishing stuff from 2020 (because it goes away when we change)
  * [ ] Also misc associated stuff like https://docs.google.com/drawings/d/1z1owGCwGQscPfuLbHr-hwciGukhn6WEkzbl6qVt0wGU/edit

**Comment by nathenf** [comment]
@laurenwigmore see this issue RE style guide - we never got to completing it.

**Comment by rufuspollock** [comment]
FIXED / WONTFIX. We did a bunch. If we want to revisit this we can open a new issue. Suspect some brand update to be done at some point but not really a priority atm.
