### ISSUE TITLE
Wiser Newsletter

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#166]
**TODO: brief overview and description**

* [Wiser Newsletter A10](https://docs.google.com/document/d/12GLL3ljWZem1zXBec_na_vRlAoRhiu-dLAcQHGoMlK4/edit#)
* [Newsletter Issue Tree](https://docs.google.com/spreadsheets/d/1-lJq5mG8a3rI7SmXYkEhA9OZMrTGKLBmOL8yj4gPXDc/edit#gid=884760664)

## Acceptance

- [x] A10 for Newsletter ✅ **[A10 is complete](https://docs.google.com/document/d/12GLL3ljWZem1zXBec_na_vRlAoRhiu-dLAcQHGoMlK4/edit#)
- [ ] Four months of weekly newsletters sent
- [ ] Summary & Analysis of the newsletter after four months

### By middle of November

- [x] Create A10 ✅ **[Done](https://docs.google.com/document/d/12GLL3ljWZem1zXBec_na_vRlAoRhiu-dLAcQHGoMlK4/edit#)**
- [X] Complete budget proposal  ✅ **[Done](https://docs.google.com/document/d/12GLL3ljWZem1zXBec_na_vRlAoRhiu-dLAcQHGoMlK4/edit#)**
- [x] Survey analysis and create summary ✅ **[Done](https://docs.google.com/document/d/1VLEeByF5mPNkvSJxJgBQOK6qkd-VagTpTwFRhEdwtWE/edit#heading=h.6sfjapbgg3jb)**
- [X] Competitor Analysis ✅  [See here](https://docs.google.com/document/d/1E_zb3QNyx9steTrjtGhRx6hohVz7ZMQNuRyjSOsRHWY/edit#) and [here](https://docs.google.com/spreadsheets/d/1Ep9r3VEhiWNaFx3PVMReu22nft3d6Uz79D4GBFni30c/edit#gid=541671272)
- [ ] Do job stories, user journey & user profile
- [ ] Define what “this working” looks like

### By end of November

- [x] Decide which mail platform to use
  - [x] Test options (Revue, Zoho, Mailerlite, etc.) for functionality, ease of use & price ✅  **After weighing up options, we will use Beehiiv** [see comparisons here](https://docs.google.com/spreadsheets/d/1Ep9r3VEhiWNaFx3PVMReu22nft3d6Uz79D4GBFni30c/edit#gid=1676172603)
  - [ ] Set-up mail platform #203 
- [ ] Create design inline with brand
- [ ] Finalize curation strategy & criteria
  - [ ] Setting up Mailbrew
  - [ ] Gathering other newsletters
  - [ ] Deciding criteria for inclusion
  - [ ] Set up curation workflow
  - [ ] Create SOP for curation
- [ ] Creating landing page and sign-up processes
  - [ ] Research good landing pages and copy
  - [ ] Write landing page copy
  - [ ] Design landing page
  - [ ] Build landing page 
  - [ ] Decide sign-up placement (e.g pop-up, top of website, twitter, etc.) + create drafts of this
- [ ] Set up Patreon
  - [ ] Signing up 
  - [ ] Design
  - [ ] Decide donation levels
  - [ ] Writing copy 

### By end of 2nd week of December

- [ ] Make prototype newsletter to get feedback on
  - [ ] Finalize newsletter structure
  - [ ] Make a template
  - [ ] Test curation strategy
  - [ ] Get team feedback & iterate
- [ ] Do 6 user research interviews using a prototype newsletter (signing-up, actual email, decision making, providing feedback, donation option)
  - [ ] Arrange interviews 
  - [ ] Plan what we will ask 
  - [ ] Complete interviews 
  - [ ] Analyze interviews
  - [ ] Summarise and use feedback to iterate 

### Before Christmas

- [ ] Have metrics finalized and spreadsheet set up
  - [ ] Decide metrics
  - [ ] Create spreadsheet
- [ ] Create launch plan & prepare 
  - [ ] Brainstorm what we do
  - [ ] Preparing copy
  - [ ] Pre-launch content
- [ ] Create PR/outreach plan

### By end of first week of January

- [ ] Prepare draft for the first issue
- [ ] Launch the newsletter on the first friday
  - [ ] Content across platforms
  - [ ] Dming certain people
  - [ ] Getting people to share it
  - [ ] Going live with landing page/ctas etc.

### Ongoing (Jan-April)

- [ ] Weekly Curation
- [ ] Weekly Analytics Collection 
- [ ] Weekly PR/Outreach
- [ ] Weekly creation and delivery
- [ ] Monthly feedback form
- [ ] Monthly check-in, feedback analysis and iteration session 

### Post-Experiment

- [ ] Create another survey to get feedback and reflections on the newsletter 
- [ ] Retrospective summary

### Inbox of potential topics

Tips and tricks

* [ ] Irregular Interruptions - and the app on my phone @rufuspollock can you remember what this is? 

Key ideas

* [ ] Fundamental wellbeing (aka waking up) - moving off the end of the maslow spectrum

**Comment by nathenf** [comment]
Have decided on Beehiiv for the email platform as seems most useful and also free up to 2500 subscribers. Its a relatively new company but product updates are coming thick and fast

**Comment by nathenf** [comment]
I've done a competitor analysis and made a summary of insights [here](https://docs.google.com/document/d/1E_zb3QNyx9steTrjtGhRx6hohVz7ZMQNuRyjSOsRHWY/edit#), I didn't find any direct competitors.

**Comment by EilidhRoss1** [comment]
Currently paused

**Comment by EilidhRoss1** [comment]
@nathenf can we close this as won't fix?

**Comment by nathenf** [comment]
@EilidhRoss1 yes we can, but can you first check that these tasks are the same as logged in the A10, if its the same then let's close this

**Comment by nathenf** [comment]
WONT FIX - We are no longer working on this project and is therefore not relevant to keep open. The A10 contains all information about the roadmap and this can be revisited with whatever topic we choose in the future.

**Comment by rufuspollock** [comment]
@nathenf great to clean this stuff up. can we add `wontfix` label when closing as wontfix.
