### ISSUE TITLE
Migration of ecosystem.lifeitself.org to lifeitself.org

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#167]
Context: https://github.com/life-itself/community/blob/main/projects/digital-garden-2022.md

Goal: ecosystem site part of lifeitself.org

Requires: lifeitself.org (at least in part) running off a nextjs site - probably booted off flowershow (in long run whole of site)

2 parts:

1. Preliminary: setup basic nextjs infrastructure for lifeitself.org site going forward
1. ecosystem.lifeitself.org migrates to lifeitself.org

## Acceptance

- [ ] lifeitself.org/ecosystem/ exists and sub-pages and contains content of current ecosystem.lifeitself.org

## Tasks

- [ ] copy over ecosystem content into base directory at e.g. ecosystem
- [ ] symlink into content at `content/ecosystem`
- [ ] symlink components from relevant location to right place
- [ ] get it running

Comment: i prefer model where we symlink things into content folder - it allows us to have one layer of indirection and keep structure of content for editors slightly distinct from that on the site itself

### Extras

- [ ] what do we do with current content at lifeitself.org/ecosystem? (migrate to markdown and relcoate somehow?)
  - [ ] Move to an old blog post?

**Comment by rufuspollock** [comment]
@khalilcodes have site deployment now working at https://next.lifeitself.org via netlify

**Comment by khalilcodes** [comment]
@rufuspollock @olayway 

Current progress on ecosystem migration - https://github.com/life-itself/community/tree/ecosystem-migration

- [x] ecosystem content in root folder symlinked to site - `site/ecosystem --> site/content/ecosystem`
- [x] ecosystem components working by moving to `flowershow/components/ecosystem`
- [x] page working @ `/ecosystem`

Unfortunately the ecosystem component imports were not working if symlinked from content folder which now resides outside flowershow folder. I believe this is because `package.json` is in flowershow folder and content folder (since outside) cannot resolve the required packages.

**Comment by rufuspollock** [comment]
@khalilcodes thanks for the excellent update. Quick comments:

- `ecosystem` folder should be in root of repo rather than site i think inline with other folders we have (site is pretty much empty).

> Unfortunately the ecosystem component imports were not working if symlinked from content folder which now resides outside flowershow folder. I believe this is because package.json is in flowershow folder, and content folder (since outside) cannot resolve the required packages.

This is an interesting point - in most flowershow installations we won't have the content folder inside the flowershow folder ...

**Comment by khalilcodes** [comment]
@rufuspollock @olayway PR is up at #174

**Comment by olayway** [comment]
@khalilcodes I think you can assign me as a reviewer

**Comment by rufuspollock** [comment]
FIXED. All done. See 594422d31ed33c11698ff1d0c01ff24b613aee82
