### ISSUE TITLE
[epic] Life Itself new integrated website 2022 

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#170]
We are doing a major update of the Life Itself website to. It consists of several interlocking parts:

- Tech upgrade: switch from Wordpress to Flowershow both to provide a better (faster) experience, to allow for easier contribution and to set us up to add new features going forward (e.g. digital garden)
- Content consolidate: consolidate and refactor bringing together content from various sites (e.g. tao, ecosystem) into main site and doing a bit tidy and improvement to reflect current activities and make material more accessible
- Add a new digital garden with a wiki-like where we can publish more informal material and can have community contribution

Underpinning

- Content migration: migrate content from old site to new site
- Consolidation: get all our content into one site integrate content from dispersed other sites e.g. tao, sutras, cultural-values 
- Content refactor: refactoring and cleaning up our content to 
- Digital garden section: ...

## Key Documents

- [A10 for Website Update](https://docs.google.com/document/d/1fhl4quGen3KmglOYzfG6MXAbk7yR2H87weeN8ACqxBg/edit#heading=h.599vpyhb8naq)
- [Mainpage Excalidraw](https://app.excalidraw.com/s/9u8crB2ZmUo/3HFKSwsU9zH)
- [Website Structure in Coggle](https://coggle.it/diagram/YsUYJmqIBdEcOuNM/t/wiser-2022)

## Acceptance

* [x] Next steps (feb 2023) #334  **🚧2023-02-16 80% there.** **✅2023-03-10 focus is on #170 and #335 followed by more site pages (see acceptance below)**
* [ ] Job stories for new site 🚧 **See [gdoc](https://docs.google.com/document/d/1qKvH41W5s2IW16UHyk16fr3uj9gbhAC3k5pSvQ66aXg/edit)** **💬2023-03-10 major updates and have a good set of first stories.**

Migration and integration

* [x] LifeItself.org migrated and live #184  
* [x] Integrated other sites ✅ **All integrated 20/12/2022**
  * [x] Tao #182 ✅ 
  * [x] Cultural values #200 ✅ 
  * [x] Sutras #125 ✅ 
  * [ ] Climate?? **WONT FIX - will stay as own site for now**
* [x] Switch over #259
* [x] Immediate next steps (post go-live) #260 **✅2023-02-16 all done now**
* [x] Ecosystem integrated #167 **✅2022-12-10. Note some next steps below**
  * [x] Redirect of ecosystem.lifeitself.org to lifeitself.org/ecosystem/ ✅ 
* [x] New Digital garden / notebook section **✅2022-12-21 Have a notes section and content in there so useable. more can be done - have more items below**

Improvements and next steps

- [x] Create Project pages #97 ✅ **Initiative pages are live**
- [x] Homepage updated with current offers and calls to action #335 
- [x] Key sub landing pages
  - [x] Learn for topic X
  - [x] Ideas or Writings #124 
  - [x] Projects landing page (may be part of #97) ✅ 
- [ ] Refactored Life Itself site #223 **⛔ 05/01/2023 have worked on this ah-hoc, requires job stories as next step. 2023-02-16 @rufuspollock look through this and see whether this can merge back here etc.**
- [x] (?) Improved blog page #317 

Digital garden extra

* [ ] Digital garden improvements e.g. a special theme for this section that flags you are in digital garden and that some things are incomplete
* [ ] /notes/ works and introduces the wiki/garden
* [ ] Section clearly marked as such so people know less polished / developed
  * [ ] maybe even mark individual pieces as more or less polished

Maybe

* [ ] Forum??

## Inbox (Tasks)

NB: 🚩 thes are not tasks to do so much as inbox. Tasks that are substantial and prioritized move to acceptance and get their own issue.

Content

- [ ] Pages in need of an update - [see this spreadsheet for notes](https://docs.google.com/spreadsheets/d/13RVMrZ02Rw6a1BtftIUO4v7R7rXt5_phQLR4rHa343M/edit#gid=453234015)
- [x] Improve blog page for better content display #317 
   - [ ] Categories clearly defined and assigned
- [ ] Optimise Residencies page for people to apply
   - [ ] Testimonials
   - [ ] Intro Video
- [ ] Volunteer/Contribute Page
- [ ] Donate Page (see https://newrepublicoftheheart.org/donate/ for example)

UX

- [ ] categories have gone away - what do we do? [lifeitself.org/category/institute/conscious-parenting](https://lifeitself.org/category/institute/conscious-parenting/) **🚧2023-02-16 ~rufus suggest we wait until we have tags stuff in flowershow and use that plus redirects**
- [ ] nav for subareas of site #264 
- [x] Footer is elegant

Misc

- [ ] ➕2023-02-21 add link to facebook in our social media
- [ ] support for `posted` attribute in front matter (which is url of post on blog or elsewhere)
- [ ] ➕2022-12-18 evaluate forum software and good features of specific ones e.g. ForumMagnum **🚧2022-12-18 see https://app.excalidraw.com/s/9u8crB2ZmUo/16qvtKbcHwg**
- [ ] fix all lifeitself.us links to lifeitself.org links (and preferably relative links)
- [ ] Tidy up `co-x` in notebook
- [ ] clarify what is difference between project/stream and item in notebook (e.g. is `co-x` a project/stream or just and entry in the notebook) 
- [ ] Update `notebook/spaces` and what it is
- [ ] in merging ecosystem how do we merge stuff
  - [ ] what do we do with current content at lifeitself.org/ecosystem? (migrate to markdown and relcoate somehow?) e.g. Move to an old blog post?
  - [ ] what do we do with navbar of current site
    - [ ] how does sub-navigation within a project work - e.g. does ecosystem get its own navigation (and how does that work)
- [ ] Deprecate https://lifeitself.org/notes/projects/digital-garden-2022 @rufus 💤
  - [ ] Process content out of here into A10 or epic?

### Ecosystem

Following on from #167 which did basic content migration.

- [ ] How do we want ecosystem to integrate into the main site - is it a separate mini-section or more central. e.g. do we connect with notebook entries on particular orgs. e.g. when writing notes about an org do we put it in ecosystem or in notebook? TODO: write some job stories here **✅2023-02-16 ❌ for now i think we leave things as they are and see how they go**
- [ ] what do we do with current content at lifeitself.org/ecosystem? (migrate to markdown and relcoate somehow?) Or move to an old blog post? 🔼 **2023-02-16 this is worth doing i think mainly as back-blogging but also some relocation.**
- [ ] how do we make editing and contributing super easy? ;
	- [x] could we add commenting perhaps to these pages? **✅2023-02-16 ❌ wontfix. not priority. would be good to have some comment about how to give feedback which is probably just posting on the forum.**
- [x] should ecosystem folder move into the vault? Why? Why not? **✅2023-02-16 my instinct is yes, move this to the vault. no real issue in doing so and it means we can link things more easily. imagine this is cheap to do e.g. ~1h**
- [ ] move ecosystem to the vault ⏫ i.e. ecosystem content in vault/ecosystem and images in `assets/ecosystem`

### SEO

- [ ] Submit new site map to Google
- [ ] Update meta descriptions for all pages
- [ ] Alt text for images
- [ ] Add feature images to pages 

### Developer oriented phase I

- [x] #172 **✅2022-10-24 - see https://next.lifeitself.org**
- [x] #171 **✅2022-10-30 `vault/notes` created and most stuff moved there**
  - [x] #173 
- [x] #167 
- [x] #181 **🚧2022-11-06 theming in progress. see #185**
- [x] #182 **🚧 90% complete**
- [x]  #125 - Migrate sutras to lifeitself.org/sutras or lifeitself.org/notebook/sutras

### Content (only)

- [x] #184

### Misc

- [x] Set up web analytics **✅2022-10-30 add GA4 analytics associated to lifeiteslf.org**
- [x] Consolidate on standard frontmatter e.g. `authors` or `author` **✅2022-10-30 go with `author` and it's an array**
- [x] 404 page (with search if possible like we have today!) **✅ 2023-01-14 Done in PR #262**

### Why not do the simplest thing possible: nextjs app at root and everything in content? (2022-10-29)

What's the simplest thing possible right now?

- nextjs app at root
- content folder is the folder for the site
  - put it in nextjs folder

Why don't we do this? ??

- Probably don't want everything at root as messy and some stuff will arrive over time that isn't part of the app => have app at e.g. `/site/`

### Questions

- [ ] Do we have books as a subdirectory (or use a type? or use a category link?)
- [x] Why have tao and garden separate? what's the real difference? **✅2022-10-29 tao is our official guide to community etc whilst garden is more informal and in progress. tao can link to garden and vice-versa.**
- [ ] do we want whole site managed in obsidian or have sub-parts that are separate
  - If they are separate how do we deal with linking ...
    - between parts? no easy solution
    - have links even within a part deploy correctly e.g. if `tao` is it owns vault in obsidian then how do we have links work correctly? Ans: use relative link path formats. Sub-question: how does that work with e.g. assets and excalidraw?

**Comment by rufuspollock** [comment]
@nathenf i've done quite a bit of refactoring here e.g.

- split acceptance into groups
- tasks
  - moved most completed items down into tasks completed
  - created inbox and moved tasks there that aren't prioritized or analyzed (almost all that remained)

**Comment by nathenf** [comment]
FIXED - The main bulk of website work has now be complete. Open tasks have now been merged into our ongoing website issue tracker #454
