### ISSUE TITLE
Digital Notebook v0.1 live on site

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#171]
Take our existing notes etc and consolidate and get up on site. Also do this in way that prepares for integration of more content.

❗ we are going to use our obsidian vault to edit the whole site i think, not just the notebook so we are going to set up a vault that includes the notebook but is not limited to it ... (see discussion below in analysis).

## Acceptance

- [x] Repo is "clean" with only a few folders at root and README with brief outline **✅2022-10-30 now just have README, `site` and `vault` (plus primers and research to move)**
- [x] first version of digital garden live at https://next.lifeitself.org/notebook/ **✅2022-10-30 it is working, see e.g. https://next.lifeitself.org/notebook/ken-wilber**

## Tasks

- [x] Refactor repo in preparation for use for life itself site and digital garden
- [x] Integrate notebook section into site
- [x] deploy

### Refactor repo

- [x] Analyse existing files and recommend changes **✅2022-10-29 see below**
- [x] Prep the vault 
  - [x] Create `vault` folder
  - [x] move things into it 
  - [x] Rename `notes` to `notebook` (in obsidian so that links are fixed)
  - [x] Move `books` into `notebook`
  - [x] Move `journal` into `notebook`
  - [x] Move projects into `notebook` (and tidy up e.g. remove irrelevant ones)
  - [x] remove streams for now as empty
  - [x] remove FYI.md
- [x] Refactor `site` to just be flowershow (makes things simpler)
- [x] Update README.md

FUTURE

- [x] move `co-x` into notebook
- [x] move `spaces` into notebook
- [ ] tidy up `primers` 

### What is vault, why have it and is it just the notebook or whole site?

2 needs

- setup for obsidian so you can use obsidian e.g. for linking
  - will end up including most of the site ==> 
  - don't want it including e.g. `site` as that leads to issues with e.g. `node_modules`
- mirror the main content layout so links work as expected

=> that our vault is not just the notebook though for now that will be mostly what it is

### Repo layout

Currently we have a miscellany and files and folders at the root level (see list). It is a mix of items that are part of the nascent digital garden plus others (e.g. co-x) that are older leftovers. Furthermore, we are about to bring in some new items such as tao and sutras. 

```bash
# move into vault
Excalidraw
assets
books
journal
notes
templates

# delete
FYI.md
streams

# keep
README.md
projects    # may later move 

# process into vault/notes later
co-x
primers
research
spaces

# website
site 
```

**Comment by rufuspollock** [comment]
FIXED. All done. Primer stuff in #173
