### ISSUE TITLE
Skeleton of new life itself site powered by flowershow

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#172]
lifeitself.org (at least in part) running off a nextjs site - probably booted off flowershow (in long run whole of site)

Preliminary: setup basic nextjs infrastructure for lifeitself.org site going forward

## Acceptance

- [x] next.lifeitself.org live running off flowershow **✅2022-10-23 it's work see https://next.lifeitself.org/**

![image](https://user-images.githubusercontent.com/180658/198870767-7531ef0e-c183-44ed-80cd-8475967d6fce.png)

## Tasks

- [x] Identify repo to use for this? **✅2022-10-20 use https://github.com/life-itself/community as we already have content there**
- [x] boot flowershow instance in it (and probably commit it) located at e.g. `site` or just in default `.flowershow`
- [x] Set up build on e.g. netlify **✅2022-10-26 working deploy at https://next.lifeitself.org**

**Comment by rufuspollock** [comment]
FIXED. https://next.lifeitself.org

![image](https://user-images.githubusercontent.com/180658/198870774-9ab32afc-9f0a-4809-81cd-0d90d3347bb7.png)
