### ISSUE TITLE
Process primers into notebook

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#173]
S: primers are result of very first research efforts in autumn 2016. They contain an intro with summary of our early research effort (starting autumn 2016) plus the first "primers" we wrote (primers = short topic summaries on areas of interest). cf #96 

C: this material should now be somewhere else e.g. integrated into notebook. Plus some of it was posted (which stuff?)

H: migrate material into notebook. don't worry some of it was posted b/c the material may yet evolve - though let's note if was posted (e.g. use `posted` tag). move research summary into a section for 

## Acceptance

- [x] `primers` no longer exists **✅2022-10-30 removed in 32423d980916d3bba5987dbd727740a002d39a69**
- [x] all substantive content is migrated **✅2022-10-30 moved into notebook**
- [x] community research initiative "area" (as in PARA area) with summary **✅2022-10-30 created with summary from primers stuff**

Bonus

- [x] Back-blog to 10 Sep 2016 the overview and idea for research effort (this is date when material was created based on [gdoc history](https://docs.google.com/document/d/18_vdpVcpKCvdhpwO3cUDPBsMttMD9AzueH4e7cVjHhc/edit#heading=h.gmi8hdjvtbi)) ✅ **backblogged [here](https://lifeitself.org/2016/09/10/community-research-initiative/)**

## Tasks

- [x] Analyse what is in primers and what to keep or not and where to move it
- [x] Create community research program area in notebook
- [x] move primers to notebook
  - [x] add link for associate blog post link
  - [x] link from research area item to primers as outputs

Extras

- [ ] remove line-wrapping at 80 characters from primers we migrated @EilidhRoss1 
- [x] add all the additional material to the research overview from the [gdoc](https://docs.google.com/document/d/18_vdpVcpKCvdhpwO3cUDPBsMttMD9AzueH4e7cVjHhc/edit#heading=h.2mc6d1vgitxs) as primers only has a part of it. 🚧 **[commit pushed 21/12/22](https://github.com/life-itself/community/pull/227/commits/9a418e2d480b543d2bda8e868beb21fa43fc0056)**
- [x] check mindfulness primer as in markdown vs the [gdoc](https://docs.google.com/document/d/14mJmmLYmaqLY5aoX1dFskHsbVL5SkXcXWSWsfoqq_-Y/edit#) which seems longer @EilidhRoss1 (start with quick notes) **Eilidh update: content in mindfulness primer gdoc is same as the primer as in markdown**
- [ ] ?? somehow capture annotated discussion on [mindfulness primer gdoc draft](https://docs.google.com/document/d/14mJmmLYmaqLY5aoX1dFskHsbVL5SkXcXWSWsfoqq_-Y/edit#) (which was really amazing)
- [x] convert mindfulness page https://lifeitself.org/mindfulness/ on site to a blog post with correct date @EilidhRoss1 **✅2022-12-19 as part of #184**
- [x] non-attachment to views is missing some images in the source [gdoc](https://docs.google.com/document/d/1OTyGESR8UMNZr3zRMZTuxbYB3hQsE4xpVcZcAcSRB6I/edit#) @EilidhRoss1 ✅ **images added https://github.com/life-itself/community/pull/227/commits/aba70417cccd296e9c528752258e8017061a9524**

Really extras

- [x] https://lifeitself.org/2016/10/23/my-introduction-to-gautamas-uncommon-wisdom/ has image for non-attachment to views event https://artearthtech.files.wordpress.com/2020/03/non-attachment.png but in old wordpress location and not migrated @EilidhRoss1 (migrate this into wordpress media library) ✅ **image in wordpress media library**
  - [x] use this image in notebook (as well as in blog) @EilidhRoss1  ✅ **image in non-attachment-to-view page in community/vault/notes**

### Analysis of primers contents

Key material is in chapters. Rest is build material of built output. 

- For historical interest we might keep ArtEarthTech

```
00_title.md  # delete
index.md      # delete
introduction.md # overview of research program. move to notebook/area/research. maybe also back-blog

# these are actual 
memes.md   # not posted afaict
mindfulness.md   # posted as a subpage rather than blog post https://lifeitself.org/mindfulness/
non-attachment-to-views.md - https://lifeitself.org/2016/10/20/open-mindedness-and-non-attachment-to-views/
summary-how-much-is-enough.md - https://lifeitself.org/2017/02/05/summary-how-much-is-enough-skidelsky-2012/
```

#### Full tree

```
├── Makefile
├── README.md
├── chapters
│   ├── 00_title.md
│   ├── index.md
│   ├── introduction.md
│   ├── memes.md
│   ├── mindfulness.md
│   ├── non-attachment-to-views.md
│   └── summary-how-much-is-enough.md
├── docs
│   ├── 00_title.html
│   ├── ArtEarthTechPrimers.pdf
│   ├── CNAME
│   ├── css
│   │   ├── bootstrap.min.css
│   │   └── style.css
│   ├── images
│   │   ├── meme.png
│   │   └── topics_overview.png
│   ├── index.html
│   ├── introduction.html
│   ├── memes.html
│   ├── mindfulness.html
│   ├── non-attachment-to-views.html
│   └── summary-how-much-is-enough.html
├── images
│   ├── README.md
│   └── meme.pdf
└── style
    ├── bootstrap.min.css
    ├── default.epub
    ├── default.html
    ├── default.latex
    ├── preamble.latex
    └── style.css
```

**Comment by rufuspollock** [comment]
All of the core work is done. However, in the process have found a lot of things to fix / improve (especially in comparing primers as produced with what was in source gdocs)

**Comment by rufuspollock** [comment]
FIXED. All done. (can leave line-wrapping for now!)
