### ISSUE TITLE
Integrate tao into main site at lifeitself.org/tao (migrate from tao.lifeitself.org)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#182]
move contents of tao.lifeitself.org (https://github.com/life-itself/tao) to lifeitself.org/tao (i.e. vault/tao in this repo)

Why? See LifeItself.org migration A10

## Acceptance

- [x] (next.)lifeitself.org/tao is live with home page **✅2022-12-11 see https://next.lifeitself.org/tao**
- [x] All content is migrated to relevant location (or deleted) **✅2022-12-21 everything in spreadsheet processed. See notes below and https://next.lifeitself.org/tao/ plus the notes section**
  - [x] tao
  - [x] note(book) **✅ see https://docs.google.com/spreadsheets/d/13RVMrZ02Rw6a1BtftIUO4v7R7rXt5_phQLR4rHa343M/edit#gid=453234015, all content destined for the notes has now been moved**

## Tasks

- [x] What are principles of what goes in tao vs notebook **✅2022-11-08 see below**
- [x] Analyze current contents of tao and where it goes **✅2022-11-08 analyzed all tao pages in this spreadsheet with summary, action and priority https://docs.google.com/spreadsheets/d/13RVMrZ02Rw6a1BtftIUO4v7R7rXt5_phQLR4rHa343M/edit#gid=453234015**
- [x] Take actions based on that
  - [x] Migrate files to tao **✅2022-12-11 see PR #216 and https://next.lifeitself.org/tao**
    - [x] fix internal links
    - [ ] bulk fix lifeitself.us links to internal links where possible (once life itself migration done?) 
  - [x] Delete files (this just means don't migrate!)
  - [x] Migrate files to notes (notebook) **✅ see https://docs.google.com/spreadsheets/d/13RVMrZ02Rw6a1BtftIUO4v7R7rXt5_phQLR4rHa343M/edit#gid=453234015, all content destined for the notes has now been moved**
  - [x] Blog stuff **✅ see https://docs.google.com/spreadsheets/d/13RVMrZ02Rw6a1BtftIUO4v7R7rXt5_phQLR4rHa343M/edit#gid=453234015, all content destined for blog has now been moved**
  - [ ] See also #92 
- [x] Backblogging
  - [x] Hubs - ✅ see [spreadsheet](https://docs.google.com/spreadsheets/d/13RVMrZ02Rw6a1BtftIUO4v7R7rXt5_phQLR4rHa343M/edit#gid=453234015&range=F14)
    - [x] Context, agreement, readme all backblogged in [Our Hubs post](https://lifeitself.org/2017/12/02/our-hubs/ ). ✅ **Published 20/12/22, backblogged to 02/12/17**
    - [x] Bergerac page backblogged to [Bergerac Hub post](https://lifeitself.org/bergerac-hub/)  ✅ **Published 20/12/22, backblogged to 01/10/20**
  - [x] Governance - see [spreadsheet](https://docs.google.com/spreadsheets/d/13RVMrZ02Rw6a1BtftIUO4v7R7rXt5_phQLR4rHa343M/edit#gid=453234015&range=B17) ✅ **v1 backblogged [here](https://lifeitself.org/2018/08/01/governance-at-life-itself-previously-art-earth-tech-v1/) and v2 backblogged [here](https://lifeitself.org/2020/01/01/governance-at-life-itself-v2/)**
  - [x] coliving - see [spreadsheet](https://docs.google.com/spreadsheets/d/13RVMrZ02Rw6a1BtftIUO4v7R7rXt5_phQLR4rHa343M/edit#gid=453234015&range=B17)  ✅ **backblogged [here](https://lifeitself.org/2018/09/05/conscious-coliving-at-life-itself/)**

### What goes in the Tao vs the Notebook? - 2022-11-08

Conclusion: we go with option 3 based on principle that only items in tao are those re culture, practices and ops of Life Itself. Furthermore, info on standard practices, howtos etc go in notebook and get linked.

Options

- Everything in notebook except for an index page in Tao that references pages and hence makes them "part of the Tao"
- No tao section at all and just the notebook with a tao page in it (or even "Tao of Life Itself")
- Tao has some pages. Those pages are distinct in being specifically about the culture, philosophy and practice of life itself
  - Examples?
    - Where does an item about how we close issues or manage git go? My instinct is it goes to notebook
      - ditto for 'once-upon-a-time' and other random-ish items we wish to record
    - What about `glossary`? This is more specific to culture etc so would put it in
  - Sense from these examples is that principles are:
    - General howtos e.g. re git go to notebook and get referenced from tao
      - Other generic items like key texts would go to notebook and get referenced from the tao e.g. five mindfulness trainings go to notebook. If we have a special version of five mindfulness trainings that could be in the tao
    - Items re culture, practices and ops of Life Itself go in Tao

**Comment by rufuspollock** [comment]
@EilidhRoss1 @nathenf done all the preliminary analysis and given amount of content and need for refactoring this is a good one to try out migration by hand. Do you want to take a look at the spreadsheet and let me know if it is clear and then we can start on this.

**Comment by nathenf** [comment]
@rufuspollock it makes sense, we can start this

**Comment by nathenf** [comment]
@rufuspollock we are meeting at 2pm today to go through and begin migration

**Comment by rufuspollock** [comment]
I don't have that in mind calendar. I think you could definitely start and do some initial pull requests to get the hang of it.

Note we want to move from having readme in different rectory to raw file name eg

```
/xyz/README.md in Tao now

Becomes

/xyz.md in new setup
```

**Comment by EilidhRoss1** [comment]
Have submitted a pull request to move contents of tao.lifeitself.org (https://github.com/life-itself/tao) to lifeitself.org/tao: https://github.com/life-itself/community/pull/202/commits 
Have taken action based on: https://docs.google.com/spreadsheets/d/13RVMrZ02Rw6a1BtftIUO4v7R7rXt5_phQLR4rHa343M/edit#gid=453234015 
Still need to do the blog stuff.

**Comment by rufuspollock** [comment]
@EilidhRoss1 👏 and will review. Note both for this task and other ones i would strongly recommend doing just a page or two in an initial pull request to check you are on right track before doing the whole lot (kind of like doing a small experiment).

**Comment by rufuspollock** [comment]
So in PR #216 i have migrated all the files that were listed to be migrated to the *tao* (not stuff for notebook). There is plenty of tidying we could still do in the Tao but that could be for later. Next step is moving stuff to notebook.

**Comment by nathenf** [comment]
@rufuspollock we have now shifted all Tao pages that were required to shift. Notes and back posts and created and pushed. Links made in relevant places. 

##Outstanding
- Pull Request regarding migration of Library to Tao 
- Any that had the action of delete have not been transferred anywhere, will these remain in the tao archive? 
- #92 
- Bulk fix lifeitself.us links

**Comment by rufuspollock** [comment]
> Pull Request regarding migration of Library to Tao

I will review. Looks a bit of a mix ... can probably just merge.

> Any that had the action of delete have not been transferred anywhere, will these remain in the tao archive?

Yes, i'm going to archive the tao repo. So we have a backup.

> https://github.com/life-itself/community/issues/92

This can be later - this is low priority.

> Bulk fix lifeitself.us links

I think this can be something we do generally later - i'm going to add a checklist item on #170
