### ISSUE TITLE
[epic] MVP V1 of the Tao

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#190]
Originally created: March 2020

## Description

When coming to Life Itself, whether as investor, hub member, team member, or other interested party, I want to know who they are, what they believe, what they do and how they do it, so I can see whether Life Itself is right for me and how I can participate further.

Full job stories, content map etc in this spreadsheet: https://docs.google.com/spreadsheets/d/1Xtb46pYLNDeetsxCCd-3-8K2ancsnfgUXK7dGYpXnL0/edit#gid=0

Overview of content structure: https://coggle.it/diagram/XwV93bXjqAex-HlD/t/tao-content-structure-👣-mvp-of-the-tao

## Acceptance

* [ ] Interested Person Journey complete
* [ ] Potential investor/interested party Journey complete
* [ ] New team member Journey complete
* [ ] New hub member Journey complete

### Preparation

* [ ] Finalize Map of the primary flows **DONE: see below for diagrams**
  * [x] Overviewer 4 Oct 2020
  * [x] New Hubber 4 Oct 2020
  * [x] New Joiner
  * [ ] Reference
* [x] Naming: Work out nomenclature e.g. practices, patterns, principles etc **We are using Principles and Patterns. If we refer to Practices they are a subcase of Patterns**

### List of tasks

* [ ] Finalize new joiner section https://gitlab.com/lifeitself/tao/-/issues/26
* [ ] Finalize overviewer section https://gitlab.com/lifeitself/tao/-/issues/39
* [ ] Add member character traits https://gitlab.com/lifeitself/tao/-/issues/29 **not sure whether Sophie finished this**
* [ ] Finalize Governance https://gitlab.com/lifeitself/tao/-/issues/31
* [ ] Finalize Coliving https://gitlab.com/lifeitself/tao/-/issues/32
* [x] Finalize Hubs https://gitlab.com/lifeitself/tao/-/issues/33
* [x] Add Project Management guide to Tao https://gitlab.com/lifeitself/tao/-/issues/34 **merged with getting stuff done**
* [ ] Add design items to Tao https://gitlab.com/lifeitself/tao/-/issues/35 **this is empty at the moment**
* [ ] Add reference page to Tao https://gitlab.com/lifeitself/tao/-/issues/37
* [ ] Add Getting Stuff Done https://gitlab.com/lifeitself/tao/-/issues/40 
* [ ] Finalize v1-alpha of culture page https://gitlab.com/lifeitself/tao/-/issues/30
* [ ] Create Sprint Planning Guide https://gitlab.com/lifeitself/tao/-/issues/42

Misc

* [x] The library (in zotero) **DONE: Rufus put up https://tao.lifeitself.us/library/**
* [ ] The forum (? partially operational) - https://gitlab.com/lifeitself/forum. Need to decide what to do here.
* [ ] Add Gratitudes as pattern or to glossary 2020-03-07

### New Joiner

```mermaid
graph TD

subgraph New Joiner
  working[Working With Us]
  systems[Key Systems]
  tools[Key Tools]
  gsd[Getting Stuff Done]
  pre[Prerequisites]
  narr[Narrative]
  
  pre --> working
  
  subgraph Practicalities
    working --> systems
    systems --> tools
    tools --> gsd
  end
  
  gsd --> principles
  
  subgraph CultureX
    principles --> narr
  end
end
```

### Hub member

```mermaid
graph TD

subgraph Hub Member
  member[Hub Member]
  principles2[Principles]
  
  member --> What[What is a Hub<br/>Where, costs, people, timetable]
  What --> Why[Why Hubs<br/>How do they fit into our bigger vision / mission]
  Why --> principles2
  principles2 --> Practices
  Practices --> Governance
  Governance --> Agreement[Agreement<br/>What is expected of me, what can i expect]
  Agreement --> Coliving[Coliving<br/>Background on coliving background at life itself]
end
```

### Overviewer

v1

```mermaid
graph TD

overview[Overview - maybe front page]
specific[Specific areas e.g. Hubs]
initiatives[Initiatives]
culture[Culture]

overview --> specific
specific --> initiatives
initiatives --> culture
```

v2

```mermaid
graph TD

hubs[lifeitself.us/hubs]
business[lifeitself.us/businesses]
research[lifeitself.us/research]
activism[lifeitself.us/activism]
people[lifeitself.us/people]
collaborators[lifeitself.us/collaborators]
blog[life itself blog]
history[lifeitself.us/history]
involved[hubs, jobs and contact website pages]

About --> hubs
hubs --> business
business --> research
research --> activism
activism --> initiatives
initiatives --> plans
plans --> people
people --> collaborators
collaborators --> SCQH
SCQH --> culture
culture --> blog
blog --> history
history --> involved
involved --> governance
```

**Comment by rufuspollock** [comment]
FIXED. A first version of the tao was completed in Oct 2020. It was live at https://tao.lifeitself.org/
