### ISSUE TITLE
Podcast landing page for next.lifeitself.org

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#193]
A podcast page that lists all the podcasts with links to their respective pages.

## Acceptance

- [x] Create a Podcast page with list for next.lifeitself.org using template from here tailwindui.com transmit at `next.lifeitself.org/podcast/` @ https://next.lifeitself.org/podcast
- [x] OPTIONAL: individual podcast page

<img width="1458" alt="Screen Shot 2022-11-17 at 2 43 44 PM" src="https://user-images.githubusercontent.com/42637597/202425963-6cbe12b7-ee84-4b65-a489-5bf6de453f16.png">

<img width="1456" alt="Screen Shot 2022-11-18 at 8 19 46 PM" src="https://user-images.githubusercontent.com/42637597/202751989-c0f2eb4a-7abf-4f1f-ad36-a2655316e64a.png">

## Tasks

- [x] Add a Podcast layout in `site/layouts/podcast.jsx` **✅ 2022-11-16**
- [x] Create a Podcast page eg. in `content/podcasts/index.md` **✅ 2022-11-16**
- [x] Add a Podcast player that plays podcast within each page **✅  2022-11-16**
- [x] Add all podcasts as markdown pages from life itself's anchor.fm in `content/podcasts` folder **✅ 2022-11-16**

**Comment by rufuspollock** [comment]
@khalilcodes is there a PR for this?

**Comment by khalilcodes** [comment]
@rufuspollock not ready yet

**Comment by rufuspollock** [comment]
@khalilcodes i think it is ok  to get it in and we can add list of podcasts later (team can do that).

**Comment by khalilcodes** [comment]
There's a 🐛 where the podcast player doesn't show up on the list page but works on individual podcast pages. The `<AudioProvider>` doesn't seem to get the updates on play even after adding it to `_app.js`. Needs debugging.

Closing this issue with latest merge from #199
