### ISSUE TITLE
Weekly Comms tasks

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/community#197]
Weekly comms tasks that will keep our social media presence going even when we are otherwise letting social media output take a backseat as we figure out wider strategy stuff. 

This is the structure for weekly tasks, put weekly updates of comms work in comments.

## Acceptance 

- [ ] 1 insta post every 2 weeks
- [ ] 1 twitter thread per week
- [ ] 1 hour twitter engagement a week
- [ ] Insta stories

## Tasks

- [ ] Insta post
  - [ ] Select images
  - [ ] Write copy
  - [ ] Publish
- [ ] Twitter thread
  - [ ] write copy
  - [ ] publish
- [ ] Twitter engagement
  - [ ] Retweet, quote tweet, high value comments
- [ ] Insta stories
  - [ ] a good place to say what we’re doing in the moment. eg when on hub pics from hub, or otherwise what we're working on that week, interesting stuff we've seen on twitter.

**Comment by nathenf** [comment]
Thanks @EilidhRoss1, once you've gone through the process can you add amount of hours to deliver each main task?

**Comment by EilidhRoss1** [comment]
Rebooting the use of this issue.

Week ending 9/12/22

- [x] twitter thread ✅ **[Pragmatic Utopians explainer tweet done](https://twitter.com/forlifeitself/status/1601194249680478209)**
- [x] Twitter engagement ✅

Total time taken: 3 hours on twitter thread, 1 hour on twitter engagement

**Comment by rufuspollock** [comment]
@EilidhRoss1 is this done? or is this an ongoing issue?

**Comment by rufuspollock** [comment]
FIXED. / INVALID. This was an ongoing task. This is now in https://lifeitself.org/tao/communications and in any case i think we are pausing "day to day" posting for a month and focusing on specific launches of content e.g. web3 guide.
