### ISSUE TITLE
[epic] Create online dictionary of communitarian initiatives

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#2]
[NB: this issue originally created 3-4y ago in gitlab]

We want to research communitarian initiatives from around the world to understand what works, so we can learn from them to perhaps implement their methods amongst our community building efforts with art earth tech.

## Acceptance 

* [ ] to learn about the different communitarian initiatives worldwide
* [ ] to create a diverse dictionary/archive that documents the different types of initiatives
* [ ] to make the dictionary/archive easily available and readable online

## Tasks

* [ ] read Oved’s work as a starting point 
* [ ] research other works similar to Oved’s - particularly that branches out from American-based communitarianism initiatives
* [ ] research ways to present the dictionary AND research online in a way that is accessible for any interested audiences
* [ ] document all research so a cohesive bibliography can be created

**Comment by rufuspollock** [comment]
In progress at https://github.com/life-itself/intentional-communities
