### ISSUE TITLE
Migrate https://github.com/life-itself/cultural-values to digital garden

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#200]
Created this 6y ago: https://github.com/life-itself/cultural-values - useful stuff we could put in digital garden.

## Acceptance

- [x] Relevant content migrated e.g. https://lifeitself.org/notes/schwarz-cultural-values **✅ https://next.lifeitself.org/notes/schwartz-cultural-values with further reading added to Zotero and linked in the note**
- [x] Repo marked as deprecated with notice about where to go now **Repo archived and marked as moved, with note to go to https://lifeitself.org/notes/schwartz-cultural-values**

## Tasks

- [x] Analyse what is in repo and what should migrate and where **see below**
- [x] Do the migration **✅2022-12-21**
- [X] Migrate issues **All issues either transferred, transferred and converted to discussion, or deleted**

## Notes

-  README.md - Ten Values summary ⏭️ Migrate to notes/schwarz-cultural-values
  -  cultural-values/img/motivational_types_of_values.png	Ten Values diagram
- cultural-values/archive/schwartz-2008-cultural-value-orientations.pdf	PDF filed from which plain text version above is extracted ⏭️ Move to zotero and ref from the notes pages
- cultural-values/archive/draftmanual_svs_14feb2009.doc	Doc version of plain text version in txt folder ⏭️ ditto
  -  cultural-values/txt/draftmanual_svs_14feb2009.md	Rufus note when he added it: "good guide to using schwartz value survey from 2008" ⏭️ drop
  - cultural-values/txt/schwartz-2008-cultural-value-orientations.md	plain text version of Schwartz 2008 "Cultural Value Orientations: Nature & Implications of National Differences". ⏭️ drop

**Comment by catherinet1** [comment]
@EilidhRoss1 @nathenf there's not much in here; I think it's just the README file we'd migrate into the notebook. I will try that now. And then there's one or two research papers, which maybe it makes sense to save in Zotero

**Comment by nathenf** [comment]
@rufuspollock this is now migrated as a new note https://next.lifeitself.org/notes/schwartz-cultural-values with the other texts added to Zotero and linked from the note. 

OUTSTANDING
- Mark Repo as Depreciated and show where to go now. I'm not sure on the best approach to do this.

**Comment by catherinet1** [comment]
FIXED. Relevant content migrated and repo archived.
