### ISSUE TITLE
Move from Mailchimp to Beehiv

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/community#203]
## Acceptance

- [ ] We are using Beehiv rather than Mailchimp

## Tasks

- [ ] Sign up for Beehiv
- [ ] Transfer audience from mailchimp
- [ ] make template for monthly newsletter

### Why Beehiv?

See newsletter platform comparison: https://docs.google.com/spreadsheets/d/1Ep9r3VEhiWNaFx3PVMReu22nft3d6Uz79D4GBFni30c/edit#gid=1676172603

**Comment by EilidhRoss1** [comment]
@nathen I'm going to unassign myself from this and assign you

**Comment by rufuspollock** [comment]
WONTFIX for now. No compelling motivation right now.
