### ISSUE TITLE
[epic] Prep and (schedule) release of 3 podcasts from Autumn 2022

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#206]
We have 3 podcasts we recorded in Sep / Oct 2022 that we can publish. Let's get them out there!

Happy for this to split into 3 issues (or split out the 2nd two interviews) - just posting here quickly now.

Right now i would say getting at least Henrich item out b4 xmas would be great.

## Acceptance

- [x] Henrich podcast published #207  ✅ **[YouTube](https://youtu.be/vYzOr7l-U20), [Podcast](https://anchor.fm/life-itself/episodes/Joseph-Henrich-and-the-Emergence-of-a-Rigorous-Culturology-e1r9pgv), and [Blog](https://lifeitself.org/2022/11/25/joseph-henrich-and-the-emergence-of-a-rigorous-culturology/) published 1/12/22**
- [X] Steininger podcast published #211  ✅  **[YouTube](https://youtu.be/T2MFJC6oahg), [podcast](https://anchor.fm/life-itself/episodes/Thomas-Steininger-on-Emergent-Dialogue-and-Transcending-Individualism-e1rul4l/a-a7gpq18) & [blog](https://lifeitself.org/2022/12/08/thomas-steininger-on-emergent-dialogue-and-transcending-individualism/) published 08/12/22**
- [x] Martin podcast published #263 ✅ **[Published](https://lifeitself.org/blog/2023/01/19/a-scientific-approach-to-awakening-and-fundamental-wellbeing)**

## Tasks

- [x] Prep initial materials @rufuspollock **✅2022-11-24 see below**
- [ ] Move our current playbook for podcast/interview prep and sharing into the tao @EilidhRoss1 
  - [ ] Update it

### 1. Joseph Henrich

Title: (?) The Revolutionary new science of cultural evolution (aka the Emergence of Culturology)

Recording: https://us02web.zoom.us/recording/detail?meeting_id=FEdlFYg2RR2T%2BnaS88LyOw%3D%3D

Notes: see https://next.lifeitself.org/notes/henrich-culturology-interviews-2022

Description: TODO

### 2. Thomas Steininger

Title: (?) Transcending Individualism, Emergent Dialog (and what Happened to Integral)

Recording: https://us02web.zoom.us/recording/detail?meeting_id=gmpWg9ccQxam3cyvyith8Q%3D%3D

I think this can be split into two e.g. ~45m parts. To get split would be worth getting a transcript first as there was a point we moved from emergent dialog to more general discussion.

Description: TODO - either Rufus or Eilidh from review

Bio:

Dr. Thomas Steininger. He has been cultivating transformative “We Space” practices for nearly 30 years. He is a philosopher, practitioner, and spiritual mentor and has dived deeply into the practice of meditation and into an exploration of the evolution of human consciousness, particularly the current transition from a hyperindividual “I” culture to a co-conscious “We.”

As an authority on cultural evolution and the different spiritual and religious currents that have formed our postmodern world, he brings this perspective into my work as publisher of evolve-magazin, the leading German magazine on consciousness and culture and as faculty at Meridian U. in California. He also co-founded and developed a process of emergent dialogue, an advanced practice in conscious communication.

Notes / outline: don't have one atm. Let's see what we have from the transcript.

### 3. Jeffrey Martin

Title: (?) A Scientific Approach to Awakening and Fundamental Wellbeing

Recording: https://us02web.zoom.us/recording/detail?meeting_id=93WnebaqR2qmNzrkvEc37g%3D%3D

Description: TODO (probably for Rufus, though Eilidh could have a go based on listen!)

Bio:

Jeffery is a founder of the Transformative Technology space, a serial entrepreneur, and a social scientist who researches personal transformation and the states of greatest human well-being.

https://drjefferymartin.com/

Notes: (some very basic ones here) https://docs.google.com/document/d/1lPcDZh_IFGLGS9-6hxD7FGR73ec30ZQyrfiJGaY5euI/edit

**Comment by EilidhRoss1** [comment]
FIXED all published
