### ISSUE TITLE
Joseph Henrich conversation

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/community#207]
## Acceptance 

- [x] Conversation published on Youtube & Anchor ✅ **[YouTube](https://youtu.be/vYzOr7l-U20) [Podcast](https://anchor.fm/life-itself/episodes/Joseph-Henrich-and-the-Emergence-of-a-Rigorous-Culturology-e1r9pgv) Scheduled for Weds 30/11 4pm**
- [x] Blog Post published ✅ **[Done](https://lifeitself.org/2022/11/25/joseph-henrich-and-the-emergence-of-a-rigorous-culturology/) Scheduled for Weds 30/11 4pm**
- [ ] Secondary Content and Direct links shared on Social Media 

## Tasks

- [x] Duplicate this Template and rename as the working title of the conversation
- [x] [Create a new folder for the conversation and assets here](https://drive.google.com/drive/folders/12BskqKPp85XNdU2sespI--E7VPi45hGJ?usp=sharing) ✅ **[Done](https://drive.google.com/drive/folders/1Yog4g2xX8alJJ_CuWE6YlPl7T0XAYjkf)
- [x] Source the video file and transcript from the conversation and add to folder
- [x] Create a document for the conversation that includes: Title, Conversation Summary, About the person in conversation, links to resources mentioned in the podcast, timestamps for at least two video excerpts and two quotes and timestamps for ["chapters"](https://www.youtube.com/watch?v=pvkTC2xIbeY). Add this to folder.  ✅ **[Done](https://docs.google.com/document/d/1rk43YmihnKHMN2YVNb0YqXBi4H9BEP5zCV66HfRbpO8/edit#)**

- [x] **Create Youtube video** [YouTube](https://youtu.be/vYzOr7l-U20)
  - [x] Create the Youtube Thumbnail from [this template](https://www.canva.com/design/DAE99drPH4s/7mR8CgHWyHfimwC9jDerDA/edit?utm_content=DAE99drPH4s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).
  - [x] Edit the video file in Da Vinci Resolve:
    - [x] Trim beginning and end, plus any sections of poor internet connection or other interruptions
    - [x] Add thumbnail at the beginning of the video with a fade transition to the video
    - [x] Add graphic overlay ["Please Like & Subscribe"](https://drive.google.com/file/d/1iQjSdgjTyrN9xnQ8Xnlzdjmk2sw2eKXJ/view?usp=sharing) at the 5, 10, 20, 40 minute 
    - [x] [Add End Screen with a fading transition](https://drive.google.com/file/d/1fC8c_tyoOxxGGhGqgJuwFscu6vYzbrqe/view?usp=sharing)
    - [x] Increase the sound volume as much as possible without clipping the sound (you will notice because it will sound bad) 
  - [x] Export as Video for Youtube
  - [x] Upload to Youtube: Add title, thumbnail, summary including [contents chapters](https://www.youtube.com/watch?v=pvkTC2xIbeY), page stub URL, add to Web3 playlist, Add Language, Make License Creative Commons.
  - [ ] Inform Rufus and Guest that youtube video is ready to go.
  - [x] Publish
  - [ ] Ensure Rufus & Guest tweet about video

- [x] **Create Podcast** ✅ [Podcast](https://anchor.fm/life-itself/episodes/Joseph-Henrich-and-the-Emergence-of-a-Rigorous-Culturology-e1r9pgv)
  - [x] In Anchor click create new episode, use the "Intro Jingle" and add the audio only edit
  - [x] Add title & summary (incl page URL)
  - [x] Create and add thumbnail from [this template](https://www.canva.com/design/DAE87pGGDUg/EgrVC9iJX5eATZGF5rE2pg/edit?utm_content=DAE87pGGDUg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
  - [ ] Add season number and episode number

- [x] **Create Twitter Secondary Content**
  - [ ] Cut the video excerpts from the main video and leave all the clips in one timeline
         - [ ] Export just the audio
         - [ ] Upload Audio to Otter.ai to create srt file (srt file settings: no more than 1 line and 60 letters per line) - make sure that the speech from each clip is correctly separated in Otter.ai
         - [ ] Upload the srt file to the project 
         - [ ] Crop top and bottom of video - add title to top and subtitles at the bottom
  - [ ] Create Quote posts using [this template](https://www.canva.com/design/DAE-ett42vU/63HsI5cGixlZ6cFQd09zCg/edit)
  - [ ] Add all content to the folder that has been created 

- [x] **Create Blog Post** ✅ **[Done](https://lifeitself.org/2022/11/25/joseph-henrich-and-the-emergence-of-a-rigorous-culturology/)
  - [x] Create a blog post beginning with the summary then embed the video, the podcast and include the transcript ✅ **all done except transcript**
  - [ ] Add the relevant quotes and video excerpts (Twitter format) as images between the transcript

**Once blog is complete we can schedule content on Twitter**

**Comment by EilidhRoss1** [comment]
FIXED: https://lifeitself.org/2022/11/25/joseph-henrich-and-the-emergence-of-a-rigorous-culturology/
