### ISSUE TITLE
2022 Year in Review post and mailout

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#209]
Idea: creating a "year in review" piece covering some highlights from across Life Itself and the network - plus maybe some (joky) metrics (e.g. number of residents over the year, number of tweets) would be nice.

Could also include some calls to action e.g. pointers to new residency, trailing the website revamp.

@EilidhRoss1 if you were happy to prep this we could then schedule this to go out ~ 2nd week of dec (w/c 12th). This could replace our usual newsletter in dec.

Eilidh update: working doc [here](https://docs.google.com/document/d/1EpwAadVUWNIJe84-5bMhzQIhhSElXT4a-DwYgNo5_sU/edit#heading=h.pfsy3ohe1riz)

## Acceptance

- [ ] Year in review is sent out 🚧 **Scheduled for 11am 15/12**

## Tasks

- [x] @EilidhRoss1 get in touch with team about various contributions ✅
- [ ] Copy is written
  - [ ] Intro
  - [ ] Highlights
    - [ ] Life Itself Labs launch
    - [ ] Ecosystem Mapping
    - [ ] Web3
    - [ ] Residencies
    - [ ] Top content
    - [ ] Berlin Hub
  - [ ] Look forward to 2023
    - [ ] Labs
    - [ ] Mapping
    - [ ] Residencies
    - [ ] Website revamp
- [ ] Metrics are done

**Comment by EilidhRoss1** [comment]
Sounds good 👍

**Comment by rufuspollock** [comment]
@EilidhRoss1 do you want to update tasks and acceptance?

**Comment by nathenf** [comment]
FIXED - This went out on the 15.12.2022 and was opened by 31.2% of our audience.
