### ISSUE TITLE
Review call with Ian MacKenzie

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/community#215]
On 7/12/22 I spoke with filmmaker Ian MacKenzie who had reached out enquiring about the possibility of collaborating/ integrating with Life Itself. 

I've written up a [brief from the call](https://docs.google.com/document/d/1AD0OHIzKjuIK47GiiOcG-seyvUAn7Dn01OmxXRr7xjk/edit#heading=h.a128nakbq8mg). It's 6 pages in total, with a 1.5 page overview. I would request @rufuspollock read the document and let me know how I should follow up with Ian. There was also talk about the possibility of Ian hosting a residency so I will also get in touch with Valerie. 

## Acceptance

* [x] Eilidh has spoken with Valerie
* [ ] We have decided how to follow up

## Tasks

* [x] Valerie has read the brief ✅
* [x] Valerie has watched the film ✅
* [x] Valeria has responded to Ian ✅
* [ ] We have decided how to proceed

**Comment by EilidhRoss1** [comment]
Valerie has read the brief, watched the recording of the call and watched Ian's film. She replied to Ian 12/01/22 saying: "First of all I want to say a big whaou for your film and the way you were able to clearly pictured  the political posture of Tamera regarding intimacy in community as a model for new culture . 
I also listened to the talk you had with Eilidh and I would be happy to talk with you to precise your curiosity about what we do at the Praxis hub and what you imagine to do there. We are now planning residencies from June so it is the right time for this conversation. Please tell me when you would be available to talk about it."

**Comment by rufuspollock** [comment]
Unassigning myself as i think this is with @EilidhRoss1 and Valerie.

**Comment by EilidhRoss1** [comment]
Valerie and praxis team to take over @msantolini @Liyubov

**Comment by Liyubov** [comment]
thanks Elidh, yes we had follow up with him, Valerie was arranging the meeting.

**Comment by nathenf** [comment]
FIXED - Has been directed to Valerie who is now in contact with him
