### ISSUE TITLE
[epic] Exploring Conscious Coliving

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#257]
We have made a choice for an initial theme and "What" for our offers see https://next.lifeitself.org/notes/projects/life-itself-v3 

Hypothesis: Let's focus on conscious coliving and communities as a theme for 2023 and deliver our wiser offer ideas specifically for this. 

Key issues:
- #566
- #720

## Acceptance

- [x] Completed A10 for this project ✅  see below
- [x] Project launched with MVP ✅ Conscious Coliving 101 is live 🎉 https://lifeitself.org/conscious-coliving-course

FUTURE

- [ ] Offer created and providing revenue

# Tasks 

## Phase 1

- [x] Write A10 or similar ✅ See below
- [x] Create MVP #566 ✅ 
- [x] Build project database ✅ https://docs.google.com/spreadsheets/d/1Oz09uehrtQLes6-W2oRklbMSUN4v6JYCqeT1krNWBIE/edit#gid=869164973
- [ ] Competitor Analysis
- [x] Create landing page 🚧 Initiative page has been created, but learn page still needs to be created. https://lifeitself.org/initiatives/conscious-coliving 
  - [ ] Write copy

## Phase 2

- [ ] Brainstorm monetization opportunities and decide on which one to do next ✅ Paid Masterclasses 
- [ ] Implement paid masterclasses #720 

# Notes

- How do we better integrate the Whatsapp community, course and community calls? Can this all be on one platform? 
- Circle.so is an option that we could use to do this. While it has a cost this might be a small investment for us to propel our online community + get it off mainstream social media (META) 
- To scale we can ask for a small monthly contribution (£1-3 a month which would cover the platform fees and enable us to have an enhanced experience) 

# A10 Updated September 2023

## Purpose & Principles
Conscious Coliving as been a key theme for Life Itself over the last 6 months and has proven to be fruitful in engagment (140+ course attendees for CC101, 200+ people in our Whatsapp group, higher frequency of residency enquiries). We have already set a foundation for explore this theme and should continue to expand our offers. 

Our vision is to become one of the top websites to visit for Conscious Coliving, Intentional Communities and Ecovillages. Additionally, we want to cultivate an active online community devoted to building offline communities. 

Offers and media may include:

- Guides to community living, conscious coliving, ecovillages
- Tutorials for conscious coliving
- In-depth podcasts with key conscious coliving experts
- Paid masterclasses about conscious coliving
- Articles covering all aspects of conscious coliving

## Outcome Visioning

By the end of 2024 we have a suite of offerings, both free and paid:

- One core in-depth guide on conscious coliving
- A directory of conscious communities, key experts and organizations 
- A book list with ongoing summaries/notes
- 24 articles 
- 12 podcast interviews with experts in the field
- 6 explainer videos about key concepts for conscious coliving (e.g. non-violent communication)
- 4 paid masterclasses 
- 1 paid masterclass bundle 
- 1 paid mini-course for conscious community practices 

Could end 2024 with a Conscious Coliving Summit online or in-person hosted at a big ecovillage.

Would expect this to lead to:
- Rank highly on Google for keywords (e.g. ecovillages, communal living, etc.)
- 100-200 paid users
- 2000+ new website users monthly

## Strategic Alignment 

The theme of conscious coliving makes sense for a number of reasons:

- We have experience, content, research and practice in conscious coliving
- It synergises with team interests and current offers (DDPs)
- We already have an audience for this and there is a far greater audience out there
- We can monetize this effectively
- Advances/explores key areas of our larger strategic objective of a wiser, weller 
- Aligns effectively with the core theory of change that Life Itself adheres to. 
- Creates concrete application of mostly intellectual concepts (Stage Theory, etc.)
- Acts as a prototype framework for other key themes in the future (already iterating from exploring web3)
- Building a core following/audience interesting in conscious coliving which means we are more likely to find pioneers

## Plan of Work

As of the beginning of September, 2023 we have written and published Conscious Coliving 101 and have had 140 people complete the course. Additionally, our whatsapp chat of 200+ people has regular engagement around the Conscious Coliving topic and many are joining community calls. The next phase entails creating a paid offer. 

## Budget & Resourcing

TBC

## Risks 

- Narrow focus may lead us away from other opportunities
- Might be less interesting for some of our audience - AKA web3 lot
- We may not be able to fully achieve suite of offers if our time capacity is low

**Comment by nathenf** [comment]
@rufuspollock I have created [A10](https://docs.google.com/document/d/18j7gdIBMEfbIdfL_dISpItQkehAyMFfSP5T-h6B_IoQ/edit#) and started to build the [database](https://docs.google.com/spreadsheets/d/11WXmllrEtOdQm6yDwY7pun-3r78FDkOQsQ_bd8Y2VEo/edit#gid=1544587184). Will work more on this tomorrow.
