### ISSUE TITLE
Switch over to new Flowershow-based site

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#259]
Switch over from wordpress site to new flowershow based site.

## Acceptance

- [x] have switched over to new site **✅2023-01-12 we did switchover**
- [x] Old site still available at old.lifeitself.org **✅  2023-01-23 Site is live**
- [x] Backups in gdrive and backups repo **✅  2023-01-17 @khalilcodes to update. Backup uploaded in shared gdrive and xml in repo https://github.com/life-itself/backups**

## Tasks

- [x] we lock-down main site for editing **✅2022-12-20 as of 20th December**
- [x] Migrate content #184 **✅2022-12-29 all done**
- [x] Check new site and make fixes **✅2023-01-04**
- [x] Switch to new site (no downtime) **✅2023-01-10**
	- [x] Warn team of changeover day
	- [x] Move current lifeitself.org to old.lifeitself.org **✅  2023-01-23**
	  - [x] Add DNS record
	  - [x] Change site url in wordpress config
	- [x] Move next.lifeitself.org to lifeitself.org
	  - [x] Add this as a domain in netlify
	  - [x] Switch DNS record in cloudflare
- [x] Test all looks good
- [x] Add redirects listed in [spreadsheet](https://docs.google.com/spreadsheets/d/13RVMrZ02Rw6a1BtftIUO4v7R7rXt5_phQLR4rHa343M/edit#gid=1933881587) in simplest way possible a la https://nextjs.org/docs/api-reference/next.config.js/redirects **✅ 2022-01-13**

Backups

- [x] Push backup of xml to https://github.com/life-itself/backups (see naming convention) **✅ 2022-01-12**
- [x] Contents of wp-content
  - [x] got a download (3.5Gb) 
  - [x] search for pdf files that should be added to new site **⚠️ 2022-01-12 found 7 pdf documents (3 uploaded as rest were not referred in any of the pages). Other missing pdfs not found in `wp-content` and listed in comment below. Moved over to #260 tasks**
  - [x] upload content into gdrive in a folder somewhere **✅ 2022-01-12**

**Comment by khalilcodes** [comment]
**List of missing pdfs that were not downloaded by tool during wordpress xml export**

| page | pdf |
| --- | --- |
| blog/2022/04/01/mapping-metamodern-alternative-economics.md | dp-a-safe-and-just-space-for-humanity-130212-en_5.pdf |
| blog/2017/04/20/logic-of-our-purpose-and-reason-for-our-existence-scqh.md | sketches-of-a-future-society-art-earth-tech-scqh-rufus-april-2017.pdf |
| blog/2017/02/05/summary-how-much-is-enough-skidelsky-2012.md | econ_growth_and_carrying_capacity.pdf, Arrow_et_al_JEP_04.pdf |
| blog/2019/11/29/the-case-for-contemplative-activism-why-why-now-and-what-are-we-offering.md | deepadaptation.pdf |
| blog/2019/01/22/ken-wilber-integral-spirituality.md | overview-of-developmental-levels-wilber-graves-etc.pdf |
| blog/2019/12/13/contemplative-activism-primer-the-pre-gathering-read.md | deepadaptation.pdf |
| blog/2021/03/18/berlin-hub-community-projects.md | What-determined-the-fate-of-slavery-comparing-the-US-and-Haiti-1.pdf |
| blog/2020/10/05/sunday-salon-menstruation-in-community.md | coexist-menstrual-policy-2020.pdf |
| blog/2020/07/14/the-equality-complex-sunday-salon-19th-july-2020-3pm.md | questioning-equality.pdf |
| blog/2016/07/28/co-x-coliving-coworking-coops-gathering-2016.md | co-x-for-helsinki-20160902.pdf |
| blog/2016/09/29/mindfulness-an-introduction.md | JKZ_thinking.pdf |

**Comment by rufuspollock** [comment]
@khalilcodes i suspect some of these pdfs will then be in our old hugo site (pre wordpress). The web3.md i'm surprise about but doesn't matter much.

**Comment by rufuspollock** [comment]
@khalilcodes what is happening re dreampress?

Re the missing pdfs can you add that to #260 so it does not linger in this issue.

**Comment by khalilcodes** [comment]
@rufuspollock submitted a ticket and moved the missing pdfs to tasks in 260.

**Comment by khalilcodes** [comment]
@rufuspollock dreampress support replied and fixed the issue. The site works now 👍. The issue is also explained in the message and can be found by going to (contact -> support history) for future reference.

**Comment by rufuspollock** [comment]
@khalilcodes are the redirects deployed? Because e.g. https://lifeitself.org/2022/02/01/cultivating-an-emerging-paradigm (found via google) is not redirecting to https://lifeitself.org/blog/2022/02/01/cultivating-an-emerging-paradigm. This now becoming high priority and urgent as these are important items and google SEO will start dropping them out of search if 404s keep happening.

**Comment by khalilcodes** [comment]
@rufuspollock redirects working

**Comment by khalilcodes** [comment]
FIXED
