### ISSUE TITLE
[epic] Next steps for lifeitself.org after go live Jan 2023

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#260]
We have launched the new site. This is a capture issue for immediate next steps that are related to getting back to similar status of what we had before.

Parent #170 

## Acceptance

- [x] Newsletter signup back
- [x] Social media links
- [x] Search in top bar is working
- [x] UX fixes
	- [x] Set favicon ~5mins **✅ 2023-01-30**
	- [x] Person page ~5mins **✅ 2023-01-30**
	<img src="https://user-images.githubusercontent.com/180658/214543385-ea9a4eb8-4a2d-4981-b461-db222f03bb6a.png" height=300 />
- [x] All old urls work
  - [x] old blog urls work
  - [x] author pages work
  - [x] Categories work (? note we may need to defer this on reworking categories?) **✅2023-02-16 ❌ wontfix for now - suggest defer until have a proper tag system for the blog rather than create search filter etc. plus not high value or urgent**
- [x] find and add the missing pdfs to `assets` folder (from old hugo site repo ?) (see list in notes below) **✅ Located all pdfs and uploaded to assets see #318**

### Fixes

- [x] https://lifeitself.org/2021/11/30/community-hangout-december-2021/ not working! (are there more pages like this) **In this case, the new url is https://lifeitself.org/blog/2021/11/30/community-hangout-december-2021, i.e. with "blog" before the date. It seems that all blog posts are like this** **✅ Now auto redirects to `blog/YYYY/mm/dd/...` resolved in commit https://github.com/life-itself/community/commit/901098761e90a00692d9ba150a9453c9e39fcda1 (~1h)**
- [x] categories have gone away - what do we do? https://lifeitself.org/category/institute/conscious-parenting/ **🚧 2023-02-02 create filter on blog page for categories which follows url category structure** **✅2023-02-16 ❌ see comment in acceptance**
- [x] author pages have gone away - what do we do? e.g. https://lifeitself.org/author/rufuspollock/ **✅ 2023-01-17 suggest that these should be resurrected in some way.
   - [x] Redirect form /author/{name} to `/people/{name}/`**✅ 2023-01-30 redirects added (~5mins)** 
   - [x] List posts on person page (this is probably more complex) **(~1hr)**
- [x] some pages seem to have duplicated images at the top e.g. https://lifeitself.org/blog/2021/11/30/community-hangout-december-2021 (i suspect this is pages with a featured image in wordpress). I think here we should just have the image in `image: ` frontmatter and then the actual image once in the markdown **✅ 2023-01-30 fixed (for blog pages) with commit [d12bae7](https://github.com/life-itself/community/commit/d12bae74df1cf44a894587b2f8479b4eefefae57) (~30mins)**

Extra

### Next Steps After Go Live

- [x] Add social links 
   - [x] In header add Twitter, Instagram, Whatsapp ✅ **see #332 (~30mins)**
- [x] #307 ✅ **Now on every page of the website (~2hr)**
- [x] Add latest posts slider block to homepage below contributors @khalilcodes use https://tailwindui.com/components/marketing/sections/blog-sections#component-720cf60b960fecb99c45f462f24db2d9 with see more button below that links to blog page **✅ 2023-02-20 Done in merge commit [266dfd1](https://github.com/life-itself/community/commit/266dfd124016e34cea0324300a85ad5b1549a053) (~2hr)**

### List of old PDFS

| page | pdf |
| --- | --- |
| blog/2022/04/01/mapping-metamodern-alternative-economics.md | dp-a-safe-and-just-space-for-humanity-130212-en_5.pdf |
| blog/2017/04/20/logic-of-our-purpose-and-reason-for-our-existence-scqh.md | sketches-of-a-future-society-art-earth-tech-scqh-rufus-april-2017.pdf |
| blog/2017/02/05/summary-how-much-is-enough-skidelsky-2012.md | econ_growth_and_carrying_capacity.pdf, Arrow_et_al_JEP_04.pdf |
| blog/2019/11/29/the-case-for-contemplative-activism-why-why-now-and-what-are-we-offering.md | deepadaptation.pdf |
| blog/2019/01/22/ken-wilber-integral-spirituality.md | overview-of-developmental-levels-wilber-graves-etc.pdf |
| blog/2019/12/13/contemplative-activism-primer-the-pre-gathering-read.md | deepadaptation.pdf |
| blog/2020/10/05/sunday-salon-menstruation-in-community.md | coexist-menstrual-policy-2020.pdf |
| blog/2020/07/14/the-equality-complex-sunday-salon-19th-july-2020-3pm.md | questioning-equality.pdf |
| blog/2016/09/29/mindfulness-an-introduction.md | JKZ_thinking.pdf |
| web3.md | BTC-QF.pdf |

**Comment by khalilcodes** [comment]
@rufuspollock nextjs redirects in netlify don't seem to work. 

According to their docs: https://docs.netlify.com/integrations/frameworks/next-js/redirects-and-rewrites/

* Manually add the nextjs-runtime as a package or from the UI https://github.com/netlify/next-runtime#readme
* (if above doesn't work) we may have to add them in `netlify.toml` or `_redirects` folder in public

**Comment by rufuspollock** [comment]
@khalilcodes shall we try first adding the runtime plugin.

**Comment by khalilcodes** [comment]
@rufuspollock added the runtime plugin and also replaced redirects to rewrites in `next.config.js` but still doesn't seem to work. 

So the workaround solution for now would be to add a *_redirects* folder in public where we can also add `/:year/:month/:date/:slug  /blog/:year/:month/:date/:slug` as specified in their docs here - https://docs.netlify.com/routing/redirects/redirect-options/#placeholders

**Comment by rufuspollock** [comment]
@khalilcodes ok let's do workaround for now i.e. use _redirects folders.

**Comment by rufuspollock** [comment]
@khalilcodes i think redirects stuff should be in #259 as that is where redirects task is. Can you confirm this is now working - see my comment there https://github.com/life-itself/community/issues/259#issuecomment-1401100516

**Comment by rufuspollock** [comment]
@khalilcodes can you estimate time for the fixes item per task.

**Comment by nathenf** [comment]
@rufuspollock just flagging that I have cleaned this up to represent only immediate next steps which need to be completed. I have moved other tasks into epic #170 and currently cleaning that up too

**Comment by olayway** [comment]
@khalilcodes how are you getting on with this issue?

**Comment by rufuspollock** [comment]
> categories have gone away - what do we do? [lifeitself.org/category/institute/conscious-parenting](https://lifeitself.org/category/institute/conscious-parenting/) 🚧 2023-02-02 create filter on blog page for categories which follows url category structure

@khalilcodes @nathenf i would suggest we defer this until we have a proper working tag system for the blog rather than create search filter etc. so suggest this go out of this issue - imo it is not urgent in next steps.

**Comment by rufuspollock** [comment]
Ditto #264 can move to an item in #170 and need not be in here (it is a substantial bit of work and not urgent and needs proper analysis and relates to functionality in flowershow).

**Comment by rufuspollock** [comment]
Ditto for #317 - which can be hoisted to #170 and is not high priority IMO.

**Comment by rufuspollock** [comment]
> Add latest posts slider block to homepage below contributors @khalilcodes use [tailwindui.com/components/marketing/sections/blog-sections#component-720cf60b960fecb99c45f462f24db2d9](https://tailwindui.com/components/marketing/sections/blog-sections#component-720cf60b960fecb99c45f462f24db2d9) with see more button below that links to blog page

Can we make this a distinct issue. I believe we already implemented something like this on web3 for the deep dives etc. For now i'd even live with this being hardcoded (as it started out on web3) and later we can add feature to select the posts we want.

Aside: more i think more i think  latest posts is less important than "key posts" or something for now which makes hard-coding even simpler.

**Comment by rufuspollock** [comment]
@khalilcodes @nathenf i'll leave you to do any final tidying / updating and close this.

@khalilcodes @nathenf also please can we get an update on actual time spent on this (to give a rough sense of how much time we are spending on the site atm).

**Comment by nathenf** [comment]
FIXED - All items complete leading onto #334
