### ISSUE TITLE
Jeffery Martin on A Scientific Approach to Awakening and Fundamental Wellbeing

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/community#263]
## Acceptance 

- [x] Conversation published on Youtube & Anchor ✅ [YouTube](https://youtu.be/EmsLdIH8nzU) and [Anchor](https://anchor.fm/life-itself/episodes/Dr-Jeffery-Martin-on-A-Scientific-Approach-to-Awakening-and-Fundamental-Wellbeing-e1ti8og/a-a7gpq18)
- [x] Blog Post containing all content published ✅ https://lifeitself.org/blog/2023/01/19/a-scientific-approach-to-awakening-and-fundamental-wellbeing 
- [x] Secondary Content and Direct links shared on Social Media ✅https://twitter.com/forlifeitself/status/1616113824708366336 

## Tasks

- [x] Duplicate this Template and rename as the working title of the conversation ✅
- [x] [Create a new folder for the conversation and assets here] (https://drive.google.com/drive/folders/12BskqKPp85XNdU2sespI--E7VPi45hGJ?usp=sharing) ✅ **[New folder here](https://drive.google.com/drive/folders/1dofLYNeaUGfcZDX7htocQ0wqqloA6VCU)**
- [x] Source the video file and transcript from the conversation and add to folder ✅
- [x] Create a document for the conversation that includes: Title, Conversation Summary, About the person in conversation, links to resources mentioned in the podcast, timestamps for at least two video excerpts and two quotes and timestamps for ["chapters"](https://www.youtube.com/watch?v=pvkTC2xIbeY). Add this to folder. ✅ https://docs.google.com/document/d/1oFDepygLDcoCipUX7eznJRLxKJn1ZIiDwodqwuH10NQ/edit#heading=h.bre73nhotd0f 

- [x] **Create Youtube video** ✅ 
  - [x] Create the Youtube Thumbnail from [this template](https://www.canva.com/design/DAE99drPH4s/7mR8CgHWyHfimwC9jDerDA/edit?utm_content=DAE99drPH4s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).
  - [x] Edit the video file in Da Vinci Resolve:
    - [x] Trim beginning and end, plus any sections of poor internet connection or other interruptions
    - [x] Add thumbnail at the beginning of the video with a fade transition to the video
    - [x] Add graphic overlay ["Please Like & Subscribe"](https://drive.google.com/file/d/1iQjSdgjTyrN9xnQ8Xnlzdjmk2sw2eKXJ/view?usp=sharing) at the 5, 10, 20, 40 minute 
    - [x] [Add End Screen with a fading transition](https://drive.google.com/file/d/1fC8c_tyoOxxGGhGqgJuwFscu6vYzbrqe/view?usp=sharing)
    - [x] Increase the sound volume as much as possible (~3.21) without clipping the sound (you will notice because it will sound bad) 
  - [x] Export as Video for Youtube
  - [x] Upload to Youtube: Add title, thumbnail, summary including [contents chapters](https://www.youtube.com/watch?v=pvkTC2xIbeY), page stub URL, add to Exploring Social Transformation playlist, Add Language, Make License Creative Commons.
  - [x] Notes from the conversation are on the webpage for that conversation.
    - [x] Notes are complete, comprehensive and tidied
  - [x] Inform Guest that youtube video is ready to go.
  - [x] Publish
  - [ ] Ensure Guest tweet about video
  - [ ] Share on Insta stories

- [x] **Create Podcast** ✅ 
  - [x] In Anchor click create new episode, use the "Intro Jingle" and add the audio only edit
  - [x] Add title & summary (incl page URL)
  - [x] Create and add thumbnail from [this template](https://www.canva.com/design/DAE87pGGDUg/EgrVC9iJX5eATZGF5rE2pg/edit?utm_content=DAE87pGGDUg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
  - [x] Add season number and episode number
  - [x] Publish
  - [ ] Share on Insta stories

- [x] **Create Twitter Secondary Content** ✅ 
  - [x] Cut the video excerpts from the main video and leave all the clips in one timeline 
    - [x] Export just the audio
    - [x] Upload Audio to Otter.ai to create srt file (srt file settings: no more than 1 line and 60 letters per line) - make sure that the speech from each clip is correctly separated in Otter.ai
    - [x] Upload the srt file to the project 
    - [x] Crop top and bottom of video - add title to top and subtitles at the bottom
  - [ ] Create Quote posts using [this template](https://www.canva.com/design/DAE-ett42vU/63HsI5cGixlZ6cFQd09zCg/edit)
  - [x] Add all content to the folder that has been created 

- [ ] **Create Insta Secondary Content** 
  - [ ] Use the same clips from Twitter and reformat for Reels

- [x] **Create Blog Post** 
  - [x] Create a blog post beginning with the summary then embed the video, the podcast and include the transcript
  - [x] Add the relevant quotes and video excerpts (Twitter format) as images between the transcript

- [x] **Send email out to Life Itself General Audience**

**Once blog is complete we can schedule content on Twitter, Instagram**

**Comment by EilidhRoss1** [comment]
FIXED. Episode is published on [YouTube](https://youtu.be/EmsLdIH8nzU) and [Anchor](https://anchor.fm/life-itself/episodes/Dr-Jeffery-Martin-on-A-Scientific-Approach-to-Awakening-and-Fundamental-Wellbeing-e1ti8og/a-a7gpq18), email has been sent to mailing list, guest has been notified and sent the links, [blog post](https://lifeitself.org/blog/2023/01/19/a-scientific-approach-to-awakening-and-fundamental-wellbeing) is up including transcript, episode has been added to [podcast page on website](https://lifeitself.org/podcast/a-scientific-approach-to-awakening-and-fundamental-wellbeing-podcast), episode has been marketed on [twitter](https://twitter.com/forlifeitself/status/1616113824708366336).
