### ISSUE TITLE
Logo page (in tao)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#266]
Page with logos (start of a style guide?) for easy use by ourselves and others

Inspiration from things like https://vercel.com/design/brands (note original version from zeit on wayback machine is prob even simpler)

![image](https://user-images.githubusercontent.com/180658/212940399-e32fa33f-5be5-4a61-a2c0-9c0d8de594fe.png) 

## Acceptance

- [x] Page on e.g. tao with our logos (or links to) for use e.g. at `/tao/logos` **🚧 30/01/2023 page created and merged to main which includes link to drive folder: https://lifeitself.org/tao/communications/logos**
- [x] Guide to creating modified ones for different subprojects **🚧 included a guide to using Canva to make logo alterations. Very simple currently but should be enough**

## Tasks

- [ ] Add individual logos (not zip) for download
- [x] Identify current location of logos **🚧2023-01-23 this drive folder has most version https://drive.google.com/drive/folders/1LAwR00CFvEv9nYHzrUb4QeScgXOWN01V however it is all logotypes (no logos alone) afaict**
- [x] Guide to creation of variations (e.g. details of fonts, placement of text) **✅ this has been added to the guide page**
- [x] change page location to tao/logos instead of tao/communications/logos ✅ **see #324** 
- [x] Add all logo files to Tao for download ✅ **see #324**

**Comment by rufuspollock** [comment]
@nathenf given your experience with comms assets i think this could be a good quick one for you. Let me know if you need a bit of clarity on what is needed.

**Comment by nathenf** [comment]
@rufuspollock I have made a page in the tao now https://lifeitself.org/tao/communications/logos which links to the google drive. I have also added just icon logo to the folder and created a guide for making logo alterations in Canva. It is worth noting that the original logo uses Restora which isn't avaiable on Canva so in the guide I suggested using Martel instead. However if you would prefer I can load Restora into Canva as a custom font and change this.

**Comment by rufuspollock** [comment]
@nathenf great! this is a perfect start.

only suggestion would the that i tao/logos is marginally better (less nesting is preferable). and this is a 2c comment.

**Comment by rufuspollock** [comment]
@nathenf and did you locate logo and well as logotype versions? i also wonder if we want to move stuff (e.g. logos) out of drive into the tao? wdyt? (one place for things etc).

**Comment by rufuspollock** [comment]
Logotype is logo *and* text.

We want SVG and PNG versions of both if possible.

**Comment by rufuspollock** [comment]
@nathenf any chance we close this out today before the end of the sprint? 😄

**Comment by nathenf** [comment]
@rufuspollock will complete this morning

**Comment by nathenf** [comment]
FIXED - www.lifeitself.org/tao/logos now includes a downloadable file which contains all variations of the Life Itself logo in both png and svg filetype. In addition, there is a guide to creating a new sub project logo.

**Comment by rufuspollock** [comment]
@nathenf i think people who need to download logos can probably work out to right click and "save as". And if that is tough for people we can provide instructions (there is no need for the link to automatically download).

**Comment by nathenf** [comment]
FIXED - https://lifeitself.org/tao/logos updated with links to each logo #329
