### ISSUE TITLE
Publish hubcast episode with Sylvie

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/community#267]
## Acceptance 

- [x] Conversation published on Anchor ✅ **https://spotifyanchor-web.app.link/e/BxTM0Q0uQwb**
- [x] Page up for episode on website ✅  **https://lifeitself.org/podcast/sen-zhan-and-sylvie-barbier**

## Tasks

- [x] **Create Podcast**
  - [x] In Anchor click create new episode, use the "Intro Jingle" and add the audio only edit
  - [x] Add title & summary (incl page URL)
  - [x] Create and add thumbnail from [this template](https://www.canva.com/design/DAE87pGGDUg/EgrVC9iJX5eATZGF5rE2pg/edit?utm_content=DAE87pGGDUg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
  - [x] Add season number and episode number
  - [x] Publish

**Comment by EilidhRoss1** [comment]
FIXED 
- [x] Conversation published on Anchor ✅ **https://spotifyanchor-web.app.link/e/BxTM0Q0uQwb**
- [x] Page up for episode on website ✅  **https://lifeitself.org/podcast/sen-zhan-and-sylvie-barbier**

**Comment by EilidhRoss1** [comment]
FIXED 
- [x] Conversation published on Anchor ✅ **https://spotifyanchor-web.app.link/e/BxTM0Q0uQwb**
- [x] Page up for episode on website ✅  **https://lifeitself.org/podcast/sen-zhan-and-sylvie-barbier**
