### ISSUE TITLE
Update Podcast page on site with recent episodes

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/community#274]
## Acceptance

- [ ] [Podcast page](https://lifeitself.org/podcast) is up to date with all episodes featured
- [ ] Add episode to podcast is added to podcast production protocol/checklist

## Tasks

- [ ] Add the following episodes to [podcast page](https://lifeitself.org/podcast) on website:
  - [ ] [Thomas Steininger](https://anchor.fm/life-itself/episodes/Thomas-Steininger-on-Emergent-Dialogue-and-Transcending-Individualism-e1rul4l)
  - [ ] [Joseph Henrich](https://anchor.fm/life-itself/episodes/Joseph-Henrich-and-the-Emergence-of-a-Rigorous-Culturology-e1r9pgv)
- [ ] Publish episode production protocol to tao including this step

**Comment by EilidhRoss1** [comment]
FIXED episode pages created and podcast protocol in tao
