### ISSUE TITLE
Esther Montmany episode 3

### ISSUE THREAD

**Issue by EilidhRoss1** [life-itself/community#284]
## Acceptance 

- [x] Conversation published on Youtube & Anchor. ✅ **https://youtu.be/YkgQ6Iarrp4** and **https://anchor.fm/life-itself/episodes/Esther-Montmany-on-Conscious-Parenting-Part-3-e1u045v/a-a7gpq18**
- [x] Blog Post containing all content published.✅ **https://lifeitself.org/blog/2023/01/31/esther-montmany-on-conscious-parenting**
- [x] Episode page added to the website.✅ **https://lifeitself.org/podcast/esther-montmany-on-conscious-parenting-part-3**
- [x] Guest informed that the episode is out and has been sent the links.✅ 
- [x] The new episode has been announced on twitter.✅ **https://twitter.com/forlifeitself/status/1620447563139919872**
- [x] Email announcing new episode has been sent to mailing list.✅ **Sent**
- [x] Secondary content has been shared on social media✅ 

## Tasks

- [x] Copy this Template into a new GitHub issue. Name the issue as the working title of the conversation
- [x] [Create a new folder for the conversation and assets here](https://drive.google.com/drive/folders/12BskqKPp85XNdU2sespI--E7VPi45hGJ?usp=sharing)
- [x] Source the video file and add to folder
- [x] Create a document for the conversation that includes: Title, Conversation Summary, About the person in conversation, links to resources mentioned in the podcast, timestamps for at least two video excerpts and two quotes and timestamps for ["chapters"](https://www.youtube.com/watch?v=pvkTC2xIbeY). Add this to folder. ✅ **https://docs.google.com/document/d/1PpZGy5ShSNt6QNxJV429_Vc8ubOeKmTOaziXnSHxW1E/edit**
- [x] Watch the video. Note any moments that need edited eg moments of bad internet connectivity. Note down timestamps for chapters to be used when publishing to YouTube. Note timestamps of short sections that will be good for social media (max length for twitter 2m20s) and note down quotes that will be good for marketting the episode.

- [x] **Create Youtube video** ✅ **[saved as private](https://youtu.be/YkgQ6Iarrp4)**
	- [x] Create the Youtube Thumbnail from [this template](https://www.canva.com/design/DAE99drPH4s/7mR8CgHWyHfimwC9jDerDA/edit?utm_content=DAE99drPH4s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).
	- [x] Edit the video file in [Da Vinci Resolve](https://www.blackmagicdesign.com/products/davinciresolve):
		- [x] Trim beginning and end, plus any sections of poor internet connection or other interruptions
		- [x] Add thumbnail at the beginning of the video with a fade transition to the video
		- [x] Add graphic overlay ["Please Like & Subscribe"](https://drive.google.com/file/d/1iQjSdgjTyrN9xnQ8Xnlzdjmk2sw2eKXJ/view?usp=sharing) at the 5, 10, 20, 40 minute
		- [x] [Add End Screen with a fading transition](https://drive.google.com/file/d/1fC8c_tyoOxxGGhGqgJuwFscu6vYzbrqe/view?usp=sharing)
		- [x] Increase the sound volume as much as possible without clipping the sound (around 3 is normally good) 
	- [x] Export as Video for Youtube
	- [x] Export audio only for podcast
	- [x] Upload to Youtube: Add title, thumbnail, summary including [contents chapters](https://www.youtube.com/watch?v=pvkTC2xIbeY), page stub URL, add to relevant playlist, Add Language, Make License Creative Commons.
	- [ ] Schedule publication for desired day and time

- [x] **Create Podcast** ✅ **[saved](https://anchor.fm/dashboard/episode/e1u045v)**
	- [x] In Anchor click new episode then click create new episode. Click on reuse your previously uploaded audio and scroll down until you find the "Intro Jingle". Drag the file in the box into the right. Add the audio only edit of the episode after the intro. Click save episode.
	- [x] Add title & summary.
	- [x] Create and add thumbnail from [this template](https://www.canva.com/design/DAE87pGGDUg/EgrVC9iJX5eATZGF5rE2pg/edit?utm_content=DAE87pGGDUg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
	- [ ] Add season number and episode number
	- [ ] Schedule publication for desired day and time
  
- [x] **Create blogpost**
	- [x] Draft blogpost prior to scheduled publication of the episode on YouTube and Anchor. 
	- [x] Add a new blog in the vault/blog folder in the Community repo. 
		- [x] Follow the format: put it in date structured folders eg. vault -> blog -> 2023 -> 01 -> 16 -> blog-file-name.md. For the frontmattter fields have a look at any of the other blog posts within that folder and follow that format. Once added commit the new file as you usually would. For more directions on how to add to the website see the [Web3 site contributors' guide](https://web3.lifeitself.org/meta/editing) and/or the [ecosystem mapping site guide](https://ecosystem.lifeitself.org/contributors-guide).
	- [x] You can add in the YouTube link as you can access that even before the video is published, however you can't with the Anchor link. Once the podcast is published, source the embed link to the episode found when you click on the episode on Anchor, and paste into the blog (use previously published podcast blogposts as a guide).
	- [x] The blog should feature a brief introduction of the guest and an intro to the episode (eg v brief overview of what is discussed).
	- [ ] Add any notes. Ensure they are complete, comprehensive and tidied.
	- [ ] Add any references and further reading
	- [ ] Add the transcript
		- [ ] run the video through Otter to generate the transript. Go through and fix any errors. Export as docx with speaker names and timestamps.
		- [ ] Copy the transcription into a google doc and save in the episode folder.
		- [ ] Convert into markdown. Copy and paste into blog post.

- [x] Once episode is published to YouTube and Anchor, publish the blog post with the links. Once blog post is published, edit the YouTube and Anchor episode bios and paste in the link to the blog.

- [x] Once YouTube video, podcast episode and blog post are published, **create a page for the episode on the [podcast page](https://lifeitself.org/podcast) of the website.**
	- [x] Add a new page in vault/podcast in the community repo. Use [Jeffery Martin episode page](https://lifeitself.org/podcast/a-scientific-approach-to-awakening-and-fundamental-wellbeing-podcast) as a guide. Generate the links for the frontmatter:
		- [x] Follow this link: https://rss2json.com/
		- [x] Paste this link in the box on the page (under the text that says Enter the URL to your RSS feed): https://anchor.fm/s/79b39934/podcast/rss 
		- [x] Find the podcast episode you are wanting to create the page for (likely the first episode listed, this will be the first episode under the line that says "items")
		- [x] Click the button with 4 arrows pointing outwards to make it full screen to ensure you don't copy only part of a link.
		- [x] Copy the link for "thumbnail" and paste it after "image:" in the frontmatter.
		- [x] For the src link, scroll down to where it says "enclosure" and copy the link that follows "link". Paste this after "src" in the frontmatter. 
		- [x] Fill out the rest of the frontmatter.
	- [x] Paste the same short intro to the episode and guest as used in the blog post below the frontmatter. Paste the youtube link and the link to the blogpost. 

- [x] **Inform the guest that the episode is out.** Send all links and encourage them to share.

- [x] **Send email out to Life Itself General Audience on Mailchimp** announcing that the latest episode of the Life Itself Podcast is now available. Use the same intro to the episode and guest as used in blog. Paste link to the podcast page - they can navigate to everything they need from that one link. Use a previous podcast episode launch email as a guide - you can replicate that email, just remember to change the text, link, subject line and preview text. 

- [x] **Announce release on Twitter.** Make sure to @ the guest and tweet the link to the podcast page.

**Comment by EilidhRoss1** [comment]
FIXED 

- [x] Conversation published on Youtube & Anchor. ✅ **https://youtu.be/YkgQ6Iarrp4** and **https://anchor.fm/life-itself/episodes/Esther-Montmany-on-Conscious-Parenting-Part-3-e1u045v/a-a7gpq18**
- [x] Blog Post containing all content published.✅ **https://lifeitself.org/blog/2023/01/31/esther-montmany-on-conscious-parenting**
- [x] Episode page added to the website.✅ **https://lifeitself.org/podcast/esther-montmany-on-conscious-parenting-part-3**
- [x] Guest informed that the episode is out and has been sent the links.✅ 
- [x] The new episode has been announced on twitter.✅ **https://twitter.com/forlifeitself/status/1620447563139919872**
- [x] Email announcing new episode has been sent to mailing list.✅ **Sent**
- [x] Secondary content has been shared on social media✅
