### ISSUE TITLE
Posting footage of AET 2017 gathering

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#29]
Posting footage of AET 2017 gathering (we have lots!)

## Acceptance

* [ ] all video of 2017 gathering up on our youtube channel

## Task
* [ ] receive the hard drive
* [ ] edit the footage
* [ ] add the name of the speaker, date, topic on the footage, and Life itself logo
* [ ] put up the video on the youtube channel
* [ ] let sylvie know
