### ISSUE TITLE
Newsletter signup on main site

### ISSUE THREAD

**Issue by theo-cox** [life-itself/community#307]
Our new main site has lost the newsletter signup box, so there's no way for people to sign up to our newsletter.

SEE https://excalidraw.com/#room=cbed68bdcd0ef72c78b5,BHedlhnS9SpLQ_2pb_Mv7Q for Footer Structure

## Acceptance

- [x] Newsletter signup box on main page **✅ 2023-02-08 merged commit [2718155](https://github.com/life-itself/community/commit/2718155cc8bd3238a93cabbbd2b7a0ac3276a21d)**
- [x] Banner on bottom of pages (?)

## Tasks

- [x] Create footer following footer structure design here: https://excalidraw.com/#room=cbed68bdcd0ef72c78b5,BHedlhnS9SpLQ_2pb_Mv7Q (under the title footer structure 
 - [x] Title - "Stay Connected"
 - [x] Text - "We're actively contributing to a wiser, weller world. If you believe a better world is possible, our activities will interest you. Join our newsletter to be regularly updated with what's happening at Life Itself" 
 - [x] Social media icons to include: Twitter, Instagram, Whatsapp, Youtube, Github

### Implementation

**✅ 2023-02-08**

- [x] Create custom components for newsletter - `Newsletter.jsx`, `useMailchimp.js`
  * Add jsonp package (to fetch/post to mailchimp)
- [x] Add Newsletter form component in layout
- [x] Add Mailchimp env variable in Netlify

<img width="1457" alt="Screen Shot 2023-02-08 at 6 27 32 PM" src="https://user-images.githubusercontent.com/42637597/217577615-cc8559fb-a260-4f93-8797-00ab62053b22.png">

**Comment by nathenf** [comment]
@khalilcodes I've added details about the footer email sign-up box here

**Comment by olayway** [comment]
@khalilcodes have you tried implementing it already? If so, please let me know if you've managed to make it work. If not, as we agreed, please don't spend too much time on it (I'd say 1h tops) as there is no point in trying to test out all the possible options by a 3rd person already (counting me and Philippe). If this is really urgent, we can just use iframes as I did on datopian.com. But for now, focus on other tasks as there is a strictly related issue I'll be working on this week on the Datopian product board: https://github.com/datopian/product/issues/54. Once this is solved you'll be able to use the solution for this Newsletter as well.

cc: @nathenf, @theo-cox

**Comment by khalilcodes** [comment]
@olayway no actually I just ended up reading the docs first and `pages/api` is not supported when using `next export`. So the solution is either the iframe embed or by using [jsonp](https://github.com/webmodules/jsonp) used in replacement of fetch or axios that handles the cors issue. I'll implement what you have done with datopian.

docs from nextjs:
https://nextjs.org/docs/messages/api-routes-static-export

Also just want to point out that we are losing these nextjs functionalities by using next export eg. redirects in `next.config`, pages/api, etc. don't work.

**Comment by olayway** [comment]
> no actually I just ended up reading the docs first and pages/api is not supported when using next export. So the solution is either the iframe embed or by using [jsonp](https://github.com/webmodules/jsonp) used in replacement of fetch or axios that handles the cors issue. I'll implement what you have done with datopian.

Yes, I know, `pages/api` is not supported. I hoped maybe you'll figure out another solution, but I don't think there is one if we're going to stick with SSG. Even if you'd use the trick with jsonp we'll still need the web server running to handle recaptcha...

> Also just want to point out that we are losing these nextjs functionalities by using next export eg. redirects in next.config, pages/api, etc. don't work.

Maybe we could create an additional non-static Flowershow template? I think sth worth considering.

**Comment by nathenf** [comment]
@khalilcodes sorry I forgot to give you the Whatsapp link https://chat.whatsapp.com/JNJCTZugNQn1fq89xbHtfA can you add this to the Whatsapp Icon?

**Comment by nathenf** [comment]
FIXED - Newsletter sign up on every page
