### ISSUE TITLE
[epic] Create a Research Program ("Wiser World")

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#31]
Create a general research program / agenda that outlines what we are pursuing and which others can connect with and contribute to.

## Tasks

* [ ] Capture existing work
  * [ ] 2016/2017 outline: https://docs.google.com/document/d/18_vdpVcpKCvdhpwO3cUDPBsMttMD9AzueH4e7cVjHhc/edit#
  * [ ] SCQH for "Transforming the Narrative" - https://tao.lifeitself.us/plans/#two-pillars
* [ ] Clarify
* [ ] Publish

### Post about original 2016/2017 research group work

* [ ] For historical purpose back-post about our early research group meetings and the outline we created
  * [ ] README: https://docs.google.com/document/d/18_vdpVcpKCvdhpwO3cUDPBsMttMD9AzueH4e7cVjHhc/edit#heading=h.2mc6d1vgitxs
  * [ ] Meeting minutes https://docs.google.com/document/d/1Bx15z--nrtvsO1UcgK74pi_8COL6YDCJRPeDoFCvMHU/edit#heading=h.ms6tig4hmb68

### Inbox of existing material

* Wiser world stuff with Geoff e.g. https://lifeitself.us/2020/06/22/bridging-the-wisdom-gap/
  * Also much more background and SCQH done that could be consolidated

**Comment by nathenf** [comment]
@rufuspollock would this be better place in Someday Maybe or are we planning to pursue this in the short term?

**Comment by rufuspollock** [comment]
I'm planning to do this near-term.

**Comment by rufuspollock** [comment]
FIXED. We have https://lifeitself.org/research and quite a bit of clarity about what we are doing so i think this is now done.
