### ISSUE TITLE
Developing whatsapp community 

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#316]
We now have an accessible way for people in our community or interesting in joining to chat in real time via Whatsapp (see #303).

Now it exists we want to let people know and start using it.

To help with that we may want to structure it e.g. add channels for particular items. and also notify community about it and provide avenue for newcomes to discover and join (Jobs board, Coliving, Events).

## Job Stories

- I want a place I can learn about jobs and volunteer opportunities in the social transformation/climate space so that I don't have to go searching in each individual organisation for placements
- I want a place to learn about all the events going on so that I can easily browse and find events I want to attend
- I want a place to find out about coliving opportunities so that it can be my first port of call when looking for a new living situation
- I want a place to discuss social transformation topics with like-minded people

## Acceptance

- [x] Life Itself community is set-up and in use on Whatsapp
- [x] Groups for coliving, events & jobs are up
- [x] Announced to the community
- [x] Way to join on website
- [x] For Feb, nathen dedicating max ~15-20m a day (to welcome people)
- [x] For Feb, invite people to tell us stuff for newsletter

Bonus

- [ ] Each group has a volunteer admin who manages most of the posting

## Tasks 

- [x] Create new channels for specific topics
  - [x] change coliving and jobs open (for now) ✅ **2023/02/06 they are now open**
- [x] Add "join the community chat" on the website (navbar and contact page) ✅ **see #332**
- [x] Notify existing whatsapp groups
  - [x] draft short announce for whatsapp: new channels for posting, idea of whatsapp community ✅ **see below**
  - [x] send to germany, uk ✅ 
- [ ] Begin adding posts to the groups and figure out a good workflow
- [x] Announce on Twitter and pin tweet ✅ 
- [x] Announce on Instagram ✅ 
- [x] Announce in a dedicated post (may want to explain "why whatsapp") https://lifeitself.org/blog/2023/02/13/new-community-chat ✅ 2023-02-13
- [x] Announce in Newsletter ✅ 2023-02-13

### Draft to announce in preexisting groups

Hey folks, 

You may have seen a few changes in this group recently, particularly it moving to the Life Itself community. For some time now we've been looking for a solution to get the community talking in real-time and we've landed here. Why Whatsapp you might ask... Well its now the most common messaging app around, so rather than pulling people over to somewhere new we thought we might as well start here.

So, welcome to the Life Itself community message board! You are free to leave anytime, but we hope you will like it here. You'll already see a few new groups which will be super useful. There is an events board, a coliving board and a jobs board. We'll be regularly updating them with new opportunities and so can other people too! 

Be sure to join the general chat and say hey as well! I'll see you there!

**Comment by nathenf** [comment]
FIXED - Whatsapp community has been created and is functioning with 50+ people in the general chat. We have carried out 1 community call with 9 attendees and great responses.

**Comment by rufuspollock** [comment]
@nathenf just want to acknowledge what an *amazing* 🚀 job you did here. You did this like a complete pro at community management. 👏👏 🥇

I think we may want some kind of follow up issue about how we maintain things e.g. a monthly community call etc.
