### ISSUE TITLE
Blog page improve layout

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#317]
The current blog page has limited functionality as it only shows latest posts. 

S: People arrive at our blog often after reading the about page and home page
C: The blog is linear and does not provide access to any key content or content arranged by topic
Q: How do we create a user friendly blog that enables user to access content they want
H:

The blog should be full page not just a single line of content down the center
We should have different options to organise blog content (Latest, Key Articles, By Category)
Categories should be a drop-down menu selection which then sorts the posts based on this category
Rather than having category pages let's link back to the blog page with the correct selected category from the drop-down menu

## Job Stories
- When I come to the Life Itself Blog I want to see the most recent articles so that I can stay up to date with what is new at Life Itself
- When I first come to the Life Itself Blog I want to be able to find the most important articles so that I can get the maximum quality of reading in first 
- When I come to the Life Itself Blog I want to sort post by category (e.g. Conscious Coliving) so I can dive into that specific content

## Acceptance 

- [ ] V2 of Blog Page Completed
- [ ] Analytics captured to assess the benefit of the change 

## Tasks

- [ ] Decide on what is important for the blog and how we present the content we have (do job stories)
- [ ] Draft out a skeleton of the format
- [ ] Decide on categories and assign them correctly to the blog posts

### Notes 

https://docs.google.com/spreadsheets/d/13RVMrZ02Rw6a1BtftIUO4v7R7rXt5_phQLR4rHa343M/edit#gid=0 current categories (not including news ones we've made since new website) 

## Structure 

> Important to note that these elements contain descriptions, we want to have an option to add custom descriptions in the Metadata. Obviously old posts do not have this, so the fallback should be what it is currently (taking the first sentences of the post) for any where description is blank or not included. 

> Also can we change the image dimensions for Top Selection and Categories section to 2240x1260px (this would also be great to do on the homepage)

https://tailwindui.com/components/marketing/sections/blog-sections

### Title: Teams Top Selection

<img width="1371" alt="Screenshot 2023-08-11 at 17 33 51" src="https://github.com/life-itself/community/assets/95729108/f82874cc-77e1-47a4-af06-181d7129f6b2">

> For this we want to have an option to change these from time to time. Maybe it can be based on a category type? "Top Pick"

### Title: Latest
<img width="1379" alt="Screenshot 2023-08-11 at 17 34 04" src="https://github.com/life-itself/community/assets/95729108/0abb9e00-5521-4832-a78a-7f98c1b4c28a">

> This is just to be populated based on most recent 

https://www.datopian.com/blog

### Title: All Blog Posts 

> For this we want to sort by category. We are aware there are a lot of categories right now and will work towards refining these with @rufuspollock prior to the launch of the new blog

<img width="1382" alt="Screenshot 2023-08-11 at 17 34 14" src="https://github.com/life-itself/community/assets/95729108/4ce7d2c8-facc-4205-9320-35f65071c607">

### Bonus 

- Can we add reading time like on the Datopian website based on number of words? 
- Can the blog pages look a little more like this? https://writingcooperative.com/the-magic-art-of-saying-more-with-less-ab1a3c203faa 
  - Width of 700px rather than 630px
  - Titles slightly small font, maybe down 1 size
  - Body font up a few sizes to match that of mediums
  - Can we add the ability to share? See image below
  - A way to read next articles at the bottom (based on category and most recent) 

<img width="455" alt="Screenshot 2023-08-11 at 17 57 11" src="https://github.com/life-itself/community/assets/95729108/5f839860-094b-42a9-8009-8844262dcbe3">

**Comment by rufuspollock** [comment]
Let's pause this until datopian layout is implemented as we could reuse.

**Comment by nathenf** [comment]
@rufuspollock is blog at Datopian implemented now? If so would be good to use for Life Itself as a quick way to make our resources more accessible

**Comment by rufuspollock** [comment]
@nathenf can we add this into the inbox of things we will do at some point for website - i want to gather a good chunk of them (plus  don't think this is urgent/important right now).

**Comment by olayway** [comment]
@nathenf I have a green light from @rufuspollock to work on adding support for searching blog posts by categories. Just let me know if the above specification is up to date and this is how you want this to work/look.

**Comment by laurenwigmore** [comment]
@ola

> @nathenf I have a green light from @rufuspollock to work on adding support for searching blog posts by categories. Just let me know if the above specification is up to date and this is how you want this to work/look. If it is, please mark this issue as Ready.

@olayway we've updated the issue above with details. Let us know if you need anything else.

**Comment by olayway** [comment]
@nathenf, @laurenwigmore what do you mean by this?

> Also can we change the image dimensions for Top Selection and Categories section to 2240x1260px (this would also be great to do on the homepage)
