### ISSUE TITLE
Post up "transforming the narrative" SCQH and analysis

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#32]
Post up "transforming the narrative" (big vision conversation) SCQH and analysis on tao (and blog)

Could back-post to when we wrote it (july 2020)

## Acceptance

* [x] Added to tao in `/scqh/` (i think) **Done**
* [x] Blog post (back-blogged i think) **https://lifeitself.us/2020/10/14/transforming-societies-scqh/**

## Tasks

* [x] Locate SCQH **DONE: see https://docs.google.com/document/d/1MoUxQesbdsmApqwhHAoxvgN3NZXIFog9GxLA7B0kbK0/edit**
* [x] Locate issue tree in coggle and google sheets **Google sheets https://docs.google.com/spreadsheets/d/1j2R0AKDXFMOELoEa2vYwIG-MNsa6nph5LLd3DV62SBo/edit#gid=889421189**
* [ ] Add to tao **Done**
* [ ] ...

**Comment by theo-cox** [comment]
FIXED. uploaded and blog posted.
