### ISSUE TITLE
Correction to Conscious Parenting podcast release

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#321]
@nathenf one issue i noticed is that we have published the "hangout" content (see #91) as part of the podcast series which was never the intention (and doesn't make a lot of sense on quality / continuity front).

Can we remove the hangout from our podcasts both on the relevant channels and on the podcast page. The only intention for the hangout was we publish it to youtube and embed in the hangout post for that event (from dec 2021).

Relates #156 

<img height="400" alt="image" src="https://user-images.githubusercontent.com/180658/216810170-16e1a507-35fd-412d-8295-25ef7157eb49.png">

## Acceptance

- [x] first item here (hangout item) is removed from podcast platforms
- [ ] Removed from our podcast page lifeitself.org/podcast/
- [ ] Removed from https://lifeitself.org/blog/2023/01/31/esther-montmany-on-conscious-parenting
- [ ] Is still on youtube (though not in podcast stuff) and embedded in https://lifeitself.org/blog/2021/11/30/community-hangout-december-2021

## Tasks

- [ ] ...

**Comment by nathenf** [comment]
FIXED - Removed from podcast and other tasks done in PR #322
