### ISSUE TITLE
Whatsapp Community March

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#344]
Following up of #316 

We now have a flourishing Whatsapp community of 50+ people. We foster engagement and activity, while building community resiliency.

## Acceptance

- [x] 2 community calls carried out
- [ ] General group 100 members 🚧 **74 so far, expected increase after next newsletter** ❌ Newsletter failed to go out and will solve in the next days.
- [x] Community guidelines document created and agreed upon by general consensus ✅ **Agreed upon by 6 people in the last call with feedback used https://docs.google.com/document/d/1znEHFliH1Aztyu2jXN_DckS3iYP9Lz6Y9Nqptjq-R6U/edit** 

## Tasks

- [x] Daily Activity 15-20mins
  - [x] #357
- [x] Create topics list for calls ✅ **Next four calls organised - 9th March Madelaine Ley on Care, Food & Tech research, 23rd March Valerie on Praxis & Community, 6th April Stephen Reid, 20th April Alex Goodall of Relevant Education.**
- [x] Learn how to create breakout rooms in Zoom
- [x] Draft community guidelines ✅ **version 1 is ready https://docs.google.com/document/d/1znEHFliH1Aztyu2jXN_DckS3iYP9Lz6Y9Nqptjq-R6U/edit**
  - [x] Create discussion to get open feedback on community guidelines ✅ This happened in last community call
  - [x] Add the the Tao once confirmed 🚧 **see #392**
- [x] Create github discussion to capture information about coliving etc. ✅ **see #391**
- [x] Create "Posing Questions" youtube series from community call presentations. 
  - [x] Crop, fix sound, add layers, write-up for each call
  - [x] Publish and initiate discussion around the topic

## Notes

Where to find jobs:
- [Curation Google Group](https://groups.google.com/a/lifeitself.org/g/curation?hl=en)
- [80,000 Hours jobs board](https://jobs.80000hours.org/)
- [Environment Jobs](https://www.environmentjob.co.uk/jobs)
## Inbox

DM from community member - Hi Nathen,
I mean quite a few things:
Purpose of the group. 
How we treat each other. 
How we engage (eg being brief and to the point, not monopolising the conversation, etc)
How we choose themes and reflect on them, and what we do when other themes come up as a result of our conversations...
How we structure the meetings
Is there ever a need for confidentiality, if so what does that mean?
Start and end times
Just some thoughts...

**Comment by nathenf** [comment]
@ZybN I've created the beginning of a draft for community guidelines above. Would appreciate your input, you can provide comments in the google doc

**Comment by rufuspollock** [comment]
@nathenf this is a great as an issue and really loving how this was going!

Small question re the estimate. 30h seemed quite a bit. if we allowed 10-20m a day plus 2h every 2 weeks for a call = 4-6h + 4h = 8-10h. I guess we also allow 2h for call guidelines etc. did you have in mind some other more substantive items?

**Comment by nathenf** [comment]
@rufuspollock good point. I do have one other item, which I am adding above. I will record the 15 minute presentation part by our guests and the question that they ask, this will be a new youtube series called Posing Questions. So a small amount of work there for formatting, publishing. I will wait until end of month so we have two ready before launching it on youtube

**Comment by nathenf** [comment]
@rufuspollock what do you think about adding the guidelines to the tao?

**Comment by rufuspollock** [comment]
@nathenf yes, very good idea: guidelines in the tao. can you post as a PR which we can then review (don't just immediately merge is that is ok ...)

**Comment by nathenf** [comment]
FIXED - Last month we had two community calls with approx 10 people at each. These have been uploaded to youtube and collectively viewed 130+ times. The community guidelines have been added to the tao at lifeitself.org/tao/community-guidelines 🎉
