### ISSUE TITLE
Back Publish Integral Theory Blog Post

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#347]
I want to back publish integral blog post alongside other blog posts from this series so that we have them all posted and collected together and we can close issue #128.

And so that Zaib can learn how to create and upload a new blog post 🎉 

Example: https://lifeitself.org/blog/2022/04/29/mapping-metamodern-buddhism 

Blog post content: [Mapping Metamodern: Integral] (https://docs.google.com/document/d/1tXR6SaGfStFKX31yfWoZLF2XRpSscHsaoD37grESoSU/edit) 

## Notes

You can see our recording of how to get set up with editing the website here: https://drive.google.com/file/d/1Ow0RYya8e3JMZhY5cpCYspsZAA1loses/view 

Here is the markdown cheatsheet you can use: https://rossgriffin.com/tutorials/obsidian-basics-guide/ 

## Acceptance

- [x] Blog post is back published on the website ✅ **see article here: https://lifeitself.org/blog/2022/05/27/mapping-metamodern-integral**

## Tasks 

- [x] Create feature image using canva (we already have design template, just a matter of adding new image) @ZybN 
- [x] Add blog post to the website (we can do this together @ZybN)
- [x] Add to article the five elements which are currently missing from section 2.3

**Comment by ZybN** [comment]
@nathenf can we close this issue?

**Comment by nathenf** [comment]
FIXED - see article at https://lifeitself.org/blog/2022/05/27/mapping-metamodern-integral
