### ISSUE TITLE
Website Updates [Inbox]

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#358]
A place to keep track of small website updates as requests come in.

## Tasks
- [x] Add Bergerac Praxis Hub to people page #355 🚧 see #433 
- [x] Add Zaib to Team Page & move Eilidh to Alumni 🚧 see #433 
- [x] Sync sign up forms with Sendinblue #359 ✅ 
- [x] Redirect tao.lifeitself.org to lifeitself.org/tao ✅ this now redirects

**Comment by nathenf** [comment]
@rufuspollock is this what you meant?

**Comment by nathenf** [comment]
@rufuspollock I've attempted to update the team page to include Zaib and move Eilidh to alumni and correct the images for Marc and Liu. The PR is #433 and I added you as a reviewer

**Comment by rufuspollock** [comment]
@nathenf i'm a bit bandwidth limited atm so don't have much time to review PRs. Can i suggest you ask @khalilcodes to review (made need to ping on group).

**Comment by nathenf** [comment]
FIXED - These small tasks are all complete now
