### ISSUE TITLE
Netlify build fails (maybe out of memory)

### ISSUE THREAD

**Issue by khalilcodes** [life-itself/community#383]
As we fetch data for pages in `[[...slug]].jsx`, some exceed the recommended threshold of 128kb eg. blog posts are above 9mb. Due to this netlify builds may exit / kill process with error `failed with exit code 137: npm run export` (https://ntl.fyi/exit-code-137)

<img width="1135" alt="Screen Shot 2023-03-22" src="https://user-images.githubusercontent.com/42637597/227017789-d138f647-e22e-4072-bf21-ab139afdbc75.png">

## Acceptance

- [x] Site builds every time **✅2023-04-08 this is working fine on cloudflare pages**

## Tasks

- [x] temp solution to limit fetching no. of posts to 30 for `/blog` page. **2023-03-22 commit https://github.com/life-itself/community/commit/cc0a5f22f897a2329329d997409b4d71e649eb58**
- [x] find long term solution ... eg. for all other pages **✅2023-04-08 switched to cloudflare pages**

### Notes

- Nextjs recommends reduce amount of data in `getStaticProps` to only essential data. https://nextjs.org/docs/messages/large-page-data
- Netlify may have a limit on page size on it's cdn.

current workflow:
* get all posts from contentlayer eg. in `content/getters/blogs.js`
* add data reference in markdown frontmatter - `data: blogs`
* use above reference to fetch data on page in `[[...slug].jsx` getStaticProps function

**Comment by nathenf** [comment]
@khalilcodes  thanks so much for looking into this. Would be great to learn what I can do to make sure I'm not causing this to happen again.

**Comment by rufuspollock** [comment]
This is happening pretty much [all the time now](https://app.netlify.com/sites/zesty-liger-3a5c29/deploys/6426998d8b6d754ecef3edcc) with error 137. More research on error 137:

https://answers.netlify.com/t/support-guide-making-sure-your-builds-use-appropriate-resources-for-netlifys-build-system/5349

https://answers.netlify.com/t/support-guide-what-can-i-do-if-my-build-fails-for-memory-overallocation-related-errors/36549

Neither of which are that helpful for identifying our problem or the resolution.

The one useful point is that there is 8GB of memory for the build. We should be a way below this - even if all pages are in memory we only have 700 pages and most are well under a 1Mb in size (most are below 128kb threshold).

Beyond that the only thing would be the node cache (1.4Gb) and maybe the git clone is large (we have ~1Gb of material in git lfs). But altogether this should be still well below 8Gb ...

**Comment by khalilcodes** [comment]
@rufuspollock researching a few more answers in netlify it seems like "killed" mostly looks like running out of memory, without much info on the cause ...

* https://answers.netlify.com/t/netlify-build-issue-while-generating-nextjs-static-pages/71667/7
* https://answers.netlify.com/t/builds-constantly-killed-with-exit-code-137/81265/3

The workaround or suggestions provided there are running a build locally and manually deploying via the netlify CLI.

We can setup github action workflows for both _push_ and _pull_requests_ that would build the site and run deploy and deploy previews respectively. Note that manual deploys via CLI don't use netlify build minutes.

**Comment by rufuspollock** [comment]
Overall, this makes little sense to me given the size of our site and fact they are supposed to allocate 8GB of memory. Right now i'm trying building on cloudflare which seems to have few issues.

**Comment by rufuspollock** [comment]
FIXED. Cloudflare is building fine and have switched site there (seems a bit faster too). Bonus: no build minutes limit.

**Comment by rufuspollock** [comment]
Update: i hadn't set up deployment previews on non-production branches for cloudflare so we weren't  getting cloudflare previews. Have just fixed that.

<img width="1063" alt="image" src="https://user-images.githubusercontent.com/180658/231080207-7c1249d8-f260-44eb-a91f-9f0b03a1af76.png">

I'm going to disable netlify for now.
