### ISSUE TITLE
Boot up "open" research community call once a month

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#388]
Boot up "open" research community call once a month

## Tasks

- [x] Have discussion about idea and check good idea **✅2023-03-25 see https://github.com/orgs/life-itself/discussions/381 and below**
- [x] Schedule a new monthly meeting for this e.g. "Research Community Monthly Call" **✅2023-04-05**
- [x] Create mailing list **✅2023-04-05**
  - [x] Add attendees of existing research group
  - [x] Add new requestors
- [x] Add mailing list to monthly meeting **✅2023-04-07**

### Discussed in https://github.com/orgs/life-itself/discussions/381

<div type='discussions-op-text'>

<sup>Originally posted by **rufuspollock** March 23, 2023</sup>
- What: Create an open research community call once per month
- Why
  - Situation: we currently have weekly calls for (initial) research (interest) group (following from #261). New people would like to join the community. also some people like Boaz and Jamie aren't able to come to interest group every time.
  - Complication: weekly calls are big commitment for some people. we have potential new joiners who need to find out what it is about.
- When: monthly call on Friday at 1330 European
- Where: online on hangouts
- Who: open to all

Next actions

- [x] Discuss the proposal
- [x] Agree to take forward or now **✅2023-03-25 i think most people seem to be happy so taking this forward**
</div>

**Comment by rufuspollock** [comment]
Rolling over as going to complete  this in working session tomorrow.

**Comment by rufuspollock** [comment]
FIXED. All done.
