### ISSUE TITLE
[epic] Jeffery Martin series episodes 2 & 3 (and Fundamental Wellbeing page)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#395]
Recorded episodes 2 & 3 back in Jan 2023 and would be good to publish these.

Thought: may be worth a dedicated landing page for this series as a mini initiative on fundamental wellbeing / scientific approach to awakening. This could be part of the "learn" section.

## Acceptance

- [x] Published episode 2 #414 ✅ **2023-04-20 This is complete**
- [x] Published episode 3 (could be spaced) #415 ⏭️ 
- [x] 🏆 Landing page for project with additional material (NB: this could become a separate issue) #452 🚧 **page created, but needs reviewing (see issue)** 

## Tasks

- [x] See examples / templates (maybe in tao) for publishing podcast episodes
- [x] Create tasks from that (perhaps one for each episode) ✅ **Issues created and linked above plus added to the issue here**
- [ ] ...

## Notes

Jeffery Martin is a renowned author, speaker, and entrepreneur who has dedicated his life to studying and helping people achieve transformative experiences. He is the founder of the Transformative Technology Lab, a non-profit organization that seeks to develop and promote technologies that enhance human well-being.

Martin has a Bachelor's degree in Psychology and a Ph.D. in Transformative Studies, and has conducted extensive research on human potential and consciousness. He has authored several books, including "The Fourth Awakening," "The God Formula," and "The Seeker's Guide to Harry Potter," which explore various aspects of human transformation and spirituality.

In addition to his work as an author, Martin is also an experienced public speaker, having delivered talks at numerous conferences and events around the world. His speeches and workshops focus on helping people understand and achieve transformative experiences, using a combination of scientific research and practical techniques.

Martin is also an entrepreneur, having founded several successful companies over the course of his career. His latest venture, drjefferymartin.com, provides coaching and training services to individuals seeking to achieve transformative experiences in their personal and professional lives.

Through his work, Martin has helped thousands of people achieve greater levels of personal fulfillment and success. His unique blend of scientific research, spiritual insights, and practical advice has made him a sought-after speaker, coach, and mentor.

**Comment by nathenf** [comment]
@rufuspollock I've set hours here at 15, this is to give Zaib the time to learn the process as well. This may take longer and we will try to integrate the podcast sound levelling

**Comment by nathenf** [comment]
@rufuspollock  I created issues for each podcast using our template and will train @ZybN to do these

**Comment by nathenf** [comment]
@rufuspollock to give you an update here, episode 2 is now live with full transcript on the podcast etc. The fundamental wellbeing page has been created at www.lifeitself.org/learn/fundamental-wellbeing and episode 3 is set to be complete by end of week or early in the next iteration

**Comment by ZybN** [comment]
DONE: 

Fundamental Wellbeing Page: https://lifeitself.org/learn/fundamental-wellbeing

Podcast 2: https://lifeitself.org/podcast/a-scientific-approach-to-awakening-and-fundamental-wellbeing-part-2-jeffery-martin
YouTube: https://youtu.be/0l_jrk0HTVY
Spotify:  https://spotifyanchor-web.app.link/e/c34gB9Bb8yb

Podcast 3: https://lifeitself.org/podcast/a-scientific-approach-to-awakening-and-fundamental-wellbeing-part-3-jeffery-martin
YouTube: https://youtu.be/vDuh7vDgGIg
Spotify: https://podcasters.spotify.com/pod/dashboard/episode/e22vp6s
