### ISSUE TITLE
Comparing Social Media Management Platforms

### ISSUE THREAD

**Issue by theo-cox** [life-itself/community#41]
When I'm using social media to engage the broader Life Itself community, I want the best integrated platform to manage the content we post across our channels.

## Acceptance
- [x] Platform recommendation made **Recommend Buffer as it's the best value for the features we want**
- [x] Subscription purchased **We're on the Buffer free plan already - have switched email to accounts@lifeitself.us and updated Bitwarden**

## Tasks
- [x] Find relevant platforms eg loomly, later **Found a number but many extremely expensive, so whittled down for comparison to top 4**
- [x] Create comparison spreadsheet for pricing, features etc [**Comparison Spreadsheet**](https://docs.google.com/spreadsheets/d/1uCk97BS45MjBsW05vpiIrn0RqZIRsyTsR20Se4NCr6w/edit#gid=0)

**Comment by theo-cox** [comment]
@rufuspollock spreadsheet linked and recommendation made above

**Comment by rufuspollock** [comment]
@theo-cox great - and i think we fit in the free plan for now. Let's go for it get an account with accounts email ...

**Comment by theo-cox** [comment]
Cool @rufuspollock on the todoist and will aim to do today!

**Comment by theo-cox** [comment]
FIXED. We have the Buffer free plan.
