### ISSUE TITLE
Comms Iteration w/c 3 April 2023

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#410]
## End of Sprint Summary

We acheive about 60% of our goal closing Key ideas, Initiatives, and making a big dent in the residencies section. The part 2 podcast by Jeffery Martin will be live by end on day April 17th. 

Nathen Spent 27.5 hours: 
- 5 on Website
- 8.5 on Praxis
- 4.5 on Community
- 9.5 on Comms, Meeting, Misc

## Acceptance

- [x] Finish key ideas page #124 ✅ **Edited and fixed, could go through another round of revision but fine for now**
- [x] Initiatives pages with new design #97 ✅ 
- [ ] New homepage designed and launched #335 🔥🔥 **Will do in next iteration as Khalil is unavailable to finish. Preparation is underway** 🚧 
- [x] Fundamental Wellbeing episode 2 launched #414 part of #395 🔥 🚧 2023-04-17 80% complete will finished today
  - [ ] `Waking up` landing page ❌ **Will do in next iteration**
- [x] New about page launched #413 🔽 💬 **2023-04-13 I added initiatives to the page and removed old content which was no longer relevant**
- [x] Update to residencies pages #423 🚧 **Bulk done (80%) for this iteration, just need to sync with Khalil for final work**

## Tasks

- [x] Create key ideas page #124 ✅ 
- [x] Complete #97 ✅ 
  - [x] Create a template design for the initiative pages (Khalil)
  - [x] Implement design across all projects
  - [x] Link initiatives index page in the header menu 
  - [x] Update projects to initiatives in copy
- [x] Our story, part of about us page copy and update #413  💬 **2023-04-13 I added initiatives to the page and removed old content which was no longer relevant**
- [x] Whatsapp Community (Nathen) ✅  **Stephen Reid on 6th April, and video complete**
  - [x] Run community call and create youtube video
- [x] Give feedback Obsidian Guide ✅ Feedback given, now needs to be compiled and turned into guide
- [ ] Jeffery Martin podcasts (and a landing page e.g. learn/fundamental-wellbeing??) #395 ❌ 
  - [x] Launch Podcast 1 #414 ❌ 
- [x] General comms tasks
  - [x] Share Theo’s article on Twitter & Linkedin ✅  [Linkedin](https://www.linkedin.com/feed/update/urn:li:activity:7049268880157945856) [Twitter](https://twitter.com/forlifeitself/status/1641742137128542208)
  - [x] Sharing the community call videos
  - [x] Creating an article from Valerie call #425
  - [x] Create an article from Stephen Reid Call #437 
  - [x] Case sensitive on front matter (Nathen to check) ✅  #417 

---

# 2023-04-12

Present: Nathen, Rufus

Intention: 

- [x] Remove blocker around deploy previews
- [x] Setup for Nathen road trip i.e. what is needed from him
  - [x] Priorities before then
  - [x] Prioritiese during that time

Agenda:

- [x] 👋 Check-in
- [x] 🎯 Set intentions
- [x] 📝 Set agenda
- [x] 🏃‍♀️ Review agenda
  - [x] Sort out deploy previews now on cloudflare **✅2023-04-13 see notes below for new approach**
  - [x] Nathen away time
  - [x] Current sprint and priorities **✅2023-04-13 focus on shipping home page**
  - [x] AOB
    - [x] Notes on brand: move away from b&w photos if we can, more pictures of people. A sense of aliveness. 
    - [x] Clean up old meeting notes below e.g. move to relevant places and/or delete 
- [x] ⏭️ Checkout and next steps
  - [x] @nathen Post about monthly open research meeting https://lifeitself.org/research - https://lifeitself.org/research#monthly-open-meeting tomorrow at 3pm european - can add the google hangout link

## Nathen away time

Whilst away will:

- Weekly check-in with Zaib
- Biweekly (bimonthly also!) community call

Notes:

- Screen shot for possibility now ✅ 

## Preview deployments

Why no previews?

Aha! https://developers.cloudflare.com/pages/platform/known-issues/

> Commits/PRs from forked repositories will not create a preview. Support for this will come in the future.

![](https://i.imgur.com/Tbv5QgY.png)

Workarounds: switch to branches approach (in master repo) vs forks with main branch

- [ ] You actually create a new branch in master repo for each thing call e.g. `332-move-residencies` where `332` is related issue number (or your fork - though easier to work now directly with master)
- [ ] Push everything to that (you get a deploy)
- [ ] Then if that looks good you merge to main

**Comment by nathenf** [comment]
@rufuspollock I've updated acceptance criteria and task list here. I will expand some tasks into issues and add them to the iteration accordingly

**Comment by nathenf** [comment]
@rufuspollock included our capacity in the Metadata: 20 hours for me and 20-25 for Zaib

**Comment by nathenf** [comment]
Good point @rufuspollock, I removed that and create #422 for the next iteration for when we need it

**Comment by rufuspollock** [comment]
@nathenf can you update where we got to on each item and do a brief assessment of sprint at the top (e.g. what % of goal reached, how many hours spent, any learnings).

**Comment by nathenf** [comment]
@rufuspollock I have updated the issue above. Zaib will also add her hours and complete the Jeffery Martin Episode before we close this issue.

**Comment by rufuspollock** [comment]
@nathenf being strict we should now roll the issue since we into the next sprint 😜

**Comment by nathenf** [comment]
FIXED - Tasks here have either been completed or transferred to next sprint!
