### ISSUE TITLE
Update about page 

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#413]
About is our second most visited page after the homepage. We need to update the text to reflect current activities and direction so that it is relevant and provides pathways to other areas of the website:
- Initiatives
- Key Readings
- Residencies

## Acceptance

- [ ] About page is updated and live

## Tasks

- [ ] Create job stories for the about page 🚧 **we have initial job stories for website here including about us [GDoc For Job Stories](https://docs.google.com/document/d/1qKvH41W5s2IW16UHyk16fr3uj9gbhAC3k5pSvQ66aXg/edit#heading=h.ywfbwdu3jazi)**
- [ ] Write copy for the about page using current copy
- [ ] Update the website
