### ISSUE TITLE
Jeffery Martin Episode 2

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#414]
[Original recording](https://drive.google.com/drive/folders/1oZ0b5_loOH7_qe7vX0A9pAgUoVfMXkwC)

## Acceptance

- [x]  Conversation published on Youtube & Anchor.
- [x]  Episode page added to the website.
- [ ]  Guest informed that the episode is out and has been sent the links.
- [x]  The new episode has been announced on twitter.
- [ ]  Email announcing new episode has been sent to mailing list.
- [x]  Secondary content has been shared on social media

## Tasks

- [x] Copy this Template into a new GitHub issue. Name the issue as the working title of the conversation
- [x] [Create a new folder for the conversation and assets here](https://drive.google.com/drive/folders/12BskqKPp85XNdU2sespI--E7VPi45hGJ?usp=sharing) 
- [x]  Source the video file and add to folder ✅ [Folder Link](https://drive.google.com/drive/folders/1oZ0b5_loOH7_qe7vX0A9pAgUoVfMXkwC)
- [x]  Create a document for the conversation that includes: Title, Conversation Summary, About the person in conversation, links to resources mentioned in the podcast, timestamps for at least two video excerpts and two quotes and timestamps for ["chapters"](https://www.youtube.com/watch?v=pvkTC2xIbeY). Add this to folder. ✅ [Link of Folder](https://docs.google.com/document/d/17wITSm2B7sbRS-syyxqYwWCLUtUpnlRQw93vdVc_nB0/edit?usp=sharing)
- [x]  Watch the video. Note any moments that need edited eg moments of bad internet connectivity. Note down timestamps for chapters to be used when publishing to YouTube. Note timestamps of short sections that will be good for social media (max length for twitter 2m20s) and note down quotes that will be good for marketing the episode.

### Create Youtube video
- [x]  Create the Youtube Thumbnail from [this template](https://www.canva.com/design/DAE99drPH4s/7mR8CgHWyHfimwC9jDerDA/edit?utm_content=DAE99drPH4s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).
- [x]  Edit the video file in [Da Vinci Resolve](https://www.blackmagicdesign.com/products/davinciresolve):
- [x]  Trim beginning and end, plus any sections of poor internet connection or other interruptions
- [x]  Add thumbnail at the beginning of the video with a fade transition to the video
- [x]  Add graphic overlay ["Please Like & Subscribe"](https://drive.google.com/file/d/1iQjSdgjTyrN9xnQ8Xnlzdjmk2sw2eKXJ/view?usp=sharing) at the 5, 10, 20, 40 minute
- [x]  [Add End Screen with a fading transition](https://drive.google.com/file/d/1fC8c_tyoOxxGGhGqgJuwFscu6vYzbrqe/view?usp=sharing)
- [x]  Increase the sound volume as much as possible without clipping the sound (around 3 is normally good)
- [x]  Export as Video for Youtube
- [x]  Export audio only for podcast
- [x]  Upload to Youtube: Add title, thumbnail, summary including [contents chapters](https://www.youtube.com/watch?v=pvkTC2xIbeY), page stub URL, add to relevant playlist, Add Language, Make License Creative Commons. ✅ **Done: [Link Here](https://youtu.be/0l_jrk0HTVY)**
- [ ]  Schedule publication for desired day and time

### Create Twitter Secondary Content e ✅ [Twitter Thread in the File](https://docs.google.com/document/d/17wITSm2B7sbRS-syyxqYwWCLUtUpnlRQw93vdVc_nB0/edit?usp=sharing) **T[witter Thread Posted](https://twitter.com/forlifeitself/status/1649027257258897408?s=20)**
- [ ]  Cut the video excerpts from the main video and leave all the clips in one timeline
- [ ]  Export just the audio
- [ ]  Upload Audio to Otter.ai to create srt file (srt file settings: no more than 1 line and 60 letters per line) - make sure that the speech from each clip is correctly separated in Otter.ai
- [ ]  Upload the srt file to the project
- [ ]  Crop top and bottom of video - add title to top and subtitles at the bottom
- [ ]  Create Quote posts using [this template](https://www.canva.com/design/DAE-ett42vU/63HsI5cGixlZ6cFQd09zCg/edit)
- [ ]  Add all content to the folder that has been created
 
###  Create Podcast
- [x]  In Anchor click new episode then click create new episode. Click on reuse your previously uploaded audio and scroll down until you find the "Intro Jingle". Drag the file in the box into the right. Add the audio only edit of the episode after the intro. Click save episode.
- [x]  Add title & summary.
- [x]  Create and add thumbnail from [this template](https://www.canva.com/design/DAE87pGGDUg/EgrVC9iJX5eATZGF5rE2pg/edit?utm_content=DAE87pGGDUg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
- [x]  Add season number and episode number
- [x]  Schedule publication for desired day and time
- [x]  Create a page for the episode on the [podcast page](https://lifeitself.org/podcast) of the website. You can prep this before the podcast and YouTube video are published, however you will not be able to add the podcast link in until the podcast is up. 🚧 waiting to get front matter 🚧 ** generated pull request**
- [x]  Add a new page in vault/podcast in the community repo. Use [Jeffery Martin episode page](https://lifeitself.org/podcast/a-scientific-approach-to-awakening-and-fundamental-wellbeing-podcast) as a guide. Generate the links for the frontmatter 🚧 
- [x]  Follow this link: https://rss2json.com/
- [x]  Paste this link in the box on the page (under the text that says Enter the URL to your RSS feed): https://anchor.fm/s/79b39934/podcast/rss
- [x]  Find the podcast episode you are wanting to create the page for (likely the first episode listed, this will be the first episode under the line that says "items")
- [x]  Click the button with 4 arrows pointing outwards to make it full screen to ensure you don't copy only part of a link.
- [x]  Copy the link for "thumbnail" and paste it after "image:" in the frontmatter.
- [x]  For the src link, scroll down to where it says "enclosure" and copy the link that follows "link". Paste this after "src" in the frontmatter.
- [x]  Fill out the rest of the frontmatter.
- [x]  Paste a brief introduction of the guest and an intro to the episode (eg v brief overview of what is discussed) below the frontmatter.
- [x]  Paste the youtube link.
- [ ]  Add the transcript
- [x]  run the video through Otter to generate the transript. Go through and fix any errors. Export as docx with speaker names and timestamps.
- [x]  Copy the transcription into a google doc and save in the episode folder.
- [ ]  Convert into markdown. Copy and paste into page ❓ **do I need to post the transcript to the podcast page?** 
- [x]  Add any notes. Ensure they are complete, comprehensive and tidied.
- [x]  Add any references and further reading
- [x]  Once the page is up, edit the YouTube and Anchor episode bios and paste in the link to the page.
- [ ]  Inform the guest that the episode is out. Send all links and encourage them to share.
- [ ]  Send email out to Life Itself General Audience on Sendinblue announcing that the latest episode of the Life Itself Podcast is now available. Use the same intro to the episode and guest as used on the podcast page on the website. Paste link to the podcast page - they can navigate to everything they need from that one link. Use a previous podcast episode launch email as a guide - you can replicate that email, just remember to change the text, link, subject line and preview text.
- [x]  Announce release on Twitter. Make sure to @ the guest and tweet the link to the podcast page. Tweet the secondary content throughout the following week. Consider writing a twitter thread covering the main points of the conversation. Use this guide to write an effective twitter thread: https://www.ship30for30.com/post/how-to-write-a-twitter-thread

**Comment by ZybN** [comment]
Hi @nathenf I am working on the podcast and I have a few questions: 

- It seems to me that the episodes are already edited. I want to know what is the status of these podcasts. I see that the Youtube Thumbnail is already created. 
- Anchor is now part of Spotify so the steps mentioned above for editing the podcast don't work anymore. 
- I also want to know if the audio version is edited or not. I am listening to it but I don't see any parts that should be removed. 

Please guide

**Comment by nathenf** [comment]
Hey @ZybN ,

> It seems to me that the episodes are already edited. I want to know what is the status of these podcasts. I see that the Youtube Thumbnail is already created.

Where have you seen them? There are three episodes in total and one has already been published. Maybe you can update this issue with the link to the file so we can always access easily. 

> Anchor is now part of Spotify so the steps mentioned above for editing the podcast don't work anymore. 

This is new, I will have a look at this. Do you think its fairly simple and you could go through the process with instruction and then update the workflow? 

> I also want to know if the audio version is edited or not. I am listening to it but I don't see any parts that should be removed.

Again if you can link it here so I can check that would be great

**Comment by nathenf** [comment]
I've added the recording above!

**Comment by ZybN** [comment]
Kindly give me access to Life Itself Youtube. @nathenf

**Comment by ZybN** [comment]
Remaining Tasks: 

- Post Video on YouTube 
- Add a Youtube link to the Podcast page, 
- Add Podcast page link to Youtube
- Share with Whatsapp Community
- Share with the participant

**Comment by ZybN** [comment]
Last task is to Announce the podcast through Email and Share with Dr Martin.

**Comment by nathenf** [comment]
<img width="839" alt="Screenshot 2023-04-20 at 16 39 39" src="https://user-images.githubusercontent.com/95729108/233508514-1396d618-9a4f-4213-befb-dd782232542d.png">

<img width="305" alt="Screenshot 2023-04-20 at 16 39 43" src="https://user-images.githubusercontent.com/95729108/233508520-29681866-0fe2-4464-9777-5b7e5eca1830.png">
<img width="424" alt="Screenshot 2023-04-20 at 16 39 48" src="https://user-images.githubusercontent.com/95729108/233508523-e6c05ccb-c846-40fd-9383-0da3fa29cca1.png">

@ZybN just a few things to note here the is a rogue # in the first heading, the "podcast transcript" should probably be a header as well. Finally, I don't think we need this link to spotify or anchor. All the information is on this page and we don't want to direct the elsewhere.

**Comment by nathenf** [comment]
@ZybN here is Jeffery's email jm@drjefferymartin.com let's try to close this by Monday.

- When you closed this issue you want to close it with a comment. 

So you might say:

FIXED - then a summary of what has been done and the key links to show the work

**Comment by ZybN** [comment]
The podcast is life on all channels, and the creator has been informed through email.
