### ISSUE TITLE
Jeffery Martin Episode 3

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#415]
[Original Recording on Zoom](https://us02web.zoom.us/recording/detail?meeting_id=s9mhaq8aQ5ubNSommVi4YA%3D%3D)

## Acceptance

- [x]  Conversation published on Youtube & Anchor.
- [x]  Episode page added to the website.
- [ ]  Guest informed that the episode is out and has been sent the links.
- [x]  The new episode has been announced on twitter.
- [ ]  Email announcing new episode has been sent to mailing list.
- [ ]  Secondary content has been shared on social media

## Tasks

- [x] Copy this Template into a new GitHub issue. Name the issue as the working title of the conversation
- [x] [Create a new folder for the conversation and assets here](https://drive.google.com/drive/folders/12BskqKPp85XNdU2sespI--E7VPi45hGJ?usp=sharing) 
- [x]  Source the video file and add to folder
- [x]  Create a document for the conversation that includes: Title, Conversation Summary, About the person in conversation, links to resources mentioned in the podcast, timestamps for at least two video excerpts and two quotes and timestamps for ["chapters"](https://www.youtube.com/watch?v=pvkTC2xIbeY). Add this to folder.
- [x]  Watch the video. Note any moments that need edited eg moments of bad internet connectivity. Note down timestamps for chapters to be used when publishing to YouTube. Note timestamps of short sections that will be good for social media (max length for twitter 2m20s) and note down quotes that will be good for marketing the episode.

### Create Youtube video
- [x]  Create the Youtube Thumbnail from [this template](https://www.canva.com/design/DAE99drPH4s/7mR8CgHWyHfimwC9jDerDA/edit?utm_content=DAE99drPH4s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).
- [x]  Edit the video file in [Da Vinci Resolve](https://www.blackmagicdesign.com/products/davinciresolve):
- [x]  Trim beginning and end, plus any sections of poor internet connection or other interruptions
- [x]  Add thumbnail at the beginning of the video with a fade transition to the video
- [x]  Add graphic overlay ["Please Like & Subscribe"](https://drive.google.com/file/d/1iQjSdgjTyrN9xnQ8Xnlzdjmk2sw2eKXJ/view?usp=sharing) at the 5, 10, 20, 40 minute
- [x]  [Add End Screen with a fading transition](https://drive.google.com/file/d/1fC8c_tyoOxxGGhGqgJuwFscu6vYzbrqe/view?usp=sharing)
- [x]  Increase the sound volume as much as possible without clipping the sound (around 3 is normally good)
- [x]  Export as Video for Youtube
- [x]  Export audio only for podcast
- [x]  Upload to Youtube: Add title, thumbnail, summary including [contents chapters](https://www.youtube.com/watch?v=pvkTC2xIbeY), page stub URL, add to relevant playlist, Add Language, Make License Creative Commons.
- [x]  Schedule publication for desired day and time

### Create Twitter Secondary Content
- [x]  Cut the video excerpts from the main video and leave all the clips in one timeline
- [ ]  Export just the audio
- [ ]  Upload Audio to Otter.ai to create srt file (srt file settings: no more than 1 line and 60 letters per line) - make sure that the speech from each clip is correctly separated in Otter.ai
- [ ]  Upload the srt file to the project
- [ ]  Crop top and bottom of video - add title to top and subtitles at the bottom
- [ ]  Create Quote posts using [this template](https://www.canva.com/design/DAE-ett42vU/63HsI5cGixlZ6cFQd09zCg/edit)
- [ ]  Add all content to the folder that has been created
 
###  Create Podcast
- [x]  In Anchor click new episode then click create new episode. Click on reuse your previously uploaded audio and scroll down until you find the "Intro Jingle". Drag the file in the box into the right. Add the audio only edit of the episode after the intro. Click save episode.
- [x]  Add title & summary.
- [x]  Create and add thumbnail from [this template](https://www.canva.com/design/DAE87pGGDUg/EgrVC9iJX5eATZGF5rE2pg/edit?utm_content=DAE87pGGDUg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
- [x]  Add season number and episode number
- [x]  Schedule publication for desired day and time
- [x]  Create a page for the episode on the [podcast page](https://lifeitself.org/podcast) of the website. You can prep this before the podcast and YouTube video are published, however you will not be able to add the podcast link in until the podcast is up.
- [x]  Add a new page in vault/podcast in the community repo. Use [Jeffery Martin episode page](https://lifeitself.org/podcast/a-scientific-approach-to-awakening-and-fundamental-wellbeing-podcast) as a guide. Generate the links for the frontmatter:
- [x]  Follow this link: https://rss2json.com/
- [x]  Paste this link in the box on the page (under the text that says Enter the URL to your RSS feed): https://anchor.fm/s/79b39934/podcast/rss
- [x]  Find the podcast episode you are wanting to create the page for (likely the first episode listed, this will be the first episode under the line that says "items")
- [x]  Click the button with 4 arrows pointing outwards to make it full screen to ensure you don't copy only part of a link.
- [x]  Copy the link for "thumbnail" and paste it after "image:" in the frontmatter.
- [x]  For the src link, scroll down to where it says "enclosure" and copy the link that follows "link". Paste this after "src" in the frontmatter.
- [x]  Fill out the rest of the frontmatter.
- [x]  Paste a brief introduction of the guest and an intro to the episode (eg v brief overview of what is discussed) below the frontmatter.
- [x]  Paste the youtube link.
- [x]  Add the transcript
- [x]  run the video through Otter to generate the transript. Go through and fix any errors. Export as docx with speaker names and timestamps.
- [x]  Copy the transcription into a google doc and save in the episode folder.
- [ ]  Convert into markdown. Copy and paste into page
- [x]  Add any notes. Ensure they are complete, comprehensive and tidied.
- [x]  Add any references and further reading
- [x]  Once the page is up, edit the YouTube and Anchor episode bios and paste in the link to the page.
- [x]  Inform the guest that the episode is out. Send all links and encourage them to share.
- [ ]  Send email out to Life Itself General Audience on Sendinblue announcing that the latest episode of the Life Itself Podcast is now available. Use the same intro to the episode and guest as used on the podcast page on the website. Paste link to the podcast page - they can navigate to everything they need from that one link. Use a previous podcast episode launch email as a guide - you can replicate that email, just remember to change the text, link, subject line and preview text.
- [ ]  Announce release on Twitter. Make sure to @ the guest and tweet the link to the podcast page. Tweet the secondary content throughout the following week. Consider writing a twitter thread covering the main points of the conversation. Use this guide to write an effective twitter thread: https://www.ship30for30.com/post/how-to-write-a-twitter-thread

**Comment by rufuspollock** [comment]
@nathenf @ZybN  is this really going to happen in this iteration 😉?

**Comment by ZybN** [comment]
The podcast is published on Youtube, and Spotify, and the podcast page is live with the transcript. It was also announced on Twitter. 

It will be updated in the Whatsapp group today. It has already been sent in April Newsletter.
