### ISSUE TITLE
Simplify site layout (e.g. removing symlinking)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#420]
Simplify site so that pages created at e.g. root of content folder show up automatically (plus simpler structure overall).

Why?

- See quite a few issues / confusion with symlinking e.g. just now #417 
- We don't get anything from separation at the moment really (minor simplification of vault)

## Acceptance

- [x] `site` at root? (means we can build on cloudflare) **✅ 2023-04-06 commit [3855dc4](https://github.com/life-itself/community/commit/3855dc4e01ec7da72e85168449b36d4fa0b1ed5a)**
- [x] One content folder i.e. `content` i.e. `vault` moves to `content` and current `content` merges in to it (no need for symlinking etc) **✅ 2023-04-06 commit [3855dc4](https://github.com/life-itself/community/commit/3855dc4e01ec7da72e85168449b36d4fa0b1ed5a)**
  - [x] Move ecosystem into vault at ecosystem **✅ 2023-04-06 commit [3855dc4](https://github.com/life-itself/community/commit/3855dc4e01ec7da72e85168449b36d4fa0b1ed5a)

Bonus

- [ ] Use classic nextjs js pages for more complex pages with components (stop trying to do this in markdown)
  - [x] Move ecosystem index to pages/ecosystem **✅  2023-04-06  commit [5a66d32](https://github.com/life-itself/community/commit/5a66d321224f82bbebc6163bd6dd33858bc70f34)**

## Tasks

- [x] Remove symlinks in `content`
- [x] Move `components` from `content` in `site/components/custom`
- [x] Move everything from `vault` to `content`
- [x] Move ecosystem stuff from root into `content` **✅  all ecosystem pages work**
  - [x] Move `ecosystem/index.md` to `pages/ecosystem.jsx` 
- [x] Clean up root
  - [x] Remove `hubs` (accidentally added by @nathenf)
  - [x] Move `research` folder to `content/notes/projects/research-communal-coliving-space-usage-2021`
- [x] Merge root README.md into site README.md and then remove root README.md
- [x] Move `site/*` to root

**Comment by nathenf** [comment]
🎉

**Comment by rufuspollock** [comment]
FIXED. All done. The use of nextjs pages can happen incrementally as we need it.
