### ISSUE TITLE
Comms Iteration w/c 17 April 2023

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#422]
Summary: 

85% of all work completed with a few outstanding tasks on the Jeffery Martin/Fundamental Wellbeing project. Great progress made on the residencies and homepage and misc comms tasks completed. Major outstanding project is building the guide for the tech stack, however most people now up to speed with what we are doing. 

Total hours spent: 
- Nathen: 16
- Khalil: 12

Expected Hours: 
- Nathen: 25
- Zaib: 30
- Khalil: 15

## Acceptance
- [x]  Newsletter published at end of month ✅ Scheduled to go live 2023-05-01
- [x]  Fundamental Wellbeing Initiative page created with podcasts on https://github.com/life-itself/community/issues/395 🔥 
- [x] Alex Goodall call + video made ✅ **the Youtube video and Blog post are live** [Youtube](https://www.youtube.com/watch?v=P0ZL-lFyXoc); [Blog Pull Request](https://github.com/life-itself/community/pull/474)
- [x] Home Page Shipped #335 🔥 
- [x] #423 completed with residencies designed and easy to use
- [ ] Start draft on Tech Stack Guide ❌ have not had time for this in the end, perhaps needs a focussed push to create at some point. However, most people now up to speed on what they need. 

## Tasks 

- [x] Newsletter #419 @ZybN 
- [x] Whatsapp Community Call 19th April with Alex Goodall @nathenf 
  - [x] #453 @ZybN 
- [x] #335 @nathenf 
- [x] #423 @nathenf 
- [x] #414 @ZybN 
- [ ] #415 @ZybN 🚧 80% complete by end of iteration, just requires publishing in the next iteration
- [x] #452 @ZybN 
- [ ] #395 @ZybN 🚧 95% complete by end of iteration. Once episode 3 is published and loaded, this will be complete.
- [ ] Work on the Obsidian Guide https://github.com/orgs/life-itself/discussions/393 @nathenf ❌

**Comment by rufuspollock** [comment]
Great job @nathenf thank-you! Note you prob want to count some hours from @khalilcodes

**Comment by nathenf** [comment]
@ZybN and @khalilcodes can you add the amount of hours you worked on comms in this iteration in the summary above?

**Comment by nathenf** [comment]
@rufuspollock 85% of all work completed with a few outstanding tasks on the Jeffery Martin/Fundamental Wellbeing project. Great progress made on the residencies and homepage and misc comms tasks completed. Major outstanding project is building the guide for the tech stack, however most people now up to speed with what we are doing.

**Comment by rufuspollock** [comment]
FIXED.
