### ISSUE TITLE
[residencies] Making it easy to publish new residencies 

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#423]
Currently we do not have a folder for residencies and we do not have a template for residency pages. I propose we create a folder /vault/residencies-and-courses/ and make the upcoming residencies page the index and move all other pages into this folder. 

In addition, I propose we create a template for the residency pages so that it is easier for praxis team to create new residency pages. 

## Acceptance

- [x] Residencies folder created and all residencies compiled there
- [x] Simple residency template created and praxis team showed how to use it 
- [x] 🏆 Residencies index page formatted similarly to initiatives index page

## Tasks

- [x] Create folder and move all residency pages into it ✅ **lifeitself.org/programs is the new locations for all residency landing pages**
- [x] Create redirects ✅ **Redirects added in _redirects.md**
- [x] Update website menu
- [x] Praxis team to create residency page structure ✅ **We met and confirmed structure**
  - [x] Turn into template ✅ **See residencies.md in templates**
  - [x] 🏆 Praxis to hire Khalil to design the page nicely #471 see https://lifeitself.org/programs/2023/ouroboros-residency example
    - [x] https://tailwindui.com/components/marketing/sections/feature-sections for header to include front matter
- [x] 🏆 Residency index page formatted similar to initiatives page 
- [ ] Record video tutorial of how to set up a residency page. 🚧 **[Praxis Playbook](https://docs.google.com/document/d/1FjzXyqYGfArdk7KrX40HPHOkB76pVYoJ2sQ-9OfneL8/edit?usp=sharing) in creation**

## Job Stories

1. When I learn about the residency, I want to find a page which contains all the essential information in an easy accessible top feature with more detail below so that I can make a quick decision or read deeper about the residency
2. When I am making the residency page, I want to be able to make it fast and easily, so that I don't spend extra time on it and have to contact others for support
3. When I make a residency page, I want it to look good so that more people apply for the residency. 

## Redirects

| Previous | New |
| --- | --- |
|content/sympoiesis/sympoiesis-2-contemplative-activism.md | content/programs/sympoiesis/sympoiesis-2-contemplative-activism.md | 
|content/sympoiesis/making-eco-spirituality-accessible-residency-2022.md | content/programs/sympoiesis/making-eco-spirituality-accessible-residency-2022.md |
|content/sympoiesis/emergent-dialogue-residency-june-2022.md | content/programs/sympoiesis/emergent-dialogue-residency-june-2022.md |
| content/sympoiesis/conscious-food-workshop-june-2023.md | content/programs/2023/conscious-food-workshop-june-2023.md |
| content/sympoiesis/conscious-food-retreats-culture-broths-1.md | content/programs/sympoiesis/conscious-food-retreats-culture-broths-1.md |
| content/sympoiesis/4-collective-intelligence-feb-mar-2022.md | content/programs/sympoiesis/4-collective-intelligence-feb-mar-2022.md |
| content/sympoiesis/3-cultivating-conscious-community-jan-2022.md | content/programs/sympoiesis/3-cultivating-conscious-community-jan-2022.md |
| content/sympoiesis/1-daily-collective-practices-oct-nov-2021.md | content/programs/sympoiesis/1-daily-collective-practices-oct-nov-2021.md |
| content/open-residency.md | content/programs/open-residency.md |
| content/light-shadow-integration.md | content/programs/light-shadow-integration.md |
| content/insight-interbeing-and-science-may-2022.md | content/programs/insight-interbeing-and-science-may-2022.md |
| content/gathering.md | content/programs/gathering.md |
| content/embodying-collective-transformation.md | content/programs/embodying-collective-transformation.md |
| content/embodying-collective-intimacy.md | content/programs/2023/embodying-collective-intimacy.md |
| content/back-to-basics.md | content/programs/back-to-basics.md |
| content/2-week-relational-embodiment-residency.md | content/programs/2023/2-week-relational-embodiment-residency.md |
| content/upcoming-residencies-gatherings.md | content/programs/upcoming-residencies-gatherings.md |
| content/ouroboros-residency.md | content/programs/2023/ouroboros-residency.md |
| content/previous-residencies.md | content/programs/previous-residencies.md |
| content/setting-the-world-to-rights-residency | content/programs/2023/setting-the-world-to-rights-residency |
| content/sympoiesis | content/programs/sympoiesis/index|

**Comment by nathenf** [comment]
@rufuspollock I've created this issue for us to discuss, but I think it would help Praxis moving forward if we could help them set the foundations on the website

**Comment by rufuspollock** [comment]
@nathenf big 👍 I've added to this sprint iteration - and do you want to add an estimate.

**Comment by rufuspollock** [comment]
@nathenf if you could capture a few quick job stories too i think that would be v useful.

**Comment by nathenf** [comment]
I've added a few job stories in the description and completed a bunch of the tasks
- Programs in now the root folder for all residencies
- All redirects have been created
- Upcoming and previous residency pages are now merged into programs page

**Comment by nathenf** [comment]
FIXED - residency pages are now set-up and designed. Outstanding task to make a video tutorial for Praxis team is now in another issue #490 to be completed when a next residency is ready to be upload, I will create tutorial with example
