### ISSUE TITLE
Create article for community call with Valerie

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#425]
The last community call with Valerie is up on youtube https://www.youtube.com/watch?v=EcLtuV7EUh4&t=601s it would be great to link it to our website and an article. 

## Acceptance

- [x] blog post with youtube video embedded is created
- [x] Post shared in the Whatsapp community 

## Tasks

- [x] Write introduction to the video using the text in the youtube description
- [x] Create blog post including youtube video embed, introduction and link to Whatsapp community

**Comment by nathenf** [comment]
@ZybN can you do this one soon?

**Comment by nathenf** [comment]
FIXED - #447 blog post is here: https://lifeitself.org/blog/2023/04/04/conscious-community-practices
