### ISSUE TITLE
Create research community landing page

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#426]
A landing page for the research community - background on the community in https://lifeitself.org/notes/research-at-life-itself-2023 plus recent research group meetings.

## Acceptance

- [x] What the research community is, what topics it covers etc
- [x] How you participate
- [x] What work has already been done
- [x] Monthly meetings (cf #388)

Bonus

- [ ] List of brown bag talks

## Tasks

- [x] what is MVP ...
  - [x] What (rough)
  - [x] How to participate
    - [x] Monthly call
  - [ ] Work so far ...
- [x] convert topical map into local excalidraw and include
- [ ] 🏆 Nice image

Future

- [ ] Organizational drawing of how things fit together
  - [ ] How does labs relate? "Labs" is our professional research and consulting arm??

### Want to learn about the community 🔥🔥🔥

I want to learn about the community so that i can decide whether to participate/join 

* What kind of work
    * How formal is it (e.g. is it academic or more informal)
    * What topics does the community work on / are interested in? ** 👉[https://lifeitself.org/notes/research-at-life-itself-2023](https://lifeitself.org/notes/research-at-life-itself-2023) **
* Who: requirements for participation
    * Plus examples of current members
* Where: online

**FAQs**

* How are you organized?
* I want to know if there is funding?

### Join / participate in the community 🔥🔥

I want to join/participate the community so that i can have access to events, resources and connect with others [so that i have prestige]

* What criteria are there?
    * Is it just participation in the forum
    * Any principles / guidelines
* What is involved?
* How do i communicate with the group
    * Whatsapp
    * Github discussions
* What levels are there … [Later]

### See your existing work and outputs 🔥

I want to see what research you are doing so that I can learn from you (or comment on it?) 

* What projects
* What topics

Examples

* Web3 research
* Mapping the metamodern ecosystem
* Research on [space for communities](https://github.com/Liyubov/community/tree/master/research) (in collaboration with Conscious Coliving)
* Research on participatory projects CityZen project (participatory urban projects)
* Research on relational embodiment

**Comment by rufuspollock** [comment]
FIXED.
