### ISSUE TITLE
Remove header menu search bar

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#429]
Three issues with header search bar:

1. does not properly index all pages
2. is unresponsive when typing and then makes the page unresponsive
3. Search bar is too long in header menu and is squashing the menu and join the community button. 

## Acceptance

- [x] Header menu looks good with reduce search bar size **✅2023-10-11 ❌**
- [x] Search function works and doesn't make the page unresponsive **✅2023-10-11 ❌**
- [ ] Search functionality removed

## Tasks

- ~[ ] Fix the search bar~
- [ ] Remove search bar

**Comment by rufuspollock** [comment]
I think we could move to someday maybe for now.

**Comment by olayway** [comment]
@nathenf, @laurenwigmore, @rufuspollock, before I start debugging this, can you please confirm if the global search will be needed at all when we implement filtering blogs by categories?

**Comment by rufuspollock** [comment]
I think we need a rethink of global search given sixe of site etc. What is a KiSS option eg just using Google site search may work?

**Comment by nathenf** [comment]
@olayway  @rufuspollock I could also agree that we simply remove it. It's a nice to have but the fact that noone has emailed us to point out it doesn't work suggests to me it is rarely used.

**Comment by nathenf** [comment]
@olayway what is the status here?

**Comment by rufuspollock** [comment]
@nathenf have you seen the PR https://github.com/life-itself/community/pull/809

**Comment by nathenf** [comment]
@rufuspollock yes, it is not building so what next?

**Comment by rufuspollock** [comment]
Ola said she was looking at it

**Comment by rufuspollock** [comment]
@olayway i'm moving this to blocked as i know you've investigated in the PR and we can't find a fix for this weird issue. Right now i think we can just ignore and come back in a few weeks in hope it has somehow fixed itself 😉

**Comment by rufuspollock** [comment]
WONTFIX. For now we wontfix. Someday we will likely switch of our current flowershow setup.
