### ISSUE TITLE
Cache and post about this great video about the 2020 Building Fest

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#43]
This is a lovely video from a volunteer who shared it on facebook. Huge props to putting it together.

https://www.youtube.com/watch?v=IU64TRTUxmo

## Tasks

* [x] Cache a copy (stuff disappears off youtube sadly) onto life itself youtube
* [ ] Blog this either newly (or add to existing follow up post) **💬2024-07-03 ❓ blog or at least categorize somewhere ...**
* [ ] Share on social media **💬2024-07-03  ❓ not sure relevant now. But why not - it is kind of cool and we can say the hub is now renovated ...**

**Comment by laurenwigmore** [comment]
Added to YT (Private video at present) and saved in Raw Content for next actions.

**Comment by rufuspollock** [comment]
FIXED. Made video public. Nothing more is needed for now I think.
