### ISSUE TITLE
Create article for community call with Stephen Reid

### ISSUE THREAD

**Issue by ZybN** [life-itself/community#437]
The last community call with Stephen Reid is up on [YouTube](https://www.youtube.com/watch?v=AXGCptB_xUs) it would be great to link it to our website and an article.

## Acceptance
 
- [x] blog post with a youtube video embedded is created 🚧 **created [pull request](https://github.com/life-itself/community/pull/450)**
- [x]  Post shared in the Whatsapp community

## Tasks
 
- [x] Write an introduction to the video using the text in the youtube description
- [x]  Create blog post including youtube video embed, introduction and link to Whatsapp community

**Comment by nathenf** [comment]
FIXED: this is written and loaded on website. It is not showing up on the website, but this will be transferred to another issue.
