### ISSUE TITLE
Process old (google form) contact requests (approx Jan 2020 to April 2021)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#44]
Check in on processing of old Art Earth Tech contact stuff https://docs.google.com/spreadsheets/d/1ab-riuFqGYi5510HgZxUnxrmZFROXckULS0_cbAzx-g/edit#gid=1997953790

## Acceptance

* [x] Have responded (or decided not to) all request
* [x] Sheet is marked as deprecated and moved to Attic in drive

## Tasks

* [x] Review requests in the sheet https://docs.google.com/spreadsheets/d/1ab-riuFqGYi5510HgZxUnxrmZFROXckULS0_cbAzx-g/edit#gid=1997953790
  * [x] Check which ones we did actually respond to and update sheet status
  * [x] Prioritize
* [x] Draft responses (in sheet?)
  * [x] standard intro apologizing for delay (switch to new system etc)
* [x] Send responses

**Comment by theo-cox** [comment]
FIXED. Replied to those worth doing and deprecated the sheet.
