### ISSUE TITLE
Pattern for handling "how do i engaged" with you requests?

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#45]
As a community we are likely to get regular inquires about how to engage with us. Would be good to clarify the pattern for responding with good pathways for people to engage.

## Acceptance

* [ ] Tao has a pattern for handling engagement enquiries

## Tasks

* [ ] Collect examples of enquiries
* [ ] Come up with suggested routes
* [ ] Routinize / standardize into a pattern
* [ ] Add to Tao

## Examples

TODO
