### ISSUE TITLE
Fundamental Wellbeing Homepage

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#452]
We want to create a topic page about Fundamental Wellbeing, so that people have a central place to go to see our podcast episodes and learn more about Fundamental Wellbeing. 

## Acceptance

- [x] Fundamental Wellbeing page is live ✅ http://www.lifeitself.org/learn/fundamental-wellbeing
- [ ] Template create in Obsidian for future topic pages

## Tasks 

- [x] Create job stories for topic page @nathenf 
- [x] Compile information to include on the page @ZybN (see job stories)
  - [x] What is Fundamental Wellbeing
  - [x] Who is Dr. J Martin
  - [x] Our podcast episodes
  - [x] Key readings and resources
  - [x] Suggested course - 45 days to awakening **Side note he may have a referral code** 
- [x] Create page /learn/fundamental-wellbeing

## Job Stories

- I want to know what fundamental wellbeing is
- I want to know if fundamental wellbeing is rigorous and legitimate
- I want to know who is behind FW
- I want to know where I can learn more

**Comment by rufuspollock** [comment]
@nathenf fine under `learn`.

**Comment by ZybN** [comment]
Page is live here: http://www.lifeitself.org/learn/fundamental-wellbeing
Template in Obsidian not created yet, I will finish and close it this week.

**Comment by nathenf** [comment]
FIXED - fundamental wellbeing page created at https://lifeitself.org/learn/fundamental-wellbeing and added to the homepage. Template for learn pages not yet defined, but not a priority right now.
