### ISSUE TITLE
Create Youtube video and blog for the Alex Goodall Community Call

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#453]
Raw Recording: https://us02web.zoom.us/rec/share/3EEiaSDQ2qvzCD1DV-DWE39-_bIeZteZewvL8aVzuR5uRHDZdO3VE0Gf81iojbpv.6J2_Yi5lGF3ShQOe 
Passcode: xUw9=48Z 

## Acceptance

- [x] [Youtube video](https://www.youtube.com/watch?v=P0ZL-lFyXoc) and [blog post](https://lifeitself.org/blog/2023/04/25/the-relevant-education-project) live ✅ 
- [ ] Shared in community chat and on Twitter

## Tasks

- [x] Create Youtube Thumbnail 
- [x] Clip video in DaVinci and add the thumbnail at start to fade in
- [x] Write caption/blog article to include:
  - [x] Introduction to the call
  - [x] Call to action - join the community
  - [x] Information about Alex and his project
  - [x] Key takeaways
  - [x] Also link to any resources or people mentioned (Martin Shaw, TLLP.org, Ian Mcgilchrist, The Nordic Secret, Roslings book
- [x] Upload video to Youtube and include caption. Add chapters to break the presentation and discussion. 
- [x] Upload to blog including embedded video
- [x] Share in community chat
- [ ] Create Twitter Thread

**Comment by ZybN** [comment]
The last task is to upload the blog article regarding the call.

**Comment by ZybN** [comment]
Not shared on Twitter and with Community yet.

**Comment by nathenf** [comment]
@ZybN I shared in community chat so just got to do Twitter now!

**Comment by nathenf** [comment]
FIXED - Community call completed and added to Youtube and shared on our blog and in the community
