### ISSUE TITLE
[inbox] Website fixes

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#454]
## Tasks

- [x] Initiatives pages: change date created to start and end date for the initiative template **✅ 2023-05-04 [85e4640](https://github.com/life-itself/community/commit/85e46405be9b52454972aaa9be792cc1fe533228)**
- [x] Feature images not showing up when blog posts and residencies are shared on social media **✅ 2023-06-05 commit https://github.com/life-itself/community/commit/6dec949b33feff60e0025be4b26b29629ab05d64**
- [x] Ken Wilber feature image should be changed to something less creepy
- [x] link from Praxis hub in Primacy of being post article is not working  ( it is also not signed )
- [x] ➕2023-05-14 https://lifeitself.org/blog/2018/06/22/synthesis-and-the-middle-way does not show up ie. 404s (but is in repo) - probably a build error or some kind. 
- [ ] Don't show image at top of blog posts automatically ... so that i can a) choose to have an image or not b) choose where to put it (e.g. after the lead paragraph). Downside of this change is you have to consciously add the image but don't think that is that big a deal. **Not a priority**

**Comment by nathenf** [comment]
Hey @khalilcodes a few outstanding things here, which we discussed in our call. Do you think you could finish these early next week?

**Comment by khalilcodes** [comment]
@nathenf 
> Feature images not showing up when blog posts and residencies are shared on social media

This is blocked atm as a bug with flowershow websites https://github.com/datopian/flowershow/issues/498

**Comment by theo-cox** [comment]
@nathenf @khalilcodes I've just added a dead link flagged to us by a visitor (https://lifeitself.org/2022/03/11/mapping-metamodern-what-is-metamodernism/)

**Comment by nathenf** [comment]
FIXED - Priority tasks complete. One outstanding task about blog post images. This can be taken up as a separate issue when necessary, but is not a priority

**Comment by rufuspollock** [comment]
@nathenf an inbox task generally just stays open forever - it is a collector task with specific items either getting done preferably becoming issues ...

**Comment by laurenwigmore** [comment]
@khalilcodes we noticed a few issues with the Life Itself website. 
- The search bar doesn't work - we were trying to locate an older blog post and nothing we typed in produced any results
- On the blogs page after a certain number of blogs the scrolling option stops, Ideally a user would be able to scroll through them all

**Comment by laurenwigmore** [comment]
@khalilcodes Hey Khalil, can you give us an update on when you might be able to look at the above issues please?

**Comment by nathenf** [comment]
@olayway this is our inbox for ongoing website issues we want to get fixed

**Comment by olayway** [comment]
@nathenf, @laurenwigmore While working on the new blog layout, I've noticed a lot of inconsistencies in the styles of different parts of the website, e.g. in spacing, font styles/sizes/weights, or buttons used. I'm addressing some of these issues along the way (primarily related to spacing) but it would be good to look into this in the future (especially on the home page).

**Comment by olayway** [comment]
> Actually we want all urls to be in the format lifeitself.org/blog/title and remove the dates

@nathenf, @laurenwigmore This was mentioned next to some unrelated issue with broken links that include trailing slashes (can be fixed with the pending PR). Can you confirm if this is really needed?

**Comment by laurenwigmore** [comment]
> > Actually we want all urls to be in the format lifeitself.org/blog/title and remove the dates
> 
> @nathenf, @laurenwigmore This was mentioned next to some unrelated issue with broken links that include trailing slashes (can be fixed with the pending PR). Can you confirm if this is really needed?

Honestly not a clue Ola. My guess is that they are there to give an insight into the theme under the category they sit. Are there many like this? Personally, unless the tags are already in the categories list, I would ignore them if it doesn't cause problems, as I imagine these are only on a handful of older posts from years ago.

**Comment by laurenwigmore** [comment]
> @nathenf, @laurenwigmore what are the tags used for? E.g. here at the bottom of the page. https://lifeitself.org/blog/2020/12/19/word-laundrette-1-nirvana How are they different from categories?

Honestly not a clue Ola. My guess is that they are there to give an insight into the theme under the category they sit. Are there many like this? Personally, unless the tags are already in the categories list, I would ignore them if it doesn't cause problems, as I imagine these are only on a handful of older posts from years ago.

**Comment by laurenwigmore** [comment]
> @nathenf, @laurenwigmore While working on the new blog layout, I've noticed a lot of inconsistencies in the styles of different parts of the website, e.g. in spacing, font styles/sizes/weights, buttons (shadow, no shadow, big, small etc.) or categories links (underlined lowercase, not underlined capitalized, with hashtag, without hashtag etc.) used. I'm addressing some of these issues along the way (primarily related to spacing) but it would be good to take a closer look at it in the future (especially on the home page) because the site looks a bit messy IMO.
> 
> Also, should the collaborators be linked? Atm the URLs are empty, so the site just reloads upon clicking on them.

maybe this should be set up as a separate issue?

**Comment by laurenwigmore** [comment]
@olayway re: the blog posts slug (and removing the dates). Are you able to start work on this, so that moving forward we post without the date in the slug? previous posts can stay as they are.

**Comment by rufuspollock** [comment]
@laurenwigmore i don't think any technical work is needed here so i think we remove that last comment to reduce noise in ola inbox 😉 (and then i can remove mine).

**Comment by laurenwigmore** [comment]
> @laurenwigmore i don't think any technical work is needed here so i think we remove that last comment to reduce noise in ola inbox 😉 (and then i can remove mine).

Sure no problem, my only question for you and @nathenf is to confirm that we just adding each blog with its title now under the Blog folder, outside of any other dated folders? And this will just publish without any issues? 

I've deleted my earlier comment for Ola.

**Comment by rufuspollock** [comment]
> Sure no problem, my only question for you and @nathenf is to confirm that we are just adding each blog with its title now under the Blog folder, outside of any other dated folders? And this will just publish without any issues?

Yes that is correct. PS: we need to be careful that an inbox issue does not become a real issue ... as we decide to do things from an inbox issue we should pull them out into actual issues.

**Comment by rufuspollock** [comment]
I think it is a priority to review this and clean out stuff we won't do and select items which are to be done ...
