### ISSUE TITLE
Post up research community open call 2023-04-14

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#461]
We want to post up the [recording](https://drive.google.com/file/d/18Xn93qJ16JdSMRayLhjcGQw--_NgXOgr/view) of our first research community call. This can be similar to our general community call see e.g. #453.

- We had our first (rebooted) research community open call on 2023-04-14.
- In the call we had an introduction to the community and some background on a potential research program.
- Be great to share this so others have the material

@mattosborn you can liase with @nathenf @Zybn for help here

## Acceptance

- [ ] Call is on youtube
- [ ] We have a blog post (embedded video, short context, invitation to come to next calls)
- [ ] Shared on community and social media

Bonus 🏆

- [ ] Transcript of overview part of call nicely proof-edited (and add to blog post)

## Tasks

See e.g. #453 for inspiration

**Comment by mattosborn** [comment]
I just had a chat with @nathenf & @ZybN.

@rufuspollock The only blocker is not being able to download the video from the drive link. Does this require explicit download permissions to be granted?

**Comment by rufuspollock** [comment]
@mattosborn fixed the permissions - you should be able to download now (had it as commenter rather than editor before).

**Comment by ZybN** [comment]
Hi @mattosborn here is a design template for the community call: https://www.canva.com/design/DAFhFmp_hf8/4IZ-djrREsuHdxr1L03rTg/edit?utm_content=DAFhFmp_hf8&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

If you dont have access to Canva then let me know.

**Comment by mattosborn** [comment]
Thanks @ZybN, I have access now.

On the design template: I don't think these open calls will necessarily be structured around a guest presenter like the community calls are, in which case it might be better to have a more generic design template.

And for the video timestamps:
- 0 – Introduction
- 1m57s – Presentation
- 24m09s - Questions and discussions

Did you also get download access to the recording?

I've created a draft PR here #478 if you could take a look.

**Comment by rufuspollock** [comment]
@mattosborn draft PR is great.

@mattosborn i could also get you access to youtube so you could upload (probably will have more stuff in future for research!)

**Comment by rufuspollock** [comment]
FIXED. See https://lifeitself.org/blog/research-community-open-call-1-april-2023
