### ISSUE TITLE
Homepage: Add Team Members to homepage

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#491]
Split from #335 

So that people know who we are/reputation

## Acceptance

- [ ] Homepage has a team section which features 3 team members and a call to action to view the people page

## Tasks

- [ ] Decide on team members to include
- [ ] Write a sentence about the team and the call to action
- [ ] Add to the homepage

**Comment by nathenf** [comment]
NOT-FIXED - I don't think this is a huge value add to the homepage as people naturally exploring the about page.
