### ISSUE TITLE
Write our story 

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#492]
Split from #335 

We want an updated version of "Our Story" including who, what, when, where, how, why so that people can concisely understand the essence and existence of Life Itself. 

## Acceptance

- [ ] Story is written in short form (for homepage) and longer form (for about page)
- [ ] Homepage and About page updated to include our story content #413 

## Tasks 

- [ ] Write Job stories for the story section
- [ ] Create wireframe for story
- [ ] Write story in short form and long form
- [ ] Update homepage 
- [ ] Update about page #413

**Comment by laurenwigmore** [comment]
@rufuspollock thinking this and the interviewing of you and Sylvie could be a good project whilst I am with you both in June/July.

**Comment by rufuspollock** [comment]
We never did this 😢 - was it on your list? For now i think we wontfix this ...

**Comment by rufuspollock** [comment]
WONTFIX. We can come back one day ...
