### ISSUE TITLE
Post Equality Complex Talk from Untitled Festival

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#512]
Post the Equality Complex Talk from Untitled Festival Sept 2020 - presented by Liam.

## Acceptance
- [x] Talk is posted with a short simple introduction
   - [x]  dated to just after the event
- [x] Video on youtube ...

## Tasks
* [x] Locate talk **located and timings below**
* [x] A completed back-post on the blog on the website **completed link [here](https://hackmd.io/@9338DWdPRD6L_MSAuk8p3g/rk15rqBEn)** 
   * [x] dated to just after the event
* [x] Upload to Youtube channel **previous issue resolved - noted on [issue 13](https://github.com/life-itself/onboarding/issues/13) video to be uploaded with video starting from relevant time stamp 40.07**
* [x] Embed into post
* [x] Have transcript available under the post and video **Transcript done basic review/edits completed - [link](https://otter.ai/u/mbwa8KtauCi2z7_DmxD8BtTR6ZQ?utm_source=copy_url)**
- [ ] Get Liam's slides

### Notes
To follow structure of [issue 13](https://github.com/life-itself/onboarding/issues/13)

**Comment by laurenwigmore** [comment]
@rufuspollock 
Recording notes (bold parts suggested to use)
~0.21-19.48: is the intro and up to where you break into groups
19.48-24.28: breakout groups (not useful)
24.28: Re-group and continue discussion~
**40.07: Equality of Being talk starts
48.02: Wider Qs/discussion on EoB**
1.11.40-1.20: Wider introduction to LI

** As mentioned on #13 it was mentioned to the participants these recordings would not be shared publicly**

**Comment by laurenwigmore** [comment]
PR request didn't build once changes made. Will re-open and resubmit.

**Comment by laurenwigmore** [comment]
FIXED - will add in Liam's slide as and when received.
