### ISSUE TITLE
Essay on Politics of Being - Untitled Festival 

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#513]
Write an essay encapsulating the key themes/discussion points from the Politics of Being - Untitled Festival talks, presented by Rufus and Sylvie in Sept 2020

### Acceptance
- [ ] Essay is published on LI website 

### Tasks
 - [ ] Review talks / read appropriate slides/documents
 - [ ] Complete [SCQA aka Clear Thinking quadrant exercise](https://scqa.lifeitself.org/)
    - [ ] Complete below context
    - [ ] Complete below outline
 - [ ] Conduct any additional research/reading arising from the above and note below for reference
 - [ ] Draft first essay in [hackmd](https://hackmd.io)
 - [ ] First draft reviewed and then edits/feedback completed
 - [ ] Finalise draft and publish

### Context
To be added

### Outline
To be added

### Notes
Day 1 video [here](https://drive.google.com/file/d/1-y1on9q-xQc1IOu-AFPKAQIe9pGS8TRv/view?usp=sharing)
Day 2 video [here](https://drive.google.com/drive/folders/1HRRnKsw_1m6Atq0XrRqT5wltw-kPfyH7) 
Shorter blog posts are/will be available soon [Issue 13](https://github.com/life-itself/onboarding/issues/13) - links to slides and docs in this issue also
