### ISSUE TITLE
Create Youtube video and blog for the Dion Community Call

### ISSUE THREAD

**Issue by ZybN** [life-itself/community#514]
## Acceptance

- [x] Create Youtube and Blog Post ✅ [Link Here](https://lifeitself.org/blog/2023/05/15/knowledge-management-community-call)
- [x] Shared in community chat and on Twitter  ✅ [Tweet Link Here](https://twitter.com/forlifeitself/status/1663874204469698560?s=20)

## Tasks

- [x] Create Youtube Thumbnail 
- [x] Clip video in DaVinci and add the thumbnail at start to fade in
- [x] Write caption/blog article to include:
  - [x] Introduction to the call
  - [x] Call to action - join the community
  - [x] Information about Alex and his project
  - [x] Key takeaways
  - [x] Also link to any resources or people mentioned (Martin Shaw, TLLP.org, Ian Mcgilchrist, The Nordic Secret, Roslings book
- [x] Upload video to Youtube and include caption. Add chapters to break the presentation and discussion. 
- [x] Upload to blog including embedded video 
- [x] Share in community chat
- [x] Create Twitter Thread

**Comment by nathenf** [comment]
@ZybN is this complete?

**Comment by ZybN** [comment]
This is complete, I haven't created a tweet for this. otherwise, this is complete.

**Comment by ZybN** [comment]
COMPLETE ✅ 

LINKS: 
Blog Post ✅ [Link Here](https://lifeitself.org/blog/2023/05/15/knowledge-management-community-call)
Twitter  ✅ [Tweet Link Here](https://twitter.com/forlifeitself/status/1663874204469698560?s=20)
