### ISSUE TITLE
Comms Iteration w/c 01 May 2023

### ISSUE THREAD

**Issue by ZybN** [life-itself/community#515]
Total hours spent: 
- Nathen: 
- Khalil: 
- Zaib: 30

Expected Hours: 
- Nathen: 
- Zaib: 30
- Khalil: 

## Acceptance
- [x] Conduct Community Call with Sylvie @nathenf 
- [x] Post Youtube and Blog article-Dion @ZybN 
- [x] Update all Podcast Pages @ZybN 

## Tasks 

- [x] Conduct Community Call with Dion ✅ https://lifeitself.org/blog/2023/05/15/knowledge-management-community-call
- [x] Convert the Call into Youtube Video & Blog Post [Issue](https://github.com/orgs/life-itself/projects/2/views/7?pane=issue&itemId=27591110) 
- [ ] Work on the Obsidian Guide https://github.com/orgs/life-itself/discussions/393 @nathenf ❌ 
General Comms: 

- Fix the image of the Research Community Call 👍 There is no image on the blog anymore 
- Give a summary of Fundamental well-being to Rufus ✅  [Fundamental Wellbeing Issue](https://github.com/life-itself/community/issues/395)- [Live Page ](http://www.lifeitself.org/learn/fundamental-wellbeing)
- Ask Rufus: Do we need to Create Learn page for Conscious Parenting 🚧 Hasvn't asked yet. 
- Find Blog post for Call with Brandon Graham (look for date of the podcast-June 2022) ✅ Done-[Added to podcast page](https://lifeitself.org/podcast/Brendan-Graham-Dempsey--Nathen-Fitchen-on-The-Meaning-Crisis--Metamodern-Spirituality)

## Updates on Podcast Pages 
Podcast Page Updates/Blockers: 

- [x] Podcast page for Fundamental Wellbeing Podcasts ✅ ([Part 1](https://lifeitself.org/podcast/a-scientific-approach-to-awakening-and-fundamental-wellbeing-podcast), [Part 2](https://lifeitself.org/podcast/a-scientific-approach-to-awakening-and-fundamental-wellbeing-part-2-jeffery-martin), [Part 3](https://lifeitself.org/podcast/a-scientific-approach-to-awakening-and-fundamental-wellbeing-part-3-jeffery-martin) 
- [x] Podcast Page for Thomas Steininger and Joseph Henrich ✅ Updated- [Thomas Steininger](https://lifeitself.org/podcast/thomas-steininger-on-emergent-dialogue), [Joseph Henrich](https://lifeitself.org/podcast/joseph-henrich-and-the-emergence-of-culturology)
- [x] Podcast page for Conscious Parenting Series ❌  (Blog content not found)
- [x] Podcast page for Exploring Social Transformation Series 🔴 None of the links are working https://lifeitself.org/podcast/Exploring-Social-Transformation-Series-Wrap-Up

**Comment by ZybN** [comment]
@nathenf Please check Updates on podcast pages. 

Closing this Issue. 
All tasks completed
