### ISSUE TITLE
Add Life Itself Hubs on Google (Maps) - just Farmhouse remaining

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#54]
Thenac hub is already on google maps 

Would be good to add Berlin and Bergerac.

![image](https://user-images.githubusercontent.com/180658/134497851-2fb78ca7-90fb-4a94-b056-7668e4f1e3cf.png)

## Acceptance

* [x] Berlin hub listed on google and search for life itself berlin shows it **Done - https://goo.gl/maps/T8Hv2J42nLBvoQn36**
* [x] Bergerac hub listed
* [ ] Current Bergerac Hub relisted as "Life Itself Farmhouse - Plum Village" **Requested address change for Thenac, as this listed as the Bergerac Hub**

## Tasks

* [ ] ...

**Comment by theo-cox** [comment]
@rufuspollock adding waiting for label until I hear back from Google

**Comment by theo-cox** [comment]
Update: need to verify this is our business to update. Awaiting something to verify in the post...

**Comment by rufuspollock** [comment]
@theo-cox any update here - this is important for the residency arrivals ...

**Comment by theo-cox** [comment]
@rufuspollock if the postal confirmation form hasn't arrived to you at the Hub then we can't verify ownership and unilaterally change. I've suggested a change to maps as a non-owner now so hopefully that will be sufficient. If it's not I will attempt to phone them from France

**Comment by rufuspollock** [comment]
When would this post have arrived at the "hub" (and which hub)?

**Comment by theo-cox** [comment]
It should have arrived at the Bergerac Hub (townhouse) at some point during December. I have just reordered as it takes up to 5 days and I will be here for that time to receive it.

**Comment by theo-cox** [comment]
In the interim. my request to change the address has gone through, so the address is now correct. Just waiting for them to update the photo to the new one I uploaded (as it still shows the farmhouse)

**Comment by rufuspollock** [comment]
Great - and can we get the Thenac Hub Listed - maybe as Life Itself Thenac
or Life Itself Plum Village (?)

Rufus
--
t: +33 670852582 / +44 7795 176 976
Pragmatic Utopian - https://rufuspollock.com/
Co-Founder, Life Itself https://lifeitself.us/
Founder and President, Datopian https://datopian.com/
Shuttleworth and Ashoka Fellow
*My book The Open Revolution: rewriting the rules of the information age
<https://openrevolution.net/>*

**Comment by rufuspollock** [comment]
@alexianetcu how did you get on here - did you find login details for this?

**Comment by rufuspollock** [comment]
OK, by chance just got a reminder

![Image](https://github.com/life-itself/community/assets/180658/f81103b5-1a83-493d-a1ea-997f86a24f74)


Here's the link to click:


https://business.google.com/locations?trk=https%3A%2F%2Fnotifications.google.com%2Fg%2Fp%2FANiao5pndRZ9bZREzynJhNLRbcNO-v2Srh_2kFUhmkaPNO5xFr3wajRepIzJDn6E6Wzaaoq4g_tsYg_76UjiiSQZtM6G4xBsrVsURhImV0mlydmirJ7s6GncLCwQKm_DEbYgRW4_rexPjC7uxd8sQ7eruyoGL2oU6o_xJm1xh5yR4nD4JX90MQvhdN-DOmfumZbdyapPqd8

I've just confirmed thenac.

**Comment by rufuspollock** [comment]
FIXED. (Assuming verification is ok).
