### ISSUE TITLE
Announce First Research Community Hackathon / Collabothon: 3rd June 2023

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#543]
Have a hackathon where a) existing team have work time together to ship something b) new people can get involved and connect 

- In person at Bergerac and online
- Contributing to and aligned with the draft research program of the community

### Outcome visioning

10+ people having a great time, 5 projects and we ship at least 3 published reading lists and have the infrastructure for doing more in ongoing collaborations.

## Tasks

- [x] Create a blog post
- [x] Create Google form for registration
- [x] Create draft brief for reading lists project

### Questions

- [x] Data collection
  - [x] Who can attend & when?
  - [x] What skills do attendees have that they can share?
- [x] Sharing the event
  - [x] Where do we share?
- [x] How many days (core day)
- [x] In person vs online
  - [x] In person where
- [x] How do you register?
- [x] Is this invite only or an open event?
- [x] Naming: makeathon, collabothon, hackathon

# Meetings

# 2023-05-12

Present: Matt, Rufus

Intention: create a plan for the june LIRC hackathon event and a draft blog post so that we know next actions and can start sharing

Agenda

- [ ] 👋 Check-in
- [ ] 🥳 Plan Event - https://github.com/orgs/life-itself/discussions/466
- [ ] Draft landing page
- [ ] ⏭️ Check-out and next actions
  - [ ] Matt: draft the blog post?
  - [ ] Matt: draft brief for reading lists project

# Background in https://github.com/orgs/life-itself/discussions/466

<div type='discussions-op-text'>

<sup>Originally posted by **rufuspollock** April 21, 2023</sup>
Organize a [research community](https://lifeitself.org/research) hackathon in the next 3-4 months. Hackathons are a great pattern we could adopt as a way of crystallising activity and community.

> A hackathon (also known as a hack day, hackfest, datathon or codefest; a portmanteau of hacking and marathon) is an event where people engage in rapid and collaborative engineering over a relatively short period of time such as 24 or 48 hours

**UPDATE 📣: 28 April**: date chosen for the event Saturday and/or Sunday 3rd/4th of June.

### 📣 Suggestions wanted!

We're brainstorming around the following questions (and please add more**

- **What (topics)?**: 🚧 **see brainstorm below 👇**
- **Who**: all welcome!
- **Facilitators**: Rufus and Matt volunteered to co-organize. Others welcome.
- **Where**: online and at [Bergerac Hub](https://lifeitself.org/hubs/bergerac) or nearby
- **When**: Sat/Sun 3rd and 4th June 2023  ~~probably a weekend some time in next 3 months (i.e. may / june / july 2023)~~
- **Naming**: this isn't really a hackathon (we aren't coding and we aren't rushing to get somewhere!). Alternative names wanted!

### Topic shortlist

Culled from suggestions below

- **High-level knowledge map**: An interactive knowledge map viz that ties together topics of focus within Life Itself.
  - Attempting to serve the Q: _"What topics is Life Itself interested in?"_ and _"What topics are adjacent or related to X?"_.
  - Inspiration: [Life Itself research topical map](https://github.com/life-itself/community/blob/914addc2405ff1e7eff1d3f28e6db6ed87a8240c/content/excalidraw/research-topical-map-2023-01-14.excalidraw.svg) / [xiq's knowledge map](https://pbs.twimg.com/media/Fa2M570WIAA7USi?format=png&name=4096x4096)
- **Reading lists / learning resource curation**: A framework for organising learning resources for newcomers to a particular topic, i.e. books, papers, videos, podcasts, thinkers, etc. This could also be integrated with a knowledge map.
  - Attempting to serve the Q: _"How can I learn about topic X as a newcomer?"._ and _"What are the canonical texts for topic X?"_
  - Inspiration: [user-generated reading lists](https://placesjournal.org/reading-lists/) / [notion reading lists](https://parameter.io/notion-reading-list-templates/) / [roadmap.sh](https://roadmap.sh/system-design) / [healthygamer.gg](https://user-images.githubusercontent.com/960919/234788298-d2ef94a1-c7ae-4f7a-b108-19128f448cc1.png)
- how to analyze data (surveys, interviews before and after coliving experiences) quantitatively or qualitatively, e.g. some of the notebook example is here https://github.com/Liyubov/community/tree/master/research/notebooks we started to discuss it with Marc as well, as he has experience in quantiative measures, survey design etc.
- related to space of coliving, we started to also map coliving space e.g. here https://github.com/Liyubov/community/blob/master/research/README.md based on discussions we had with Penny Clark from CC (consious coliving), happy to invite her for this
- Inner development guide / directory could include library of papers, literature review, visualization of key streams of work
- Textual analysis of political manifestos to analyze their cultural worldview
- Write up of cultural values work by e.g. Schwartz, Inglehart et al
- Guide to conscious communities and coliving
- Directory of exemplar intentional communities
- Prototype research program about intentional communities and what makes them work or not </div>
