### ISSUE TITLE
May Newsletter

### ISSUE THREAD

**Issue by ZybN** [life-itself/community#560]
## Acceptance 

- [x] Newsletter is sent

## Tasks

- [x] Create a Newsletter 
- [x] Test Newsletter
- [x] Send Newsletter

## Notes 

- [x] Community Calls - With Dion Shattuck: https://lifeitself.org/blog/2023/05/15/knowledge-management-community-call
- [x] Upcoming Community Calls: With Sylvie and Life Itself Research Hackathon
- [x] Upcoming Residencies: https://docs.google.com/document/d/12vUk_klDejMZ6wjmGIZxao1GZfsAtB18FY1T8lIagSQ/edit?usp=sharing
- [x] Tenzo Note 7: https://lifeitself.org/blog/2023/05/28/tenzo-note-7

**Comment by ZybN** [comment]
DONE: Newsletter Sent-Preview link of Brevo (SendinBlue) here: https://my.brevo.com/camp/preview/id/41
