### ISSUE TITLE
Comms Iteration w/c 29th May-11th June

### ISSUE THREAD

**Issue by ZybN** [life-itself/community#562]
# Goals

- [ ] Publish stuff
  - [x] Community Call with Sylvie Barbier 
  - [ ] "Pioneers" podcast series: Upload Podcast with Jamie Bristow - ❌  NOT FIXED this should be created into a full issue
- [ ] Contributors Guide with Datopian
- [ ] Skeleton for #566 - ❌  Rolling over to next Iteration
- [ ] #569 - 🚧 Talk complete, needs to be process and promoted in the next iteration

---

## Capacity for Iteration

- Nathen: 6h
- Zaib: 25 Hours **Zaib reduced hours to zero for the next weeks**
- Lauren: 50h
 
---

## Actions

AOB

- [ ] Contributors Guide with Datopian Team
  - [x] Create Skeleton in Coogle 
  - [x] Create a sandbox **Repo: https://github.com/datopian/flowershow-sandbox; Deployment: https://flowershow-sandbox.vercel.app/**
  - [x] Write a draft **https://hackmd.io/qAJFi0O0Q9G4ZubeSCet9g?edit**
  - [ ] Write the content (no screenshots in this step yet)
  - [ ] Try it out and adjust if necessary
  - [ ] Improvements
    - [ ] Screenshots
    - [ ] Video (you have the script already with the tutorial)

---
---

# Meetings

# 2023-06-01

Present: Rufus, Lauren, Nathen

Intentions: planning the next sprint up to a month. Getting ourselves connected with the bigger picture.

- [x] Reconnections e.g. nathen back, lauren and nathen etc
- [x] Groomed backlog **✅2023-06-01 ❌ not really, created new items**
- [x] Sprint issues **🚧2023-06-01 created two new epics**
- [x] Bigger picture **✅2023-06-01 good discussion. two clear focus areas right now**

Agenda

- [x] 🧘 meditation
- [x] 👋 Check-in
- [x] 🎯 Set intention
- [x] 📝 Create agenda
- [x] 🏃‍♂️ What happened whilst nathen was away **✅2023-06-01 did newsletter. shipped diginomics, website editor guide in progress etc**
- [x] Big picture https://link.excalidraw.com/l/9u8crB2ZmUo/5JRFK7pQSDO
  - [x] Resolve 🎾 about changing strategy. **✅2023-06-01 lessons are a) Have someone full-time or close to full-time in comms b) Rufus has focused time in bigger specific chunks c) Finalize the v3 strategy**
- [x] 🏃‍♂️ Near-term strategy and backlog grooming see e.g. board and backlog https://github.com/orgs/life-itself/projects/2
- [ ] ⏭️ Next steps
  - [ ] Make a note that at some point (30-40m in did a bunch of explanation of theory of change again 📹. TODO: turn this into an animation / writeup that we can publish)
- [x] AOB
  - [x] 📆2023-05-31 Jonathan Reams research community event on June 9th 2023 - promotion and signup - see Context https://github.com/orgs/life-itself/discussions/435#discussioncomment-5653189 **✅2023-06-01 see the issue https://github.com/life-itself/community/issues/569**
  - [x] Community sessions **✅2023-06-01 briefly touched on. For now nothing that important and can go slowly**
- [x] 👋 Check-out

## Nathen's note 

We need to have comms for sharing and promoting but also for adding value.
- Shelf-life of twitter content is low (like hours)
    - Therefore repetition and high-quanity, but low effort works best
    - Break down of content we already have 
    - consistent retweeting 
- Youtube is better
    - Creates a body of work we can refer back to
- Right now if we build this email course for conscious coliving and breakdown from that
    - A10 for wiser has a lot of good process and ideas in it, which can relate to conscious coliving (should look into this)
- Question: In this lull moment should we take the time to build an offer first before focussing efforts on comms? 
    - Yes, so we can be more consistent when we begin

### Big picture discussion

See call recording around 40m mark (??) plus https://link.excalidraw.com/l/9u8crB2ZmUo/5JRFK7pQSDO

- 3 levels of ways to engage:
  - Research collective
  - Courses and incubator
  - Sangha
- Three levels of an audience those:
  - generally interested
  - sangha involved
  - sangha/shambhala warriors
- how to engage the sangha's who are doing their own projects
  - scarcity is resources and attention
  - aim we want to be around long enough so that people can in join our group and give up on there own eventually
- where/how can people get very involved with Life Itself - currently there are very small avenues in
- current issue connections/contacts are lost/dropped - poor funnel
- People come for residencies but what's the next step . . . no follow upv after - currently hub is empty and it is the key time (May/June)
- Actual goal of LI: now: produce online courses/material that brings more people into the middle of funnel
  - i.e. conscious community course, or email course
  - better newsletter use
- Aim for greater presence e.g. email list of interested people, more twitter followers on LI account

**Comment by nathenf** [comment]
@laurenwigmore can you update on the Contributors guide here and close the issue? With a summary of work done and completion?

**Comment by laurenwigmore** [comment]
@nathenf 
Sure. I haven't worked on the The Contributors Guide, only the Editors Guide the Datopian Markdown Sprint,  so I can't really share any information on it. Perhaps its better to wait until @ZybN can update.

**Comment by nathenf** [comment]
DEPRECATE - Old iteration which should be closed
