### ISSUE TITLE
Community Call with Sylvie Barbier

### ISSUE THREAD

**Issue by ZybN** [life-itself/community#563]
The last community call with Sylvie is being recorded and the recording will be available in few hours. 

## Acceptance

- [x] blog post with a youtube video embedded is created ✅  [Link of Blog](https://lifeitself.org/blog/2023/05/19/sylvie-barbier-second-renaissance) and [Youtube Link](https://www.youtube.com/watch?v=dg_cG4AqIHI)
- [ ] #588

## Tasks

- [x] Write introduction to the video using the text in the youtube description
- [x] Create blog post including youtube video embed, introduction and link to Whatsapp community

**Comment by ZybN** [comment]
The blog and youtube video is live, next step is to share them with the community.

**Comment by nathenf** [comment]
FIXED - #588 is a follow-up on this issue
