### ISSUE TITLE
[epic] Conscious Community Living Course

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#566]
3-5 session course free email course (with 1 day trailer and optional 2 session bonus). also can present as ebook/pdf and/or long post.

[Coggle of skeleton](https://coggle.it/diagram/ZJCEkWO5NHMGoe06/t/conscious-coliving-email-course-v-01)
[Conscious Coliving Course Document v.02](https://docs.google.com/document/d/12paZt8ZwPomkDkyaLG_8KDNaQTIiaplQey6sQpR9SVE/edit?usp=sharing)
- Strategy #636
- Content calendar #657 
-  A10 #257 
- where do we go from here

## Purpose and principles

Provide accessible, introductory course to learn about conscious coliving and more generally living more intentionally and in community.

Secondarily

- Entry point to discover Life Itself residencies and other consious coliving opportunities (and prep for those)
- Discovery point for Life Itself and our work and educational materials for a specific aligned audience (i.e. those interested in more conscious (co)living, community etc)

## Who is it for?

3 core audience personas (12.30-13mins)
1. Already living or close to coliving and want to become more conscious
2. Those living atomistically who want to colive more
3. Those who want to start a full on intentional community

## Outcome visioning

To have a regularly attended course which is seen as a go to resource for coliving principles and practices utilised by both individuals and organisations to support them to live more consciously with others. We have a high completion rate and people report being more inspired to live in community within the next 6 months (after comleting the course). 

Key metrics within 6 months: 
- 150 number of course attendees
- 30% completion rate (aka % of last email open rate)

Secondary:
- 5 other websites backlinking to our resources or posting about it on socials (use consciouscoliving.com collabs page as a reference point)
- Increased attendance to residencies due to interaction with the course (In form for applying, how did you find out about Praxis Hub add the course as an option)
- Direct positive feedback after the course (via feedback form)
- 30% click through rate to Whatsapp group in the Day 0 email
- Be ranked on 1st or 2nd page of Google in relation to Coliving tag
  - Especially Coliving + term searches e.g. "Coliving community", "What's the criqitue of coliving" "Intentional Communities" etc

## Acceptance

- [x] Full Draft of Course - see [Conscious Coliving Course Document v.02](https://docs.google.com/document/d/12paZt8ZwPomkDkyaLG_8KDNaQTIiaplQey6sQpR9SVE/edit?usp=sharing)
- [x] Course in system and online
  - [x] Brevo
  - [x] Landing page(s) - #607
 [initial sign up form here](https://app.brevo.com/contact/forms/subscription/edit/6495dac04e3c752fca63dc02)
- [x] Launch strategy created
- [x] Launch implemented
- [x] 150 people sign up to the course
- [ ] French translated version available August 2023

## Tasks

- [x] Draft skeleton of the course e.g. heading for each day and bullet points for sections [Coggle](https://coggle.it/diagram/ZJCEkWO5NHMGoe06/t/conscious-coliving-email-course-v-01?utm_source=transaction&utm_medium=email&utm_campaign=retain) 
- [x] Review and revise
- [x] Draft
- [x] Setup course in system
- [x] Add offer to site (or create new site)
  - [x] Link this to the homepage so people can access from there #722 
- [x] Market
    - [x] Create ancillary content (breakdown into content, formats, hooks, etc.) #636 

## Next Steps / Paid Offering Brainstorm
- Video Course
  -  Conscious Conflict Management 
  - Understand your values
  - Something around loneliness/sense of belonging
- Masterclass
  - Understand your values
  - Introduction to Conflict Management
  - Authentic Relating
  - Paid MC (or series) with experts on CC related aspects
  - Free MC if show up live and paid if watching re-run
 - Summit (live for free and paid after)
  
### Questions

- [x] What's next at end of email course?
  - [ ] Potentials ...
    - [x] come to a residencies
    - [ ] in depth programme
    - [ ] group community
    - [ ] incubator (one day)

### Ideas to include
- Let's use a narrative or meme people are already used to AKA Friends (the tv show)
- Facts about people living alone. Why: isolation and mental health are rife
- Email topics: 
    - What is conscious coliving and Types of coliving situations (myths busted)
    - Benefits of coliving more consciously
    - What makes a good conscious coliving situation (and conscious coliver) and tools for conscious coliving
    - Bonus: How to find coliving situations
- How to live more consciously in life generally 
- Stories from people who have been to LI residencies and moved onto community living 
- Unless you live on your own, this course is for you 

### Demographic
People who are fresh to alternative living and are curious and apprehensive (aka have some skepticism about how it would suit them) about how to live in a community situation

- Wants:
  - Connection
  - Like-minded people sharing values
  - Belonging
  - Support and security
  - Health and wellbeing
  - Different pace of life
  - Deeper more conscious connection
  - Feeling more intentional

Nathen:
- I want to learn about conscious coliving so that I can find a place to live and people to live with
- I want to know the skills and resources of community livng so that I can excel in community living 
- Demographics:
    - People who are new to community living
    - Have tried community living, but it wasn't so good and want to find a better way to do it AKA conscious
    - Maybe dipped toes in retreats and short communal living situations, looking for something more permanent
    - Like the idea of community living but have a lot of concerns about how it fits into their lifestyle 
    - Probably not for people who already live in permanent community (but they may join out of curiousity)

Lauren:
- I am curious about living alternatively but I don't really know what that means / where to start
- I want to experience more community
- I want to live outside of a city in an already connected community
- I want to live more consciously in a city
- I want to set up a new community for likeminded people
- Demographics:
  - Those already living somewhat 'alternative'
  - May have tried communes, nomadic type lifestyles
  - Craving/want more connection 
  - Want to contribute to a community and the wider world 
  - Newer of people

## Budget

60 hours of our time for build of course
20 hours for primary launch
10 hours for website tweaks and a pop-up

11.5 person days $250 = $2875

## Coliving Skeleton (old - please refer to coggle from 2023.06.17)

- 3-5 email course
- Day 0 trailer
- Optional 2 session bonus 

How to be more conscious in coliving

 - Day 0: Welcome
     - Introduction
     - What the course includes
         - Day breakdown
     - Course goal (why do it or what you will gain)
     - Who is Life Itself
     - Actions
 - Day 1: What is conscious coliving and Types of coliving situations (myths busted)
     - What is conscious coliving? https://lifeitself.org/blog/2021/07/14/what-is-conscious-coliving 
     - What counts as coliving?
         - Family 
         - Partner
         - Your street
         - Houseshare
         - The workplace
         - Your village
         - Intentional communities 
     - Busting the myths of conscious coliving
         - All communities are sex cults
         - You have to share everything (including your toothbrush)
         - Communities are completely ostrasized from society 
         - Communities are not for normal people
         - You have to be spiritual
         - You have to be naked
         - You always have to do things for the "greater good"
         - You have to be a communist
         - People in communities are wierd and mentally unstable and are trying to escape the responibilities of life
     - Key takeaways and what is next
- Day 2: Benefits of coliving more consciously
    - Recap from Day 1
    - What are the benefits
        - Bluezones story: community is important to longevity
        - Greater support system
        - Less consumption of resources/less waste
        - Shared tasks
        - Deeper connections
        - Great for parenting - takes a village to raise a child 
        - Develop better social skills and have more empathy/compassion - moving away from polarisation, learning boundaries, manage conflicts
- Day 3: What makes a good conscious coliving situation (and conscious coliver)
- Day 4: tools and techiques for conscious coliving
- Bonus: How to find coliving situations
     - List of coliving directories 
- Bonus: All about intentional communities

**Comment by nathenf** [comment]
@laurenwigmore any motions on this yet?

**Comment by laurenwigmore** [comment]
@rufuspollock would you be able to view the skeleton Nathen and I have drafted [here](https://docs.google.com/document/d/1C7CRuVG6I6KEToKNzgZiKj1Kyw8AVwPcP8_rni-EkfI/edit?usp=sharing) and let us know any thoughts or feedback please?

**Comment by laurenwigmore** [comment]
Update - Nathen and I have completed
- [x] Finish outcome visioning
- [x] 3 core audiences distilled
- [x] Maybe test on group chat by asking?
And beyond

- [x] Finish the skeleton as a skeleton (in coggle link above)
- [x] Add a day 1
- [x] Compare to Ex: Start Writing Online

Next actions
-[ ] Lauren to begin drafting Day 0-2 (Monday)
-[ ] Nathen and Lauren to reconnect next week to finish expanded skeleton - Aim for Tuesday (approx.4 hours needed)
- [ ] Aim - first draft fully completed for review on 2023-06-21

**Comment by laurenwigmore** [comment]
@khalilcodes can we set up another landing page please, like we did for the Diginomics course? 

The suggested slug is https://lifeitself.org/conscious-coliving-course 

I've created the [form in Brevo](https://app.brevo.com/contact/forms/subscription/edit/6495dac04e3c752fca63dc02) for this. I wasn't sure how to create the page for this though. If you have time on Monday, could show me please? I'd need it live before the newsletter gets sent next week.

**Comment by laurenwigmore** [comment]
@nathenf 2023-06-23 update

- All days drafted (including Day 0 and Day 9), except for the Day 13 - Bonus day. I think it reads very strong, so it should be easy for you to review and tweak/comment as you see fit ahead of our meeting on Wednesday.
- There is 1 section I've tagged you in which would be good for you to extend on
- There are a few side comments I've added for us to consider/be aware of
- The sign-up form for those who want to register for the course has been created, I'll get this set up on the Life Itself website with Khalil on Monday (even if we are going to have it on a separate site as it hasn't been finalised and we want to reference it in the newsletter next week we'll need a sign up page, and later it can always be moved or used as a second entry point)
- [June's Newsletter blurb for the course has been written](https://docs.google.com/document/d/1vsuZWDAkdaR12kmbsNgRcIdvtPSF1tEJ7DlUfTE-mH8/edit?usp=sharing) feel free to review if you have time
- Marc has supplied two documents related to the Praxis Hub - these are listed at the top of the v.02 doc and the basic info incorpated
- [ ] I/we still need to create the feedback form

**Comment by laurenwigmore** [comment]
### 2023-06-29 & 30 Updates
- [ ] Automation
- Test Day 0 email sent. Note - not to add the long copy sign up form used in the newsletter or the course sign up tag so it doesn't trigger the automation whilst we are still finalising (although I've not activated it yet). The course sign up tag can be added after, and the long copy form will become obsolete in favour of the other sign up form button.

**Next actions from 2023-06-29 :**
- [ ] Build the landing page by end of next week [issue](https://github.com/life-itself/community/issues/607)
- [x] Create header images for each email
- [x] Set up automation :construction: only added day 0 until design finalised

**Next actions from 2023-06-30**
- [x] Brevo text - use different headings and bold in main body text (image in via Banner)
- [x] Can I create a standard footer? 
  - [ ] 🚩 Unsure how to amend the unsubscribe button to the custom one I've set up for the course...
  - [ ] Check social links in all days
- [ ] Review how frequently we use 'important' in day 1 
- [ ] run MVPs through chat gpt
- [ ] Find/confirm link to document with MVPs that can be inserted into day 6
- [ ] add note to issue about approaching directories from day 13 to advertise - add this into the marketing strategy doc once done
- [x] Add all days in to Brevo - day 13 not included - all to be reviewed
- [ ] Finalise day 13 content
- [ ] Send out to Life Itselfers for general feedback

https://www.canva.com/design/DAFnSpJa9Qg/j_cxs3ZJpkjj479XBsPuUA/edit?analyticsCorrelationId=dcbcb69b-b0ff-4cbb-990d-980d2d109a32

**Comment by laurenwigmore** [comment]
## 2023-07-03 Updates
- Test run of course set up and sent to Nathen and Zaib
- Some images still to be added on some days. There also seems to be an issue with the residency images I've inserted... 
  - [ ] ^ needs to be fixed
- [ ] I have set up a custom unsubscribe button for the course only but I can't figure out how to add this in place of the default one in the footer
- The pre-apply form for the newsletter has been amended 
- I've set up tags to be added to everyone who signs up and is sent the day 0 campaign
- Day 13 has been written and added and Day 6 updated with a better explanation of the MVPs - copy all in google doc & in the automation

**Comment by laurenwigmore** [comment]
### 2023-07-04 Update/ to do's 

- [ ] Nathen to review emails
- [ ] Create Landing page
- [ ] Send out to others for review (on Thursday 6th return Monday 10th)- Matthew, Jake, Catherine, Rufus - intentions are to get key-takeaways but not pinickety stuff. 
- [ ] Plan launch strategy and ongoing, lets have next meeting on this
- [ ] Lauren to work on other issues from yesterday's update

**Comment by laurenwigmore** [comment]
@rufuspollock do you have information you could share on the donation button you use so I can add this into the content? is it the same as the one that was on Diginomics Open Revolution book page (which is down btw with a 404 error and any book links link back to the Diginomics course not the OR book - I have messaged Khalil re this)?

**Comment by rufuspollock** [comment]
> @rufuspollock do you have information you could share on the donation button you use so I can add this into the content? is it the same as the one that was on Diginomics Open Revolution book page (which is down btw with a 404 error and any book links link back to the Diginomics course not the OR book - I have messaged Khalil re this)? 2023-07-24 update Ola is actioning the 404 and link issues.

We used donorbox for that i think. As i'm not sure of setup on that, i think worth setting something new up. Do note we have a stripe account already. I think this should be its own issue btw as setting up donation is probably something general we want to do.

**Comment by laurenwigmore** [comment]
> > @rufuspollock do you have information you could share on the donation button you use so I can add this into the content? is it the same as the one that was on Diginomics Open Revolution book page (which is down btw with a 404 error and any book links link back to the Diginomics course not the OR book - I have messaged Khalil re this)? 2023-07-24 update Ola is actioning the 404 and link issues.
> 
> We used donorbox for that i think. As i'm not sure of setup on that, i think worth setting something new up. Do note we have a stripe account already. I think this should be its own issue btw as setting up donation is probably something general we want to do.

Great, thanks, will set up new issue for this.

**Comment by rufuspollock** [comment]
@laurenwigmore i'd say we could close this epic now. wdyt?

**Comment by laurenwigmore** [comment]
FIXED.
