### ISSUE TITLE
Emerge 2021 including satellite stuff, material etc #29

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#58]
Emerge is taking place in Berlin and several members of community are attending and it is location of Life Itself Berlin Hub!

## Acceptance

* [ ] Materials 
* [ ] Attended event
* [ ] Satellite events at Berlin Hub
* [ ] Collated all relevant contacts
* [ ] 

## Tasks

* [ ] Coordination meeting with @theo-cox @IljaMaiber etc to understand plan ... (esp as @lkavanagh30 can't attend now)
* [ ] Event ideas
  * [ ] Ecosystem mapping (launch)
  * [ ] Intentional Developmental Spaces (and Conscious Collective Living)
