### ISSUE TITLE
Updating process for community and research calls

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#585]
When I plan a community call, I want to have a standard operating procedure so that I can improve efficiency and have a prepared structure to follow (or delegate with). 

## Acceptance

- [x] Process  doc created and completed in detail
- [x] Templates created where possible (emails, designs, blog post, etc.) 

## Tasks

- [ ] Draft process doc 🚧 [working on this doc](https://docs.google.com/document/d/1N6fkZh-tZZ7ZBmK3dZpTmjTgYdM_8-FKE5sZV5G0JfA/edit#) 
  - [x] Include youtube description template
  - [x] Create Loom for Canva Image
  - [ ] Create blog post page template in Obsidian and add instructions to insert template
  - [x] Create Loom on how to remind zoom registered peeps
  - [x] Loom for creating story graphic
  - [x] Create loom on making chapters
  - [x] Add card information youtube
- [x] Create template for emails to go out about calls. Refer to process doc for touch points we need to consider @laurenwigmore 💬 **created and links added to the google doc and here. Ready to review:**
  - Announcement use - [Calls Invitation Template](https://my.brevo.com/camp/template/58/message-setup)
  - Reminder use - [Call Reminder To Those Registered Template](https://my.brevo.com/camp/template/59/message-setup)
- [x] Update CRM with previous calls at least a few 
- [ ] Figure out post event promotion #588 this is the experiment

### Brainstorm

- Where do we log contact informations? Let's start with our CRM spreadsheet and create new tab https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1186866634 
  - What do we call our calls? digital campfires, town halls, 
  - Can we diversify the calls? Posing a question for discussion, or creating a panel 
  - What is the purpose of these calls?
  - Do we quote tweet the thread or add to bottom of thread for ongoing announcement?

### Notes
- 2023.06.08 - On Brevo I still can't get the link to the IG account to work - I've tried numerous ways. YouTube all updated though.

**Comment by nathenf** [comment]
FIXED - this SOP is now complete https://docs.google.com/document/d/1N6fkZh-tZZ7ZBmK3dZpTmjTgYdM_8-FKE5sZV5G0JfA/edit
