### ISSUE TITLE
Community Call with Brendan Graham Dempsey

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#587]
## Acceptance

- [ ] Community call hosted and recorded
- [ ] Uploaded to Youtube and blog post

## Tasks

Pre-event

- [ ] Confirm speaker
- [ ] Collect and confirm details
  - [ ] Contact for speaker
  - [ ] Time
  - [ ] Date
  - [ ] Blurb for speaker
  - [ ] Profile picture
  - [ ] Confirm who is hosting/mcing
  - [ ] Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [ ] Create Canva graphic using template 
- [ ] Create registration using Zoom
- [ ] Create the blog post
  - [ ] Include image, registration link, biography of speaker or description of the event
- [ ] Promotion
  - [ ] Emails
    - [ ]  Initial announcement (main group)
    - [ ] Day before announcement (main group)
    - [ ] Email reminder (recipients)
    - [ ] Plus in newsletter (if applicable)
  - [ ] Whatsapp
    - [ ] Initial announcement
    - [ ] 3 days before
    - [ ] Day before
    - [ ] 1-2 hours 
  - [ ] Twitter
    - [ ] Thread for initial announcement
    - [ ] 3 days
    - [ ] Day before
  - [ ] Instagram
    - [ ]  Stories
      - [ ] Story template or resharing post
      - [ ] Initial
      - [ ] 3 days before
      - [ ] Day before
  - [ ] Post for initial announcement 

Post-event

- [ ] Make the youtube video 
- [ ] Update original blog post with youtube video plus information
- [ ]  Title: Should include name of person, plus keywords/topic
- [ ] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [ ] Update CRM with links etc. 
- [ ] Let the speaker know and make it easily shareable

**Comment by nathenf** [comment]
FIXED - 20 people attend this discussion and the blog post is here - https://lifeitself.org/blog/2023/06/11/emergentism-a-philosophy-of-complexity-and-meaning-with-brendan-graham-dempsey
