### ISSUE TITLE
Promotion trial of the community call with Myka

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#588]
When we do a community call and upload it to youtube, we want to have a content strategy to drive traffic to the youtube video so that the reach of our content is greater. 

## Acceptance

- [ ] Guide for post-prod promotion of community calls 🚧 https://docs.google.com/document/d/1sbBk5SxHHJkLc1LruXMkTqNBc0Aob-JhtLhbIXolJS0/edit?usp=sharing 
- [ ] Get to 200 views on the video, currently at 66 🚧 at 101 after making one short

## Tasks

- [ ] Draft a list of ideas for promoting call video
- [ ] Experiment with different promotion techniques (types of video, style, etc.) 
- [ ] Optimize youtube video to drive traffic onwards from the video to website and email sign-up 

### Brainstorm 

Take a look at: 
- Use animated textures: https://www.premiumbeat.com/blog/free-animated-textures/ 
- Use background ambience https://www.premiumbeat.com/blog/free-ambient-background-tracks/
- https://www.premiumbeat.com/blog/free-holographic-video-loops/
- https://www.premiumbeat.com/blog/10-free-film-grains-for-video-editors/
- https://www.premiumbeat.com/blog/80-free-cinematic-atmospheres-sound-files/
- https://www.flickr.com/people/britishlibrary/

Look for inspiration:
- What do other podcasts do? 
- What cuts can we use to make the video more stimulating? 
- What text do we overlay? 
- How does all this represent our brand? 

- We can link to the blog post directly from tweets and from Instagram stories, but not posts
- We can create excerpts from the video for reels or for twitter or for youtube shorts - 1 or 2 great moments from the whole video
- We can do a distilled text version of the presentation

Our greatest value here is that we have lots of video content with great knowledge sharing. We can now improve audio quality free and easily with AI and make our info top quality. 

what can we do with the video? We can remove background and add a different background which makes sense for the person to be in.

**Comment by nathenf** [comment]
In hindsight the community call with Sylvie is difficult to take clips from as there are not many concise moments of sharing concrete tips, etc. Will now focus on Myka's community call for this instead #738

**Comment by nathenf** [comment]
To leave a bit of an update here: I have drafted an [SOP](https://docs.google.com/document/d/1sbBk5SxHHJkLc1LruXMkTqNBc0Aob-JhtLhbIXolJS0/edit?usp=sharing) and experimented with creating 2 shorts. These have shown greater engagement on Instagram and a new option for Youtube. While it is only 2 and experimenting with more would be useful, I believe that this would be a useful way to improve our content sharing process to create these short form break downs and link back to the main content. 

I will not have time to carry out any more work on this task, so @laurenwigmore please ask any clarifying questions before I leave if you need.

**Comment by laurenwigmore** [comment]
NOT FIXED. Good insight for future tasks and sprints but not relevant to keep working on now. Closed.
