### ISSUE TITLE
Comms Iteration 21: 12-25th June

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#590]
## Tasks 

🔥 🔥 🔥 

- [x] Skeleton and first draft for #566 🚧 **Skeleton is done, draft ongoing https://coggle.it/diagram/ZJCEkWO5NHMGoe06/t/conscious-coliving-email-course-v-01**
- [ ] #589 as part of #568 ❌ paused until future iteration as coliving course is most important

🔥 🔥 

- [ ] #585 
- [ ] #588 
- [x] #587 
- [x] #569 
- [ ] Create Issue for Jamie Bristow Podcast @ZybN #601 
- [x] Begin preparation and create issue for June Newsletter (items to include below to be added into issue once created) @ZybN #602 
  - [x] Diginomics course summary (@laurenwigmore to draft)
  - [x] Datopian 'How to guide' summary 
  - [x] Next Research Call 4 (check details with Rufus)
  - [x] Next Comms Call in July
  - [x] Update on the to be released Conscious Coliving Course (@laurenwigmore to draft)
  - [x] Summary of past calls available to watch from June (comms calls: Sylvie's, Brendan's, Research call: Jonathan Ream's)
  - [x] Other ... ?
- [ ] Promotion of Diginomics course https://github.com/life-itself/diginomics/issues/72
- [ ] Create issue (?) for podcast featuring Sylvie bio required from Sylvie @ZybN #603 

## Availability

Nathen: 30 hours until the 21st of June (Unavailable for rest of the Iteration as I will be at Glastonbury Festival).
Lauren: 50-60 hours 
Zaib: 15-20 hours

**Comment by nathenf** [comment]
FIXED - We completed the draft for conscious coliving 101, sent out the June newsletter and processed the community call with Brendan GD, Research call and Marc Santolinis call.
