### ISSUE TITLE
Seeking Berlin Hubholders: Announce

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#593]
Current phase of Berlin is coming to an end at end of July 2023. We are seeking new hubholders on the succesful model of Bergerac. We are fortunate to have a flexible timescale for this (with our landlord) and are prioritizing finding a great group who want to take the hub forward.

## Acceptance

- [ ] Announcement out there
- [ ] Discussion with potential hubholders
- [ ] Hubholder MoU agreed

## Tasks

- [ ] Draft announce: https://docs.google.com/document/d/12x7JWCPHnY_MTSb4TRy00ezvxTuKBzz9iWCymcdarEE/edit
- [ ] Post blog post about it
- [ ] ...

**Comment by nathenf** [comment]
@ZybN speak to Rufus about this if he still wants to announce

**Comment by rufuspollock** [comment]
WONTFIX. Current plan is for Berlin Hub to go into hibernation for a period so we will leave this for now.
