### ISSUE TITLE
Post up Politics of Being talk at Untitled 

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#595]
Write up Politics of Being Talk at Untitled in Sep 2020 talk. i.e. create a simple blog post for it ... 

- [Day 1 Video of the talk (from zoom) in GDrive](https://drive.google.com/file/d/1-y1on9q-xQc1IOu-AFPKAQIe9pGS8TRv/view?usp=sharing)
- [Day 2 Video of the talk](https://drive.google.com/drive/folders/1HRRnKsw_1m6Atq0XrRqT5wltw-kPfyH7?usp=share_link)
- Abstract (gdocs): https://docs.google.com/document/d/1n0f6HxwHmPVYULM8hTrHIOvYbGNzCtOH6rZ0XpqS7n0/edit#heading=h.ri7e3vl704
- Slides: https://docs.google.com/presentation/d/1JyNzqJyAUNH4l2rTjlPxwE4G-fGeQxSNoTdy7s3vTos/edit
- Transcript [Day 1 link](https://otter.ai/u/mbwa8KtauCi2z7_DmxD8BtTR6ZQ?utm_source=copy_url) [Day 2 link](https://otter.ai/u/IiuCqNyfzbmC9d8k1jQ4xLB82gw?utm_source=copy_url)

Notes

- Talk/session was split over 2 days
- On 1st day IIRC Rufus and Sylvie gave a talk and then one by Liam a co-founder of Life Itself (Liam talk could also be published - but's that another issue - however could take notes on this now)

## Acceptance

- [x] A completed back-post on the blog on the website **✅2023-06-13 https://lifeitself.org/blog/2020/09/17/politics-of-being-talk-untitled-festival**
  - [x] Content like  “We gave this talk at {insert info at date} about XYZ, {insert abstract}, here are the slides (embedded) and recording (embedded)"
  - [x] Link to event website etc **added**
  - [x] Video on youtube ... **✅2023-06-20**
  - [ ] Ensure slides are tidy … **reviewed and tidied - final 3 slides suggested to remove, Q on this below**
- [x] Liam talk post
- [ ] Shared on chat channel and social media

## Tasks

* [x] Watch the [video](https://drive.google.com/file/d/1-y1on9q-xQc1IOu-AFPKAQIe9pGS8TRv/view?usp=sharing) on fast speed to note where Rufus and Sylvie talk finishes (and if any more notable parts)
* [x] Read [Abstract](https://docs.google.com/document/d/1n0f6HxwHmPVYULM8hTrHIOvYbGNzCtOH6rZ0XpqS7n0/edit#heading=h.ri7e3vl704x)
* [x] Review [Slides](https://docs.google.com/presentation/d/1JyNzqJyAUNH4l2rTjlPxwE4G-fGeQxSNoTdy7s3vTos/edit)
* [x] Review if further tasks to be added at this point
* [x] Use SCQH / Minton Pyramid structure (?) **✅2023-05-10 ❌ not relevant**

Transcript

- [x] Upload to otter ... INSERT LINK
- [x] Is it worth extracting the text? (or what sections)?
- [x] Time estimate 
- [x] do it

Blog post

* [x] Review other blog posts structure/style for reference and alignment 
* [x] Complete first draft of blog
* [x] Review first draft - input / thoughts / amends from Rufus and Sylvie
* [ ] Amend first draft into second/final draft

Youtube

- [x] Upload to youtube ⏭️ **12.05.23 - day 2 uploaded and edited - just processing and then I will add link. day 1 to be done**
- [x] Identify key timestamps ⏭️ **12.05.23 - day 2 timestamps undated below. Day 1 to be done**
- [ ] Check-in
- [ ] Do the edit
- [ ] Videos to be made live and embedded into blog
