### ISSUE TITLE
Community Call with Marc Santolini

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#596]
## Acceptance

- [x] Community call hosted and recorded 
- [x] Uploaded to Youtube and blog post 

## Tasks

Pre-event

- [x] Confirm speaker
- [x] Collect and confirm details
  - [x] Contact for speaker
  - [x] Time
  - [x] Date
  - [x] Blurb for speaker
  - [x] Profile picture
  - [x] Confirm who is hosting/mcing
  - [x] Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [x] Create Canva graphic using template 
- [x] Create registration using Zoom
- [x] Create the blog post
  - [x] Include image, registration link, biography of speaker or description of the event
- [x] Promotion
  - [ ] Emails
    - [x]  Initial announcement (main group)
    - [x] Day before announcement (main group)
    - [ ] Email reminder (recipients)
    - [x] Plus in newsletter (if applicable) ❌ 
  - [ ] Whatsapp
    - [x] Initial announcement
    - [x] 3 days before
    - [x] Day before
    - [ ] 1-2 hours 
  - [ ] Twitter
    - [x] Thread for initial announcement
    - [x] 3 days
    - [x] Day before
  - [ ] Instagram
    - [ ]  Stories
      - [x] Story template or resharing post
      - [ ] Initial
      - [x] 3 days before
      - [x] Day before
  - [x] Post for initial announcement 

Post-event

- [x] Make the youtube video 
- [x] Update original blog post with youtube video plus information
- [x]  Title: Should include name of person, plus keywords/topic
- [ ] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [x] Update CRM with links etc. 
- [x] Let the speaker know and make it easily shareable

### Write up

Our next community call is on Thursday 29th June at 7:30pm CET.

Register here: https://us02web.zoom.us/meeting/register/tZUldu-opj0uEtKfISNxw3YIvVVukgHxNZTM 

We are delighted to invite Marc Santolini to join us for our next community call.

In this discussion we will explore the concept of participatory wisdom. Marc will inquire into how an extreme citizen science of contemplation can be built, bringing together the wisdom of ancient contemplative practices and the rigor of modern scientific methodologies.

Marc is a research fellow at the Learning Planet Institute (Université Paris Cité) and co-founder of the Life Itself Praxis Hub. With a background in network science and epistemology, his work focuses on innovation, collaboration, and learning within open and citizen science communities. As a core resident of the Praxis Hub, Marc investigates how collective practices impact relational well-being and foster group self-regulatory processes.

To learn more about Marc and his work you can visit his website: https://marcsantolini.com/

**Comment by nathenf** [comment]
@laurenwigmore I've updated this issue with what I have done, if you could do a bit more promotion on Monday that would be awesome!

**Comment by laurenwigmore** [comment]
> @laurenwigmore I've updated this issue with what I have done, if you could do a bit more promotion on Monday that would be awesome!

Have posted in community chat, tweeted from thread and added a story on IG. 10 registrants so far.

**Comment by nathenf** [comment]
FIXED - https://lifeitself.org/blog/2023/06/20/participatory-wisdom-with-marc-santolini call recorded and added to Youtube and blog. Announced in the chat and will be in this months Newsletter.
