### ISSUE TITLE
Comms Iteration 22: 26th June-9th July

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#599]
## Tasks 

🔥 🔥 🔥 
- [ ] Completion and launch of #566 
- [x] Send #602 
- [ ] https://github.com/life-itself/community/issues/589 as part of https://github.com/life-itself/community/issues/568 (carried over from #590) 
- [x] #618 this needs be done - see issue for details

🔥 🔥 
- [ ] #585 
- [x] Delete zoom recordings ahead of next comms call currently at 95% of storage used - @nathenf to advise

## Availability
Lauren - 60 hours
Zaib: 40-50 Hours
Nathen: 40 Hours

**Comment by nathenf** [comment]
FIXED - Other tasks have been carried to next iteration. We have completed the draft of conscious coliving 101 which is now set-up on Brevo and have begun to build the landing page.
