### ISSUE TITLE
Jamie Bristow Podcast

### ISSUE THREAD

**Issue by ZybN** [life-itself/community#601]
**NOTE** - This all needs to be reviewed and a number of amendments to be done i.e. recording re-edited, templates changed, intro jingle added to spotify. 

## Acceptance 

- [x] Conversation published on Youtube & Anchor. 
- [x] Blog Post containing all content published.  [_done on series with reference to this as first one_](https://lifeitself.org/blog/once-upon-a-time-new-podcast-series)
- [x] Episode page added to the website.
- [x] Guest informed that the episode is out and has been sent the links. _Sylvie actioning_
- [ ] The new episode has been announced on Twitter. @moonimmisch 
- [ ] Email announcing a new episode has been sent to mailing list. _will add to November newsletter_
- [ ] Secondary content has been shared on social media @moonimmisch 

## Tasks

- [x] Copy this Template into a new GitHub issue. Name the issue as the working title of the conversation
- [x] [Create a new folder for the conversation and assets here](https://drive.google.com/drive/folders/12BskqKPp85XNdU2sespI--E7VPi45hGJ?usp=sharing) ✅ All [assets uploaded here](https://drive.google.com/drive/folders/1eAFmJon0I5583CQjADe-nyUOsktEo0u8?usp=sharing)
- [x] Source the video file and add to folder
- [x] Create a document for the conversation that includes: Title, Conversation Summary, About the person in conversation, links to resources mentioned in the podcast, timestamps for at least two video excerpts and two quotes and timestamps for ["chapters"](https://www.youtube.com/watch?v=pvkTC2xIbeY). Add this to folder. 
👉  **https://docs.google.com/document/d/1PpZGy5ShSNt6QNxJV429_Vc8ubOeKmTOaziXnSHxW1E/edit**
- [x] Watch the video. Note any moments that need edited eg moments of bad internet connectivity. Note down timestamps for chapters to be used when publishing to YouTube. Note timestamps of short sections that will be good for social media (max length for twitter 2m20s) and note down quotes that will be good for marketting the episode.
- [x] **Create Youtube video** 👉  **[saved as private](https://youtu.be/YkgQ6Iarrp4)** ✅ [Scheduled for 8th July ](https://youtu.be/g40xTkyKLtE)
	- [x] Create the Youtube Thumbnail from [this template](https://www.canva.com/design/DAE99drPH4s/7mR8CgHWyHfimwC9jDerDA/edit?utm_content=DAE99drPH4s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).
	- [x] Edit the video file in [Da Vinci Resolve](https://www.blackmagicdesign.com/products/davinciresolve):
		- [x] Trim beginning and end, plus any sections of poor internet connection or other interruptions
		- [x] Add thumbnail at the beginning of the video with a fade transition to the video
		- [x] Add graphic overlay ["Please Like & Subscribe"](https://drive.google.com/file/d/1iQjSdgjTyrN9xnQ8Xnlzdjmk2sw2eKXJ/view?usp=sharing) at the 5, 10, 20, 40 minute
		- [x] [Add End Screen with a fading transition](https://drive.google.com/file/d/1fC8c_tyoOxxGGhGqgJuwFscu6vYzbrqe/view?usp=sharing)
		- [x] Increase the sound volume as much as possible without clipping the sound (around 3 is normally good) 
	- [x] Export as Video for Youtube
	- [x] Export audio only for podcast
	- [x] Upload to Youtube: Add title, thumbnail, summary including [contents chapters](https://www.youtube.com/watch?v=pvkTC2xIbeY), page stub URL, add to relevant playlist, Add Language, Make License Creative Commons.
	- [x] Schedule publication for desired day and time

- [x] **Create Podcast** 👉  **[saved](https://anchor.fm/dashboard/episode/e1u045v)** ✅ [Scheduled for 8th July](https://podcasters.spotify.com/pod/dashboard/episode/e26m23g) 
	- [x] In Anchor click new episode then click create new episode. Click on reuse your previously uploaded audio and scroll down until you find the "Intro Jingle". Drag the file in the box into the right. Add the audio-only edit of the episode after the intro. Click save episode.
	- [x] Add title & summary.
	- [x] Create and add thumbnail from [this template](https://www.canva.com/design/DAE87pGGDUg/EgrVC9iJX5eATZGF5rE2pg/edit?utm_content=DAE87pGGDUg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
	- [x] Add season number and episode number
	- [x] Schedule publication for desired day and time
- [ ] **Create blogpost**
	- [x] Draft blogpost prior to scheduled publication of the episode on YouTube and Anchor. 
	- [ ] Add a new blog in the vault/blog folder in the Community repo. 
		- [ ] Follow the format: put it in date structured folders eg. vault -> blog -> 2023 -> 01 -> 16 -> blog-file-name.md. For the frontmattter fields have a look at any of the other blog posts within that folder and follow that format. Once added commit the new file as you usually would. For more directions on how to add to the website see the [Web3 site contributors' guide](https://web3.lifeitself.org/meta/editing) and/or the [ecosystem mapping site guide](https://ecosystem.lifeitself.org/contributors-guide).
	- [x] You can add in the YouTube link as you can access that even before the video is published, however you can't with the Anchor link. Once the podcast is published, source the embed link to the episode found when you click on the episode on Anchor and paste into the blog (use previously published podcast blog posts as a guide).
	- [x] The blog should feature a brief introduction of the guest and an intro to the episode (eg v brief overview of what is discussed).
	- [x] Add any notes. Ensure they are complete, comprehensive and tidied.
	- [x] Add any references and further reading
	- [x] Add the transcript
		- [x] Run the video through Otter to generate the transcript. Go through and fix any errors. Export as docx with speaker names and timestamps.
		- [x] Copy the transcription into a Google doc and save it in the episode folder.
		- [x] Convert into markdown. Copy and paste into a blog post.
- [ ] Once the episode is published to YouTube and Anchor, publish the blog post with the links. Once the blog post is published, edit the YouTube and Anchor episode bios and paste in the link to the blog.
- [ ] Once the YouTube video, podcast episode and blog post are published, **create a page for the episode on the [podcast page](https://lifeitself.org/podcast) of the website.**
	- [ ] Add a new page in the vault/podcast in the community repo. Use [Jeffery Martin episode page](https://lifeitself.org/podcast/a-scientific-approach-to-awakening-and-fundamental-wellbeing-podcast) as a guide. Generate the links for the frontmatter:
		- [ ] Follow this link: https://rss2json.com/
		- [ ] Paste this link in the box on the page (under the text that says Enter the URL to your RSS feed): https://anchor.fm/s/79b39934/podcast/rss 
		- [ ] Find the podcast episode you are wanting to create the page for (likely the first episode listed, this will be the first episode under the line that says "items")
		- [ ] Click the button with 4 arrows pointing outwards to make it full screen to ensure you don't copy only part of a link.
		- [ ] Copy the link for "thumbnail" and paste it after "image:" in the front matter.
		- [ ] For the src link, scroll down to where it says "enclosure" and copy the link that follows "link". Paste this after "src" in the front matter. 
		- [ ] Fill out the rest of the frontmatter.
	- [ ] Paste the same short intro to the episode and guest as used in the blog post below the frontmatter. Paste the youtube link and the link to the blogpost. 
- [ ] **Inform the guest that the episode is out.** Send all links and encourage them to share.
- [ ] **Send email out to Life Itself General Audience on Mailchimp** announcing that the latest episode of the Life Itself Podcast is now available. Use the same intro to the episode and guest as used in blog. Paste link to the podcast page - they can navigate to everything they need from that one link. Use a previous podcast episode launch email as a guide - you can replicate that email, just remember to change the text, link, subject line and preview text. 
- [ ] **Announce release on Twitter.** Make sure to @ the guest and tweet the link to the podcast page. 

## Podcast Landing page content

INTRO 
This podcast shatters the myth that extraordinary lives are reserved for a select few. Join us as we dive deep into the lives of seemingly ordinary people who are walking extraordinary paths, uncovering their motivations, practices, and moments of transformation. We demystify hero worship and share accessible narratives of real individuals who have transcended societal expectations and norms. Each guest delicately navigates the balance between introspection and worldly engagement. Listeners are offered empowerment, kinship and inspiration for embarking on their own extraordinary journey. 

DEVELOPMENT

Embark on a captivating journey with  a podcast that shatters the belief that an extraordinary life may only be achieved by those who are naturally exceptional. In this  series, we delve into the lives of individuals who have defied societal expectations and embarked on extraordinary paths, despite their seemingly ordinary backgrounds.

In today's world, where disillusionment with the conventional consumerist dream is pervasive, many are searching for an alternative. This podcast is a testament to that alternative. Our interviews seek out individuals who have chosen extraordinary lives, exploring the motivations behind their choices and the impact of their upbringing and environment. We dive into their practices, moments of transformation, and the delicate balance between retreat from worldly temptation and engagement with social change.

At the heart of these extraordinary lives lies a common thread: unwavering commitment to something greater than oneself. Through the power of storytelling, we aim to demystify the concept of hero worship, revealing that these figures are not larger-than-life beings, but rather individuals who found something worth dedicating their lives to. By sharing their remarkable stories, we aim to inspire listeners to believe in their own potential for making a difference and embarking on their own extraordinary paths.

It is a platform where extraordinary lives are unveiled and practical guidance is extracted. Each episode, ranging from 45 minutes to an hour, features interviews that are deeply personal though broadly scoped in their insight. Listeners will leave with tangible tools to embark on their own unique journeys of purpose and fulfillment.

In essence, the podcast challenges the perception that extraordinary lives are beyond the reach of ordinary individuals. We unravel unrealistic idolisation, offering accessible narratives and insights into the lives of those who have defied the norm. By delving into their motivations, practices, and transformative moments, we ignite the spark within our listeners, empowering them to embrace their own extraordinary potential. Join us on this captivating odyssey, as we guide you to discover a life that surpasses societal expectations and embraces the extraordinary.

One para with the essence
Few paras with developments
Some Notes from transcript:
Where do I find like-minded people
Figures that brought radical change tended to be middle class
Reverence of figures like Gandhi, Voltaire puts them beyond the reach of normality - reading their biographies reveals that in many ways, they are just like the rest of us
Interested in those navigating the balance between introspection and worldly engagement
Not those forcing themselves into the public eye, nor those retreating into the monasteries. Those on the middle way.
Showing stories of extraordinary lives may encourage listeners to take risks
The great figures were all touched by something, they found something to truly commit to and they gave their life to that commitment. Something bigger than themselves
What makes someone extraordinary
Sharing a range of practices and experience
Aimed at the curious, and at those who want to live life completely

**Comment by ZybN** [comment]
Few comments: 

1. This podcast is called Once Upon A Time by Sylvie Barbier, 

- I have created a separate Playlist on Youtube
- Thumbnail design is the same as our previous podcasts 

2. Podcast is scheduled on [Spotify: Link ](https://podcasters.spotify.com/pod/dashboard/episode/e26m23g)
3. Question: where shall I add the Landing page content that Jake created? the podcast page usually includes links to Spotify and Youtube and Bios.

**Comment by rufuspollock** [comment]
@alexianetcu are you clear on what you need to do next here? If not can you sync with Lauren and add a comment here with clear next steps 😄

**Comment by laurenwigmore** [comment]
> @alexianetcu are you clear on what you need to do next here? If not can you sync with Lauren and add a comment here with clear next steps 😄

I'm actually just about to send an email to Sylvie to understand more about the series. @nathenf  and I discussed he will be able to support Alexia to run through podcast aspects as needed this/next week, once she has detailed her next steps/what she needs.

**Comment by alexianetcu** [comment]
@rufuspollock quick update: I've been in touch with Lauren about this, once comms team is more clear on what to do with Podcast we will get clear next steps down. I have time to start working on it on Friday.

**Comment by alexianetcu** [comment]
*ignore closing, I clicked by mistake*

**Comment by laurenwigmore** [comment]
> @rufuspollock quick update: I've been in touch with Lauren about this, once comms team is more clear on what to do with Podcast we will get clear next steps down. I have time to start working on it on Friday.

@alexianetcu just a recap on what I understood was agreed: you will review the steps for this to make sure you are understanding what to do. We will all speak re the Series, to avoid any duplicate tasks i.e. creating the cover images or description as standalone podcast and then having to recreate with a series notice. But, there are a lot of steps that will need to happen either way, so I would suggest you get your head around these and check you are clear on next steps for when we provide the series update. For things like the editing, these can be started and the cover images added later, the descriptions drafted (you can view the Culturology podcasts to understand how we would reference the series - just adding a sentence or two) etc.

**Comment by laurenwigmore** [comment]
@moonimmisch to practice creating issues with acceptance and tasks can you create a new issue for the two items I have tagged you in (twitter and socials for this episode). You can use the blog post issues as an example of what to include for the socials. 
Can you draft in a new document the [tweet, instagram, linkedin and whatsapp promo text and images for this episode](https://drive.google.com/drive/folders/1eAFmJon0I5583CQjADe-nyUOsktEo0u8)

**Comment by laurenwigmore** [comment]
Podcast is now live, promo is underway and Jamie has been informed.

https://lifeitself.org/podcast/jamie-bristow-sylvie-barbier-mindfulness-inner-development
