### ISSUE TITLE
June Newsletter 2023

### ISSUE THREAD

**Issue by ZybN** [life-itself/community#602]
- [x] Begin preparation and create an issue for June Newsletter (items to include below to be added into an issue once created) @ZybN 

## Acceptance 

- [x] Newsletter is sent

## Tasks

- [x] Create a Newsletter 
- [x] Test Newsletter
- [x] Send Newsletter

## Notes 
**Life Itself General**
  - [x] Diginomics course summary (@laurenwigmore to draft)
  - [ ] Datopian 'How to guide' summary 
  - [ ] Next Research Call 4 (check details with @rufuspollock )
  - [x] Next Comms Call in July
  - [x] Update on the to-be-released [Conscious Coliving Course](https://github.com/life-itself/community/issues/566) (@laurenwigmore to draft) 
  - [x] Summary of past calls available to watch from June (comms calls: Sylvie's, Brendan's, Research call: Jonathan Ream's)
  - [ ] Other 

**Community Calls**

- [x] With [Brenden Dimpsey](https://github.com/life-itself/community/issues/587) 
- [x] With [Sylvie Barbier](https://github.com/life-itself/community/issues/569)
 
**Research Community Calls**

- [x] With [Jonathan Ream's](https://github.com/life-itself/community/issues/569)

**Residencies**

- [x] [Elder Gathering, August 2023](https://lifeitself.org/programs/2023/elder-gathering)

**Comment by laurenwigmore** [comment]
@ZybN here is the [document](https://docs.google.com/document/d/1vsuZWDAkdaR12kmbsNgRcIdvtPSF1tEJ7DlUfTE-mH8/edit) for the text related to the Dignomics and Conscious Coliving Couse and suggested images for these the June Newsletter.
Please note I'm still waiting for Khalil to create the landing page for the Conscious Coliving Course Sign Ups - this will need to be included once done.

**Comment by ZybN** [comment]
The Research Forum wasn't added as I received the material a little late. Need to send it in a separate Newsletter
