### ISSUE TITLE
Conscious Coliving Course Landing Page

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#607]
When I am curious or feeling unfulfilled with my current living situation and I feel like I need more connection to 'something', and I have a knowing that I want to live better or differently, I want to find a website that helps me understand if others feel like this and to gain quick and reliable information to reassure me that it is possible to live differently, and tell me how I can take action in this moment to make changes to feel better.

When I visit the landing page I want to immediately understand what is available, why it is useful for me and to easily access the information.

- Linked to #566  
- Useful #636 

## Acceptance
- [x] Landing page with CTA sign up button live 

## Tasks
- [x] Brevo sign up form and list created
- [x] Brevo sign up form embed as a CTA button on the landing page
- [x] Landing page [text](https://docs.google.com/document/d/12paZt8ZwPomkDkyaLG_8KDNaQTIiaplQey6sQpR9SVE/edit) drafted using the [Landing Page Guide](https://lifeitself.org/notes/landing-page-guide)
- [x] Image added to landing page
- [x] #653
- [x] @olayway pull requests 648,649, 651 didn't build - can you look into and fix? **fixed with bfb21a1**

**Comment by olayway** [comment]
@laurenwigmore changes are live, let me know if you need anything else

**Comment by olayway** [comment]
@laurenwigmore the issue was that you used `<br>` instead of `<br/>` for line breaks.

**Comment by nathenf** [comment]
FIXED - Basic landing page complete https://lifeitself.org/conscious-coliving-course
