### ISSUE TITLE
[epic] Post up content for all Life Itself Salons 2017-2020

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#61]
We ran a variety of salons from ~2017-2020 with majority being in 2019-2020 and coordinated by Petro (Salons have sort of gone on hiatus since 2020 and will probably be replaced by imaginary society and community calls).

## Acceptance

* [ ] We have a list of all the salons
* [ ] We have posted the recordings of the salons
* [ ] We have blog post for each salon which includes recording or other content

## Tasks

* [ ] Get a list of salons (ask Petro ...)
* [ ] For each salon
  * [ ] Identify content for each of these e.g. zoom recording, presentation etc
  * [ ] Upload to relevant location
  * [ ] Create blog post

### Salons to process

* [ ] Salon on Art led by Sylvie Barbier
[Presentation - aet-wise-art.pdf](https://github.com/life-itself/community/files/7246725/aet-wise-art.pdf) ~ early 2020
* [ ] ...

Additional items (not strictly salons)

* [ ] https://lifeitself.us/2020/03/25/the-opportunities-and-lessons-to-take-away-from-coronavirus-community-call-28th-march/ + subsequent calls (this led into possibility now)
.
