### ISSUE TITLE
Evolve Poster (and Hub Poster)

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#611]
We have been invited to create a full-page poster in the Evolve magazine - deadline Monday 3rd July. 

When I read the Evolve magazine I want to find new projects and initiatives, so that I can find clear pathways and people to connect with. I would be attracted to something outstanding. 

## Acceptance

- [x] Full-page poster submitted to Evolve by Monday 3rd July, with a single call to action leading to:
- [ ] A Landing page containing our theory of change and practical pathways for them - NOT FIXED redirected to homepage for now. 

## Tasks

- [x] Brainstorm Poster ✅ https://app.excalidraw.com/l/9u8crB2ZmUo/9XlL9rIxvzS **Main idea is to go for the propaganda poster with lower third editorial and QR Code leading to landing page**
- [x] Oliver to draft poster idea 
- [ ] Create a specific landing page to link to from the poster, should include:
  - [ ] Our theory of change
  - [ ] What we are doing about it
- [ ] BONUS: Use page and poster to create second more detailed poster for the hub

## Brainstorm 

What’s the approach
Make people excited about Life Itself
Provide next steps …

https://link.excalidraw.com/l/9u8crB2ZmUo/9XlL9rIxvzS - advert sketch

https://link.excalidraw.com/l/9u8crB2ZmUo/8F30hhvlTcl - theory of change

Nathens ideas: 
Choose your journey: There are many ways to a wiser, weller world “START HERE” 
=> Do you want to be pragmatic or intellectual?
	=> Do you want to live in community? 
	=> Or join remotely?
		=> Are you ready to try it out? (residencies) 
		=>Or learn more? (conscious coliving course)
Cartoon of someone sat on the sofa with GAME B on the laptop, speech bubble “We should really do something about this” => start now
The rebellion - You and I both know that something feels wrong. We’re rebels gathering for the revolution to be on the right side of history.
ENLISTING NOW
Recruiting Revolutionaries for the 2nd Renaissance
We’re done with talking. Time to take action.
Metamodern neighbourhoods, schools and communities are under construction. We need you. 
​​

Recruiting for the 2nd Renaissance
We’re done with talking. Time to take action.
Metamodern neighbourhoods, schools and communities are under construction. We need you. 

Rufus ideas:
Fed up of theory and want some actual practice? Building Bergerac's Metamodern Neighbourhood since 2018

“Real Teal”

Other notes: 
Metamodern Neighbourhoods - Bergerac as a pioneer Write an article on this? 
2nd renaissance “hotspots”

Dreams / aspirations
Army of Bodhisattvas, Shambhala Warriors: i.e. people committed to awakening and awakening societies (waking up themselves and others waking up)
Regions of transformation. “Metamodern Neighborhoods”
2nd renaissance / awakening society
https://lifeitself.org/awakening-society 
We are pioneering

The 2nd Renaissance is here.

Be a part of it.

### Landing page copy

- We can all feel the world is changing
- Everyone is talking about how - the metamodernism, game b, integral
- We all talk a good talk, but where is the walk? 
- We want to make this real, actually walk the talk. 
- And we have an approach to doing that
- We want to build an awakened society
- To get there we need a 2nd renaissance
- To create a 2nd renaissance we need regions/hotspots of transformational change
- Here is what we are doing about it
- We're pioneering a Metamodern neighbourhood in Bergerac
- We're carrying out research and development in our research community
- We're creating courses and incubating enterprises for the second renassaince
- We're building a digital portal and network for renaissance actors 
- But for all of this we need you, people willing and able to be part of the 2nd renaissance
- Are you with us?

```[tasklist]
### Tasks
```

**Comment by nathenf** [comment]
@rufuspollock I've added in some more for the landing page copy in bullet points here. Is there anything you would add or remove? If not I can expand into some full copy for the 1st iteration of this landing page. 

## Question 

Where do we go after the landing page? 

Do we want people to join the community as the most simple call to action?

**Comment by nathenf** [comment]
FIXED - The Evolve poster was complete and a new issue has been created for hub content #673. We did not make a landing page but directed the poster to the home page instead.
