### ISSUE TITLE
Create nextjs starter templates with tailwind + mdx

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#62]
## Tasks

* [ ] Why do this
* [ ] Research existing
  * [ ] e.g. GitHub - https://github.com/mihalik/nextjs-mdx-tailwind-starter - has 3*
  * [ ] https://github.com/timlrx/tailwind-nextjs-starter-blog - excellent but far too many batteries included for what i need

## Why do this

Pros / cons of doing my own nextjs template for tailwind + nextjs (vs e.g. https://github.com/timlrx/tailwind-nextjs-starter-blog)

Pros:

* need this for life itself community, tao site, even standard portal sites. Can’t find something simple that provides this atm (the timlrx one is good but much too complex - we want the simplest and you add things).

Cons: takes time from just doing it (e.g. just create the site)

Pros: just doing it has become a bit time consuming and buggy ...

**Comment by rufuspollock** [comment]
DUPLICATE now of https://github.com/datopian/nextjs-tailwind-mdx/issues/1
