### ISSUE TITLE
[epic] Comms Standard Operating Procedures (SOPs)

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#623]
We want to create a document of SOPs and guidelines to enable us to be more consistent and streamlined with our communications moving forward. This is especially important now the team is growing and old members with the knowledge on procedures are leaving.

## Acceptance
- [ ] Tao updated to reflect current processes
- [ ] Google document completed and available on Gdrive for use and shared with everyone 

## Tasks
- [x] Order and prioritse the below:
- [x] Create and iterate processes for the comms we do now and ongoing
		- https://github.com/life-itself/community/issues/585 ✅ https://docs.google.com/document/d/1N6fkZh-tZZ7ZBmK3dZpTmjTgYdM_8-FKE5sZV5G0JfA/edit **This can be added to Tao at some point**
- [x] Review tao comms guides https://lifeitself.org/tao/communications **✅2024-07-11 ❌ wontfix at this point**
- [x] #655 / New SOP written
- [x] People Page SOP #656 
- [x] Create one for research forum 
- [x] Newsletter SOP **✅2024-07-11 ❌ pretty simple now - and on substack**
- [x] Praxis and residencies SOPs/guidance ❌ not required for now
- [x] Life Itself research communication ❌ this is limited for now and does not have a cohesive comms
- [x] #656
- [x] Create publishing a blog post

💤 Someday / Nice to have ...

- [ ] Course building SOP 
- [ ] https://github.com/life-itself/community/issues/588 We need to do this to decide on an SOP/guidance for comms post call
- [ ] https://github.com/life-itself/community/issues/589 produce this then make SOP then brainstorm pages
- [ ] Image management - tools use / where saved / size requirements etc

## Notes for reference

- LI-General tag added to all 800+ contacts and set up as a tag when someone receives the welcome email
- Previous issue with link on the front page - learn: ensure buttons and forms sync

**Comment by rufuspollock** [comment]
FIXED. (or wontfix for remaining items)
