### ISSUE TITLE
[epic] Community and Research Calls Tracker 2023

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#624]
Ongoing issue to provide an overview of community calls scheduled. All calls to have there own issues created using the SOP for community calls and the issue number added below for ease of reference.

All Community calls 730pm CET biweekly unless otherwise stated (community calls)
All Research calls [time/frequency]

## Upcoming community calls
- [x] Fabienne Vailes	12/07/2023 - Flourishing Education #627 https://lifeitself.org/blog/2023/06/29/future-of-education-with-fabienne-vailes
- [x] Liam Kavanagh	27/07/2023 - Climate Majority Project (co-host) #628 https://lifeitself.org/blog/2023/06/29/climate-majority-project-with-liam-kavanagh
- [x] #682 
- [x] Matthew McCarthy	23-24/08/2023 - The Importance of Uncertainty (Lauren Takes Over) #630 
- [x] Isabella Roberts 06/09/2023 - Collective Wisdom (Nathen hosts) #725
- [x] Alan Williams | 20/09/2023 | 31 Values (Lauren hosts) #717
- [x] Myka Mclaughlin | 12/10/2023 | Community practices/living #738 
- [x] Boaz Feldman | 26/10/2023 - Multi-level resilience: building capacity from neurons to nations #629 
- [x] Victoria | 09/11/2023 - Creatives in community #867 
- [x] James Baker | 22/11/23 - How to grow to handle anything #904 
- [x] Myka McLaughlin and Elizabeth | 07/12/2023 #925 

### Later
- [ ] Spor - Creativity and Community Living - Nathen in contact
- [ ] Jana Milbou - Biodynamic Farming - Lauren in contact

## Upcoming Research Calls
- [x] Marc Santolini and Liam Kavanagh 21/07/ 2023 - Collaborative Citizen Science #618 https://lifeitself.org/blog/2023/07/05/research-forum-4-marc-santolini-liam-kavanagh

# Issue Template

## Acceptance

- [x] Community call hosted and recorded 
- [x] Uploaded to Youtube and blog post 

## Tasks

Pre-event

- [ ] Confirm speaker
- [ ] Collect and confirm details
  - [ ] Contact for speaker
  - [ ] Time
  - [ ] Date
  - [ ] Blurb for speaker
  - [ ] Profile picture
  - [ ] Confirm who is hosting/mcing
  - [ ] Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [ ] Create Canva graphic using template 
- [ ] Create registration using Zoom
- [ ] Create the blog post
  - [ ] Include image, registration link, biography of speaker or description of the event
- [ ] Promotion
  - [ ] Emails
    - [ ] Initial announcement (main group) on if newsletter was more than a week ago
    - [ ] Day before announcement (main group) only if initial announcement was more than a week ago
    - [ ] Email reminder (recipients)
    - [ ] Plus in newsletter (if applicable)
  - [ ] Add to Dandelion events 
  - [ ] Whatsapp
    - [ ] Initial announcement
    - [ ] 3 days before
    - [ ] Day before
    - [ ] 1-2 hours 
  - [ ] Twitter
    - [ ] Thread for initial announcement
    - [ ] 3 days
    - [ ] Day before
  - [ ] Instagram
    - [ ]  Stories
      - [ ] Story template or resharing post
      - [ ] Initial
      - [ ] 3 days before
      - [ ] Day before
  - [ ] Post for initial announcement 

Post-event

- [ ] Make the youtube video 
- [ ] Update original blog post with youtube video plus information
- [ ]  Title: Should include name of person, plus keywords/topic
- [ ] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [ ] Update CRM with links etc. 
- [ ] Let the speaker know and make it easily shareable

**Comment by laurenwigmore** [comment]
FIXED. Tracker for Q3 & Q4 period updated and completed. All community calls hosted, research calls not added to this issue. Moving forward we will use the uber epics for tracking of community calls.
