### ISSUE TITLE
Comms Iteration 23: 10th July-23rd July

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#625]
## Tasks 

♾️ ♾️ 
- [ ] #454
- [ ] #657
- [ ] #624 for reference

🔥 🔥 🔥 
- [x] Completion and launch of #566 
  - [ ] Pre-launch and launch sections of #636 🚧 **Launch has been complete, currently working on creating content plan until December and then creating a launch SOP document**
- [ ] Start on #623 
  - [ ] #585 
  - [ ] podcast SOP written - #655 🚧 **Zaib has updated, waiting for podcast for Lauren to try** #664 
  - [ ] peoples pages SOP written #656 **Nathen & Lauren to record tutorial**
- [ ] Community Calls
  - [x] #627
  - [x] #628 **Will happen next week, but has already been promoted**
  - [x] Create and prep for #629, #630, #631 
  - [ ] Team action - update in comments a summary of tasks completed, and number of hours
  - [x] Create next iteration
  
🔥 🔥 
- [x] #618 this needs be done ✅ **Announced on all platforms**
  - [ ] Research Forum Friday 21st - create issue following community call guidelines
- [ ] Comms Strategy skeleton for launches #636 
- [x] #626
- [ ] #638 🚧 [Ready for Review](https://docs.google.com/document/d/1ViTerMTzUNaf33uoz9W0abFXABgoTU8VdelYLILJXfU/edit?usp=sharing)
- [x] #643 

⏭️
- [ ] #642
- [ ] BONUS: Create questionnaire for feedback from Whatsapp group (create an issue)
- [ ] #664 

⏭️ ⏭️ 
- [ ] #588
- [ ] #589 as part of #568

## Availability & Total Hours done
Lauren - 60 hours ✅ 
Nathen: - 40 hours ✅ 
Zaib: - 35 Hours ✅

**Comment by nathenf** [comment]
@ZybN and @laurenwigmore adding the meeting notes here

- [ ] Tasks to do
	- [ ] Fabienne call https://github.com/life-itself/community/issues/627 (max 3 hours)
	- [ ] Boaz Set Up Blog post https://github.com/life-itself/community/issues/629 (max 2 hours)
	- [ ] Set up newsletter issue (max 30mins) and add to the iteration 24
	- [ ] Add team images https://github.com/life-itself/labs/issues/150 just do Boaz and Matt - Lauren will do her own with Zaib who can have a meeting and record it (max 2 hours)
	- [ ] https://github.com/life-itself/community/issues/638 draft posts for this, check with us and then post (max 4 hours)
	- [ ] https://github.com/life-itself/community/issues/623 from this create an issue to podcast SOPs, continue to update and then get Lauren to test it. (max 2 hours)

Next actions
- Research call blog post needs a new image (Nathen To do)

## Notes

- Must do daily standups
- Now 30 hours a week and then after september 15-20
- Zaib hours - 1pm-8pm general availability
- add thursday 2pm meeting for half an hour
- Invite Rufus to the next comms call 
- Zaib skills: 
	- Twitter and Linkedin posts 
	- Writing is strong point
	- Now knows the podcast set-up and newsletters
	- Research especially for Climate Change and Sustainability
-  


What does a daily stand up look like? 

- Last 24 hours: What you've been working on
- Next 24 hours: What you're gonna work on next
- Blockers: What are you stuck on and need support
- Availability: What times are you available for work/when

**Comment by laurenwigmore** [comment]
## Meeting 2023-07-18
Present: Nathen, Lauren, Zaib, Matthew
- [x] Meditation
- [x] Check-in
- [x] Set intentions - prep for back log and feel good about it. And gain an understanding on DDS project to support promo.
- [x] Agenda
	- [x] Updates
	- [x] Comms Iteration https://github.com/life-itself/community/issues/625
	- [x] Podcast and People SOPs

### Next actions
Nathen: redirect how to with video, create peoples page how to and launch strategy, calendly form creation for community call research

Zaib: Complete Boaz community call, set up the community call with Matthew, review promotional posts, meet with Matthew

Lauren: Launch CC101 - email, linkedin, blog posts; Brevo review and follow up with Jan, launch strategy, how to's, fix Obsidian, calendly form creation for community call research

Matthew: meet with Zaib, fix the blog post link

**Comment by laurenwigmore** [comment]
@ZybN could you update the blog links for the community calls in the [CRM spreadsheet](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) please?

**Comment by nathenf** [comment]
FIXED - In total we worked Approx 135 hours. We:
- Completed and launched CC101 and 50% of content prep for 2023. So far 80 people starting the course with a completion rate of 30%
- Community Call and Research Forum Completed and Community Call Recordings published
- Begun working on SOPs but didn't have time to really dive into this yet 
- Initial promotion of DDS Research project 
- Several meetings to discuss next phase of work and team communication improvements
