### ISSUE TITLE
Add Team Updates to July Newsletter and Blog Post

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#626]
To communicate the LI team member updates to the community

## Acceptance
- [ ] Updates included in July Newsletter
- [ ] Blog post live on website

## Tasks
- [ ] Get information on new members, role, responsibilities
- [ ] Get images
- [ ] Create copy

## Notes
- Jake hirsch as an intern
- Boaz Feldman as researcher
- Matthew McCarthy as researcher
- Marc and Liubov directors of research at Life Itself
- Lauren Wigmore as ...
- Zaib ...

**Comment by nathenf** [comment]
MERGED into #642
