### ISSUE TITLE
Community Call with Fabienne Vailes

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#627]
## Acceptance

- [ ] Community call hosted and recorded 
- [ ] Uploaded to Youtube and blog post 

## Tasks

Recording Link: https://us02web.zoom.us/rec/share/1ROsR7eidGjrqVCiqsfsuyoRCpeocs0PoQnQF_JnFZZoicuA8MxPqSjlQo7G9rDi.1aQcqGSawJT7B340 
Passcode: kgjiU=F0

Pre-event

- [x] Confirm speaker
- [x] Collect and confirm details
  - [x] Contact for speaker
  - [x] Time
  - [x] Date
  - [x] Blurb for speaker
  - [x] Profile picture
  - [x] Confirm who is hosting/mcing
  - [x] Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [x] Create Canva graphic using template 
- [x] Create registration using Zoom
- [x] Create the blog post
  - [x] Include image, registration link, biography of speaker or description of the event
- [x] Promotion
  - [x] Emails
    - [ ] Initial announcement (main group) on if newsletter was more than a week ago
    - [ ] Day before announcement (main group) only if initial announcement was more than a week ago
    - [ ] Email reminder (recipients)
    - [ ] Plus in newsletter (if applicable)
  - [x] Whatsapp
    - [ ] Initial announcement
    - [ ] 3 days before
    - [ ] Day before
    - [ ] 1-2 hours 
  - [x] Twitter
    - [ ] Thread for initial announcement
    - [ ] 3 days
    - [ ] Day before
  - [x] Instagram
    - [ ]  Stories
      - [ ] Story template or resharing post
      - [ ] Initial
      - [ ] 3 days before
      - [ ] Day before
  - [x] Post for initial announcement 

Post-event

- [x] Make the youtube video 
- [x] Update original blog post with youtube video plus information
- [x]  Title: Should include name of person, plus keywords/topic
- [x] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [x] Update CRM with links etc. 
- [x] Let the speaker know and make it easily shareable

**Comment by nathenf** [comment]
FIXED - this is now live at https://lifeitself.org/blog/2023/06/29/future-of-education-with-fabienne-vailes
