### ISSUE TITLE
Community Call with Boaz Feldman - 26/10/2023

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#629]
Boaz Feldman | 26/10/2023 | Multi-level resilience: building capacity from neurons to nations

## Acceptance

- [ ] Community call hosted and recorded 
- [ ] Uploaded to Youtube and blog post 

## Tasks

Pre-event

- [x] Confirm speaker
- [x] Collect and confirm details
  - [x] Contact for speaker
  - [x] Time
  - [x] Date
  - [x] Blurb for speaker
  - [x] Profile picture
  - [x] Confirm who is hosting/mcing - @rufuspollock will for this call
  - [x] Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) ✅  Blog page link needs to be updated 
- [x] Create Canva graphic using template 🏗️  [Canva Link](https://www.canva.com/design/DAFc2iT9fSw/AXQU_Qsap1THrs18X8bP9A/view?utm_content=DAFc2iT9fSw&utm_campaign=share_your_design&utm_medium=link&utm_source=shareyourdesignpanel)
- [x] Reach out to Boaz for introduction to the topic 🚧 Call moved to October, Draft received from Mathew
- [x] Check graphic with Nathen/Lauren before using ✅  Reviewed 
- [x] Create registration using Zoom ✅  [Registration Link](https://us02web.zoom.us/meeting/register/tZIlce2ppz4rHdJt3uuwCXFzbnpXjM5eG7iV) Note: Update the meeting date for October
- [ ] Create a Google calendar inviting Nathen, Lauren, Boaz to it and include the link to the registration ❌ Not created yet
- [ ] Create the blog post 👉  [Template for Blog Page](https://docs.google.com/document/d/1OzdH54wTWuq1yMMEUUQokjEYvS2ADw1S5weRNeUO9sw/edit) 
  - [ ] Include image, registration link, biography of speaker or description of the event
- [ ] Promotion
  - [ ] Emails
    - [x] Initial announcement (main group) on if newsletter was more than a week ago
    - [ ] Day before announcement (main group) only if initial announcement was more than a week ago
    - [ ] Email reminder (recipients)
    - [ ] Plus in newsletter (if applicable)
  - [ ] Whatsapp
    - [ ] Initial announcement
    - [x] 3 days before
    - [ ] Day before
    - [ ] 1-2 hours 
  - [ ] Twitter
    - [ ] Thread for initial announcement
    - [x] 3 days
    - [ ] Day before
  - [ ] Instagram
    - [ ]  Stories
      - [x] Story template or resharing post
      - [ ] Initial
      - [x] 3 days before
      - [ ] Day before
  - [ ] Post for initial announcement 

Post-event

- [x] Make the youtube video 
- [x] Update original blog post with youtube video plus information
- [x]  Title: Should include name of person, plus keywords/topic
- [ ] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [ ] Update CRM with links etc. 
- [ ] Let the speaker know and make it easily shareable

## Note

Call postponed till October: [Blog Content Docs File Here](https://docs.google.com/document/d/1OzdH54wTWuq1yMMEUUQokjEYvS2ADw1S5weRNeUO9sw/edit?usp=sharing)

**Comment by ZybN** [comment]
the community call focuses on the concept of multi-level resilience building capacity, from individual neurons to entire nations. The core idea is to understand how we have evolved pathways for feeling safe and good, and by comprehending these pathways on neurological, social, and societal levels, we can optimize and "hack" into them. This optimization allows us to enhance resilience at the individual, group, and societal levels, enabling us to effectively face complex problems, cope, collabor
collaborate*
and engage with the world in grounded and stable ways. By strengthening these pathways, we can lead more meaningful and connected lives.

**Comment by laurenwigmore** [comment]
@nathenf  would you have capacity to process this call after Thursday? So I can include a link in the October newsletter next week?

**Comment by laurenwigmore** [comment]
FIXED.
