### ISSUE TITLE
Community Call with Matthew McCarthy

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#630]
Matthew McCarthy | 23-24/08/2023 | The Importance of Uncertainty

## Acceptance

- [x] Community call hosted and recorded 
- [x] Uploaded to Youtube and blog post 

## Tasks

Pre-event

- [x] Confirm speaker
- [x] Collect and confirm details
  - [x] Contact for speaker
  - [x] Time
  - [x] Date
  - [x] Blurb for speaker
  - [x] Profile picture
  - [x] Confirm who is hosting/mcing
  - [x] Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [x] Create Canva graphic using template 
- [x] Create registration using Zoom
- [x] Create the blog post
  - [x] Include image, registration link, biography of speaker or description of the event
- [x] Promotion
  - [x] Emails
    - [x] Initial announcement (main group) on if newsletter was more than a week ago
    - [x] Day before announcement (main group) only if initial announcement was more than a week ago
    - [x] Email reminder (recipients)
    - [x] Plus in newsletter (if applicable)
  - [x] Whatsapp
    - [x] Initial announcement
    - [x] 3 days before
    - [x] Day before
    - [x] 1-2 hours 
  - [x] Twitter
    - [x] Thread for initial announcement
    - [x] 3 days
    - [x] Day before
  - [x] Instagram
    - [x]  Stories
      - [x] Story template or resharing post
      - [x] Initial
      - [x] 3 days before
      - [x] Day before
  - [x] Post for initial announcement 
- [x] Create LinkedIn event/post 

Post-event

- [x] Make the youtube video 
- [x] Update original blog post with youtube video plus information
- [x]  Title: Should include name of person, plus keywords/topic
- [x] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [x] Update CRM with links etc. 
- [x] Let the speaker know and make it easily shareable

**Comment by nathenf** [comment]
FIXED - this is live on the blog and Youtube
