### ISSUE TITLE
Community Call with Isabella Roberts

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#631]
Isabella Roberts | 06/09/2023 | Collective Wisdom Research 

## Acceptance

- [ ] Community call hosted and recorded 
- [ ] Uploaded to Youtube and blog post 

## Tasks

Pre-event

- [x] Confirm speaker
- [x] Collect and confirm details
  - [x] Contact for speaker
  - [x] Time
  - [x] Date
  - [x] Blurb for speaker
  - [x] Profile picture
  - [x] Confirm who is hosting/mcing
  - [x] Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [ ] Create Canva graphic using template 
- [ ] Create registration using Zoom
- [ ] Create the blog post
  - [ ] Include image, registration link, biography of speaker or description of the event
- [ ] Promotion
  - [ ] Emails
    - [ ] Initial announcement (main group) on if newsletter was more than a week ago
    - [ ] Day before announcement (main group) only if initial announcement was more than a week ago
    - [ ] Email reminder (recipients)
    - [ ] Plus in newsletter (if applicable)
  - [ ] Whatsapp
    - [ ] Initial announcement
    - [ ] 3 days before
    - [ ] Day before
    - [ ] 1-2 hours 
  - [ ] Twitter
    - [ ] Thread for initial announcement
    - [ ] 3 days
    - [ ] Day before
  - [ ] Instagram
    - [ ]  Stories
      - [ ] Story template or resharing post
      - [ ] Initial
      - [ ] 3 days before
      - [ ] Day before
  - [ ] Post for initial announcement 

Post-event

- [ ] Make the youtube video 
- [ ] Update original blog post with youtube video plus information
- [ ]  Title: Should include name of person, plus keywords/topic
- [ ] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [ ] Update CRM with links etc. 
- [ ] Let the speaker know and make it easily shareable

**Comment by nathenf** [comment]
NOT FIXED - new issue for this #725 with updated process
