### ISSUE TITLE
[epic] CC101 Launch Strategy and Template for a General Launch Strategy

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#636]
Create a launch strategy that can be used for the #566 and then adapted into a template that can be used for future launches of courses, ebooks etc as needed

For Conscious Coliving 101 we want to have 150 participants in the next 5/6 months (July-end of December)

We expect a rate of 2% lead conversions we need to reach about 7500 people over the next 6 months.

Launch date is Tuesday 18th July

## Acceptance
- [x] CC101 Strategy Document drawn up and available on the Googledrive
- [x] CC101 Strategy steps started and course launched
- [ ] Template Document created and available on the Googledrive
- [x] #657 drafted

### Pre-Launch

- [x] Get setup on Reddit and lurk in subreddits (Lauren & Nathen)
- [x] Sign up for Quora (Lauren)
- [x] Create Promo Video https://www.youtube.com/watch?v=9FE9queHUEw
  - [x] Write video script
  - [x] Do Voiceover
  - [x] Find stock video and music
  - [x] Put together using Davinci Resolve
- [x] [Generate blog post ideas](https://docs.google.com/document/d/1gmLrgNaOLbuPKIhWL4AcuYuOuRjehblcxFbvxqWuFO8/edit)
  - [x] Review and select 8 to begin
  - [x] Create content schedule until December
- [x] Announce in Newsletter
- [x] "We're creating a coliving course..." post ASAP
  - [x] Twitter
  - [x] Instagram
  - [x] Linkedin
  - [x] Blog post ⏭️ https://github.com/life-itself/community/pull/654
- [x] Tell Whatsapp community about pre-apply and date for release on Thursday 13th
- [x] Internal Communication about the launch - and suggest and recommend ⏭️ 
- [x] Backlog of content ready #657 
  - [x] All pre-launch and launch content prepared
  - [x] 8 blog posts prepped and broken down into Tweets
- [x] List of potential people to have on calls
  - [x] Get list of people until December
- [x] Identify key entry points to access audience (AKA which FB Groups, subreddits)
- [x] Ask internal and others to share with their networks

### Launch 18th July 

- [x]  Official launch email
- [x] Tweet
- [x] Whatsapp Chat
- [x] Update Blog post
- [x] Post in relevant subreddits
  - [ ] Post draft 
- [x] Linkedin post 
- [x] Instagram 
- [x] BONUS: Youtube video about the conscious coliving course.

### Post-Launch (Ongoing Tasks)

**Weekly output:**
- Minimum 1 article a week for conscious coliving, ideally 2 a week
- 2 thread for Twitter
- Linked in post
- Share to reddit
- Share to 2-3 facebook groups
- Reach out to 5 media spaces to get featured on (AKA podcasts, blogs, etc.)
- In weekly comms meeting decide on FB, Reddit and LinkedIn group and construct aligned posts to promote in those groups
- Instagram -  (use twitter text or blog post as a carousel)

**Monthly output:**
- Featured on 1 podcast (ideal but aspirational not optional)
- Guest post on 1 blog  (ideal but aspirational not optional)
- Promoted in 1 other newsletter/email (ideal but aspirational not optional)
- 2 community calls with Conscious Coliving relevant experts

### As and when tasks

- [ ] Reach out to Community finders to present our course and invite for community call
- [ ] Analyze and extract inspiration from Community Finders website
- [ ] Put course up as a free resource on online teaching platforms
  - [ ] Udemy
  - [ ] Teachable
  - [ ]  Skillshare

## Launch strategy brainstorm

[Strategy Plan](https://www.canva.com/design/DAFn3eFYdtk/zzVYlfelC84k2L6Gg7mzOA/edit)

**What can our sources be?** 
- Primary
	- Mailing list: 300 people approx
	- Whatsapp group: 80 people approx
	- Twitter: :fire: potential here to reach a lot with good strategy
	- Instagram: :x: 
	- Youtube: :question: 
	- Google through blog posts: :question:
	- Linkedin: We need access but wait and see 
	- High SEO ranking blog posts - lists, 
- Secondary 
	- Who can we get to share in our circles
		- Emerge
		- Advaya
		- People in the Whatsapp community
		- Look through curation group for emails that might share us
	- Need to create email template/rough idea of what we will say 
- Tertiary 
	- Rank on google through blog posts
    - Facebook groups about coliving
		- Ideas
			- Coliving groups
			- Uni groups
			- Digital nomad groups
			- Spiritual groups
			- Community living
			- Homesteading 
			- Permaculture groups
			- Helpx, Wwoofing, Workaway, Couchsurfing, Spareroom
		- Create a template message - although will be different for each group/audience
		- Create Facebook page for the course
		- Get the page to join groups 
	- Reddit
		- Find subreddits
		- Answer top questions
		- Create own posts around 
	- Podcasts (guest)
		- Community living podcasts
		- Self-development 
	- Medium article
		- Chat gpt to write article from the course
		- Conscious Coliving 101
	- Quora Questions
		- Finding the right places where questions get asked
	- The community orgs we share in the course
		- Reach out once course is live 
	- Paid Ads

**Content Ideas:**
- Breaking down the course
	- Top red flags
	- Places to find coliving
	- Myths
	- Benefits 
	- https://communityfinders.com/community-living-books/
		- https://lifeitself.org/blog/2021/05/14/notes-on-creating-a-life-together-by-diana-leafe-christian
 - Use answer the public 
 - Intentional communities etc into google - see top Qs to use for blogs/reddit/twitter
 - atomic essays (short blog posts - see ship30for30)

**Considerations**
- Our community calls should be relevant to conscious coliving
	- Ilja to talk about hosting a coliving space
	- Tamera spokesperson
	- Findhorn
	- Auroville
	- Alnoor Ladna - Brave Earth
- If we have someone is really good on a call, create a masterclass which can then be bonus for the course or an upsell

**Comment by laurenwigmore** [comment]
@nathenf Reddit and FB group posts need to be discussed still (next week?). Otherwise all launch promo has been completed.

**Comment by nathenf** [comment]
@laurenwigmore I think we just need to document our launch and promotion process in a document (or Tao) and then close this issue.

**Comment by laurenwigmore** [comment]
@nathenf yes agreed

**Comment by nathenf** [comment]
@laurenwigmore I've started writing up the launch strategy template or guide. It's rough and not detailed. https://docs.google.com/document/d/1scGq_VXZIxn9m8uILn82-HiSsbG9Y3tsKWjQa3cnLC0/edit  

I think we should create another issue for this and close this one now as all the information is captured.

**Comment by nathenf** [comment]
FIXED - Since launching the CC101 we have 176 attendees and have generated 12 blog posts about conscious coliving which redirect to the course. We have promoted in several groups on Facebook, Linkedin and Reddit. As a result of this there has been a notable jump in the Whatsapp community of people joining from these other places. 

NOTE: The launch strategy is being drafted here: https://docs.google.com/document/d/1scGq_VXZIxn9m8uILn82-HiSsbG9Y3tsKWjQa3cnLC0/edit and #864 has been opened to complete this task.
