### ISSUE TITLE
Promotion of Deliberately Developmental Spaces Project

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#638]
To promote to a wider audience and create awareness around the Deliberately Developmental Spaces project.

## Acceptance
- [x] Thread created on twitter
- [x] Featured in July newsletter 
- [x] IG post
- [x] LinkedIn post

## Tasks

- [x] Publish Manifesto 
- [ ] Promote Manifesto

### For Zaib 

- [x] Draft and post LinkedIn post from original blog (link to other orgs) - Please check draft with Lauren/Nathen before sending out
- [x] Draft tweet thread - Please check draft with Lauren/Nathen before sending out
- [x] Draft IG post - Please check draft with Lauren/Nathen before sending out
- [x] Find out if there are any CTA's - CTA is go read the blog posts 
- [x] [Link of Promotional Material Ready for Review](https://docs.google.com/document/d/1ViTerMTzUNaf33uoz9W0abFXABgoTU8VdelYLILJXfU/edit?usp=sharing)

### For Lauren/Nathen
- [ ] Add DDS into wider Comms Plan
- [ ] Find out time frames required for promo of project (Nathen or Lauren to call with Boaz or Catherine)
- [ ] Create strategy if needed

## Notes
[Main Blog post](https://lifeitself.org/blog/2023/06/20/building-field-for-developmental-spaces)
[Secondary older blog post](https://lifeitself.org/blog/2021/10/05/deliberately-developmental-spaces-a-key-to-addressing-the-metacrisis)
[Research page](https://lifeitself.org/initiatives/building-the-field-for-developmental-spaces)

**Comment by nathenf** [comment]
Last discussion between myself and Boaz is that he wanted to create a separate website for the DDS project. This was outside of my bandwidth and I told Boaz to discuss with Rufus. @BoazBF where are you at with this?

**Comment by laurenwigmore** [comment]
> @nathenf the manifesto is now shipped at https://developmentalspaces.org. I think we could promote this end of November in the next newsletter etc. Have changed iteration accordingly.

I've added a note to the November Newsletter issue

**Comment by rufuspollock** [comment]
FIXED. All done.
