### ISSUE TITLE
July Newsletter

### ISSUE THREAD

**Issue by ZybN** [life-itself/community#642]
## Acceptance 

- [ ] Newsletter is sent

## Tasks

- [x] Create a Newsletter 
- [ ] Test Newsletter
- [ ] Send Newsletter

## Notes 

**Life Itself Labs becomes Life Itself Research**
https://lifeitself.org/notes/research-at-life-itself-2023 

## **Life Itself General**
  - [x] New Team Members
- Jake hirsch as an intern
- Boaz Feldman as researcher
- Matthew McCarthy as researcher
- Marc and Liubov directors of research at Life Itself
- Lauren Wigmore as Communications 
- Zaib communications officer
- [ ] Datopian 'How to guide' summary 
- [x] Conscious Co-Living Course 
- [x] Conscious Co-Living Blog Posts
- [ ] Once Upon a Time Podcast Series? ❓ Yes or No?

## **Community Calls**

To Watch
- [x] With Fabienne: https://lifeitself.org/blog/2023/06/29/future-of-education-with-fabienne-vailes
- [ ] With Liam: https://lifeitself.org/blog/2023/06/29/climate-majority-project-with-liam-kavanagh

Up next

- [x] Jan
- [x] Matthew 

 
## **Research Community Calls**

- [ ] Share recording and next forum 
- [ ] Research Community Call with Liam and Marc: https://lifeitself.org/blog/2023/07/05/research-forum-4-marc-santolini-liam-kavanagh

## **Residencies**

**Conscious Coliving 101 is live**

**New Blog Posts/Podcasts/etc**

**Comment by laurenwigmore** [comment]
@matthewmccarthy11 link to [text to add](https://docs.google.com/document/d/1vsuZWDAkdaR12kmbsNgRcIdvtPSF1tEJ7DlUfTE-mH8/edit) related to a form we are requesting people fill in

**Comment by nathenf** [comment]
FIXED - Newsletter went out today
