### ISSUE TITLE
Problem Cloning the Github Community Repo to use in Obsidian 

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#643]
Working to find a solution to help anyone having problems cloning the Github Community repo to use within Github Desktop/Obsidian. 

## Acceptance
- [ ] Lauren can use Github Desktop and Obsidian to create content to be published on the LI website

## Tasks
- [ ] Share screenshots and information related to the error here
- [ ] Try out suggested solutions from the tech team
- [ ] Update SOPs #623 to include this solution for future LI members/issues

## Notes
I'm using Windows. 

Process:
![image](https://github.com/life-itself/community/assets/132304704/4254258b-b8cc-4d7c-acc2-676918aebfd2)

**Error Message**
Cloning into 'C:\Users\laure\OneDrive\Desktop\community'... remote: Enumerating objects: 10041, done. remote: Counting objects: 100% (2802/2802), done. remote: Compressing objects: 100% (1183/1183), done. remote: Total 10041 (delta 1668), reused 2504 (delta 1585), pack-reused 7239 Receiving objects: 100% (10041/10041), 60.47 MiB | 525.00 KiB/s, done. Resolving deltas: 100% (3983/3983), done. Updating files: 100% (2374/2374), done. Downloading content/assets/images/giselle-skeena.jpg (175 KB) Error downloading object: content/assets/images/giselle-skeena.jpg (4531d15): Smudge error: Error downloading content/assets/images/giselle-skeena.jpg (4531d15834d6409a297aeddd74336cff76bb608b29428cf458d0c335144223f9): batch response: Post "https://github.com/life-itself/community.git/info/lfs/objects/batch": dial tcp: lookup github.com: no such host Errors logged to 'C:\Users\laure\OneDrive\Desktop\community\.git\lfs\logs\20230714T123752.1800755.log'. Use `git lfs logs last` to view the log. error: external filter 'git-lfs filter-process' failed fatal: content/assets/images/giselle-skeena.jpg: smudge filter lfs failed warning: Clone succeeded, but checkout failed. You can inspect what was checked out with 'git status' and retry with 'git restore --source=HEAD :/'

[Source/instructions Lauren used for the above](https://docs.github.com/en/desktop/contributing-and-collaborating-using-github-desktop/adding-and-cloning-repositories/cloning-a-repository-from-github-to-github-desktop)

**Comment by laurenwigmore** [comment]
@matthewmccarthy11 Nathen mentioned you may have had a similar issue as the above and were able to solve it? Could you help if so 🙏

**Comment by nathenf** [comment]
FIXED - Lauren now has Obsidian 🎉
