### ISSUE TITLE
Zaib tweak the podcast SOP

### ISSUE THREAD

**Issue by ZybN** [life-itself/community#655]
When I am publishing a podcast episode, I want to have a standard operating procedure so that I can prioritize tasks and improve efficiency. 

## Acceptance

- [x] SOP Document Created
- [ ] Template Shared on Website under Comms Guide 

## Tasks

- [x] Draft process doc 🚧 [Draft Ready to be Reviewed](https://docs.google.com/document/d/1tFBXgKM9w6VRMoDymdlV5cJ0GXWqu-OJlFeyZfkyV58/edit?usp=sharing) 
  - [x] Review the [Old Document ](https://lifeitself.org/tao/communications/producing-a-podcast-episode-guide)
  - [x] Edit the Guide for Uploading to YouTube 
  - [x] Edit the Guide for Uploading to Spotify (Previously Anchor)
  - [x] Edit the Guide for Podcast Page on the Website 

### Notes
- [ ] Blog and Transcript are added on the Podcast Page

**Comment by ZybN** [comment]
UNDER REVIEW: 

This will be reviewed by @laurenwigmore while working on the Joseph Henrich Podcast #664

**Comment by nathenf** [comment]
@laurenwigmore @ZybN I've added some comments for experimentation with AI and also where we need to edit and expand. Happy to support here if needed, but I think between you you can really iterate this SOP. 

One big suggestion is to turn this into two separate SOPs - one for the creation of the podcast and another then for the promotion. I think the second has similarities to community calls promotion, blog promotion etc. The first is pretty clean cut whereas the second requires curation, creativity. 

There is also the possibility to separate content creation from content publishing and scheduling. The latter part can be a simple documented process.

**Comment by laurenwigmore** [comment]
FIXED. SOP available on the Googledrive.
