### ISSUE TITLE
People's Page SOP

### ISSUE THREAD

**Issue by ZybN** [life-itself/community#656]
When I am adding a new profile or updating the People's page, I want to have a standard operating procedure so that I can create new profiles efficiently and accurately. 

## Acceptance

- [ ] SOP Document Created
- [ ] Template Shared on Website under Comms Guide 

## Tasks

- [ ] Draft process doc 
- [ ]

**Comment by nathenf** [comment]
FIXED - We have recorded a video tutorial on how to update the team section and added this to the Comms SOPs section.
