### ISSUE TITLE
[epic] Content calendar for comms posting July-Dec 2023

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#657]
Editorial calendar mapping out the next 6 months to provide an overview of the weekly comms content and dates to post. This will include blogs, posting on LinkedIn, IG and Twitter and in FB groups, Reddit Groups. *note each item should have its own issue created and linked to this epic

#636 for post launch actions that may need to be included later e.g. blog post on a podcast feature

- Organisational Feature - Topic TBC ⛰️ on sparse weeks
- Use polls in WA group chats for engagement
- [Content to post in groups doc](https://docs.google.com/document/d/1sKgvepNVVBQrWYmTuS19I0j2yWi4x99ReggZljpk1Gg/edit)

## Acceptance
- [ ] Plan drafted below
- [ ] All content posted 

## Calendar
**Week 30** _w/c 24th July 2023_
- [x] CC101 Blog Post & Promo - #662
- [x] #671
- [x] Tenzo Note # 9 
- [x] Outreach in 1 [FB Group](https://www.facebook.com/groups/1080313605696014), [LinkedIn Group](https://www.linkedin.com/groups/8334169/) 🚧 waiting for approval & Subreddit self sufficient group ✔️ 
- [ ] Main topic of conversation in WA Group - Are Ecovillages the best way to live? ❌ let's drop this for now as we do not have capacity and there is generally a decent flow of conversation. 
 
**Week 31** _w/c 31st July 2023_
- [x] #702
- [x] Community Call w Liam Kavanagh Updated 
- [x] Research Forum Post Update
- [x] Community Call Blog Post & Promo (for call taking place on week 33) #682  
- [x] Outreach in 1 FB Group, LinkedIn Group & Subreddit

**Week 32** _w/c 7th August 2023_
- [x] #663 
- [x] Continue Community Call Promo for call this week #682  
- [x] Research Article - Boaz reflection on time in German Ecovillage ❌ *not completed*
- [x] Outreach in 1 FB Group ✅ , LinkedIn Group & ✅ Subreddit  ❌ *not completed*
- [x] Whatsapp chat - promo of Osa's study
- [ ] Whatsapp chat or email announcement? re the Insights Form (no one has completed as of 4th Aug - or carry over into August newsletter?) ❌ *not done due to wider qualitative project*
- [ ] Post re Joe Henrich podcast/series? #664 🚧 *still in progress*

**Week 33** _w/c 14th August 2023_
- [x] CC101 Blog Post & Promo - Topic #712 
- [x] Outreach in 1 [FB Group](https://www.facebook.com/groups/312167269342975/) , LinkedIn Group ❌ _not sure how useful LinkedIn groups are_ & Subreddit ✔️ 
- [x] Community Call Blog Post ✅  & Promo (for call taking place on week 34) - #630 
- [x] Community Call Blog Post & Promo (for call taking place on week 36) #725 
- [x] Research Article - Boaz reflection on time in German Ecovillage #727 

**Week 34** _w/c 21st August 2023_
- [x] CC101 Blog Post & Promo - #735 
- [x] Community Call Promo #630 
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit
- [ ] Post re Joe Henrich podcast/series? #664 

**Week 35** _w/c 28th August 2023_
- [x] #765
- [x] Last weeks Community Call Updated #630 
- [x] Community Call Promo #725 
- [x] Matt to write article on Moral Agency @matthewmccarthy11 ❌ _carried over_
- [ ] Community Call Blog Post & Promo (for call taking place on week 38) - #717 ❌ _Alan not supplied info carried over_
- [ ] Tenzo Note - Topic TBC ❌ _Valerie hasn't had the capacity to do_
- [ ] Outreach in 1 FB Group awaiting approval and will post in https://www.facebook.com/groups/2152029665072491/, & Subreddit - _@selfreliance group on subreddit - post was rejected twice_ 🚧 
- [x] Values challenge/initiative post
- [ ] Promo books list blog on IG and twitter

**Week 36** _w/c 4th September 2023_
- [x] #775
- [x] Community Call Blog Post & Promo (for call taking place on week 38) - #717 
- [ ] Guest Post or Special Feature - Suggested announcement of Joe Henrich podcast series? 
- [x] Research Article - Moral Agency @matthewmccarthy11  (?)
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit

**Week 37** _w/c 11th September 2023_ ❌ minimal completed this week
- [ ] CC101 Review (book, documentary etc)- #773 - turned into a discussion 
- [ ] Research Forum Post Update @matthewmccarthy11 is this possible? 
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit
- [ ] Main topic of conversation in WA Group - TBC
- [x] Values Rally post updated 
- [ ] Joe Henrich Podcast Series
- [ ] Cohere+ on Socials IG / LinkedIn / Twitter

**Week 38** _w/c 18th September 2023_ 
- [x] #825
- [ ] Research Forum Updated @matthewmccarthy11 any updates?? **we've decided not to do the RF's for now, once we decide to pick it up again I'll send a reminder**
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit
- [x] Main topic of conversation in WA Group - Values/Community Call 
- [x] Organisational Feature - Intern and Fall Residencies
- [x] Joe Henrich Podcast Series

**Week 39** _w/c 25th September 2023_
- [x] #830
- [x] Last weeks Community Call Updated 
- [ ] Research Forum Post 
- [ ] Blog post announcing the DDS Event
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit
- [ ] Main topic of conversation in WA Group - ?? 
- [x] Tenzo Note #10 - Topic TBC

**Week 40** _w/c 2nd October 2023_
- [x] #845
- [ ] Guest Post or Special Feature - Values Day (18th Oct) ?? ❌ values initiative changed
- [ ] **Outreach in 1 FB Group,& Subreddit**
- [x] Creativity/Art post - Sylvie's Art to Social Awakening
- [x] DDS blog post- 'Immersion'
- [x] Community Call Blog Post & Promo (for call taking place on week 41) - Myka

**Week 41** _w/c 9th October 2023_
- [x] #854
- [ ] Sylvie's 2nd blog - 
- [x] Community Call Blog Post & Promo (for call taking place week 43) ✔️ completed in week 41
- [ ] #860
- [x] Outreach in 1 FB Group, LinkedIn Group & Subreddit 🔥 

**Week 42** _w/c 16th October 2023_
- [ ] CC101 Blog Post & Promo - TBC ❌ 
- [ ] #629 promo @alexianetcu @matthewmccarthy11 - can you work together to action this? 
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit 🚧 N: I have done Facebook and LinkedIn
- [x] Values week 2 post & promo of call #718 
- [x] Last weeks Community Call Updated 

**Week 43** _w/c 23rd October 2023_
- [ ] https://github.com/life-itself/community/issues/832
- [ ] CC101 Blog Post & Promo - 10 Ecovillages to Visit in Europe ❓ 
- [ ] Values jam call collective blog post
- [x] Community Call Blog Post & Promo (for call taking place on week 44) - For Boaz Call
- [ ] Research Forum Post 
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit - @laurenwigmore Nathen's whatsapp request

**Week 44** _w/c 30th October 2023_
- [ ] CC101 Blog Post & Promo -  #772
- [ ] Community Call Blog Post & Promo (for call taking place on week 45)
- [ ] Tenzo Note - Topic TBC
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit
- [ ] Main topic of conversation in WA Group - TBC

**Week 45** _w/c 6th November 2023_
- [ ] CC101 Review (book, documentary etc)
- [ ] Community Call Blog Post & Promo (for call taking place on week 46)
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit

**Week 46** _w/c 13th November 2023_
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit 

**Week 47** _w/c 20th November 2023_
- [ ] CC101 Blog Post & Promo - 10 Ecovillages to visit in Europe
- [ ] Community Call Blog Post & Promo (for call taking place on week 50) TBC
- [ ] Organisational Feature - Topic TBC
- [ ] Research Forum Post 
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit
- [ ] Main topic of conversation in WA Group - ?? 

**Week 48** _w/c 27th November 2023_
- [ ] CC101 Blog Post & Promo - 
- [ ] Research Article - 
- [ ] Tenzo Note - Topic TBC
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit
- [ ] Main topic of conversation in WA Group - TBC

**Week 49** _w/c 4th December 2023_
- [ ] CC101 Review (book, documentary etc)- TBC
- [ ] Community Call Blog Post & Promo (for call taking place on week 50)
- [ ] Organisational Feature - Topic TBC
- [ ] Research Forum Post Update
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit
- [ ] Main topic of conversation in WA Group - TBC

**Week 50** _w/c 11th December 2023_
- [ ] CC101 Blog Post & Promo - TBC
- [ ] Tenzo Note - Topic TBC
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit
- [ ] Main topic of conversation in WA Group - TBC 

**Week 51** _w/c 18th December 2023_
- [ ] CC101 Blog Post & Promo - 
- [ ] Last weeks Community Call Updated 
- [ ] Community Call Blog Post & Promo (for call taking place on week 52) TBC
- [ ] Organisational Feature - Topic TBC
- [ ] Research Forum Post 
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit
- [ ] Main topic of conversation in WA Group - ?? 

**Week 52** _w/c 25th December 2023_
- [ ] CC101 Blog Post & Promo - 
- [ ] Guest Post or Special Feature - Topic TBC 
- [ ] Research Article - 
- [ ] Outreach in 1 FB Group, LinkedIn Group & Subreddit
- [ ] Main topic of conversation in WA Group - TBC

## Processes to follow
These can be copied and added to the individual issues and information filled in accordingly

### Conscious Coliving Blog Post (and others where relevant)
 - [ ] Blog Post Published with engaging image
   - [ ] Repositioned for LinkedIn post
   - [ ] Write Twitter thread use [Ship30for30](https://www.ship30for30.com/post/how-to-write-a-twitter-thread) for guidance of how to write a good thread
   - [ ] Post on IG (carousel of twitter thread)
   - [ ] Post in relevant subreddits and/or FB groups (add details of groups)
   - [ ] Whatsapp groups post? 

### Community / Research Calls
[Pre and post event process here](https://docs.google.com/document/d/1N6fkZh-tZZ7ZBmK3dZpTmjTgYdM_8-FKE5sZV5G0JfA/edit#heading=h.jf0ssyjxsimy)

**Comment by nathenf** [comment]
FIXED - This is no longer in use as we are tracking elsewhere and this hasn't been updated since end of October
