### ISSUE TITLE
6 Reasons to Join a Conscious Coliving Environment CC101 Blog Post

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#662]
Week 30 - w/c 24th July 2023 blog post for Conscious Coliving is [6 Reasons to Join a Conscious Coliving Environment](https://docs.google.com/document/d/1l5UK1PKeR6Z-TK_rg_mtH5ZgKPR_JO7pmkhViSocA4M/edit?usp=drive_link)

## Acceptance
- [x] Blog post is live ✅ #670 
- [x] All social media promo is completed

## Tasks
 - [x] Blog Post Published with engaging image ✅ https://lifeitself.org/blog/2023/07/24/6-reasons-to-join-a-conscious-coliving-environment
   - [x] Repositioned for LinkedIn post
   - [x] Write Twitter thread use [Ship30for30](https://www.ship30for30.com/post/how-to-write-a-twitter-thread) for guidance of how to write a good thread
   - [x] Post on IG

**Comment by nathenf** [comment]
FIXED - These posts are now complete
