### ISSUE TITLE
Top 3 Benefits of Conscious Coliving CC101 Blog Post

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#663]
Week 32 - w/c 7th August [Top 3 Benefits of Conscious Coliving](https://docs.google.com/document/d/1avvvD9rMQCONwguBo0aAfZHyqSOxlqUYczQ5TZZ8O-M/edit?usp=drive_link)

## Acceptance
- [x] Blog post is live
- [x] All social media promo is completed

## Tasks
 - [x] Blog Post Published with engaging image 🚧 trialed midjourney ... 😬 used free stock image
   - [x] Repositioned for LinkedIn post
   - [x] Write Twitter thread use [Ship30for30](https://www.ship30for30.com/post/how-to-write-a-twitter-thread) for guidance of how to write a good thread 🚧 at bottom of blog post doc
   - [x] Post on IG - designed need some photo images to break up the feed before posting - https://www.canva.com/design/DAFp0sAE8Cg/TlDs1v-GH7VwCX295G3erA/edit

**Comment by laurenwigmore** [comment]
FIXED. All actions completed.
