### ISSUE TITLE
Publish Joseph Henrich Podcast ep.2

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#664]
Use the Podcast SOP and publish the Joseph Henrich Podcast

[Draft SOP for review/to follow](https://docs.google.com/document/d/1tFBXgKM9w6VRMoDymdlV5cJ0GXWqu-OJlFeyZfkyV58/edit)

## Acceptance 

- [ ] Conversation published on Youtube & Anchor. 
- [ ] Blog Post containing all content published.
- [ ] Episode page added to the website.
- [ ] Guest informed that the episode is out and has been sent the links.
- [ ] The new episode has been announced on Twitter.
- [ ] Email announcing a new episode has been sent to mailing list.
- [ ] Secondary content has been shared on social media

## Tasks

- [x] Copy this Template into a new GitHub issue. Name the issue as the working title of the conversation
- [x] [Create a new folder for the conversation and assets here](https://drive.google.com/drive/folders/12BskqKPp85XNdU2sespI--E7VPi45hGJ?usp=sharing) - 📂 [Exact Folder Link](https://drive.google.com/drive/folders/1cJRGGmWLZpzWX8sNkP_09Bvf92Jx3nBa?usp=drive_link) and [Culturology Link](https://drive.google.com/drive/folders/1dpP6gxfdor0y0SRSmLQzRrShW4VIjfSq?usp=drive_link)
- [x] Source the video file and add to folder
- [x] Create a document for the conversation that includes: Title, Conversation Summary, About the person in conversation, links to resources mentioned in the podcast, timestamps for at least two video excerpts and two quotes and timestamps for ["chapters"](https://www.youtube.com/watch?v=pvkTC2xIbeY). Add this to folder. 
- [x] Watch the video. Note any moments that need edited e.g. moments of bad internet connectivity. Note down timestamps for chapters to be used when publishing to YouTube. Note timestamps of short sections that will be good for social media (max length for twitter 2m20s) and note down quotes that will be good for marketing the episode.

#### Create Youtube video
- [x] Create the Youtube Thumbnail from [this template](https://www.canva.com/design/DAE99drPH4s/7mR8CgHWyHfimwC9jDerDA/edit?utm_content=DAE99drPH4s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).
- [x] Edit the video file in [Da Vinci Resolve](https://www.blackmagicdesign.com/products/davinciresolve):
  - [x] Trim beginning and end, plus any sections of poor internet connection or other interruptions
  - [x] Add thumbnail at the beginning of the video with a fade transition to the video ✔️ _no fade done though and the thumbnail was added in Youtube_
  - [ ] Add graphic overlay ["Please Like & Subscribe"] ❌ (https://drive.google.com/file/d/1iQjSdgjTyrN9xnQ8Xnlzdjmk2sw2eKXJ/view?usp=sharing) at the 5, 10, 20, 40 minute
  - [x] [Add End Screen with a fading transition](https://drive.google.com/file/d/1fC8c_tyoOxxGGhGqgJuwFscu6vYzbrqe/view?usp=sharing)
  - [x] Increase the sound volume as much as possible without clipping the sound (around 3 is normally good) 
- [x] Export as Video for Youtube
- [x] Export audio only for podcast
- [x] Upload to Youtube: Add title, thumbnail, summary including [contents chapters](https://www.youtube.com/watch?v=pvkTC2xIbeY), page stub URL, add to relevant playlist, Add Language, Make License Creative Commons. - https://youtu.be/Ct1mq0sxrMI
- [x] Schedule publication for desired day and time 🚧 _currently saved as draft for Nathen to review_

#### Create Podcast
- [x] In Anchor click new episode then click create new episode. Click on reuse your previously uploaded audio and scroll down until you find the "Intro Jingle". Drag the file in the box into the right. Add the audio-only edit of the episode after the intro. Click save episode.
- [x] Add title & summary.
- [x] Create and add thumbnail from [this template](https://www.canva.com/design/DAE87pGGDUg/EgrVC9iJX5eATZGF5rE2pg/edit?utm_content=DAE87pGGDUg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
- [ ] Add season number and episode number ❓ _couldn't see this on others_
- [x] Schedule publication for desired day and time 🚧 _Nathen to review scheduled 7/09 11.11am_
  
#### Create blogpost
- [x] Draft blogpost prior to scheduled publication of the episode on YouTube and Anchor. 
- [x] Add a new blog in the vault/blog folder in the Community repo. 
	- [x] Follow the format: put it in date structured folders eg. vault -> blog -> 2023 -> 01 -> 16 -> blog-file-name.md. For the frontmattter fields have a look at any of the other blog posts within that folder and follow that format. Once added commit the new file as you usually would. For more directions on how to add to the website see the [Web3 site contributors' guide](https://web3.lifeitself.org/meta/editing) and/or the [ecosystem mapping site guide](https://ecosystem.lifeitself.org/contributors-guide).
- [x] You can add in the YouTube link as you can access that even before the video is published, however you can't with the Anchor link. Once the podcast is published, source the embed link to the episode found when you click on the episode on Anchor and paste into the blog (use previously published podcast blog posts as a guide).
- [x] The blog should feature a brief introduction of the guest and an intro to the episode (eg v brief overview of what is discussed).
- [x] Add any notes. Ensure they are complete, comprehensive and tidied.
- [x] Add any references and further reading
- [x] Add the transcript ❓ _add it here as well as on the podcast page?_
	- [x] Run the video through Otter to generate the transcript. Go through and fix any errors. Export as docx with speaker names and timestamps.
	- [x] Copy the transcription into a Google doc and save it in the episode folder. 
	- [x] Convert into markdown. Copy and paste into a blog post.

#### Next
- [x] Once the episode is published to YouTube and Anchor, publish the blog post with the links. Once the blog post is published, edit the YouTube and Anchor episode bios and paste in the link to the blog.
- [x] Once the YouTube video, podcast episode and blog post are published, **create a page for the episode on the [podcast page](https://lifeitself.org/podcast) of the website.**
	- [x] Add a new page in the vault/podcast in the community repo. Use [Jeffery Martin episode page](https://lifeitself.org/podcast/a-scientific-approach-to-awakening-and-fundamental-wellbeing-podcast) as a guide. Generate the links for the frontmatter:
		- [x] Follow this link: https://rss2json.com/
		- [x] Paste this link in the box on the page (under the text that says Enter the URL to your RSS feed): https://anchor.fm/s/79b39934/podcast/rss 
		- [x] Find the podcast episode you are wanting to create the page for (likely the first episode listed, this will be the first episode under the line that says "items")
		- [x] Click the button with 4 arrows pointing outwards to make it full screen to ensure you don't copy only part of a link.
		- [x] Copy the link for "thumbnail" and paste it after "image:" in the front matter.
		- [x] For the src link, scroll down to where it says "enclosure" and copy the link that follows "link". Paste this after "src" in the front matter. 
		- [x] Fill out the rest of the frontmatter.
	- [x] Paste the same short intro to the episode and guest as used in the blog post below the frontmatter. Paste the youtube link and the link to the blogpost. 
- [ ] **Inform the guest that the episode is out.** Send all links and encourage them to share.
- [ ] **Send email out to Life Itself General Audience on Mailchimp** announcing that the latest episode of the Life Itself Podcast is now available. Use the same intro to the episode and guest as used in blog. Paste link to the podcast page - they can navigate to everything they need from that one link. Use a previous podcast episode launch email as a guide - you can replicate that email, just remember to change the text, link, subject line and preview text. 
- [ ] **Announce release on Twitter.** Make sure to @ the guest and tweet the link to the podcast page. 

## Podcast Landing page content

**Comment by laurenwigmore** [comment]
@rufuspollock I'm working through creating a podcast using the Joseph Henrich recordings. 
You mentioned you wanted to make this into a series .... I've downloaded both conversations (one titled Podcast, one Culturology Part II) onto the [Gdrive](https://drive.google.com/drive/folders/1Yog4g2xX8alJJ_CuWE6YlPl7T0XAYjkf?usp=drive_link). 

From our conversation my understanding is that these recordings will be divided up and a new series created. 
Three questions:
- [ ] Will both the Podcast and Culturology recordings be used in the series? 
- [ ] Should I decide on where to divide them? 
- [ ] Do you have a title for the series?

**Comment by rufuspollock** [comment]
> From our conversation my understanding is that these recordings will be divided up and a new series created.
Three questions:

First, i think i reflected on this at the end of our last meeting and you could relisten to the recording there as quite useful i think in giving context.

- Will both the Podcast and Culturology recordings be used in the same series? **✅2023-07-28 yes this is one series.**
- Should I decide on where to divide them (or you)? **✅2023-07-28 see comments below**
- Do you have a title for the series? **✅2023-07-28 "Cultural Evolution: An Introduction" (or "Cultural Evolution: A new discipline is born" if you want something more dramatic.*

Series:

- Episode 1 (original podcast): "Culturology and Cultural Evolution: Emergence of a New Field"
- Episode 2: "Homo Sapiens: The Cultural Species" (first new recording)
- Episode 3: "Cultural Evolution: Culture, Cultural Evolution and the Scaling of Societies" (part 1 of the second new recording)
- Episode 4: "Cultural Evolution: Implications and what's next" (part 2 of the second new recording)

Note: if we kept things easy we could just have episode 3 and 4 together as one big 3h recording and go with that.

**Comment by laurenwigmore** [comment]
@nathenf would you be able to review the Spotify podcast and the YouTube video and let me know if they're all OK as per previous ones. The draft podcast page has also been done minus the src link - obsidian://open?vault=content&file=podcast%2Fhomo-sapiens-the-cultural-species
Blog post created for the series here: 

Questions - 
- [ ] shall we publish all 3 episodes together? or is it best to stagger them?
- [ ] we will create a learn page for these episodes, but do we need to do anything else on the podcast page for this series?

**Comment by laurenwigmore** [comment]
- [ ] Create a learn page for all 4 episodes #568

**Comment by laurenwigmore** [comment]
> @laurenwigmore what's the timeline on this? I'd like to share this 😄

@rufuspollock I've asked Nathen to do a quick review as these were the first podcasts I have done, but basically everything is ready to go live. I do still need to do the Learn page for this though and potentially tweak the blog post - as it was mentioned the copy on the blog was too descriptive and would work better as the copy for the Learn page. 
But to answer your question I will release and make all amends by mid next week.

**Comment by nathenf** [comment]
@laurenwigmore I've made some notes on the PR and here are some additional notes: 

- On Spotify the thumbnails are the black of Web3 episodes rather than the usual yellow ones (that you've used for the Youtube) - As a side note actually a review of the thumbnails should be done as I can see Jamie Bristow is incorrect and Jefferey Martin ones are incomplete (no outline box)
- Once the learn page is complete, again link to this in the Spotify notes
- I would also add "For a full transcript and further information about the episode please visit [insert podcast page here]"
- On youtube again I would link to the learn page and individual podcast pages for the transcript
- Be sure to go back and edit episode 1 as well to align the copy and add in links to the learn page and podcast

**Comment by nathenf** [comment]
@laurenwigmore otherwise FANTASTIC 🎉

**Comment by nathenf** [comment]
@laurenwigmore is this complete and ready to close?

**Comment by laurenwigmore** [comment]
@nathenf I just need to update the thumbnails on Spotify still - I missed this previously. So will action this week and then close.

**Comment by laurenwigmore** [comment]
FIXED. Completed, all published.
