### ISSUE TITLE
Comms Iteration 24: 24th July-6th August

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#665]
## Tasks
♾️ ♾️ 
- [ ] #454
- [ ] #657
- [ ] #624 for reference
- [ ] #636 for reference

🔥 🔥 🔥 
- [ ] LI outreach/marketing material produced for the Hub by 7th Aug #673 @laurenwigmore @nathenf 🚧 **Phase 1 is complete and materials printed for the hub. Phase 2 for next iteration**
- [x] Week 30 completed from #657
- [ ] Continue with #623 
  - [ ] #585 @nathenf 🚧 **80% done before being reviewed and tested**
  - [ ] podcast SOP finalised - #655 #664  @ZybN @laurenwigmore  ❌ not completed due to absence. Lauren to do in next iteration.
  - [x] peoples pages SOP written #656 **Nathen & Lauren to record tutorial**
  - [ ] Write Launch Strategy SOP #636 
- [ ] https://github.com/life-itself/community/issues/588 @laurenwigmore @ZybN 
- [x] Community Calls
  - [x] #628 continue promotion and updates @nathenf @ZybN 
  - [x] #682 @ZybN 
- [ ] Team action - update in comments a summary of tasks completed, and number of hours
- [x] Create next iteration
- [x] #642 @matthewmccarthy11 @ZybN 
- [x] From last research forum #671 @matthewmccarthy11 
- [x] [Short feedback form created](https://forms.gle/hK7MQf52EwTnG4AfA)
- [ ] #686 
  

🔥 🔥 
- [x] #638 
- [x] update zoom email from accounts@artearthtech to accounts@lifeitself.us - Rufus to confirm OK

⏭️ 
- [x] BONUS: Create questionnaire for feedback from Whatsapp group (create an issue)
- [ ] #675 
- [x] #674 

⏭️ ⏭️ 
- [ ] #588
- [ ] #589 as part of #568
- [ ] IG carousel of co-founders / people - could become a bit of a 'series'
- [ ] 💡 we could do a meet a member item in the newsletter like an introducing people who want to share details to the community

## Availability
Lauren: 60-70 hours ✅ 
Nathen: 40 hours ✅ 
Zaib: 10 Hours ✅

**Comment by laurenwigmore** [comment]
### 2023-07-25 AOB Notes from Meeting with Nathen and Rufus
- [ ] AOB
	- [ ] Joseph Henrich Podcasts time break. (Rufus to clarify further which ones)
	  - [ ] 1st episode (new)
	  - [ ] And you could just do a massive other episode
	- [ ] Blog page - WE WANT A NEW BLOG **💬2023-07-25  create an issue**
	- [ ] Sharing about using AI for transparency **💬2023-07-25  sure ...**
	- [ ] Research & Manifesto - is manifesto ready for DDS? **💬2023-07-25 yes - send email to boaz and labs team.**
	- [x] Interview Rufus for content

**Comment by laurenwigmore** [comment]
## 2023-07-24 Notes from Lauren and Nathen meeting/brainstorm

## Next Actions

- [x] Complete and close this https://github.com/life-itself/community/issues/512
- [x] Set up Issue to interview Rufus - https://github.com/life-itself/community/issues/674
	- [ ] Include what is our theory of change
- [x] Create issue for a community page - https://github.com/life-itself/community/issues/675 - info to be populated
- [ ] Create epics for
	- [ ] Online Community EPIC
		- [ ] Purpose and principles 
		- [ ] Speaker to sign-up form
		- [ ] Research Community + Forum 
		- [ ] KPIs
		- [ ] SOPs at the top 
		- [ ] Call tracker
		- [ ] Build community page
		- [ ] Get feedback from community

**Comment by laurenwigmore** [comment]
@nathenf can you review this [feedback form](https://forms.gle/hK7MQf52EwTnG4AfA), I thought we could include it in the July newseltter

**Comment by laurenwigmore** [comment]
@rufuspollock Can I be added to the Google Analytics account for the website please?

**Comment by laurenwigmore** [comment]
@rufuspollock can we change the zoom account email to accounts@lifeitself.us? 
reason being it is currently office@artearthtech.com and the log in codes are being sent here, and I don't have access to this.

**Comment by rufuspollock** [comment]
> @rufuspollock can we change the zoom account email to [accounts@lifeitself.us](mailto:accounts@lifeitself.us)?
reason being it is currently [office@artearthtech.com](mailto:office@artearthtech.com) and the log in codes are being sent here, and I don't have access to this.

Done. See https://github.com/life-itself/ops/issues/140

**Comment by rufuspollock** [comment]
> @rufuspollock Can I be added to the Google Analytics account for the website please?

These are new tasks - i'd add them to a new issue (preferably in ops issue tracker).

**Comment by laurenwigmore** [comment]
### Notes for comms meeting on 2nd
- Valerie's suggestion to have the CC101 in a French version

**Comment by nathenf** [comment]
FIXED - This iteration was mostly focused on producing posters for the LI hub alongside ongoing Comms tasks to promote CC101 and community calls. We have had great success with both  reaching 115 participants in the course and 178 people in our Whatsapp group. We also published last months newsletter and worked on creating SOPs for the podcast and community calls. Due to Zaib's sudden exit from the organisation a few of the issues have been put on the back burner until further notice.
