### ISSUE TITLE
[epic] Ordinary People: A Podcast Series of Ordinary People Choosing an Extraordinary Path

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#669]
Once Upon A Time: A Podcast Series of Ordinary People Choosing an Extraordinary Path

## Acceptance

```[tasklist]
- [x] Create A10 **✅2023-10-16 https://docs.google.com/document/d/1bF2lP2u8RfAMdlHdmvgzEUssCXHRu26VL-noKbmjcGI/edit#heading=h.599vpyhb8naq**
- [x] Finished blurb **✅2023-11-11 see title and blurb section of A10**
  - [ ] Standard text to copy and paste into youtube and spotify … (can come from the blurb)
- [x] Landing page set up for the series **✅2023-11-09 https://lifeitself.org/once-upon-a-time-series**
- [x] Releasing first episode with Jamie Bristow #601 **✅2023-11-09**
- [ ] #931
- [ ] #1002
- [ ] https://github.com/life-itself/community/issues/1081
- [x] https://github.com/life-itself/community/issues/1084
- [ ] https://github.com/life-itself/community/issues/1082
- [ ] https://github.com/life-itself/community/issues/1083
- [ ] https://github.com/life-itself/community/issues/1093
- [ ] https://github.com/life-itself/community/issues/1094
```

### Prep for future episodes

- [ ] Question structure for Sylvie
- [ ] Future People to interview

## Notes on SOP

- [ ] Make sure all episodes include in the show notes a link to the main series page (on youtube as well)
- [ ] Bonus: nice image that Sylvie created for it

 ## Tasks (misc - for an epic these should usually be in the sub-issues!)

### 2023-11-11 (Rufus & Sylvie)

- [x] Consolidated all content into the project folder for the project
- [x] Went back to the blurb we had above with a few tweaks (is there a reason we did not use that)
- [x] Update landing page with blurb 
- [x] Updated image on youtube 🚩 (this is relevant for all image generation)

Todo

- [x] Update blog post (why do we have blog post *and* podcast page? seems like we always have duplication?)
- [x] Update podcast page with info
- [x] Update podcasts themselves with info
- [ ] Re-record the jingle (or just read that in future)

**Comment by nathenf** [comment]
@ZybN let me know if you have the call with Sylvie and if she would like new graphics for the thumbnails for this project

**Comment by nathenf** [comment]
@laurenwigmore and @shiweiart this is was started when Zaib was with us and had capacity, but the issue was never fulfilled. I think worth populating with better roadmap and acceptance. These interviews are just laying in Zoom so worth creating!

**Comment by laurenwigmore** [comment]
@nathenf agreed. I have a few thoughts on this - we could use the series as a beacon with a different flavour - perhaps link it somehow into other learning material/or a development type exercise related to stories/storytelling (perhaps as a second round beacon creation seeing as we seem to have ALOT for the current creation) and/or when Alexia is more up to speed we could assign her this as a more in-depth task and keep it more as a simple podcast output. What are people's thoughts?

**Comment by rufuspollock** [comment]
Update:

- Consolidated all content into the project folder for the project
- Went back to the blurb we had above with a few tweaks (is there a reason we did not use that)
- Update landing page with blurb 
- Updated image on youtube 🚩 (this is relevant for all image generation)

Todo

- [ ] Update blog post (why do we have blog post *and* podcast page? seems like we always have duplication?)
- [ ] Update podcast page with info
- [ ] Update podcasts themselves with info
- [ ] Re-record the jingle (or just read that in future)

**Comment by laurenwigmore** [comment]
@shiweiart do you need @moonimmisch to support on the rest of the to dos for this, and are you ready for us to publish the next podcast?

**Comment by moonimmisch** [comment]
> @shiweiart do you need @moonimmisch to support on the rest of the to dos for this, and are you ready for us to publish the next podcast?

Let me know how I can help! :D

**Comment by laurenwigmore** [comment]
FIXED - OP podcast series follows same SOP as our other podcasts. 
OP series will likely picked back up in 2025 by Sylvie when things are more settled with the baby. Future episodes will have individual issues.
