### ISSUE TITLE
Research Forum Updated

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#671]
https://lifeitself.org/blog/2023/07/05/research-forum-4-marc-santolini-liam-kavanagh needs to be updated with the recording. 

## Acceptance
- [x] Blog post is updated with recording and summaries
- [x] Recording is added to Youtube 
- [ ] Create a section on https://lifeitself.org/research-community at the bottom to add previous forums so people can easily navigate to them

## Tasks

- [x] Take the zoom recording and follow the same SOP as the community call 
- [x] Upload the video to Youtube including a short summary in the description and a link to the research community
- [x] Update the blog post 
- [x] Add the blog post and previous blog posts to the research community page

**Comment by nathenf** [comment]
FIXED - research forum is live
