### ISSUE TITLE
Presenting Life Itself at the Bergerac Hub and the purpose the Hub

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#673]
We want to better **present** the vision, mission, activities of Life Itself (and the Hub itself) AT the Bergerac Hub.

- S: lots of people come to the Life Itself Bergerac Praxis Hub and no indication that associated with Life Itself and no information about Life Itself and what it is up to.
- C: people lack context for why hub exists and what it is about (i.e. it is not "just another retreat center"). Plus fewer people find out about Life Itself and bigger picture of what it is up to which stops them getting engaged etc
- Q: how do we better present Life Itself at the Bergerac Hub and the true purpose and context of the Hub?
- H: .... read on dear reader ....

Aside: communicating Life Itself at Bergerac Hub is a first step in presenting Life itself more generally

- #688 

## Job stories

Job 1: When I am in the Life Itself Hub, I want to know who and what Life Itself is and what it does so that I understand the broader context, can share with others and get involved (if i want to)

Job 2: When I attend a residency or visit the life itself hub in Bergerac I want to feel more connected with the hub experience and its purpose as a deliberately developmental space and lab for those (and their "ecology of practices", etc)

### Reference Links
[Excalidraw](https://app.excalidraw.com/l/9u8crB2ZmUo/8ApLHGkiq4l)

### General Notes

- Content should be English *and* French where possible (people from Bergerac may come and would be odd if just English)
- The Hub is a "physical" landing page
- What is purpose of the Hub (not just another retreat centre)
- Seeding a metamodern region
- Stats: e.g. number of residencies, number of participants, testimonies
- 130 emails for interest in the residencies

## Acceptance

- [x] The Hub now contains several outreach materials that serve the job stories above

## Tasks - Phase 2

- [ ] Print 3x books/documents 🚧 _sent to praxis-team email to be printed - awaiting confirmation_
- [x] Decide redirect links ✅ links all direct somewhere and the pages have been optimized
- [ ] Optimizing where people land from the posters
  - [x] Update the key articles blog posts with ongoing reading or calls to action
  - [ ] Create new pages for:
    - [ ] Second Renaissance (Learn Page?)
    - [ ] Deliberately Developmental Spaces (Learn Page?)
- [ ] More posters to create ❓ Is this worth the input right now?
  - [ ] Larger Poster of Theory of Change and Manifesto summary (visual and words)
  - [ ] Second Renaissance
  - [ ] About the Hub

## Tasks - Phase 1

- [x] Decide what to produce (see brainstorm)
	- [ ] Prioritize and create parameters (time frame and budget) 
- [ ]  BONUS: Sharing about the residencies and the people coming etc to show what exciting stuff is happening and get more engagement (external) ❌ this is a new issue
- [x] Materials to Produce - What we're actually doing
- [x] bookmarks - printed via vista
- [ ] 'Books available' - Great Grasping is it edited? / if not do https://drive.google.com/drive/folders/0BwmUU3AT2rRlQnRNSXM1NUY0NUE?resourcekey=0-z_PPzfQ-4t5xLRWVBgCkzA
- [ ] 'Books available' the collective intelligence whitepaper https://drive.google.com/file/d/1NHBDtw3MplEuleEQN5oyPJtJ-rfQCgmX/view 
- [ ] do we order or is a copy available from Liam? https://www.amazon.co.uk/Collective-Wisdom-West-shadows-Enlightenment/dp/1914568028/ref=zg_bsnr_277260_48?_encoding=UTF8&psc=1&refRID=AT9J9VZHT22WMQ6TGRX8 
- [x] Praxis Ecology text by Valerie [reformatted](https://docs.google.com/document/d/1tP-GuQ6kgb8YuJCVqWi_8vdcHduXTGwNkdThJx25oPY/edit?usp=drive_link)
- [x] Posters for
  - [x] conscious coliving 101 course (use midjourney)
  - [x] This is a Life Itself Hub poster at main door (plaque??) - congrats you're part of the second renaissance ![image](https://github.com/life-itself/community/assets/145260066/5c2b3358-5bf5-4549-a917-48e2dd5a3bf0)
  - [x] Larger poster of Critical Points post ![image](https://github.com/life-itself/community/assets/145260066/430d515a-a8d4-4386-9f04-33c25a0e21ab)
  - [x] Bathroom posters - 2x design image of a bookshelf with 3 QR codes (possibly bitly links) to the top articles (6 QR code/articles in total). ![image](https://github.com/life-itself/community/assets/145260066/0a8ba878-23f2-4321-9d23-c781141a7e02)
  - [x] cultivating an emerging paradigm poster ![image](https://github.com/life-itself/community/assets/145260066/5e044d76-d191-4183-b5ee-66dcc867f193)
  - [x] deliberately developmental space poster ![image](https://github.com/life-itself/community/assets/145260066/ce5ffa32-8081-42e0-91ba-b5dd0d623977)
- [x] Guest book at front door - ordered by Printify

---

# Brainstorm 

## Ideas for later

- [ ] LI pens ❓ maybe not a priority as could be tacky - could create a pen, notepad set at cost price later on
- [ ] Stickers? brainstorm with Rufus tag line - Same as pens

### Manifesto and ToC Text Ideas

- We want to go to the stars. 
We want an awakening society.
We are seeking out pioneering individuals and deliberately developmental spaces to nurture our journey, to bring together the individual into a collective, a conscious community, spanning geographical and cultural boundaries. To exchange knowledge, and time, and questions, and actions. To ‘tip’ society into a new state of being, an awakened state that nourishes personal and collective flourishing. A society oriented to inner unlimited transpersonal growth rather than outer growth. A society that is actively ready to create a weller, wiser world.
Will you join us? 

- Thinking, talking, dreaming, doing

### 2nd Renaissance region

If we look back at past movements major or minor they had epicentres. Places where there were initial concentrations of people, ideas and activity. These places are the seeds of the coming paradigm shifts.

Whether we think of Florence and other Italian cities in the Renaissance. Chartres in the high middle ages. San Francisco in the 60s etc.

So today, in the second renaissance it will the same: there will be see

What we are trying to do here around Bergerac is to seed a transformative region, to create the first metamodern hamlets, villages, town and ultimately region.

- Jena in the romantic enlightenment
- Geneva in the reformation

Here in Bergerac and around Plum Village 20km to the south we are engaged in a conscious effort to contribute to the flowering/germination of just this kind of transitional region.

A metamodern municipality. A pioneer of the second renaissance. a teal town. ...

### Why here?

- Compared to major urban centres e.g. London, Berlin, SF
  - Today very expensive.
- At the same time, tech and transport mean that countryside or minor towns are now much more connected to wider world.
  - Can work from here
  - Easy for people to visit
  - Easy to travel elsewhere for work etc if needed
- At the same time the concentration of a town is valuable. Having bars to go to, opportunities to rent or buy within walking distance
- connection with transformative hamlets.

### Why here here?

- Partly random: you could pick anywhere and start ...
- Key issue is getting critical mass: currently second renaissance / metamodern / teal / [insert your adjective] are rare. You need to get enough of them in one place to kick-start the whole process (this is a "platform" problem)
- In this case a few pump-priming items that "sweeten the pot" for new joiners
- Plum Village
  - Leading centre of mindfulness and zen in Europe (and globally)
  - 1000s of international visitors every year
  - In last 5-10y has started to attract a critical mas

### A Second Renaissance

🚩 TODO: what is second renaissance

### 5 theses from cultivating

https://lifeitself.org/blog/2022/02/01/cultivating-an-emerging-paradigm#summary

🚩 TODO: Add a sixth thesis: this transition has begun. We are in a second renaissance

We are in a dawn of a new era - or a new dark age. What we get is up to us and our efforts. At Life Itself we believe ... 

1. Transition is Needed: there is an urgent need for a transition from where things stand today.

2. Transition is Paradigmatic: The transition involves a paradigmatic shift that includes a profound shift in worldview (views and values).

3. Transition is Inner & Outer:  the transition involves the integration of the inner and the outer – personal/collective growth as well as systemic transformation.

4. Transition prioritizes Being: whilst inner and outer are both needed, inner development has primacy, that is it should be prioritized and takes ultimate priority (also known as the “primacy of being” thesis).

5. Transition requires Engagement (of the right kind): transition can be cultivated but not engineered. There is a middle way between passive disengagement (just letting it unfold) and arrogant engineering. The challenge is therefore to facilitate transition and cultivate emergence, rather than seeking to engineer it.

6. ...

### Seedbed metaphor for new paradigm (and role of hubs)

[2023 plan outline - Jan 2023 with Oliver Nash Excalidraw](https://app.excalidraw.com/s/9u8crB2ZmUo/WYa9H1pnXQ)

Seed-bed is also a metaphor for broader development:
the coming into being of a new paradigm

* Soil (the general social context)
* Seeds / young plants: group/communities experimenting / pioneering
* Ecosystem forms: plants are bigger, connecting together.
Some point seeds join together into a "movement" or a cultural force

### A critical point

https://lifeitself.org/blog/2021/10/25/critical-point-our-reason-for-existence-in-a-nutshell

### Rufus oundle lecture

Previous content from Rufus, Oundle lecture, best attempt to solidify personal context: 

https://drive.google.com/file/d/1zo1AB6j9eFGE8cWP_dVx8_M8XBT4BJcL/view

### Surveying people re Life Itself

Have we polled people about what Life Itself (the organisation) means to them?

https://docs.google.com/forms/d/1TYiLJekVCQGKyOgq0bb3lCDP3_WdkNz9id8X5S5sPiE/edit#responses (3 responses from people we knew quite well)

22 responses from participants at 2019 gathering

https://docs.google.com/forms/d/1OlShGniX6BJYqWM7tfywPaDtCVV718GFj3npukeH5Sw/edit

### Another simple poster

Welcome to the Life Itself Hub

This Is What We're About

In the past four decades, a confirmation and expansion of wisdom traditions by scientific rigor has converged with an ever deepening polycrisis.

There has never been a more important time to “grow up”, both personally and collectively. A paradigm shift is underway and we all have a part to play.

The big question is ... how?

Life itself is a home for people who are dedicated to rigorous enquiry and deliberate action for inner growth and cultural evolution in the service of social transformation -- creating an awakening society and a radically wiser, weller world.

Inspired by integral theory, zen buddhism and other key concepts, we cultivate these ideas and apply them to life itself, through deliberately developmental programs, spaces and community building.

Visit our website to learn more

## Brainstorm - 2023-07-24

Job 1:
  - Blurb/description:
    - https://lifeitself.org/blog/2022/02/01/cultivating-an-emerging-paradigm
    - New Brand ... => flyer
  - Original manifesto
  - https://app.excalidraw.com/l/9u8crB2ZmUo/8F30hhvlTcl
  - https://app.excalidraw.com/l/9u8crB2ZmUo/9XlL9rIxvzS

Job 2: 
- https://lifeitself.org/blog/2021/10/05/deliberately-developmental-spaces-a-key-to-addressing-the-metacrisis
- Manifesto about "need for deliberately developmental spaces"
- Praxis Hub home page
- Interview Marc, Liubov, Valerie

Actual Materials:
- Boxes where people put coins in like a live poll
	- Which resonate
- Bookmark
- Something near front door
- toilet/bathroom sign/QR code
- Conscious coliving 101 poster
- Life Itself posing key questions with a form where people can enter an answer. Contributes to the citizen research - work with Marc and Luibov. This is a deliberately developmental space and we are doing research
- Posters made
	- Manifesto needs to be edited
- This is a Life Itself Hub, we are pioneering a metamodern neighbourhood here in Bergerac. Come and join the second renaissance 
- Who and what life itself is 
- Poster which compliments the reader on being part of the second renaissance
- videographer needed
- testimonials of hub/residencies
- photos of influential people in attendance at residencies
- https://www.youtube.com/watch?v=RGqM6Lceur4&t=96s - reposition
- find out photos for use
- https://lifeitself.org/ideas link to this, but make it more condensed

**Landing page copy** 
* We can all feel the world is changing
* Everyone is talking about how - the metamodernism, game b, integral
* We all talk a good talk, but where is the walk?
* We want to make this real, actually walk the talk.
* And we have an approach to doing that
* We want to build an awakened society
* To get there we need a 2nd renaissance
* To create a 2nd renaissance we need regions/hotspots of transformational change
* Here is what we are doing about it
* We're pioneering a Metamodern neighbourhood in Bergerac
* We're carrying out research and development in our research community
* We're creating courses and incubating enterprises for the second renassaince
* We're building a digital portal and network for renaissance actors
* But for all of this we need you, people willing and able to be part of the 2nd renaissance
* Are you with us?

### Purpose and principles

Purpose to redirect hubdwellers to Life Itself website and other offers - mostly in the direction of deep research and reading. We want hubdwellers to associate this transformative experience with Life Itself as an organisation and to become invested in Life Itself and become ambassadors of Life Itself. Harnessing the power of word of mouth.

### Poster links for redirection

Bookmark - /bookmark
Reading Poster - /read1, /read2, /read3, /read4, /read5, /read6
Critical Point Poster - /critical-point-poster
You Are At A Life Itself Hub Poster - /you-are-here
Deliberately Developmental Space Poster - /deliberately-developmental-space

### Resources
Lauren: 
Phase 1 - approx 40 hours

Expenditure:
Bookmarks - Vistaprint: £22.99
Posters - Vistaprint phase 1: £93.82
Guest book: £25 (?)

**Comment by laurenwigmore** [comment]
## Critical Point Slide Ideas for Poster
We are at a critical point in history
The current paradigm is broken and causing mass destruction on individual, societal and global levels

> "While practices such as mindfulness have gained popularity, this remains bound to the context of personal wellness rather than deep change"
 - I feel this is a key point ^

Ways that we used to make sense and meaning have broken or changed

There is a symptom of 'too much' prevailing that is preventing people from taking action - too much ambivalence, too much dependence on current systems, too much victim-hood, too much cynicism 

Alternative ways of being don't resonate with most

The best of the current path we are walking is we can maintain existing, without ever experiencing our true potential

Stuckness and blindspots exist on mass scale
Those that are aware of the need for transformation do not know where to gather (**answer at the Hub / LI**)

Being - Culture - Systems
**How do we shift/steer humanity into flourishing? 
Through planting the seeds of a second renaissance now.**

**Comment by laurenwigmore** [comment]
### Guestbook
[Design own here](https://www.zazzle.fr/creez_votre_livre_dor_de_mariage-256363038978235330)
If we order this week would arrive end of the w/c 7th Aug

[Ideas mock up here](https://www.canva.com/design/DAFpwVBo3po/s06Xbl3uF-oZAq9g0ooWrA/edit)

**Comment by laurenwigmore** [comment]
### Notes
Add back in commas and fullstops and remove ' quotes on 'tip' on bookmarks. Use png.

**Comment by rufuspollock** [comment]
@laurenwigmore @nathenf 

> We are at a critical point in history.
> The current paradigm is broken and causing mass destruction on individual, societal and global levels.
> Our holistic focus is limited to wellness, not profound change.
> Stuckness and blindspots exist on mass scale.
> Yet there is hope, for some there is an awareness of a need for change,
> but no one knows where to gather . . .

Previous version of this we had (from critical point slidedeck) I think is better ...

**Comment by laurenwigmore** [comment]
Article links
- https://lifeitself.org/blog/2017/05/31/the-way-we-live-now
- https://lifeitself.org/blog/2022/02/01/cultivating-an-emerging-paradigm
- https://lifeitself.org/blog/2021/10/05/deliberately-developmental-spaces-a-key-to-addressing-the-metacrisis
- https://lifeitself.org/blog/2022/06/17/history-humility-and-the-seeds-of-a-new-culture
- https://lifeitself.org/blog/2018/01/24/the-ills-of-capitalism-the-possibilities-of-abundance-and-the-limits-of-land
- https://lifeitself.org/blog/2022/05/03/art-religion-and-the-climate-crisishttps://lifeitself.org/blog/2020/06/11/contemplative-activism-a-primer

**Comment by nathenf** [comment]
![Explore our digital bookshelf](https://github.com/life-itself/community/assets/95729108/4a4a93b5-3ff7-44db-b3fa-55c65e2af595)

**Comment by nathenf** [comment]
![This one](https://github.com/life-itself/community/assets/95729108/2884a253-1ef5-4464-8527-6539f5d4c040)

**Comment by nathenf** [comment]
![We are at a critical point in history](https://github.com/life-itself/community/assets/95729108/8d742c76-21cb-42bc-a024-f15dc966e42a)

**Comment by nathenf** [comment]
![www lifeitself org](https://github.com/life-itself/community/assets/95729108/b972a194-cb4b-4373-bfde-5117ab28d565)

**Comment by nathenf** [comment]
Redirects made for current pages. Now we can begin to decide which pages we want to create

<img width="1059" alt="Screenshot 2023-08-03 at 11 18 19" src="https://github.com/life-itself/community/assets/95729108/3b9831e5-936d-4517-a6ae-395fe2d303f5">

**Comment by nathenf** [comment]
Phase one posters have now been printed and are being delivered at the weekend. I have made a phase 2 section for us to look at next

**Comment by nathenf** [comment]
@rufuspollock I guess we are done with this issue for now? Do you want to capture any of the information before closing? Would also love to see the posters in place (if they have been put up 😆)

**Comment by rufuspollock** [comment]
> @rufuspollock I guess we are done with this issue for now? Do you want to capture any of the information before closing? Would also love to see the posters in place (if they have been put up 😆)

I personally put up all the posters so they are up. You can ask @alexianetcu to take pictures which i think would be a nice way to close issue.

one question: did we build tracking into the qr codes so we know how often they are clicked? @nathenf

**Comment by alexianetcu** [comment]
@nathenf @laurenwigmore @rufuspollock I have uploaded the pictures of the posters under Phase 1 where they were outlined. Am now closing issue.
