### ISSUE TITLE
Create a Community Page on the Life Itself Website

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#675]
We want to create a landing page for the community (AKA the broad network of people connected to Life Itself and how they interact through various initiatives). 

Page goal: To get people to join the community, primarily through whatsapp

## Job Stories
- When I visit the Life Itself website, I want to know about the main activities Life Itself are currently inviting people to engage in so that I can get involved quickly and easily
- When I come to the Life Itself website, I want to know if this is a group of people where I belong so that I can decide whether I feel at home in the community

## Acceptance
- [x] Page created and live on LI website
- [ ] Page featured in menu bar

## Tasks
- [x] Brainstorm copy
- [x] Brainstorm structure of the page

### Brainstorm 

![Untitled design](https://github.com/life-itself/community/assets/95729108/c402576d-037a-4555-a927-95a6f10c03e6)

A community for people, who recognise the meta-crises we face, know there is a possibility of a new paradigm and are ready to do something about it! 

**What is the Life Itself Community?**

Welcome to our digital village! Just like a traditional village, we are a diverse community encompassing multiple generations, various backgrounds, professions, and skills. However, it's our unity in this diversity that truly shines as we come together to exchange, collaborate, learn, and innovate collectively. Our purpose is to transcend individualism and foster an inclusive environment rooted in a culture of mutual support and care.

The community is a rich mycelial ecosystem of movers and shakers doing their bit to create a wiser, weller world. From researchers to storytellers, farmers to financiers we transcend traditional mechanistic identities and embody the ideals of renaissance people. 

We are not this or that, we are both/and. 

Join 200+ other members in seeding the second renaissance! 🎉 

**How can I get involved?**

The easiest low-effort, high yield way to get involved in the community is to join our Whatsapp chat and our bi-monthly online gatherings. From there, the amount of investment in the community is up to you - but the more you put in the more you get out! 

BUTTON: Enter the community chat

Got a specific idea for a community initiative? Get in touch

**Why join us?**
- A place to belong and connect with like-minded people
- A place for innovation, networking and skills building
- An online space dedicated to cultivating offline spaces

**What do we discuss in the community**

Our 12 pillars of enquiry:

1. Creativity & Imagination
2. Spirituality & Religion
3. Health & Wellbeing
4. Ecology & Environment
5. Social Justice & Equality
6. Food Systems & Farming
7. Technology
8. Economics & Economic Systems
9. Organizational & institutional governance
10. Inner development
11. Politics & political systems
12. Community & collectivity

Topics from previous community calls include: 
- The future of education
- Embracing uncertainty
- Knowledge management systems for self and collective development
- Participatory Wisdom 
- Navigating the meaning crisis
- The second renaissance 
- The next generation of climate activism

---
Hi do we have a standard page for our community calls?

I want a page i can link people to and they can see past and upcoming calls.

Imagine something like e.g. lifeitself.org/hangouts or lifeitself.org/community-calls.

BTW i note that https://lifeitself.org/hangouts already exists and we could repurpose it for what we are now doing ... (to provide some continuity).

Job Stories
When writing an email to someone I want to tell them about our community calls including how to attend so that they can find out and come if they want

**Comment by nathenf** [comment]
FIXED - page is here: https://lifeitself.org/community

**Comment by rufuspollock** [comment]
@nathenf @laurenwigmore flagging that we do want to deduplicate lifeitself.org/hangouts - i'd suggest redirecting that and *(?) converting existing content there to a back-blog post so it's not lost (maybe have that content already though in the launch post for that).

**Comment by rufuspollock** [comment]
Quick thought on https://lifeitself.org/community

Really great and like the copy ... 👏👏

And ... there's a lot of copy before i get to call to action / info on how to participate (which i assume is main reason to go).

I'd imagine two top things are:

1. Join whatsapp community (with a bit of context on what's there)

2. Community calls - there should be a simple quick way to register for these in general and perhaps specifically register for the next one ...

wdyt of moving these right to top - and have some kind of related CTA or info in the Hero (which then links down).

**Comment by laurenwigmore** [comment]
> Quick thought on https://lifeitself.org/community
> 
> Really great and like the copy ... 👏👏
> 
> And ... there's a lot of copy before i get to call to action / info on how to participate (which i assume is main reason to go).
> 
> I'd imagine two top things are:
> 
> 1. Join whatsapp community (with a bit of context on what's there)
> 2. Community calls - there should be a simple quick way to register for these in general and perhaps specifically register for the next one ...
> 
> wdyt of moving these right to top - and have some kind of related CTA or info in the Hero (which then links down).

I've add the whatsapp chat link at the top, under the first sentence, for the time being.   
The Community Calls at present all require separate registration. Perhaps we can have a quick discussion on this in next weeks Beacons meeting, as there are pros and cons to having a generic registration link for the calls.

**Comment by rufuspollock** [comment]
@laurenwigmore re whatsapp link it would be nice to make it a bit more "button-y" 

Re the other point: can we have that discussion in the thread here ... e.g. you set out pros/cons (or open a new specific issue if we don't want to drag this one out)

**Comment by rufuspollock** [comment]
FIXED. Let's call this fixed. UX improvements can be in the future.
