### ISSUE TITLE
Community Call with Jan Demiralp

### ISSUE THREAD

**Issue by ZybN** [life-itself/community#682]
Jan Demiralp | 10/08/2023 | Not Confirmed: Life Design or 'Organising Organisations'

## Acceptance

- [x] Community call hosted and recorded 
- [x] Uploaded to Youtube and blog post ✅  https://lifeitself.org/blog/2023/08/01/The-art-of-creating-intentional-futures-Jan-Demiralp

## Tasks

Pre-event

- [x] Confirm speaker
- [x] Collect and confirm details
  - [x] Contact for speaker
  - [x] Time
  - [x] Date
  - [x] Blurb for speaker
  - [x] Profile picture
  - [x] Confirm who is hosting/mcing - Lauren
  - [ ] Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [x] Create Canva graphic using template 
- [x] Create registration using Zoom ✅ [Registration Link](https://us02web.zoom.us/meeting/register/tZApfu-urTsrEtW1RAky-Vflasr1c2G3skDh)
- [x] Create the blog post
  - [x] Include image, registration link, biography of speaker or description of the event
- [x] Promotion
  - [ ] Emails
    - [x] Initial announcement (main group) on if newsletter was more than a week ago
    - [ ] Day before announcement (main group) only if initial announcement was more than a week ago
    - [ ] Email reminder (recipients)
    - [x] Plus in newsletter (if applicable)
  - [ ] Whatsapp
    - [ ] Initial announcement
    - [x] 3 days before
    - [ ] Day before
    - [ ] 1-2 hours 
  - [ ] Twitter
    - [ ] Thread for initial announcement
    - [ ] 3 days
    - [x] Day before
  - [ ] Instagram
    - [ ]  Stories
      - [x] Story template or resharing post
      - [x] Initial
      - [x] 3 days before
      - [x] Day before
  - [x] Post for initial announcement - https://www.instagram.com/p/CvfRUyMoVnk/ 
  - [x] LinkedIn event/post

Post-event

- [x] Make the youtube video 
- [x] Update original blog post with youtube video plus information
- [x]  Title: Should include name of person, plus keywords/topic
- [ ] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [x] Update CRM with links etc. 
- [x] Let the speaker know and make it easily shareable

**Comment by laurenwigmore** [comment]
Content for LinkedIn - same as IG but set up as an event.

**Comment by nathenf** [comment]
This is now ready to share across platforms tomorrow

**Comment by nathenf** [comment]
FIXED - live and shared across all platforms
