### ISSUE TITLE
Create a donation button for the CC101 course & other general use

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#686]
When a member of the community finished the CC101 course, should they wish to make a contribution there is a clear donation button embedded into the course for them to do so.

## Acceptance
- [ ] Donation button created 
- [ ] Donation button inserted into course email(s)
- [ ] Donation button available in other identified places

## Tasks
- [ ] Set up donation button
- [ ] Decide on where to insert for CC101 - which email days? or on CC101 page?
- [ ] Decide where else it could be added on the LI website (maybe promo material?)

### Reference

> > @rufuspollock do you have information you could share on the donation button you use so I can add this into the content? is it the same as the one that was on Diginomics Open Revolution book page?
> 
> We used donorbox for that i think. As i'm not sure of setup on that, i think worth setting something new up. Do note we have a stripe account already. I think this should be its own issue btw as setting up donation is probably something general we want to do.

**Comment by nathenf** [comment]
@rufuspollock stripe is attached to your phone so we will need to log in with that. We could take 2-factor off to make it easier to sign in

**Comment by nathenf** [comment]
Stripe has it's own payment and donation option which we can embed into the email and other places.

**Comment by nathenf** [comment]
@laurenwigmore @rufuspollock should we set up a patreon? This way it can be used for the CC101 but also the community and LI in general.

**Comment by rufuspollock** [comment]
@nathenf i would do simplest thing possible that allows people to donate at the start which is probably https://support.stripe.com/questions/how-to-accept-donations-through-stripe ...

(IME of things like this the likely donation amounts are quite low so i wouldn't focus on this that much personally).

**Comment by nathenf** [comment]
@rufuspollock 

> @rufuspollock stripe is attached to your phone so we will need to log in with that. We could take 2-factor off to make it easier to sign in

We are blocked here RE stripe.

**Comment by nathenf** [comment]
@laurenwigmore @rufuspollock  maybe you can get online on Stripe during a standup. I think Rufus you just need to be available to help through 2 factor.

**Comment by rufuspollock** [comment]
WONTFIX. I don't think this is critical path for now.

**Comment by laurenwigmore** [comment]
https://givebutter.com/ - created for non-profits "Streamline fundraising, marketing, and donor management in one powerful platform—rated   for ease of use time and time again."
