### ISSUE TITLE
Re-arrange People's Page Set Up and Headings

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#687]
When I arrive on the People's Page of the LI website, I want to easily understand who works in what area and what role they have. 

Current headlines are:
- Our Team
- Research
- Pioneers
- Bergerac Praxis Hub Guardians
- Berlin Hub Residents
- Contributors
- Alumni 

This maybe no longer represents the way our team and network are structured. How can we evolve this? 

## Acceptance
- [ ] People's page redesign is live with new headings

## Tasks
- [ ] Discuss in next core community call
- [ ] Create headings
- [ ] Update and move people to be under new headings

**Comment by msantolini** [comment]
Thanks! Just adding here that indeed a section on "Research" would be nice, maybe others could be "Communication", "Founders" (?), "Art collective" etc

**Comment by nathenf** [comment]
I propose titles of:

- Operations
- Research 
- Praxis Hub Guardians 
- Contributors
- Alumni 

Berlin hub now merges into Alumni 
Contributors we must have more now who can be included here
Pioneers: It include Valerie who is now in Praxis and Esther. Either we expand this or remove it is my 2C 

@rufuspollock @msantolini @Postnormalval et al, suggestions?

**Comment by nathenf** [comment]
FIXED - relatively updated, can make new moves when neccessary
