### ISSUE TITLE
Questions for the QR Hub Promotion

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#688]
As part of #673 I want to have useful research questions available on QR code stickers/plaques placed in key rooms within the hub. To offer a real-time feedback from individuals attending residencies. Answering these questions will tell us two things:

- Which rooms are the most popular for answering Qs
- Provide further insight and qualitative answers to feed wider research

## Acceptance
- [ ] QR codes are up in the Hub in the agreed rooms

## Tasks
- [ ] Decide which rooms
- [ ] Decide how many questions
- [ ] And what the questions are
- [ ] Create the google forms that the QR code links to
- [ ] Create the QR codes
- [ ] Have these printed
- [ ] Research ways participants can record their answers, instead of typing

### Notes
[Food Q for Hub](https://docs.google.com/forms/u/3/d/1sGoD4F_wCFCDBypo5EsWHihVOlj5DaM39-dO-MTnFwI/edit?authuser=0) - 3rd Q down

We also want to have a poster which explains the core message:
- This is a Deliberately Developmental Space
- This is an experiment
- You are participating
-

**Comment by msantolini** [comment]
Just flagging a discussion topic I created on this #691

**Comment by nathenf** [comment]
@laurenwigmore @msantolini moving this to Someday Maybe... I don't know if we still plan to do this?

**Comment by msantolini** [comment]
> @laurenwigmore @msantolini moving this to Someday Maybe... I don't know if we still plan to do this?

yes, I think "Someday maybe" is a good status for now.

**Comment by rufuspollock** [comment]
WONTFIX. Nice idea ... and not a high priority.
