### ISSUE TITLE
CC101 Review (book, documentary etc)- Don't Join a Cult! - 5 documentaries to help you know when to say no.

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#702]
## Tasks
- [x] Blog Post Published with engaging image 
- [x]  Repositioned for LinkedIn post 💬 looking into how to do carousels 
- [x]  Write Twitter thread use [Ship30for30](https://www.ship30for30.com/post/how-to-write-a-twitter-thread) for guidance of how to write a good thread
- [x]  Post on IG (carousel of twitter thread) - https://www.canva.com/design/DAFp0sAE8Cg/TlDs1v-GH7VwCX295G3erA/edit for the graphics
- [ ]  Whatsapp groups post? ❌

**Comment by laurenwigmore** [comment]
FIXED. All items actioned for this blog post.
