### ISSUE TITLE
August Newsletter

### ISSUE THREAD

**Issue by matthewmccarthy11** [life-itself/community#705]
## Acceptance
- [x] Newsletter is sent Thursday 31st

## Tasks
- [x] Create a newsletter
 - [x] Draft sent to Lauren 29th AM
- [x] Test Newsletter
- [x] Send Newsletter

## Notes and resources

[Laurens ongoing doc
](https://docs.google.com/document/d/1vsuZWDAkdaR12kmbsNgRcIdvtPSF1tEJ7DlUfTE-mH8/edit#heading=h.f1cbn4oywtpg)

## Life Itself Updates
- [ ] Datopian how to guide? - Carry over to Sept
- [ ] Podcast? - Joe Henrich series?? (check with Lauren/Nathen) @laurenwigmore 
- [ ] October Values Initiative @laurenwigmore 
- [ ] Boaz at Sieben Linden 
- [ ] Elder's residency 

## Community Calls
- [x] Upcoming - Bella Roberts #739 and Alan Williams #717 
- [x] past Jan #682 
- [x] past Matthew #630 

## Research
- [ ] Research Forum @matthewmccarthy11 
- [ ] Paper from Boaz and Marc - https://hal.science/hal-04183218

## The hubs
- [ ] Info on what's happening
- [ ] Tenzo note from Valerie

?
- [ ] Meet the member

**Comment by laurenwigmore** [comment]
Add in Valerie still wants tenzo support

**Comment by laurenwigmore** [comment]
FIXED - sent.
