### ISSUE TITLE
Questionnaire for feedback from Whatsapp group 

### ISSUE THREAD

**Issue by matthewmccarthy11** [life-itself/community#706]
It was discussed that we might want to make a questionnaire to get feedback from the main whatsapp community channel.

## Tasks
- [ ] Conversation on what we want to achieve with the questionnaire
- [ ] Figure out which kind of survey to use (is there one we normally use?) and what kind of data we're looking for
- [ ] What kind of questions should we have? (more qualitative, or more quantitative) 
- [ ] Draft a feedback form
- [ ] Send feedback form

## Potential questions

- What would you like to see more of?
- What is working well?

**Comment by laurenwigmore** [comment]
NOT FIXED MERGED with #711
