### ISSUE TITLE
Comms Iteration 25: 7th August-20th August

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#707]
## Tasks
♾️ ♾️ 
- [ ] #454
- [ ] #657
- [ ] #624 for reference
- [ ] #636 for reference

🔥 🔥 🔥 
- [ ] #257 and #566 
- [ ] #675 🚧 in progress copy and images created
- [x] create issue for #710
- [ ] #711 
- [ ] LI outreach/marketing material Phase 2 produced for the Hub by ??? Aug #673 @laurenwigmore @nathenf
  - Important here is print books (Jake) 🚧 *sent to praxis team email for someone to print now Jake has left*, Update key articles with latest info ✅ 
- [ ] Continue with #623 
   - [x] #585 - review and test ✅  https://docs.google.com/document/d/1N6fkZh-tZZ7ZBmK3dZpTmjTgYdM_8-FKE5sZV5G0JfA/edit
   - [ ] #664 @laurenwigmore and update/finalise podcast SOPs 🚧 _encountered a few issues_
   - [ ] #636 
- [ ] Community Calls
  - [x] #682 
  - [ ] #630 🚧 
  - [ ] #725 🚧 
  - [ ] #717 

🔥 🔥 
- [x] w/c 7th post in chat re Osa's survey/message
- [ ] Translate CC101 into French
- [ ] Interview Sylvie and Rufus no.2 #674 
- [ ] Donation button #686 

⏭️ 
- [ ] Create a LinkedIn / Community call out for future guests? (or stalk a few people on LinkedIn?)
- [ ] #705 
- [x] Create a brainstorming document for engaging the general chat
- [ ] #737 - for next iteration

⏭️ ⏭️ 
- [ ] #588
- [ ] #589 as part of #568

💡 
- [ ] IG carousel of co-founders / people - could become a bit of a 'series'
- [ ] we could do a meet a member item in the newsletter like an introducing people who want to share details to the community
- [x] how to post blogs without the date in the slug?
- [ ] should we add the title Community Call to the canva posts we make for the calls?

## Availability
Lauren: 60 hours
Nathen: 
Matthew:

**Comment by laurenwigmore** [comment]
*2023-08-14* Reached out to Myka from WIC to use our sign up form for a future community call

**Comment by laurenwigmore** [comment]
### Update from 2023-08-17 meeting
Present: Lauren & Matthew

Updates
Matthew updates:
- has created a general brainstorm document related to the whatsapp group and our qualitative research project- https://docs.google.com/document/d/12ipxdI2egQByfXJuE_1BJ4b3VF56RKMrraZw7k1xoZQ/edit. Matthew proposes to take a more quantitative approach.
- Matthew’s community talk -Lauren will promote on Friday. Matthew will not be advertising personally on social media.
- Comms iteration was reviewed and updated
AOB
- Noted to schedule a meeting related to how best to keep in contact with all of the DDS and Eramus project contacts - Lauren/Nathen brainstorm and then come together w. Matthew/Boaz/Catherine (proposed end Aug/Sept)
Actions
- [ ] Matthew to update qualitative research issue with thoughts/comments from the meeting

**Comment by laurenwigmore** [comment]
FIXED - These 2 weeks focused on starting or continuing tasks in tandem. The conscious coliving course is now at 131 sign-ups. The content calendar by way of managing posting seems to be working well.
