### ISSUE TITLE
Create booking process for community calls

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#710]
When we have a confirmed speaker for a future community call, we want to have an easy streamlined process to allow them to schedule their community call date, and for us to receive all of the required information to promote the call. 

## Acceptance
- [x] Process created and in use
- [x] and added into the SOP

## Tasks
- [x] Create calendly schedule
- [x] Create template for outreach email 🚧 in the SOP https://docs.google.com/document/d/1N6fkZh-tZZ7ZBmK3dZpTmjTgYdM_8-FKE5sZV5G0JfA/edit and ready for review @laurenwigmore 
- [x] Create automatic email copy for Calendly with link to a form
- [x] Create form to capture all of the required information
- [x] Add short section to SOP
- [x] Trialed with future guest

### Notes

I think we also want to include why it is useful for people to do a community call. 
Important to consider how we can get our guests to share both before and after the call.

Outreach Email: 
- Who are we and why are we reaching out
- What is Life Itself and the Life Itself community
- Why we are interested in having you
- Actual invitation
- Framework for the call
- Select a date here => Calendly
- If you have any further questions please let me know and we can jump on a call

Calendly => Book a date => Send email

Once booked include:
- Thank you 
- Please fill out the form
- Next steps (we will create a blog post and registration 2 weeks before the event)
- We will inform you when to share with your community

What do we need in the form? ✅ https://forms.gle/Rpci8R8kYMqtkVv16 
- Name
- Contact Email 
- Title of topic
- Blurb of topic 
- Short Bio
- Profile Image 
- Is there anything else you would like to share
- Social media links

Follow up - Two weeks before: 
- Here is the link to the registration, please share it within your network
- Reminder of the date and time, request any information not yet given

**Comment by nathenf** [comment]
@laurenwigmore do we want to add something more about format? These should be more conversational and then we create masterclasses for things that are more teaching focussed?

**Comment by laurenwigmore** [comment]
> @laurenwigmore do we want to add something more about format? These should be more conversational and then we create masterclasses for things that are more teaching focussed?

Yes I agree, that would be a good idea. We could even include a link to a YouTube video we feel has done this the best so far for guidance in case they want to watch a past one.
