### ISSUE TITLE
[epic] Qualitative research and feedback from Whatsapp community - What does LI mean to you?

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#711]
To guide the outreach and communications aspects of Life Itself, we want to understand what Life Itself means to the Life Itself Community, how they perceive and interpret us, what they want from LI and where they see LI going. 

This will allow us to review if the LI mission is in alignment with the community we are attracting, and provide us with opportunities to understand what more we can do, what the community may want and why, and what is working well. 
This information can then be used to shape our outreach and communications moving forward.

We propose to do this via semi-structured interviews conducted online. Past google forms have low completion rates, have not provided the depth of information wanted, and/or are now out dated. 

We might also want to make a questionnaire to get feedback from the main Whatsapp community channel.

[Brainstorm](https://docs.google.com/document/d/12ipxdI2egQByfXJuE_1BJ4b3VF56RKMrraZw7k1xoZQ/edit)

## Acceptance

- [ ] 10(?) LI community members interviewed
- [ ] The interviews analysed 
- [ ] The results used to inform the next stage of the LI strategy
- [ ] Survey created and sent out to community

## Tasks

- [ ] Define aim and objective **🚧2024-07-11 unfinished SCQA below (done back in aug 2023 i think)** 
- [ ] Create research proposal (and get signed off)
- [ ] Questionnaire
  - [ ] Conversation on what we want to achieve with the questionnaire
  - [ ] Figure out which kind of survey to use (is there one we normally use?) and what kind of data we're looking for
  - [ ] What kind of questions should we have? (more qualitative, or more quantitative) 
  - [ ] Draft a feedback form
  - [ ] Send feedback form
  - [ ] Analyse results
- [ ] Interviews
  - [ ] Call out for participants
  - [ ] Schedule interviews
  - [ ] Host interviews
  - [ ] Analyse results
- [ ] Use results to inform next steps / strategy

## Potential questions

- What would you like to see more of?
- What is working well?

## Form links and docs - past and current

[Most recent insights form](https://docs.google.com/forms/d/e/1FAIpQLScpoq3Pj67GD2bH-UDRvlOTuYPUMxN-Dzs24ojJt6tT8Iu95w/viewform)
[General Brainstorm](https://docs.google.com/document/d/12ipxdI2egQByfXJuE_1BJ4b3VF56RKMrraZw7k1xoZQ/edit)
https://docs.google.com/forms/d/e/1FAIpQLScpoq3Pj67GD2bH-UDRvlOTuYPUMxN-Dzs24ojJt6tT8Iu95w/viewform

## SCQA (unfinished)

Situation: We would like to get feedback from the WA community, and in general, engage our community more. We would like to figure out ways in which they can get more involved in a number of different ways, and how they can all understand, at different levels, the kind of work that LI is doing. It was stated that we figure out how we fit into their ‘mental model’. Generally, this also seems to be concurrent with the general question of: what is the best way to organize our (mostly digital) community? How does one enable growth and transformation in a community? 

Complication: We do not exactly know how to engage people in a more meaningful way. The important thing here is that our aim is for engagement that is meaningful and lasting. Some traditional ways that user engagement occurs, in my mind, does not always create meaningful engagement. We don’t exactly know what to ask them: what would be meaningful? How can research into this area be meaningful? 

Question: How do we engage our members in a meaningful way? How can they get a better understanding of the kind of work we are doing? How can we ask them questions which make sense as it relates to our theory of change? 

Hypothesis:

**Comment by nathenf** [comment]
@laurenwigmore  can you merge this in as well https://github.com/life-itself/community/issues/706

**Comment by nathenf** [comment]
https://docs.google.com/forms/d/e/1FAIpQLScpoq3Pj67GD2bH-UDRvlOTuYPUMxN-Dzs24ojJt6tT8Iu95w/viewform also this

**Comment by matthewmccarthy11** [comment]
Made this document for a 'general chat brainstorm'

https://docs.google.com/document/d/12ipxdI2egQByfXJuE_1BJ4b3VF56RKMrraZw7k1xoZQ/edit

**Comment by matthewmccarthy11** [comment]
@laurenwigmore @nathenf I would be open to having a call about it sometime next week

**Comment by laurenwigmore** [comment]
Nathen and I agreed it might be worth me having a conversation with you around this and now linking this into an end of Q4 questionnaire that could be used to inform our next steps for 2024 Q1 (or beyond Q2-4).
Some suggested questions and information we might want to consider collecting is:
- Over the last year what has been your experience of LI?
- What improvements would you suggest?
- What do you need more clarity on?
- What were the highlights? 
- What do you hope to see next year?

@matthewmccarthy11 Could you follow up with me on Thursday 5th and we can arrange a meeting next week?

**Comment by matthewmccarthy11** [comment]
Hey @Lauren, sounds good with me. It might also make sense to ask questions around potentially different platforms, although maybe we can discuss during the meeting. Next week I have a pretty open Monday, shall we all meet sometime then?

**Comment by laurenwigmore** [comment]
2023-10-10 Meeting update
Met with Matthew, he will do a short review of the OKRs and strategy, and the past year and current work streams, to gain an understanding of developments and questions that might be useful to include in the questionnaire. A mock up may be created ahead of a meeting next week. The above questions to be used as a basis.

**Comment by rufuspollock** [comment]
WONTFIX. This never got completed and i don't think this is likely to happen any time soon.
