### ISSUE TITLE
CC101 Blog Post - Debunking the Top 3 Myths about Conscious Coliving

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#712]
## Acceptance
- [x] Blog post is live
- [x] All social media promo is completed

## Tasks
- [x] Blog Post Published with engaging image 
- [x] Repositioned for LinkedIn post
- [x] Write Twitter thread use [Ship30for30](https://www.ship30for30.com/post/how-to-write-a-twitter-thread) for guidance of how to write a good thread 
- [x] Post on IG

**Comment by laurenwigmore** [comment]
FIXED - all completed.
