### ISSUE TITLE
[epic] Values Month Initiative - October 2023

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#718]
Following on from the the initial conversation Lauren had with Alan Williams and the scheduled Community Call #717.

We would like to set up a small initiative to run throughout October related to values. Potentially a values jam based on Alan's [Values Jam Card Game](https://values-jam.com/) (more ideas and brainstorming to be done below).

- #726 

### Why October? 
World Values Day takes place in October, and having a consistent 'challenge/initiative' that our community could align with for the month could be a great way to engage more people, potentially feed into research or wider projects, or simply just be fun and community building within and outside of LI!

### About Alan
Alan works with Values and has written a number of books related to translating values into actions for individual and organisational use. [His website](http://www.servicebrandglobal.com/31practices/) and [Values Jam website](https://values-jam.com/)
He founded [Global Values Alliance](https://valuesalliance.net/), is involved with [UK Values Alliance](https://valuesalliance.co.uk/), and co-founded the [World Values Day](https://www.worldvaluesday.com/) in October.

He also has a [Values Jam podcast/YouTube channel](https://www.youtube.com/playlist?list=PLEqpRBgYB8PJAti_z19kMotaVADy5EQg0) and would like to invite Rufus to be a guest on this.

### Initial Idea / brainstorm
To be extended upon but to have a challenge to get people to have values based conversations daily. These could be based on one of the themes from the values jam cards or could be positioned as a question or based on LI and our values specifically. 
The aim would be to record the number (and value discussed?) of values based conversations actively held within the community throughout October, through self-reporting measures into one database. 

This would be shared with the community. i.e. _In October we had 2,000 values based conversations._
It could feed into a wider project or link into the LI research.

## Acceptance
- [x] Initiative agreed upon #726 
- [ ] arrange call with Rufus re Alan's invite (if Rufus would like to)
- [x] Initiative announced in September
- [x] 19th Oct Call taken place
- [x] Weekly promo in whatsapp chat re values for that week
- [x] Total number of values based conversations from within the community recorded
- [ ] Blog post about the values initiative

## Tasks
- [x] brainstorm ideas/how and feasibility of this
- [x] if feasible decide on exactly how 
- [x] Add blog post for October's Values Day to #657
- [x] Get proposal signed off by Rufus 
- [x] Announce in
  - [x] in September community call w. Alan
  - [x] September newsletter
  - [x] Whatsapp Chat
  - [x] IG
  - [x] Twitter thread
- [x]  Schedule 5 calls on monday @ 7pm CET and set up zoom registration for all ❌ completed but then changed to only 1 call in the month due to resources
- [x] Create Google form for people to log their conversations https://docs.google.com/forms/d/1VHgiRA9l5wTbbhWXLXWIYWb9r8OJbfVDiz9tz6f5ccU/edit 
  - [ ] Share with community
- [ ] Create other aligned blog posts - topics tbc

We want to create an initiative/challenge to engage our community and provide stimulating topics of conversations they can take out into their wider community. October has Values Day - Thursday 19th October. In September we have a Values expert hosting a community call https://github.com/life-itself/community/issues/717. We wanted to link all of these together as a way to connect more with the LI community and with the conscious coliving course.

Initial information and notes in https://github.com/life-itself/community/issues/718
[Googledoc with copy](https://docs.google.com/document/d/1PSfUQWx1A1xaUydglxNrLkvCFrDZT8udyRqwKCuVHzo/edit?usp=sharing)
[Google form to record conversations](https://docs.google.com/forms/d/1VHgiRA9l5wTbbhWXLXWIYWb9r8OJbfVDiz9tz6f5ccU/edit)
Zoom Registration Link for ALL 5 calls - https://us02web.zoom.us/meeting/register/tZcoce-hpzkuHNf-ec5IHkTIFG6uZw437Ebn

Acceptance
 Initiative announced in September
 Kick off call and proceeding 3 calls taken place
 Total number of values based conversations from within the community recorded
Tasks
 Add blog post for October's Values Day to https://github.com/life-itself/community/issues/657
 Get proposal signed off by Rufus
 Add more tasks following sign off/final discussions
 Announce in
 in September community call w. Alan
 September newsletter
 Whatsapp Chat
 IG
 Twitter thread
 Schedule 5 calls on monday @ 7pm CET and set up zoom registration for all
 Create Google form for people to log their conversations https://docs.google.com/forms/d/1VHgiRA9l5wTbbhWXLXWIYWb9r8OJbfVDiz9tz6f5ccU/edit
 Share with community
 Create other aligned blog posts - topics tbc
Proposal
Purpose and Principles
Following on from https://github.com/life-itself/community/issues/718 our aim is to increase engagement with our community, and to increase the number of people attending our calls and joining our community. We would also like to encourage our community to have deeper conversations within their own communities.

The topic of values also feeds into our conscious coliving course and it can be used as another way for us to promote/align to this, and support people in a more direct way who are in or considering joining a coliving environment.

Initiative / Challenge
Throughout October we would host 4 live calls. In these calls participants would go into breakout rooms and have 15-20mins to discuss a pre-agreed value. The calls would last 1 hour and cover 3 values. The 3 values of each week would be announced in the community chat, and we would encourage the community to have conversations based around these values as much as possible that week - we would position it as a challenge to have as many of these conversations throughout the month as possible.

We would invite the community to record the number of conversations they have and the values on a simple google form. Max 2 questions - 1. how many values conversations did you have this week? 2. what were the values you discussed?

At the end of the month (assuming individuals use the form) we would announce the amount of conversations we had as a community.

We would announce this via the usual methods - blog post, Whatsapp chat, newsletter, social media. We would run reminders as part of the October section of https://github.com/life-itself/community/issues/657

We would also write other articles related to 'best practices' for conversations such as circling, authentic relating, ahead of October.

Budget / Resources
Decision on values and discussions pre-set up - 5 hours
Initial set up of calls, copy for announcements and content for blogs (September) - 15 hours
October calls, engagement with community - 20 hours
Total: 40 hours

5 person days $250 = $1250

Roadmap
Newsletter September
Blog post
Newsletter October
5 meetings on Mondays in October
October 2nd: What are values, Why are we talking about values? Find your values: Reflecting and Sharing
October 9th: Community, Creativity, Compassion
October 16th: Environment, Food, Spirituality
October 23rd: Leadership, Pleasure, Responsibility
October 30th: Wrap-up, have peoples values become more concrete, What have you learnt this month?
Question for each week: What changes will you make based on discussions around these values?
Blog post wrap-up in early November
Testimonials, Metrics, What we did

**Comment by nathenf** [comment]
@laurenwigmore just flagging I will not be able to attend or facilitate any so may want to consider the amount. Totally forgot I wouldn't be able to.

**Comment by nathenf** [comment]
@laurenwigmore seems like most of the tasks are complete here. Maybe we need to update the tasks and acceptance to include the call and output afterwards.

**Comment by laurenwigmore** [comment]
The Values Jam call went really well and has resulted in a collective action of a co-authored blog post with the attendees. 
No-one has completed the form to capture if conversations were happening. 
Summary at this point is that this is a really relevant topic (lots of initial interest/reactions in the whatsapp chat) but less in-person action, unless the topic of values appears to be playing very strongly in an individuals life. Interestingly those on the call were all relatively 'new' active members of LI - who had been 'lurkers' prior to the call.

**Comment by nathenf** [comment]
@laurenwigmore might be something useful to integrate into CC workstream. Values Masterclass on Aligning Coliving Values 

I guess this issue can be closed now?

**Comment by laurenwigmore** [comment]
> @laurenwigmore might be something useful to integrate into CC workstream. Values Masterclass on Aligning Coliving Values
> 
> I guess this issue can be closed now?

It will be once I've published the blog post (next week) which was a collective action agreed upon by all those in the call. 
And agreed on the usefulness of the topic related to CC.

**Comment by laurenwigmore** [comment]
FIXED. Closing now, will write a summary and post group collective blog w/c 30th October.
