### ISSUE TITLE
Conscious Coliving Course - where do we go from here

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#720]
Following on from the success of the Conscious Coliving Course 101, we want to create ways to continue to engage our audience, provide them with useful and practical knowledge into action, and also to monetize LI offerings.

[Brainstorm - resources & ROI](https://coggle.it/diagram/ZNTmt1pO0W45A8Hv/t/-)
[v3 Strategy Revision Coogle](https://coggle.it/diagram/Y3IJZ_nDY3PfaFPG/t/life-itself-v3-strategy-revision-what%27s-not-changemakers)

## Acceptance
- [ ] Next offering agreed
- [ ] Strategy for it's implementation set up

## Tasks
- [ ] Brainstorm: where at, what could be useful - pros/cons
- [ ] conduct surveys/research into what LI members want #711

**Comment by laurenwigmore** [comment]
### meeting 2023-08-29 notes
- We can film during my time in Bergerac. 
- Q: What is the course about? 
	- Should lead off from CC101
		- Practices for conscious community? 
		- Who else is at the hub?
		- Marc hub practices
		- Valerie cooking for community 
		- Catherine non-violent communication
		- Sylvie imagination and creativity
		- Rufus economics or science of awakening\
		- Nathen sharing is caring
		- Lauren personal wellbeing, energy systems ETF/nervous system
		- Karl Steyaert - Internal Family Systems
		- Liam Kavanagh - Contemplative Activism, Interbeing
		- Boaz - Somatic experiencing/relational embodiment 
		-  Zencaster


**Course on community living practices**


Diginomics next courses:
Paying for the First Copy: Designing Digital Business Models.
Discovering Hidden Digital Cause of Rising Inequality

**Comment by nathenf** [comment]
@laurenwigmore lets link this to beacon epic and maybe transfer the notes from here that are relevant to the beacons issue

**Comment by rufuspollock** [comment]
This was an idea from summer 2023. In ideas inbox as may return to it one day. Wasn't really shaped - more ideation atm.
