### ISSUE TITLE
October Values Based Conversation Events

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#726]
We want to create an initiative/challenge to engage our community and provide stimulating topics of conversations they can take out into their wider community. October has Values Day - Thursday 19th October. In September we have a Values expert hosting a community call #717. We wanted to link all of these together as a way to connect more with the LI community and with the conscious coliving course.

Initial information and notes in #718 
[Googledoc with copy](https://docs.google.com/document/d/1PSfUQWx1A1xaUydglxNrLkvCFrDZT8udyRqwKCuVHzo/edit?usp=sharing)
[Google form to record conversations](https://docs.google.com/forms/d/1VHgiRA9l5wTbbhWXLXWIYWb9r8OJbfVDiz9tz6f5ccU/edit)
Zoom Registration Link for ALL 5 calls - https://us02web.zoom.us/meeting/register/tZcoce-hpzkuHNf-ec5IHkTIFG6uZw437Ebn 

## Acceptance
- [ ] Initiative announced in September
- [ ] Kick off call and proceeding 3 calls taken place
- [ ] Total number of values based conversations from within the community recorded

## Tasks
- [x] Add blog post for October's Values Day to #657
- [x] Get proposal signed off by Rufus 
- [ ] Add more tasks following sign off/final discussions
- [ ] Announce in
  - [ ] in September community call w. Alan
  - [ ] September newsletter
  - [ ] Whatsapp Chat
  - [ ] IG
  - [ ] Twitter thread
- [x]  Schedule 5 calls on monday @ 7pm CET and set up zoom registration for all
- [x] Create Google form for people to log their conversations https://docs.google.com/forms/d/1VHgiRA9l5wTbbhWXLXWIYWb9r8OJbfVDiz9tz6f5ccU/edit 
  - [ ] Share with community
- [ ] Create other aligned blog posts - topics tbc

### Purpose and Principles 
Following on from #718 our aim is to increase engagement with our community, and to increase the number of people attending our calls and joining our community. We would also like to encourage our community to have deeper conversations within their own communities. 

The topic of values also feeds into our conscious coliving course and it can be used as another way for us to promote/align to this, and support people in a more direct way who are in or considering joining a coliving environment. 

### Initiative / Challenge
Throughout October we would host 4 live calls. In these calls participants would go into breakout rooms and have 15-20mins to discuss a pre-agreed value. The calls would last 1 hour and cover 3 values. The 3 values of each week would be announced in the community chat, and we would encourage the community to have conversations based around these values as much as possible that week - we would position it as a challenge to have as many of these conversations throughout the month as possible.

We would invite the community to record the number of conversations they have and the values on a simple google form. Max 2 questions - 1. how many values conversations did you have this week? 2. what were the values you discussed?

At the end of the month (assuming individuals use the form) we would announce the amount of conversations we had as a community. 

We would announce this via the usual methods - blog post, Whatsapp chat, newsletter, social media. We would run reminders as part of the October section of #657 

We would also write other articles related to 'best practices' for conversations such as circling, authentic relating, ahead of October.

## Budget / Resources
Decision on values and discussions pre-set up - 5 hours
Initial set up of calls, copy for announcements and content for blogs (September) - 15 hours
October calls, engagement with community - 20 hours
Total: 40 hours

5 person days $250 = $1250

## Roadmap 

- Newsletter September
- Blog post
- Newsletter October 
- 5 meetings on Mondays in October
  - October 2nd: What are values, Why are we talking about values? Find your values: Reflecting and Sharing
  - October 9th: Community, Creativity, Compassion
  - October 16th: Environment, Food, Spirituality
  - October 23rd: Leadership, Pleasure, Responsibility
  - October 30th: Wrap-up, have peoples values become more concrete, What have you learnt this month?
  - Question for each week: What changes will you make based on discussions around these values? 
- Blog post wrap-up in early November
  - Testimonials, Metrics, What we did

**Comment by nathenf** [comment]
MERGED - into #718
