### ISSUE TITLE
Blog post about Sieben Linden by Boaz

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#727]
## Acceptance

- [ ] Blog post is published and shared through our network

## Tasks

- [ ] Add some context about the account
- [ ] Add more details and history about the eco-village
- [ ] Include call to action about the cc101 course
- [ ] Review and make any neccessary edits
- [ ] Publish - use photo from Sieben Linden 
- [ ] Inform them that the article has been written
- [ ] Share the article across our network 

### Text 

Sieben Linden: 30 solid years of eco-village experience.

A car park, completely quiet, some mud on the road, a rainy day. It’s (to say the least) a modest welcome we get when arriving in Sieben Linden, one of Germany’s oldest and most significant ecovillages. I lift my suitcase by hand, because the gravel makes it impossible to roll it, and arrive in the village center: a café, a large tent with tables, a circle of chairs in the nearby grassy space. I get a little more of a felt-sense of community. As I enter the main building, I start to greet and meet some of the people working, and it’s buzzing. Lots of movement to organize the lunch, the admin officer responding to several of us arriving at the same time, and it’s quite a heart-warming sense I get by now.

I get the instructions to my room and some details for the practicals and schedule, all in German (they make a point of that as much as possible). Then I walk over to a new building across the field, a 2-storey straw bale and 100% ecological construction – it’s impressive. They have a system of compost toilets everywhere, solar panels and no wifi (but they do have ethernet cables, it’s to prevent the waves). Triple glazed windows and a ventilation system to manage heating and freshness. It’s not only all organic but also entirely local, using the expertise from the villagers, and the local communities.

I went to do 3 courses there: “Introduction to Eco-village living,” “Exploring money, power and decision-making in community,” and “The community compass” – which have a learning architecture which is primarily based on relationships, within the group and with a wide range of villagers. I’m used to relatively intense personal development practices, so all this felt quite relaxed (though most people in the groups went through powerful experiences), yet I did get a good sense of how the community evolved to be as it is today, with its social practices and ecological principles. 3 things stand out about community living: 

(i) having a lot of social contact, so be ready for that! Living with other people means you’ll find many beautiful connection points and belonging, yet you’ll also get triggered many times. Being intent on working with emotions, communication and relational dynamics is a non-negotiable must!

(ii) A diversity of views needs to be respected and celebrated for everyone to feel included, and that means many things take time, often a lot of time, to happen. One time, some villagers wanted to have a sauna, and so they brought it up to the monthly council meeting. It took many months for a strategy to be out forward, yet nothing had started really. A small group then decided to make it themselves, and offer it to the village. While that was a pleasant surprise to many, it still took 2 years to decided how to organize it and where to place the sauna!

 (iii) The vision you start with shapes the entire trajectory – which is also a complex systems principle – so for example, one villager really care about building sangha and a community of spiritual/meditation practice. But Sieben Linden started out as an eco-village with  focus on ecology, not spirituality or meditation, and despite many efforts and years of labor, this villager and a few people supporting her never puled it through to make meditation a significant part of the village life.
 
Finally, as I left the village, I really felt it was a unique place, shaped through the millions of interactions people had had there, most of which were deeply felt and thought-through and intentional. That felt sacred.
