### ISSUE TITLE
Tenzo note 9 photo not showing on blog post

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#736]
On the blog post [Tenzo Note 9: Unveiling the Tenzo: Zen Tradition's Culinary Activist](https://lifeitself.org/blog/2023/07/28/tenzo-note-9) the main blog post image is not showing up. 

## Acceptance
- [ ] Main image now shows up on post
- [ ] Lauren informed of issue so can self-correct in future

## Tasks
- [ ] Ola to work her magic

**Comment by laurenwigmore** [comment]
Hi @olayway Ola, I've had another problem related to commit/PR https://github.com/life-itself/community/pull/759
I deleted an incorrect blog post (that I somehow managed to duplicated I think). However, when I wrote a new blog post and pushed it to a PR request, I was notified of a conflict. The original incorrect blog post still seemed to be there and I couldn't merge the two.

I think maybe the initial error was to do with how I was using the branches (main and lauren-1) but I'm not sure. Once you're back it would be great if we could go over this together, and also this might be useful to add into a 'how to'.

**Comment by laurenwigmore** [comment]
Here is another example, of content I am writing but don't want to publish yet. 
![image](https://github.com/life-itself/community/assets/132304704/c50d3e3e-1473-400c-84b8-9dd2233ce055)

**Comment by olayway** [comment]
@laurenwigmore Nathen has moved the image outside of the /content/assets/images folder, to /assets/images (in the root of the repo), so it can't have worked. See changes in this commit https://github.com/life-itself/community/commit/5c5ed13aa41ee6c906c124a461a45a33025cb6a7

<img width="834" alt="image" src="https://github.com/life-itself/community/assets/52197250/c77681d0-e64c-4efe-91e6-77685d268f9e">

In the commit, there is also one file that has been renamed to `.jpg.md` 😅 What is that?

cc: @nathenf

**Comment by olayway** [comment]
@laurenwigmore, @nathenf the frontmatter field was used incorrectly. It should be `image` instead of `images` + the path should always start with the leading `/`, so `/assets/images/...`. My advice for you guys is to always check what's different from other blog posts for which the images do show up. It is just not possible that they just randomly don't show up. In the future, I could create templates for you with all the available frontmatter fields for different content pages, as we discussed @laurenwigmore. For now, next time you write a blog post, just copy over the frontmatter from some old blog post that you're sure displays correctly.

I've fixed it for tenzo 9 but also for these two:
- exploring-intentional-communities-from-6-different-perspectives.md
- content/initiatives/possibility-now.md

For the last one though it doesn't look very good, so please double check if this is what you wanted to have.
