### ISSUE TITLE
Admin Access Tidy Up

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#737]
A review of and update of the admin access on the LI accounts, removing or adding people accordingly.

## Acceptance
- [ ] Main accounts all updated to be correct as of September 2023

## Tasks
- [ ] Identify accounts to review
- [ ] Remove individuals
- [ ] Add individuals
- [ ] Adjust permissions accordingly

### Accounts
- [ ] Linkedin
- [ ] IG
- [ ] FB
- [ ] Zoom
- [ ] Email groups
- [ ] Bitwarden LI access
