### ISSUE TITLE
Community Call with Myka McLaughlin

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#738]
Myka McLaughlin |12/10/2023 | Community Practice/Living | Title: Community Living - Two Best Practices in a Thriving Community House

## Acceptance

- [x] Community call hosted and recorded 
- [x] Uploaded to Youtube and blog post 

## Tasks

Pre-event

- [x] Confirm speaker
- [x] Collect and confirm details
  - [x] Contact for speaker
  - [x] Time
  - [x] Date
  - [x] Blurb for speaker
  - [x] Profile picture
  - [x]  Confirm who is hosting/mcing
  - [x]  Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [x]  Create Canva graphic using template 
- [x]  Create registration using Zoom
- [x]  Create the blog post
  - [x] Include image, registration link, biography of speaker or description of the event
- [x] Promotion
  - [x] Emails
    - [x] Initial announcement (main group) on if newsletter was more than a week ago ✔️ via newsletter
    - [ ] Day before announcement (main group) only if initial announcement was more than a week ago
    - [ ] Email reminder (recipients)
    - [x] Plus in newsletter (if applicable)
  - [x] Whatsapp
    - [x] Initial announcement
    - [x] 3 days before
    - [x] Day before
    - [x] 1-2 hours 
  - [x] Twitter
    - [x] Thread for initial announcement
    - [x] 3 days
    - [x] Day before
  - [x] Instagram
    - [x]  Stories
      - [ ] Story template or resharing post
      - [x] Initial
      - [x] 3 days before
      - [x] Day before
  - [x] Post for initial announcement 

Post-event

- [x] Make the youtube video ✅ https://www.youtube.com/watch?v=lnxCF4EuysU
- [x] Update original blog post with youtube video plus information ✅ https://lifeitself.org/blog/2023/10/03/community-living-two-best-practices-in-a-thriving-community-house
- [x]  Title: Should include name of person, plus keywords/topic
- [x] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [x] Update CRM with links etc. 
- [x] Let the speaker know and make it easily shareable

**Comment by laurenwigmore** [comment]
@alexianetcu it would be great if you could add doing some initial social media promotion this week for this community call. We would need an IG post, an announcement in the Whatsapp Chat, I usually set up the call as an event on LinkedIn (if you can't do that then a post is fine), and a twitter announcement. Would you be OK to do that on Thursday 5th? That is one week away from the call then. And then we can do a follow up on Tuesday next week.

**Comment by nathenf** [comment]
@laurenwigmore call is live now so you can let Myka know, I think I will do some clips from this call as it was really good, but will open a new issue for this. I will leave sharing on Whatsapp to you

**Comment by laurenwigmore** [comment]
FIXED.
