### ISSUE TITLE
Comms Iteration 26: 21st August - 3rd September

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#741]
## Tasks
♾️ ♾️ 
- [ ] #454
- [ ] #657
- [ ] #624 for reference
- [ ] #636 for reference

🔥 🔥 🔥 
- [ ] #737
- [x] #705 
- [ ] #257 and #566 
- [x] #675 - https://lifeitself.org/community
- [ ] #711 
- [ ] Continue with #623 
   - [ ] #664 @laurenwigmore 🚧 and update/finalise podcast SOPs ✔️ 
   - [ ] #636 
- [ ] Community Calls
  - [x] #630 
  - [ ] #725 🚧 
  - [ ] #717 🚧 
  - [ ] #738 

🔥 🔥 
- [ ] #761 🚧 
- [ ] Translate CC101 into French
- [ ] Donation button #686 

⏭️ 
- [ ] Create a LinkedIn / Community call out for future guests? (or stalk a few people on LinkedIn?)
- [ ] LI outreach/marketing material Phase 2 produced for the Hub on hold #673 
- [ ] Interview Sylvie and Rufus no.2 #674 
- [ ] Intro jingle on podcast to be updated - run through Adobe podcast

⏭️ ⏭️ 
- [ ] #588
- [ ] #589 as part of #568

💡 
- [ ] IG carousel of co-founders / people - could become a bit of a 'series'
- [ ] we could do a meet a member item in the newsletter like an introducing people who want to share details to the community
- [ ] should we add the title Community Call to the canva posts we make for the calls?
- [ ] community living type roommate sites - compile a list and write a blog? issue created #773 

## Availability
Lauren: 60 hours
Nathen: 25 hours
Matthew:

**Comment by laurenwigmore** [comment]
Jana - who emailed on 24th Aug - could they be a community call participant?

**Comment by nathenf** [comment]
FIXED - this iteration was mostly just ticking over on content creation, community calls. We also built a community page and Lauren has been learning how to make podcasts and is creating a learn page for Culturology. Next iteration: #774
