### ISSUE TITLE
Publish Joseph Henrich Podcast Ep. 3 & 4

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#744]
Use the Podcast SOP and publish the Joseph Henrich Podcast Ep.3 & 4 

## Acceptance 

- [x] Conversations published on Youtube & Spotify. 
- [x] Blog Post containing all content published (may be a series overview blog including ep.2)
- [x] Learn page added to the website
- [ ] Guest informed that the episode is out and has been sent the links
- [ ] The new episodes/series have been announced on Twitter
- [ ] Email announcing a new episodes/series has been sent to mailing list
- [ ] Secondary content has been shared on social media
- [x] Podcast SOP has been finalised and all templates available in it

## Tasks

- [x] Copy this Template into a new GitHub issue. Name the issue as the working title of the conversation
- [x] [Create a new folder for the conversation and assets here](https://drive.google.com/drive/folders/12BskqKPp85XNdU2sespI--E7VPi45hGJ?usp=sharing) - 📂 [Exact Folder Link](https://drive.google.com/drive/folders/1cJRGGmWLZpzWX8sNkP_09Bvf92Jx3nBa?usp=drive_link) and [Culturology Link](https://drive.google.com/drive/folders/1dpP6gxfdor0y0SRSmLQzRrShW4VIjfSq?usp=drive_link)
- [x] Source the video file and add to folder
- [x] Create a document for the conversation that includes: Title, Conversation Summary, About the person in conversation, links to resources mentioned in the podcast, timestamps for at least two video excerpts and two quotes and timestamps for ["chapters"](https://www.youtube.com/watch?v=pvkTC2xIbeY). Add this to folder. 
- [x] Watch the video. Note any moments that need edited e.g. moments of bad internet connectivity. Note down timestamps for chapters to be used when publishing to YouTube. Note timestamps of short sections that will be good for social media (max length for twitter 2m20s) and note down quotes that will be good for marketing the episode.

#### Create Youtube video
- [x] Create the Youtube Yellow Thumbnail from [this template](https://www.canva.com/design/DAE99drPH4s/7mR8CgHWyHfimwC9jDerDA/edit?utm_content=DAE99drPH4s&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton).
- [x] Edit the video file in [Da Vinci Resolve](https://www.blackmagicdesign.com/products/davinciresolve):
  - [x] Trim beginning and end, plus any sections of poor internet connection or other interruptions
  - [ ] Add yellow thumbnail at the beginning of the video with a fade transition to the video 
  - [ ] Add graphic overlay ["Please Like & Subscribe"](https://drive.google.com/file/d/1iQjSdgjTyrN9xnQ8Xnlzdjmk2sw2eKXJ/view?usp=sharing) at the 5, 10, 20, 40 minute
  - [x] [Add End Screen with a fading transition](https://drive.google.com/file/d/1fC8c_tyoOxxGGhGqgJuwFscu6vYzbrqe/view?usp=sharing)
  - [x] Increase the sound volume as much as possible without clipping the sound (around 3 is normally good) 
- [x] Export as Video for Youtube
- [x] Export audio only for podcast
- [ ] Upload to Youtube: Add title, thumbnail, summary including [contents chapters](https://www.youtube.com/watch?v=pvkTC2xIbeY), page stub URL, add to relevant playlist, Add Language, Make License Creative Commons. - https://youtu.be/Ct1mq0sxrMI
- [ ] Schedule publication for desired day and time 

#### Create Podcast
- [x] In Spotify (log in Anchor) click new episode then click create new episode. Click on reuse your previously uploaded audio and scroll down until you find the "Intro Jingle". Drag the file in the box into the right. Add the audio-only edit of the episode after the intro. Click save episode.
- [x] Add title & summary.
- [x] Create and add thumbnail from [this template](https://www.canva.com/design/DAE87pGGDUg/EgrVC9iJX5eATZGF5rE2pg/edit?utm_content=DAE87pGGDUg&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton)
- [ ] Add season number and episode number
- [ ] Schedule publication for desired day and time 
  
#### Create blogpost
- [x] Draft blogpost prior to scheduled publication of the episode on YouTube and Anchor. 
- [x] Add a new blog in the vault/blog folder in the Community repo. 
	- [x] Follow the format: put it in date structured folders eg. vault -> blog -> 2023 -> 01 -> 16 -> blog-file-name.md. For the frontmattter fields have a look at any of the other blog posts within that folder and follow that format. Once added commit the new file as you usually would. For more directions on how to add to the website see the [Web3 site contributors' guide](https://web3.lifeitself.org/meta/editing) and/or the [ecosystem mapping site guide](https://ecosystem.lifeitself.org/contributors-guide).
- [ ] You can add in the YouTube link as you can access that even before the video is published, however you can't with the Anchor link. Once the podcast is published, source the embed link to the episode found when you click on the episode on Anchor and paste into the blog (use previously published podcast blog posts as a guide).
- [x] The blog should feature a brief introduction of the guest and an intro to the episode (eg v brief overview of what is discussed).
- [ ] Add any notes. Ensure they are complete, comprehensive and tidied.
- [x] Add any references and further reading
- [ ] Add the transcript
	- [x] Run the video through Otter to generate the transcript. Go through and fix any errors. Export as docx with speaker names and timestamps.
	- [x] Copy the transcription into a Google doc and save it in the episode folder. 
	- [x] Convert into markdown. Copy and paste into a blog post.

#### Next
- [ ] Once the episode is published to YouTube and Anchor, publish the blog post with the links. Once the blog post is published, edit the YouTube and Anchor episode bios and paste in the link to the blog.
- [x] Once the YouTube video, podcast episode and blog post are published, **create a page for the episode on the [podcast page](https://lifeitself.org/podcast) of the website.**
	- [x] Add a new page in the vault/podcast in the community repo. Use [Jeffery Martin episode page](https://lifeitself.org/podcast/a-scientific-approach-to-awakening-and-fundamental-wellbeing-podcast) as a guide. Generate the links for the frontmatter:
		- [x] Follow this link: https://rss2json.com/
		- [x] Paste this link in the box on the page (under the text that says Enter the URL to your RSS feed): https://anchor.fm/s/79b39934/podcast/rss 
		- [x] Find the podcast episode you are wanting to create the page for (likely the first episode listed, this will be the first episode under the line that says "items")
		- [x] Click the button with 4 arrows pointing outwards to make it full screen to ensure you don't copy only part of a link.
		- [x] Copy the link for "thumbnail" and paste it after "image:" in the front matter.
		- [x] For the src link, scroll down to where it says "enclosure" and copy the link that follows "link". Paste this after "src" in the front matter. 
		- [x] Fill out the rest of the frontmatter.
	- [x] Paste the same short intro to the episode and guest as used in the blog post below the frontmatter. Paste the youtube link and the link to the blogpost. 
- [ ] **Inform the guest that the episode is out.** Send all links and encourage them to share.
- [ ] **Send email out to Life Itself General Audience on Mailchimp** announcing that the latest episode of the Life Itself Podcast is now available. Use the same intro to the episode and guest as used in blog. Paste link to the podcast page - they can navigate to everything they need from that one link. Use a previous podcast episode launch email as a guide - you can replicate that email, just remember to change the text, link, subject line and preview text. 
- [ ] **Announce release on Twitter.** Make sure to @ the guest and tweet the link to the podcast page. 

## Podcast Landing page content

**Comment by laurenwigmore** [comment]
@olayway I published episodes 3&4 and episode 2 #664 under the podcast section on the website. Initially episodes 3 & 4 were showing up. But since making updates to the copy episodes 3 & 4 are now no longer showing. Episode 2 has never shown up. I've compared with other podcast notes on Obsidian but I can't figure out a fix. Can you shed any light?

**Comment by olayway** [comment]
@laurenwigmore Podcast 2 is showing up but with "Invalid date":

<img width="1582" alt="image" src="https://github.com/life-itself/community/assets/52197250/9c0babf8-2111-4907-a4ff-eb876a7af584">

This is because podcast document types don't support both `created` and `date`, only `date`. I'm not gonna add support for it and soon when we upgrade to latest Flowershow, we'll probably support only one of these fields for both blogs and podcasts. Anyway, I'll fix it now.

**Comment by olayway** [comment]
@laurenwigmore 

```


15:33:27.296 | ├── 6 documents contain field data which didn't match the structure defined in the document type definition. (Skipping documents)
-- | --
15:33:27.297 | │
15:33:27.297 | │   • "podcast/Cultural-Evolution-Culture-Cultural-Evolution-and-the-Scaling-of-Societies.md" of type "Podcast" has the following incompatible fields:
15:33:27.297 | │     • author: ["lauren-wigmore"]
15:33:27.297 | │   • "podcast/Cultural-Evolution-Implications-and-whats-next.md" of type "Podcast" has the following incompatible fields:
15:33:27.297 | │     • author: ["lauren-wigmore"]
15:33:27.297 | │   • "templates/blog.md" of type "Page" has the following incompatible fields:
15:33:27.297 | │     • created: {"{ date }":null}
15:33:27.297 | │   • "templates/projects.md" of type "Page" has the following incompatible fields:
15:33:27.297 | │     • created: "{{date}}"
15:33:27.298 | │   • "templates/residencies.md" of type "Page" has the following incompatible fields:
15:33:27.298 | │     • created: null
15:33:27.298 | │   • "blog/2023/07/25/results-of-inauguaral-life-itself-research-hackathon.md" of type "Blog" has the following incompatible fields:
15:33:27.298 | │     • categories: "research"
15:33:27.298 | │
15:33:27.298 | └── Invalid markdown in 1 documents. (Skipping documents)
15:33:27.299 |  
15:33:27.299 | • "blog/2022/06/17/history-humility-and-the-seeds-of-a-new-culture.md" failed with YAMLSyntaxError: All collection items must start at the same column


```

**Comment by nathenf** [comment]
@laurenwigmore what is left in this issue? Can we close?

**Comment by laurenwigmore** [comment]
> @laurenwigmore what is left in this issue? Can we close?

I could do with doing some smaller social media actions on this to promote, but I can make a note and will close this now
