### ISSUE TITLE
The Great Turning with Joanna Macy Community Viewing

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#761]
Following on from a discussion in the community chat regarding the climate crisis, a trailer to Joanna Macy's The Great Turning was shared. Due to the interaction on the chat related to this topic (the most we've received between a number of members in a while) we would like to host a community call where we watch the documentary together and then have a discussion afterwards.

The documentary is 30 minutes long and [can be watched for free here](https://www.christopherlandry.com/greatturningfilm)

## Acceptance
- [ ] Call is hosted
- [x] Announcements made in whatsapp

## Tasks
- [x] Decide date and time - Monday 11th September 7pm CET
- [x] Schedule zoom call
- [x] Create content for community 
 - [x] Community Chat
- [ ] Host call and discussion

#### 2023-09-11 
Call to be rescheduled due to very low numbers showing up

**Comment by nathenf** [comment]
We had poor attendance, but partly due to not promoting much. Do we want to try again or leave for now? @laurenwigmore I leave to you since I am basically no longer able to attend community calls.

**Comment by laurenwigmore** [comment]
> We had poor attendance, but partly due to not promoting much. Do we want to try again or leave for now? @laurenwigmore I leave to you since I am basically no longer able to attend community calls.

I am thinking potentially in early November, after the Values Rally and community calls in October. Although if left until then I think it will be forgotten.  Or final week of September, but let's see where we end up after the interviews for the new person and the other actions still to do.

**Comment by nathenf** [comment]
@laurenwigmore shall we schedule for end of October?

**Comment by laurenwigmore** [comment]
> @laurenwigmore shall we schedule for end of October?

Very end (30th/31st) or beginning of November would be better for me - probably the beginning of Nov, as we have the newsletter at the end of October.

**Comment by nathenf** [comment]
@laurenwigmore suggest we move this to somedaymaybe or close as wontfix. Since it is not directly relevant to Conscious Coliving and we should prioritize documentaries related to CC

**Comment by laurenwigmore** [comment]
NOT FIXED. Closed. Could be introduced into a community hangout in the future.
