### ISSUE TITLE
CC101 Blog Post & Promo - Exploring Intentional Communities from 6 Different Perspectives

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#765]
## Acceptance
 - [x] Blog post is live
 - [x] All social media promo is completed

## Tasks
 - [x] Blog Post Published with engaging image
 - [x] Repositioned for LinkedIn post
 - [x] Write Twitter thread use [Ship30for30](https://www.ship30for30.com/post/how-to-write-a-twitter-thread) for guidance of how to write a good thread
 - [x] Post on IG

**Comment by laurenwigmore** [comment]
FIXED.
