### ISSUE TITLE
Comms Iteration 27: 4th September - 17th September

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#774]
## Tasks

♾️ ♾️

-  life-itself/community#454
-  life-itself/community#657
-  life-itself/community#624 for reference
-  life-itself/community#636 for reference

🔥 🔥 🔥

- [ ]  Focus in on the next actions for Conscious Coliving life-itself/community#257 and life-itself/community#566
- [ ] life-itself/community#744 and life-itself/community#664

* Community Calls*
- [ ]  life-itself/community#718 
- [x] life-itself/community#725 🚧
- [ ] life-itself/community#717 🚧
- [ ]  life-itself/community#738
- [ ] life-itself/community#761 🚧
- [ ] life-itself/community#629 

🔥 🔥

- [ ]  life-itself/ops#153
- [ ]  life-itself/community#711
- [ ] life-itself/community#669 
- [ ] life-itself/community#778 
- [ ] Continue with life-itself/community#623
- [ ]  Translate CC101 into French
- [ ]  Donation button life-itself/community#686

⏭️

- [ ]  Create a LinkedIn / Community call out for future guests? (or stalk a few people on LinkedIn?)
- [ ]  LI outreach/marketing material Phase 2 produced for the Hub on hold life-itself/community#673
- [ ]  Interview Sylvie and Rufus no.2 life-itself/community#674
- [ ]  Intro jingle on podcast to be updated - run through Adobe podcast

⏭️ ⏭️

- [ ]  life-itself/community#588
- [ ]  life-itself/community#589 as part of life-itself/community#568

💡

-  IG carousel of co-founders / people - could become a bit of a 'series'
-  we could do a meet a member item in the newsletter like an introducing people who want to share details to the community
-  should we add the title Community Call to the canva posts we make for the calls?
-  community living type roommate sites - compile a list and write a blog? issue created https://github.com/life-itself/community/issues/773
- We get a few questions about financing for residencies - should we add an FAQ section to the residencies page?

## Availability

Lauren: 60 hours
Nathen: 20 hours

# Meetings

# 2023-09-13

Present: Lauren, Nathen, Rufus

Intention

- Understand direction of Life Itself (concretely) for the next year
- To clarify the solo and collective roles of Lauren and Nathen moving forward.
- Agree upon key goals for the rest of 2023

Agenda

- [x] Check-in
- [x] Meditation
- [x] Check intention 
- [x] Updates 
  - [x] Nathen & Lauren Updates **✅2023-09-13 see notes** 
  - [x] Rufus Updates **✅2023-09-13 a lot of hub stuff this summer. Bergerac hub has a new direction 🎉. 3 pillars: lighthouse, zenhouse, greenhouse.**
- [x] Team structure and capacity - Have a clear understanding of team moving forward (for next year) **✅2023-09-14 discussed need for some additional support**
- [x] Next steps on CC101 **✅2023-09-14 two options (can do both) a) "Essentials of Conscious Coliving" online program e.g. 5 sessions once a week. 30m of info. 30m of practice/application b) Masterclass (1h with a known expert)**
- [x] Initial discussion of strategy for community **✅2023-09-14 we had an initial discussion of strategy especially around community** 
  - [ ] e.g. #789 **✅2023-09-14 ❌ wont swithc to discord for now** 
- [x] AOB
  - [x] Nathen re Flowershow etc **💬2023-09-14 Nathen only wants something until xmas - does that work?**

### Updates Last 2 months

Summary

- Course "worked" - hit signup targets, drove traffic, built our presence in a relevant area
  - What's next: how to monetize and keep growing
- Community thriving: whatsapp continues to grow. More discussions. Community calls working well
  - What's next: expansion, engagement and direction
- Better SOPs including content calendar, ...?
  - What's next: Try this out with a junior person?
- Some work in in progress: e.g. learn page for henrich, ??
  - Experimenting more with video content
- Overall spillovers to other areas e.g. residencies etc
- Content calendar working well - https://github.com/life-itself/community/issues/657

Details

- CC101: going really well
  - - 155 sign ups (2023-09-12) plus 47% last email open rate
  - Conscious Coliving Information ranks 8th on Google
  - Conscious Coliving Course ranks 1st on Google
  (but not the CC101 page - these are both the blogs)
  - Infographic posts work well on IG (still relatively low engagement - Cult Documentary post had highest impressions/reach)
  - 5500 users on website in 90 days up 25.5% from previous 90 days
  - 47% open on last email (i.e. some kind of course completion)
  - 7 responses on feedback form
  - Where to go next? (see later discussion)
- Community calls working well
- Content calendar is going well
- Residencies: people coming in more.
- Website traffic: up 25%
- SOPs
- WhatsApp at 300+ people

### Team structure

- [x] Can hire Mxxx or Azxxx or find someone else **💬2023-09-13 having a call with Axxx next week. 🚩 what is the role / tasks we want them to do**
- [x] What kind of level of person do we want to hire? **✅2023-09-13 two kinds of thing: a) doing SOP items b) A full-time person**
- [x] Lauren capacity remains the same
- [x] Nathen winding down a bit already, mid-november basically finished, but minimum engagement (2-3 hours a week) possible for organisation, planning and brainstorming throughout 2024.
- [x] Matt's contribution is limited atm (focused on research)

### Next steps on conscious coliving and community

- [ ] Discussed the various options
- [x] Rufus brainstorm
  - Online training course with the core skills
  - Incubator (i.e. 1-3m incubator for those wanting to create or improve)
  - Month immersion? (i.e. come to the hub)

#### CC101 follow up Conscious community and practice as next step - live - then record and resell

- roleplay type scenarios
- should be able to get at least 10% sign up
- price? maybe 100+ euro?
- facilitation by Rufus, Sylvie, Lauren, Nathen

#### Masterclass

 - & a MC with a guest expert as an evergreen 
 - (builders/CC essential - if you're interested in building a community or those who are about to go and live in a CC - funneling into zenhouse)

Evaluation criteria for what we do next

- 🔥🔥 Relatively low cost (to do the first MVP)
- 🔥🔥🔥 Revenue generating (so we test people pay)
- 🔥 Can learn from it (rapidly) and iterate
- 🔥 Aligned with our funnel for zenhouse or lighthouse

---

### Random notes

- LI forum - channeling from github discussions 
- and commenting on blogs available via github
- what are we trying to do with the group chat? what needs to people have?
 - ambassadors for LI
 - recognition and promotion (people seek permission first)
- what is the key topic we want to be known as an expert/the go-to on? 

### What do we want? (our job stories)

What do we want the community to do?

Rufus:

- Where is the place "in town" you come to hangout and find "the others" and discover what is going on?
  - Then get involved in something going on ...
  - Offer my own thing that is going on (find others to participate)
  - Chat about ideas and share knowledge
- What are the kind of people we want to attract?

Main reasons i go to a chat channel:

- **What's happening:** To find out if active / what's happening
- **Get info** To get information (quicker to ask, or to archive in future, also updates often posted here first)
- **Connect**: To connect with others who are like-minded (online or offline)
- **Get involved**: it want to participate and this is a way to do so ...
- **Discuss** (enthusiasts) a specific topic, learn etc

#### in managing the community

Nathen:

- When I am managing the community I want everything in one place for ease of management [so that ...], I can spend time more efficiently into developing initiatives and adding value and can write less complicated SOPs
- I want to be able to harvest key metrics, such as levels of engagement,  [which?] from the community, so that we can use them to iterate and develop initiatives in the direction people want to see the community go (within reason) [so that ...]
- I want accessible bots that can contribute meaningfully and well for basics functions (welcoming, etc.), so that the bulk of our menial tasks are reduced while optimizing community engagement
  - Rufus: at this scale of community personally welcoming makes a real difference and is possible. a bot is obviously a bot and doesn't really make people feel welcome. 
  - Nathen: The bot is moreso for onboarding process 

Lauren

- I want an easy to use platform to avoid 1. information getting lost [so that ...] I know what is important, relevant and what the wants and needs are of the community, so I can factor this in to next steps and strategy
2. me getitng overwhelmed with 'managing it'
- I want to be able to nurture and connect easily with others, and encourage intergroup connections and chat
- I want to know clearly where to direct people to 
- I want something to function/be relatively self-sustaing incase I am not able to be present (illness, holidays etc)

### Job stories of people

Nathen:

- I want to have subgroups within a community where I can discuss or share around specific themes, so that I can find deeper resonance and value 
- I want to feel like I am part of something and I can see a clear pathway to expand in my knowledge/status/connection/contribution within the community, so that I have a sense of responsibility/integration with the community
- I want a place where I feel welcomed and heard, where I can share and listen 
- I want an online space that I am excited to go to every day because it is so aligned with my life, so that I feel nourished
- I want a space where it feels permissable to reach out to people privately 

Lauren

- I want to be able to connect and integrate easily into a group and know my voice is welcome and useful
- I want to feel a sense of contribution, and understand how I can feel more active and to also receive stimulatiing or useful content/discussions, that I enjoy and support my development/growth
- I'd love to know who I can, where I can and how to connect offline with the community (either whole or sub), so it feels 'real' and tangible. I don't want to feel like it an elusive group because I will get bored
- I want to feel regularly inspired to keep showing up. It is important for me, if I am going to invest my time and energy, that I get somehting of value - I don't want it to be another scrolling on IG rabbithole group

# Meeting 14 Sep

Present: Lauren, Nathen, Rufus
Intention
- [x] Understand direction of Life Itself (concretely) for the next year
- [ ] To clarify the solo and collective roles of Lauren and Nathen moving forward.
- [ ] Agree upon key goals for the rest of 2023

Agenda
- [ ] Discuss direction of Life Itself and understanding the goals for the next year 
  - [x] What is the aim of Life Itself in the next year and where are we going? 
  - [ ] What the priorities 
- [ ] OKRs for rest of 2023
- [ ] AOB
  - [ ] Blog Categories 
  - [ ] What does Valerie need? and where is it as a priority?
  - [ ] https://www.sacredsons.com/ - example of clear brand and funnel
  - [ ] Offer to write course from that lady (she followed up)

## Core metrics
- Signing up to the second renaissance and vision of realizing an awakening society
- Forming pockets (Why) (because that is what it takes to embody and therefore sustain and transmit the chagne we want to see)
  - Pockets are transformational centers 
- Contributing to running this sangha and the infrastructure (Life Itself - is building the infrastructure for the second renaissance - or tending the seeds of the second renaissance)

## Notes

- Lauren's OKR brainstorm
  - Objective: To create a Masterclass or Mini Course that feeds into supporting people to learn and expand (raise consciousness) on the key principles (of ... ?) required to START creating an internal shift to a wisdom mindset 
  - This wisdom mindset allows people to understand ... ?
  - With the aim to inspire action of . . . further involvement with LI, further development and/or taking an action in immediate community/locally that is . . .
  - Objective 2: Clear way in to develop/identify/nurture Shambhala Warriors
    - must focus on embodiment of practices (not just mental - there are enough theorists)
- sense of belonging / expand / learn / applied / active / relationship to nature(environment),others&self
- expansion can be learning, challenging, confronting, painful, fun, playful. Completed in community and through action.

**💬2023-09-13: see outflow in the recording**

### Big picture questions

- Even if we find shambhala warriors what is the next step AKA what do we offer them?

### Docs for Reference

- [v3 SCQH](https://docs.google.com/document/d/1vnWtHxNkahW_r2FcpJMYEs-Fvv8dhrJnisqAeewHjP8/edit)
- https://coggle.it/diagram/ZQDCfX170vn6VJAG/t/-
- https://lifeitself.org/notes/strategy-macro-to-micro-2023
- https://docs.google.com/document/d/1BheCiaGvUozHFDTVKlQjp1VsQfEcPdCGq8a_W1LdS7A/edit
- https://github.com/life-itself/community/issues/720 - MC issue

**Comment by laurenwigmore** [comment]
[Short meeting summary from 13th & 14th](https://docs.google.com/document/d/1lD3lPZtYLtpCW1cqTDMRB47Wdy-PcxqgYHVPTIwOULc/edit?usp=sharing)

**Comment by laurenwigmore** [comment]
FIXED. This iteration focused predominately on continuing with the promotion, hosting and processing of the community calls, and content output for CC101. Nathen was on reduced hours and Lauren did slightly less (carried across to next iteration). Brainstorming around next steps with Rufus began and meetings with Ola re technical requirements also took place. Next iteration #808
