### ISSUE TITLE
Residency Page FAQs

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#778]
When I come to the residency page, I want to know how I apply and what the application process entails, the expected timeline, if there is any financial support available and/or a skills exchange, so that I can more easily make a decision on whether to apply or not.

## Acceptance
- [ ] Residency Page updated with the FAQs info

## Tasks
- [ ] Get the information from the Hub
- [ ] Update the page
 - [ ] Include as a downloadable pdf(?)
- [ ] Consider/review if there are any other questions to address

**Comment by laurenwigmore** [comment]
Valerie's reply to interested participant for reference:
This residency is really based on  the MVP ( mini viable practices ) that we have  listed in the page. 
That takes about 2 to 3  hours being community  ( sitting , cooking , eating and circling once a week ) and rest is for personal time where each participants will be able to generate , offer discussions. For exemple we have Emil from mettamodernista who offers a debate once a week around metamodernism. But this kind of curation will be in the open space that residents will organize by themselves ( we recommend not to pack the free space with no more than 3 evening sessions a week) . 
Regarding documentation , we have a sself assememnt post residency questionnaire to collect the effects of such frame on people . 
Please let’s have a talk this week  if you are interested to come the 15th of October . I can also send you the photos and conditions of the hub . 
We have now about 5 people who also want to bring their network so it might be busy soon.

**Comment by nathenf** [comment]
@laurenwigmore since we only have the long term residency, this is not priority now. Perhaps we can look at it again in the new year?

**Comment by laurenwigmore** [comment]
@nathenf agreed, I'll add a later iteration so it comes back at the end of the year
