### ISSUE TITLE
Add community members to website

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#788]
Job Story 1: When I join the community I want to be listed on the community website page so that I feel recognised as a community member and so that people can connect with me

Job Story 2: When I come to the Life Itself website, I want to see who else is in the community so that I can connect with like-minded people directly or decide if I want to join the community too. 

## Acceptance
- [ ] Community Members are shown on the community page 
- [ ] There is a sort function for location and area of interest
- [ ] At least 10 community members have uploaded to the website

## Tasks 
- [ ] Decide on best approach to implement with the lowest effort 
- [ ] Build the system
  - [ ] Form for people to sign up
  - [ ] Add feature to the community page
  - [ ] Test the function 
- [ ] Launch and get people to sign up

## Brainstorm 

How do we make this most simply? Can we copy from the ecosystem? 

What is the user journey? 
- Somebody joins the community by sharing their email 
- We send them a welcome email including a link to the whatsapp chat and to a google form (or similar) 
- They fill out the form
- Once submitted the data is used to automatically generate a member page and link the profile to the main community page 
- The member is informed when it is live and they can share it in the Whatsapp group

What should be included in a member profile? 
- Profile Picture
- Bio 
- Website or link 
- Country
- Contact info (optional) 
- Area of interest (from our 12 pillars) 

Q to consider - how do we manage if members want to make changes, e.g. they live in Mexico and then move to Portugal, and want to update their location.

**Comment by nathenf** [comment]
@rufuspollock what about this?

**Comment by rufuspollock** [comment]
This is currently a someday maybe IMO.

**Comment by rufuspollock** [comment]
WONTFIX. I think we want to list actual members of Life Itself collective (as we currently do on https://lifeitself.org/people) but not every general member of the community. For people who come to the hub maybe also - see #1058
