### ISSUE TITLE
[EPIC] Move Life Itself community to better functioning platform

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#789]
## Acceptance
- [ ] Community is transitioned to Discord 
- [ ] All website connections to community updated

## Tasks
- [ ] #711 
- [ ] Set-up Discord Server
- [ ] Re-launch community
- [ ] #788 

## Brainstorm 

Situation: We have a Whatsapp community with 300+ members. We have received some great responses in terms of the content and members are generally excited to join. However, we have received feedback from multiple members about the functionality of Whatsapp for a fully interactive community. 

Complication: Whatsapp only has a linear chat function, does not have threads, or simple ways for members to interact on particular topics. There is no user journey on whatsapp except when people join (also the chat looks empty when they join). Scaling the chat is limited. 

Question: What platform should we use to host our community and how do we transition successfully to it? 

Hypothesis: More to Discord as our central community space. 

Why discord?
- Always free
- Many members alreadt use it
- Huge scalability potential
- Integrates with course building platforms
- Bots and automatations can perform menial repeat tasks
- Much better ability to gauge value and impact of the community 
- Can integrate Patreon to make paid membership or private 
- Can have private channels for specific courses (aka CC101 course channel) 

Thinking into the future what utilities do we need? 
- Course hosting
- Live programs
- Summit
- Directories 
- Seamless connection between website and community

## Resources 

https://www.youtube.com/watch?v=7Thx3fMd7-8

**Comment by rufuspollock** [comment]
I would think hard about this before doing anything. You'd need something really not to work b4 we switch because getting people to move is hard.

What about if we try and complement whatsapp with github forum more?

**Comment by rufuspollock** [comment]
2 key points:

- What are job stories?
  - Capturing richer info (i.e. threads point)
  - ...?
-  Tech is a cover for social function - focus on the social function. e.g. key to community is people regularly checking in. Irrespective of the features of say whatsapp vs discord which has people more likely to check-in?

**Comment by rufuspollock** [comment]
Looks like WONTFIX based on discussion today (at least for now). Leave this to @nathenf to update as his issue 😄

**Comment by nathenf** [comment]
WONTFIX - Whatsapp is not fully disfunctioning, so don't fix it

**Comment by rufuspollock** [comment]
@nathenf one small point:

- Good to summarize why closing as wontfix in the final message (short summary - imaging reviewing this in 6m time and wondering why we wontfix'd it ...)
- please add the label "wontfix" (i just did this so you can see it for yourself)

**Comment by nathenf** [comment]
Summary: While Discord present numerous advantages for adding roles to members, integrating our community calls and courses directly into the community and threads for longer-form communication, it also has disadvantages:
- Not a platform which most people use daily
- More complex than Whatsapp (the simplicity of linear chat function is nice)

Additionally trying to shift audience to a new platform is challenge and may result in creating an "Empty Room"

For now, Whatsapp serves the purpose we need for the community space and we will endeavour to enhance this further rather than changing.

**Comment by zhiganov** [comment]
Hi guys! It's great that you're using this forum and making your decisions a bit more transparent. However, I'm wondering if decision not to use Discord is based on previous experience / gut feelings / common sense? Do you know what % of your members already have Discord accounts? I would say if it's 30% or more, opening Discord as alternative platform (while keeping WhatsApp infrastructure intact) could make sense.
Please keep in mind there are people like me who won't be engaged in WhatsApp in a meaningful way, but would happily engage much more if it was Discord (and by engaging I mean contributing, i.e. actually helping you with stuff as opposed to chatting). I know it's a tough issue for many communities who are trying to be as open / down-to-earth as possible, but at the end of the day you should consider what type of members you need more on the current stage: active contributors or passive readers / commenters.

**Comment by rufuspollock** [comment]
> Hi guys! It's great that you're using this forum and making your decisions a bit more transparent. However, I'm wondering if decision not to use Discord is based on previous experience / gut feelings / common sense? Do you know what % of your members already have Discord accounts? I would say if it's 30% or more, opening Discord as alternative platform (while keeping WhatsApp infrastructure intact) could make sense. Please keep in mind there are people like me who won't be engaged in WhatsApp in a meaningful way, but would happily engage much more if it was Discord (and by engaging I mean contributing, i.e. actually helping you with stuff as opposed to chatting). I know it's a tough issue for many communities who are trying to be as open / down-to-earth as possible, but at the end of the day you should consider what type of members you need more on the current stage: active contributors or passive readers / commenters.

I've used a lot of platforms and in fact currently use discord. My personal "gut" feeling is that if we wanted something more substantial than whatsapp we could just use github discussions which is already our forum: https://github.com/orgs/life-itself/discussions 

What do you think about that?

Background considerations/principles here are things like:

- We really want one and only one "chat" location (you don't want people wondering which location to go to)
- We want to allow for very easy initial engagement (e.g., if possible, people are already on the platform)
- We can complement basic chat with a forum e.g. discourse or github discussions etc etc (IME very few platforms/tools can or should fulfil both functions of lightweight chat and more substantive discussion - though happy to change my mind!)
