### ISSUE TITLE
Sylvie Access to Community Repo

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#805]
## Acceptance
- [x] Sylvie has access to the main Life Itself Repository
 - [x] Sylvie can access the Community Repo via Obsidian to create and add blogs and pages

### Tasks
- [x] Add Sylvie to the Repo @olayway  **No need. Sylvie is one of the owners of the LifeItself GitHub org.**
- [x] Turn into a tutorial so Lauren can do this for new staff in future (is this possible?) **If you want to be able to invite people to the org or its repositories in the future, you need to ask one of the current owners (Sylvie, Rufus, Catherine) to make you an owner as well. Then it's pretty straightforward and I don't think it requires a special tutorial/howto. You can invite new org members in "Members" tab of the org or add collaborators of specific repositories in "Settings -> Collacorators and Teams".**
- [x] Show Sylvie how to add the repo to her Obsidian (@olayway did we record this when you showed me? do we have this as a tutorial?) **Yes, we do have a tutorial that covers it: https://portaljs.org/blog/edit-a-website-locally**

**Comment by olayway** [comment]
@laurenwigmore Sylvie is an owner of the LifeItself GitHub org, so she has access to all the repositories already.

**Comment by nathenf** [comment]
@laurenwigmore  is this fixed?

**Comment by laurenwigmore** [comment]
FIXED.
