### ISSUE TITLE
[epic] Creative Practices Course

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#806]
I want to attend a low-cost regular 'stand-up', that feels like an easy, and inspiring commitment, to help me develop or reconnect to my creativity. I want this easily fit into my schedule and provide me with a noticeable shift by the end of the course.

LI team: I want to launch the Creative Practices Course again to the Life Itself Audience to start in November 2023. I want to successfully market the course to have 15 members sign up and attend each session. 

The course includes:
- Live calls every Wednesday 7:30- 8h30am CET (starting 8th November)
- Across 6 weeks
- Small financial contribution (£90)
- A mix of practical exercises and guidance, centered around different creative themes each week

The last time this course ran was 2(?) years ago. 

## Acceptance
- [x] #807 created
- [x] 6 week course completed
- [ ] 15 sign ups

## Tasks
- [x] Kick off meeting between Sylvie and Lauren/Comms
- [x] Confirm launch date and future dates 
- [ ] Create launch strategy (to include Newsletter announcement, pre-email announcement, whatsapp discussion, IG, Twitter & LinkedIn)
- [x] Sylvie is set up to use Obsidian and post  #805 
- [x] Added to 18th Sept Comms Iteration 
- [ ] Blog posts added to #657 

## Reference
- [Creative Practices](https://docs.google.com/document/d/1qcrLDe79Vc69CE4Sg0IBETImkB6v4PmFVGdviXmIOYk/edit)
- [Feedback](https://docs.google.com/forms/d/1aRso0uF3NTpxgUJjy3rVlm6aBTctIcH0O2yZZgvCOuU/edit#responses)
- [Get s*** done](https://docs.google.com/document/d/1qAVOcbTkVHQh-EP43eJj9Vlv_XozmFMkwSg39MXF2A4/edit#heading=h.4bkf3kbd0bfl) & [Feedback](https://docs.google.com/forms/d/1oYGNwtnmbT8eJz3kqF-Q8wfqLZ1RvGoRJang7w8u1u0/edit#responses)
- [Meeting notes](https://docs.google.com/document/d/1bRuuKi5yiFMKB5A6Uj2CoUBfW5O2_pI1Za3bPsVSlkc/edit)

**Comment by laurenwigmore** [comment]
FIXED. Calls completed with 10(?) sign ups. @shiweiart to confirm.
