### ISSUE TITLE
Comms Iteration 28: 18th September - 1st October

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#808]
## Goals
For this two week sprint, we aim to have a clearly defined strategy for the next year, and deeper understanding of the Life Itself Direction, with a decision on the courses/offerings to focus on developing. Nathen will be transitioning to minimal hours so there is a need to have a tidy up and completion of tasks review, whilst we work to hire a suitable admin support and start training them. 

## Tasks

♾️ ♾️

-  life-itself/community#454
- #112 - Tracker for issues anyone can participate in (AKA Get Involved: Community Members)
-  life-itself/community#657
-  life-itself/community#624 for reference
-  life-itself/community#636 for reference

🔥 🔥 🔥
- [ ]  Focus in on the next actions for Conscious Coliving life-itself/community#257 and life-itself/community#566
- [x] life-itself/community#744 and life-itself/community#664
- [x] #791 
 - [ ] Emergent Dialogue promo (early on w/c 18th) 
- [x] #762 
- [ ] #806 

* Community Calls*
- [ ]  life-itself/community#718 🚧 
- [x] life-itself/community#717 🚧
- [ ]  life-itself/community#738 🚧 
- [ ] life-itself/community#629 🚧 

🔥 🔥
- [x] #675 - CTAs 
- [ ] life-itself/ops#153
- [ ]  life-itself/community#711
- [ ] life-itself/community#669 
- [ ] life-itself/community#778 
- [ ] Continue with life-itself/community#623

⏭️
- [ ] life-itself/community#761 🚧 _to be rescheduled?_ 
- [ ] Interview Sylvie and Rufus no.2 life-itself/community#674
- [ ] Translate CC101 into French
- [ ] Intro jingle on podcast to be updated - run through Adobe podcast

⏭️ ⏭️

- [ ]  life-itself/community#588
- [ ]  life-itself/community#589 as part of life-itself/community#568 🚧 

## Availability

Lauren: 60-75 hours
Nathen: 

# Meeting Notes

# 2023-09-19

Present: Lauren, Rufus, Nathen

Intention:

- [x] Recap and summarize strategy in words **✅2023-09-19 we have a summary**
- [x] ship the OKRs **✅2023-09-19 we have a core OKR for this autumn**
- [x] plan of work - at least brainstorm **🚧2023-09-19 we have an outline of the key things we are creating**

Agenda

- [x] Check-in
- [x] Meditation
- [x] Intention
- [x] LI v3 strategy https://github.com/life-itself/community/issues/196
- [x] Q4 2023 Comms circle plan

Link for last weeks meetings ...

https://link.excalidraw.com/l/9u8crB2ZmUo/8F30hhvlTcl

## Notes

Brainstorm posters for an online event (or course) that is oriented to Bali and Tulum (and finding the right people)

Nathen

- Caring for Bali: Cultural, Environmental, Systemic Change
- Little Island, Big Picture: An exploration of global systemic improvement through the lens of Bali
- Engaged Buddhism: Not another fuckin' Cacao ceremony!
- How to practically embody your Dharma (without being a coach)
- Regenerative living: an embodied approach to living in reality
- Performative Spirituality: How to cut through the bullshit and get grounded

### Lauren

- Plants for Purpose: How to use plants to transform your community
- Grounding for Growth: Learn how an embodied practice can support your mental health and save the world
- Body - Mind - Action: Integrate the key teachings of embodiment, thinking and how to move these to support your projects
- EFT for Anxiety: A clean energy system to help you achieve your goals
- Peace into Projects: A peaceful way to create and launch your business/projects
- How can I help?: Mindfulness techniques to live better and support others
- I'm not a shaman: come and learn how to ...
- Abundance ...

### Rufus

- Seeking a middle way that integrates purpose and presence. Come find the others ...
- Seeds of a Second Renaissance: 
- Ken Wilber, Thich Nhat Hanh, ... 
- Want to understand the mess we're in (?) ... and how we can get out of it (hint: it's needs both system change and inner change)
- Wisely get sh** done
- Build a radically wiser world (together)

Note from discussion

- Go beyond *self*-development e.g. "Time to go beyond self-development (and coaching)?"
- Are we all going to become yoga teachers and coaches? (Probably not) Exploring conscious careers beyond the cliches ...

# 2023-09-18

Present: Lauren, Rufus, Nathen
  - [Previous notes](https://github.com/life-itself/community/issues/774)
  - [AI Summary (Claude)](https://docs.google.com/document/d/1lD3lPZtYLtpCW1cqTDMRB47Wdy-PcxqgYHVPTIwOULc/edit?usp=sharing)
- https://link.excalidraw.com/l/9u8crB2ZmUo/8F30hhvlTcl

### Terminology
Steps in the transition
- Pledge
- Pockets
----
- Lighthouse, Greenhouse, Clubhouse/Zenhouse
- Second Renaissance
- Shambhala Warrior
- Awakening Society
- Awakening

### Rufus
- Awakening society comes into being through critical mass in localized areas
- Starts with pockets (which) a) network together b) build a *movement* for change)
- Our initial focus (e.g. 5-6y ago) was on these "pioneering conscious collectives proximate to the mainstream" e.g. via hubs
However, that was bit early ...

![upload_c5fefa7833ee851ecd0e95bb6f926cb2](https://github.com/life-itself/community/assets/132304704/cbc6349e-04f6-48e0-8a0e-3b451a129cbf)

### How do people shift from one paradigm to the other? Why does density (i.e. pockets matter etc)
![upload_0377f6b225686a139046bf0198c70519](https://github.com/life-itself/community/assets/132304704/ad099a5f-760b-4558-9fb7-b8e4eea56c11)

What do people belong to?

### How do we support that transition (and sustained transition i.e. w/o reversion)
Answer: Sanghas and Pockets

![upload_e83a67602328cd088baf2e4d2a214b9b](https://github.com/life-itself/community/assets/132304704/8e7dc20f-cc93-4d58-8990-f19121bb6618)

### Nathen
Discussed a more clarified collective understanding of the role of Life Itself. Significantly it's role during the second renaissance and the development or facilitation of "pockets" with a Life Itself flavour
- In essence then, the role of communications is to attract the people who are interested in our flavour of transformation and develop clear pathways to engage them in the co-creation of pockets. AKA Shambhala Warriors.
- Shambhala warriors will almost always have their own work/mission, but this is aligned with Life Itself and collaborate with us or live in pockets with us. 
- The funnel we are creating is more of a Torus shape
- There is a need for a toolbox

### Lauren
-To take people from the mental understanding (of LI's mission) into embodiment (I feel FEELING is key).
- second renaissance is the journey / transition period into the new paradigm
- 2 stages main funnel wider audience into identification of the shambhala warriors. then a second stage funnel the SW's through to then take it back out into wider community - hour glass shape
- difference embodiment of space between the Hub (creative/research/tech) and the farmhouse (art/earth)
  - Objective: take people from thinking to embodying then embodiment to wider action
 
## OKRs
Top level objective: a flourising self-growing/organizing (in long-run?) sangha of people interested/committed to embodied practical action for a second renaissance

Key results
- Growing membership
- Growing activity (both online and offline)
- Deepening i.e. people taking the vow, joining pockets
- Confirmed exit of Torus to create pockets (Shambhala Ascension 🚀)

Topics and standardised flow 
| Topics | Email course | 4week zoom | Hub week |
| -------- | -------- | -------- |----|
| Conscious Coliving |          |          |
|  2nd Renaissance        |          |          |
| Cultivating Being       | Text     | Text     |

- Campfires/hangouts
- Community calls
- Watch a movie
- Book club

**Objective:** X courses introducing the key ideas and principles and practices of second renaissance, cultivating being, life itself etc
- X courses created
- Y participated

**Objective:** contribution / participation opportunities and journey
- XX people who are excited and empowered and flourishing and resonating with the vision (for themselves)
- Journey created e.g. organizing a local group, ambassadors
  - Create roles: experts, welcomer-s, gardeners (of material), ...
- Y people at stage Z

**Objective:** Develop authentic and deeply connected Sangha / create leaders or ambassadors to convey the second renaissance and awakening message
- X people carry out initiation
- X people engage in Peer to Peer engagement/mentorship

Short Summary of Discussion: 
We opened with a review and summary in our own words around last weeks discussion. Making a note of the terminology we will use moving forward and the stages our community may go through. Reflecting on the question - how do we best influence the critical mass? Referencing the non-linear journey. Noting it is the first gas bubbles in the boiling water that we are seeking as pioneers of Life Itself - the Shambhala Warriors and/or future pocket creators (in 1-3 years time). The sangha defines a more overarching structure that the pockets form within. And our 'funnel' is more likely to be a torus. We further identified the thin line around com-modifying our creations and the impatience of many in the world wanting shortcuts to 'awakening'. Our three core topics were identified as Conscious Coliving, Cultivating Being and the Second Renaissance. The rest of the years plans were briefly reviewed and reflected upon, with some suggested changes to the Values Rally to run as a pilot. We ended discussing objectives - with the importance around an initiation being seen as integral in our next steps, and that not everyone will want or needs to be a Shambhala Warrior - therefore, what are the other roles people could or might want to play?

## 2023-09-28  - RF/LW/AN
Notes and Actions:
- [x] Alexia initial items - see https://github.com/life-itself/onboarding/issues/21
  - [x] Onboarding Alexia
  - [x] Alexia capacity and context **✅2023-09-28 imagine Alexia has 50%+ available on comms. So would say 20h+ per week**
- [ ] Prep the project backlog
  - [x] Agree process **✅2023-09-28 use kanban again and iteration issue is just goals, capacity, meeting notes and screenshots of kanban before and at end**
- [ ] AOB
  - [x] cc'ing jobs@ for jobs stuff (rather than hello)
  - [ ] start to post newsletter on blog (back post past ones)

### Onboarding Alexia to comms

- [x] WhatsApp group
  - [x] Comms team - just for comms team (not support requests)
  - [x] Comms support - support requests from wider team
- [x] add to comms-team email group
- [x] add to hello@ ?
- [x] Issue tracker / board: https://github.com/orgs/life-itself/projects/2/views/17 and we use sprint issues
- [x] ### What Alexia can help on: 
- mainly with consistency of output
  - Regular sharing e.g. twitter thread, LinkedIn Post, Instagram
  - or certain events e.g. conscious co-living: write blog post about it and promote it on social media 
  - make visuals
- outreach to groups (especially about CC101) in subreddits/fb - must engage with group a little first before posting, 
    - to maximize chances of being accepted engage in group before and/or email moderators

## Actions
- [ ] start using kanban board 
- [ ] assign Alexia to some issues (LW)
- [ ] draft email for Rufus to JH (LW)
- [x] schedule meeting with Alexia and Sylvie re obsidian (LW)
- [x] send Alexia the 6 day course & canva log ins (LW)
- [ ] re-organising or ordering images on the shared drive (AN) - later task to speak with RF on
- [ ] bitwarden log ins to Alexia - Alexia to speak with Rufus to fix log in problem 
- [ ] branding and logos document - send across (LW)
- [x] set up issue for next blog and assign Alexia - https://github.com/life-itself/community/issues/830 (LW) [Folder for blog](https://drive.google.com/drive/folders/1cwkzBU4DJcyZwlZ2OG7aoZPjXCY8PR0T)
- [ ] write and send blurbs by 11am CET 29th (AN)
  - [ ] Lauren to review and then Alexia to post

# Comms Inbox
- [ ] Portals conversation (Aviv)
  - [ ] archiving videos
  - [ ] sharing?
  - [ ] showcasing on our site??

#### Examples of Alexia posts for CMP

- [commenting about something](https://www.linkedin.com/posts/climatemajorityproject_dr-andrew-forrest-ao-speaks-at-the-boao-forum-activity-7105159320601788419-NPDu?utm_source=share&utm_medium=member_ios)
- twitter posts with visuals:   
    - https://x.com/cmp_voice/status/1706587877864337463?s=46&t=T18Tuqo6ax3J5oh3iqN8kQ
    - https://x.com/cmp_voice/status/1705162792175632644?s=46&t=T18Tuqo6ax3J5oh3iqN8kQ
    - https://x.com/cmp_voice/status/1704074143111446875?s=46&t=T18Tuqo6ax3J5oh3iqN8kQ
  - https://x.com/cmp_voice/status/1699779980744384868?s=46&t=T18Tuqo6ax3J5oh3iqN8kQ
  - https://x.com/cmp_voice/status/1699769973671878863?s=46&t=T18Tuqo6ax3J5oh3iqN8kQ
- [instagram reel](https://www.instagram.com/reel/CxVtNMpIdnw/?igshid=MzRlODBiNWFlZA==)

**Comment by laurenwigmore** [comment]
In these 2 weeks we continued on with promoting CC101, hosted 1 community call, redesigned the Oct Values initiative, interviewed for the PT comms role and defined the OKRs for Q4 - leading us to the a new work stream: creation of new beacons. Alexia joined the team, and we supported with some onboarding aspects. Lauren met with Slyvie to start preparing for the Creative Practices course. Moving forward all issues we are working on will be listed on the Kanban, and the iteration issues used for availability, goals and meeting notes.
