### ISSUE TITLE
CC101 Blog Post & Promo - Unlock the Secrets of Thriving Together: 10 Common Mistakes to Avoid in Conscious Coliving

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#825]
## Acceptance
- [x] Blog post is live
- [ ] All social media promo is completed

## Tasks
- [x] Blog Post Published with engaging image
- [ ] Repositioned for LinkedIn post
- [ ] Write Twitter thread use [Ship30for30](https://www.ship30for30.com/post/how-to-write-a-twitter-thread) for guidance of how to write a good thread
- [x] Post on IG

**Comment by laurenwigmore** [comment]
FIXED - minimal social media promo done for this blog post due to shortage of time.
