### ISSUE TITLE
[epic] Core Beacons for 2024

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#826]
Following on from discussions related to #814 - the next action is to create the follow-up CC101 type courses and learn pages #566, to act as other core beacons to attract and engage Life Itself members. 

3 core topics were decided as being central to Life Itself:

- Conscious Coliving
- Second Renaissance
- Cultivating Being

### Core Beacons Ideas for 2024

- [ ] Development of Learn Pages #568 **🚧2025-11-09 this is in progress and some of this happened. Right now we are going to close this issue here and focus on this. one**
- [x] Second Renaissance #842 (new issue - no previous notes)
- [x] CC101 Masterclasses #720  **✅2024-07-03 ❌ wontfix as won't ship in 2024**
- [x] Conscious Parenting #1100 - Why: conscious parenting is one very concrete, very powerful area of application of "wiser" principles to day to day life. **✅2024-07-03 ❌ wontfix as won't ship in 2024**
- [x] Ken Wilber 101 #123 **✅2024-07-03 ❌ kind of wontfix. We also do have a wiki page for this now on second renaissance based on what we wrote before here https://wiki.secondrenaissance.net/wiki/Integral**
- [x] https://github.com/life-itself/community/issues/1101 **💬2023-11-?? Initial meeting is the only action taken on this so far. No decisions or brainstorming done.** **✅2024-07-03 ❌ WONTFIX for 2024 atm.**
- [x] Social Permaculture (Nathen to advise if has capacity for this) **✅2024-07-03 ❌ WONTFIX. Not sure even what this is and Nathen in Australia atm doing other things.**
- [x] Metacrisis **❌2024-07-03 WONTFIX. have a v basic page here https://lifeitself.org/metacrisis. Feel this is probably merged to 2R for now and won't have its own course or learn section**
- [x] https://github.com/life-itself/community/issues/1102 **✅2025-11-09 ❌ wontfix a long time ago**

Lauren and Nathen agreed Learn pages should be created for all of the above (except the toolkit) following on the below diagram.

Items to consider for each:

- Planning
- Purpose and Principles
- Outcome visioning
- Who is it for?

### Tasks
- [x] Outline the idea of beacons, stages and have a short SOP (at least for first parts e.g. learn, email course) **✅2024-07-03 https://notes.lifeitself.org/beacons**
- [ ] 6 (new/improved) learn pages live **💬2024-07-03 not really worked on this so far. Question if we want to atm ...**
- [x] 1 new email course **✅2024-07-03 would count 2R as this for now ...**
- [x] 1 MC by end of 2023 **✅2024-07-03 ❌ did not happen**

**Comment by nathenf** [comment]
A beacon about Ken Wilbur would be useful - see also #109 and #123 @laurenwigmore and @rufuspollock

**Comment by laurenwigmore** [comment]
I've updated this epic to reflect the discussions around all potential Beacons for this Q4 period, and I've created or linked related issues accordingly.

**Comment by laurenwigmore** [comment]
@rufuspollock I wasn't sure whether to close this or move to someday maybe, as some useful work and insight here (and maybe in the studio model) but not relevant now as tasks we will action

**Comment by rufuspollock** [comment]
@laurenwigmore are you asking for my input or informing me of your uncertainty 😉

I hear you think there is some material that we should somehow capture or digest. What parts most stand out to you? 

Perhaps one approach *could* be worth transferring this to the forum and adding a link to a "Map of Content" with a brief summary of what is there and why it could be relevant?

**Comment by rufuspollock** [comment]
Did a massive update and refactor

- all the misc notes and content went to respective referenced issues or to https://notes.lifeitself.org/beacons
- tidied up list of beacon ideas
- updated acceptance
- updated status and phase

Now paused as we need to decide whether we do more learn pages. This is definitely one to look at again soon and "good first issue" ...

**Comment by rufuspollock** [comment]
FIXED (and OBSOLETE). This was from Dec 2023 for 2024 and now 2025. Most of the list of items is done or wontfix. Major continuing item is learn pages #568
