### ISSUE TITLE
Life Itself Style Guide

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#837]
When I join Life Itself I want to go to an up-to-date document where I can find all of the information related to branding and styling that will support my work output for Communications related tasks. 

## Acceptance
- [ ] Style guide revised

## Tasks
- [ ] Check if this [style guide is still relevant](https://docs.google.com/document/d/1olxrOgiHu0qG6OmDYrmzlB2BB9F0gqmz0j5auHc5gjM/edit#heading=h.fl3r032n3cj7)
- [ ] update with new information
 - [ ] fonts seem to be the only ? I have
- [ ] Share with Alexia

**Comment by nathenf** [comment]
@laurenwigmore currently we do not have a consistent style guide. This was something that was supposed to come out of the work with Oliver but we didn't reach that point and instead focused on making posters. Perhaps this is something you could work with @shiweiart on as she has the creative direction for this.
