### ISSUE TITLE
Core Beacon: The Second Renaissance Email Course

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#842]
Following on from #826 

The Second Renaissance Email Course will be the next core beacon from #814 

[Coggle draft](https://coggle.it/diagram/ZSRZZ8JZbsTt7K94/t/second-renaissance-core-beacon)
[Google Document draft version](https://docs.google.com/document/d/1nKh5U6abfqsEIj8NmlnkpAUTpFYGW1iK0Yjc5ViEzwA/edit)

## Acceptance

- [x] Course content decided and mapped out in a coggle **🚧2023-11-25  course outline posted here https://github.com/orgs/life-itself/discussions/922**
- [ ] Course launched in Q4 of 2023
  - [ ] Brevo
  - [ ] Landing page
  - [ ] Blog
- [ ] Launch Strategy Created and Implemented
- [ ] Key outcome/success metrics decided

## Tasks

- [x] Arrange first planning session with NF, LW, RP, SB (10th Oct)
- [x] Draft skeleton in coggle
- [ ] Draft content
  - [ ] Review/amend - final version signed off
- [ ] Mapped into system and formatted
  - [ ] Checks completed
- [ ] Sign up page set up  
- [ ] Launch strategy mapped out
- [ ] Marketed

### From first draft and review session 2023-10-11 and following week

- [x] [Lauren] digest this material ✅
- [ ] [Lauren]: ?? extract useful parts of today’s call transcript 2023-10-09 for use e.g. part about crack in the wall.
- [ ] [Question]: should we start drafting episode 1-4 which are pretty solid and try those out with people
- [ ] [Rufus]: draft the rest of the episodes
- [ ] Lauren's thoughts: 
  - [ ] a list of key reference articles, books, thinkers etc would be useful for me.
  - [ ] Important to reference the role of creativity / expression / embodiment / mythology somehow in this to balance the intellectual aspects (not that they are separate but energetically if we want to create shifts or openings to allow for shifts, then that we need to access something that hits at a deeper level than the mind)
  - [ ] At the end of this course we could introduce the pledge idea we spoke about? I.e. something people print out and connect with daily - personalize in someway.
  - [ ] The role of intention, and the observer needs to be referenced somewhere 
  - [ ] To consider what the throughline of this is - i.e. the apple tree story worked great in diginomics, we had Sam in CC101 . . . do we somehow use the pizza/pizza restaurant analogy . . . 
  - [ ] Ideas that popped up for me: Eastern Body Western Mind - collective trauma. Caroline Myss - shifts from tribalism to individualism. Zach Bush -  cancer cells insight in relation to individual and society. 
  - [ ] Link to external videos to explain histories or key ideas deeper
  - [ ] Need to define exactly who it is for 

## Who is it for?

**Comment by laurenwigmore** [comment]
@rufuspollock I've digested and added a few comments to the document. Shall I crack on with starting to draft episodes 1 & 2? or do you want to have another meeting beforehand?

**Comment by rufuspollock** [comment]
> @rufuspollock I've digested and added a few comments to the document. Shall I crack on with starting to draft episodes 1 & 2? or do you want to have another meeting beforehand?

Crack on I think. You also have material from recording. 👏

**Comment by nathenf** [comment]
@rufuspollock @laurenwigmore I have moved this to the next Milestone

**Comment by rufuspollock** [comment]
@laurenwigmore to quickly review her notes and put that into the draft doc and then we can move this to backlog for now ...

**Comment by laurenwigmore** [comment]
> @laurenwigmore to quickly review her notes and put that into the draft doc and then we can move this to backlog for now ...

All done, notes and draft added to doc. Moving to Backlog.

**Comment by rufuspollock** [comment]
Posted outline on forum: https://github.com/orgs/life-itself/discussions/922

**Comment by rufuspollock** [comment]
FIXED / DUPLICATE / OBSOLETE. this turned into the online course which in turn generated https://secondrenaissance.net/paper etc.
