### ISSUE TITLE
CC101 Blog Post & Promo - Unlocking the Secrets of Conscious Coliving: 10 FAQs Answered!

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#845]
## Acceptance
- [x] Blog post is live
- [x] All social media promo is completed

## Tasks
- [x] Blog Post Published with engaging image
- [x] Repositioned for LinkedIn post
- [x] Write Twitter thread use [Ship30for30](https://www.ship30for30.com/post/how-to-write-a-twitter-thread) for guidance of how to write a good thread
- [x] Post on IG

**Comment by laurenwigmore** [comment]
@alexianetcu can you populate this issue using the previous blog post and then action accordingly, once I've reviewed the socials please?

**Comment by alexianetcu** [comment]
FIXED **2023-10-06 done all the above after troubleshooting obsidian image issue**
