### ISSUE TITLE
CC101 Blog Post & Promo - 10 FAQs

### ISSUE THREAD

**Issue by alexianetcu** [life-itself/community#846]
## Acceptance
- [ ] Blog post is live
- [ ] All social media promo is completed

## Tasks
- [ ] Blog Post Published with engaging image
- [ ] Repositioned for LinkedIn post
- [ ] Write Twitter thread use [Ship30for30](https://www.ship30for30.com/post/how-to-write-a-twitter-thread) for guidance of how to write a good thread
- [ ] Post on IG
