### ISSUE TITLE
CC101 Review (book, documentary etc)- 10 great documentaries exploring conscious coliving, intentional communities and ecovillages (and where to watch them)

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#854]
## Acceptance
- [x] Blog post is live ✅ https://lifeitself.org/blog/documentaries-about-conscious-coliving-intentional-communities-ecovillages 
- [x] All social media promo is completed

## Tasks
- [x] Blog Post rewritten
- [x] Blog Post Published with engaging image 
- [x] Repositioned for LinkedIn post
- [x] Write Twitter thread use [Ship30for30](https://www.ship30for30.com/post/how-to-write-a-twitter-thread) for guidance of how to write a good thread 
- [x] Post on IG

**Comment by laurenwigmore** [comment]
@nathenf do you have capacity to work on the rewriting of this and then Alexia can do the socials once published?

**Comment by nathenf** [comment]
@alexianetcu the article is now live https://lifeitself.org/blog/documentaries-about-conscious-coliving-intentional-communities-ecovillages

**Comment by nathenf** [comment]
FIXED - Article is live and shared across socials. Also repositioned in Facebook groups and Subreddit.
