### ISSUE TITLE
Collective Well-being white paper link is broken

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#855]
## Acceptance
- [ ] Link is fixed - webpage loads

## Task
- [ ] Find correct link
- [ ] Find where broken link is
- [ ] Amend on obsidian
- [ ] Publish

**Comment by rufuspollock** [comment]
@laurenwigmore my suggestion for these minorish items i would say is that we perhaps gather them in an inbox issue (e.g. website one) and we only split them out to an issue when merited i.e. we are going to work on them or some further analysis is needed. This reduces noise in the issue tracker. wdyt?

**Comment by nathenf** [comment]
@laurenwigmore I know I asked you to make this issue, but I can't remember now where we even learned about this or what the complaint was or how we would track down the broken link. 

Action here: 
1. add to #358 and close this as MERGED
2. include some more details of the original message so it makes sense

**Comment by laurenwigmore** [comment]
> @laurenwigmore I know I asked you to make this issue, but I can't remember now where we even learned about this or what the complaint was or how we would track down the broken link.
> 
> Action here:
> 
> 1. add to [[inbox] Website fixes & updates #454](https://github.com/life-itself/community/issues/454)  and close this as MERGED
> 2. include some more details of the original message so it makes sense

Original message is very vague just that the collective white paper link is broken as the subject and: "I keep referring to the idea of sustainable well-being these days. That's the reason why I found out the link was broken."
Rufus has followed up to ask for more details regarding which link exactly and which page the link is on but there hasn't been a response.
