### ISSUE TITLE
Create a launch strategy guide/template for beacons

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#864]
When I have created a new beacon I want a clear strategy of how to launch it, so that the launch is efficient and impactful. 

Guide google doc: https://docs.google.com/document/d/1scGq_VXZIxn9m8uILn82-HiSsbG9Y3tsKWjQa3cnLC0/edit

## Acceptance

- [ ] Full guide/template written 🚧 https://docs.google.com/document/d/1scGq_VXZIxn9m8uILn82-HiSsbG9Y3tsKWjQa3cnLC0/edit 

## Tasks

- [ ] Brainstorm the different scales of launch depending on the size of the beacon
- [ ] Reflect on the launch of CC101 and what we should change
- [ ] Write up the guide/template

Follow up from #636

**Comment by nathenf** [comment]
@laurenwigmore this is the new issue

**Comment by laurenwigmore** [comment]
FIXED. Initial draft on googledoc (link to document under Acceptance).
