### ISSUE TITLE
Community Call: Victoria Dobbs on Creating Communities for Creators

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#867]
Victoria Dobbs |09/11/2023 | Community Practice/Living | Title: Creating Communities for Creators

## Acceptance

- [x] Community call hosted and recorded 
- [ ] Uploaded to Youtube and blog post 

## Tasks

Pre-event

- [x] Confirm speaker
- [x] Confirm details with google form https://forms.gle/gfZfKEATSmusp5AW7
- [x]  Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [x]  Create Canva graphic using template 
- [x]  Create registration using Zoom
- [x]  Create the blog post ✅  www.lifeitself.org/blog/creating-communities-for-creators-with-victoria-dobbs
  - [x] Include image, registration link, biography of speaker or description of the event
- [ ] Promotion
  - [ ] Emails
    - [x] Initial announcement (main group) on if newsletter was more than a week ago ✔️ via newsletter
    - [ ] Day before announcement (main group) only if initial announcement was more than a week ago
    - [ ] Email reminder (recipients)
    - [ ] Plus in newsletter (if applicable)
  - [ ] Whatsapp
    - [x] Initial announcement
    - [x] 3 days before
    - [ ] Day before
    - [x] 1-2 hours 
  - [ ] Twitter
    - [x] Thread for initial announcement
    - [x] 3 days
    - [ ] Day before
  - [ ] Instagram
    - [ ]  Stories
      - [x] Story template or resharing post
      - [x] Initial
      - [x] 3 days before
      - [ ] Day before
  - [x] Post for initial announcement 

### Post-event

- [x] Make the youtube video
- [x] Update original blog post with youtube video plus information 
- [x]  Title: Should include name of person, plus keywords/topic
- [ ] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [x] Copy of zoom recording [saved here in its own folder](https://drive.google.com/drive/folders/1cKyu2A4FjTKMk-5YOuqhFpu9Er6o2jy4)
- [x] Update CRM with links etc. 
- [x] Let the speaker know and make it easily shareable

**Comment by rufuspollock** [comment]
@nathenf i suggest that we still have registration links and we say that in the calendar invite e.g. 


> Register and Join the Zoom meeting: {link}

**Comment by laurenwigmore** [comment]
> @nathenf i suggest that we still have registration links and we say that in the calendar invite e.g.
> 
> > Register and Join the Zoom meeting: {link}

I've updated this call to include registration now and amended the description.

**Comment by laurenwigmore** [comment]
FIXED. Hosted and processed.
