### ISSUE TITLE
Polish and share Fundamental Wellbeing page aka Interview series with Jeffery Martin

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#870]
S:

- We recorded an excellent in-depth interview series with Jeffery Martin which is perhaps most extensive public intro to his work
- We think that Martin's approach to "waking up" aka Finders/Fundamental Wellbeing is one of best researched, most useful frameworks and approaches
- We have a page for this material at https://lifeitself.org/learn/fundamental-wellbeing with an intro, links to episodes etc

C

- Page is unpolished (intro is copied content from the wiki) e.g.
  - weird "wiki" links e.g. `(Martin credits the "non-symbolic" terminology to [abc/@cook-greuter](https://lifeitself.org/abc/@cook-greuter)).`
  - video episodes buried down the page
  - random (publication) date shown at top
- Page is a bit confused: is it an intro the concept or to his work and does not provides a powerful introduction to this key area nor does it simply showcases the interviews we have (e.g. imagine this was titled "Introduction to Jeffery Martin's work on Fundamental Wellbeing and Waking Up" - it would be easier to just have the interviews right up there)
- This makes page hard to share either to Jeffery (for him to share with his network) or more broadly
- We are not doing the work around the videos to actual create a mini course / background.

### Q: How do we create a useful and compelling page that we can direct people to including Martin himself who may then want to share it?

- What is the page actually about? Is it "An intro to Jeffery Martin's work on Fundamental Wellbeing" or about "Fundamental Wellbeing" (Ed: i.e. Rufus, i'd personally say let's focus on the former ...)
  - What material do we need on the page
  - what do we showcase?
  - etc
- How do get the page shared etc ...

### H: this is an intro to Martin's work on Fundamental Wellbeing

this page should be "An intro to Jeffery Martin's work on Fundamental Wellbeing" and should put interviews plus other key material front and center. This page should do a better job of showcasing this amazing work than he does himself 😄

In addition to the interviews we want to do a bit of work to provide and overview or map explaining what is going on.

Aside: A bonus is why we think this is important, or even a link from another page with our overall map of the different areas of development and what we recommend as intro reading (e.g. for waking up see martin, for cultural evolution see henrich etc)

## Acceptance

- [ ] Reworked page (or even pages) with 
- [ ] Emailed Jeffery sharing the page for his feedback and sharing
- [ ] Shared with community
- [ ] Shared on relevant reddits etc

## Tasks

- [ ] Sketch the out core offer of this page as a landing page ...
- [ ] ...

**Comment by nathenf** [comment]
@rufuspollock I've reworked the copy for this page, it's a draft at the moment but might be a good time for you to take a look to make sure I am coherently capturing it.

**Comment by laurenwigmore** [comment]
@nathenf I made a few minor tweaks but I like it as the starting point for Fundamental Wellbeing and agree with the earlier comments above the content about referecing it more - perhaps an option to link into the CC102 course depending on which topic we run with.

**Comment by rufuspollock** [comment]
@nathenf great to move this forward - and let not the best be the enemy of the good!

Can we make this a proper branch pull request and i can comment better there - i.e. edit the file in a branch and open a pull reuqest like normal and then i can make comments on the changes in the pull request diff which is much nicer.

Then we go from there 😄

**Comment by nathenf** [comment]
@rufuspollock https://github.com/life-itself/community/pull/889

**Comment by rufuspollock** [comment]
@nathenf can we get a really short blurb e.g. tweet suitable e.g.

> Can you do rigorous empirical, actionable research into enlightenment? Turns out you can. And Jeffery Martin has been doing if or the last 15y. We interviewed him for hours, read his work and distilled down the key insights here:
>
> 👉   https://lifeitself.org/learn/fundamental-wellbeing

Also here's a tweak of the blurb (shorter would still be better ... but i ran out of time)

>  Awakening or enlightenment is one of humans greatest endeavours, but many find it difficult to pursue. It's complicated by uncertainty what it even looks like and a bewildering range of techniques whose (in)effectiveness is largely anecdotal.
>
> Enter Dr. Jeffery Martin. Over fifteen years ago he dedicated himself to exploring the further reaches of human wellbeing in a rigorous, empirical way. Over the last 15 years he has interviewed hundreds of people who have claimed to reach enlightenment, developed the Martin Matrix of Persistent Non-Symbolic Experiences, and created a three month protocol that has enabled thousands of people to attain fundamental wellbeing with a claimed 65% success rate. His secular, pan-traditional term for enlightenment is fundamental wellbeing. This is our introduction to fundamental wellbeing and Dr. Jeffery Martins work: https://lifeitself.org/learn/fundamental-wellbeing

NB: prefer "awakening" to "enlightenment i think.

**Comment by nathenf** [comment]
@rufuspollock is Jeffery happy for us to share it or are we still waiting for confirmation?

**Comment by rufuspollock** [comment]
@nathenf i too his response as a 👍 for the piece - and simply that he was going to share once on the road. if unclear why don't you just double check in the thread (i.e. something like "are you happy with page content? we wanted to check before we shared ..."

**Comment by rufuspollock** [comment]
FIXED. We shipped this. Split share into #901
