### ISSUE TITLE
Blog Page Website Issues

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#871]
Three items are noted as not functioning correctly, or would be great to have on the new blog page (which looks and functions so much better, thank you!)

## Acceptance 
- [ ] Blog page issues/updates done

## Tasks
- [ ] The author listed on the Latest blog - is then listed on the other 2 blogs when this isn't always the case (in this screenshot I'm actually the author of Myka's call)
![image](https://github.com/life-itself/community/assets/132304704/873f26e7-8e21-43db-a6b3-6f27dd21a852)

- [ ] Text under view all blogs to be updated to: All of our pieces. 
![image](https://github.com/life-itself/community/assets/132304704/b32fe20e-7039-4a62-8d66-d518dea9531b)

- [ ] Image of the most recent published blog to be visible above the larger latest post title and text Some of our latest pieces. (great to have)
![image](https://github.com/life-itself/community/assets/132304704/dad18ef6-db83-47f5-902a-ce5da9024cb2)

**Comment by rufuspollock** [comment]
@laurenwigmore can you have some screenshots for these so we are really clear.

Also my sense is that these aren't super urgent or important and so likely to have these on the backburner for a bit as tech capacity is low atm.

**Comment by rufuspollock** [comment]
These all seem minor bugfixes or nice to have. Let's move all of this to the website inbox for now and then can delete / close this issue as duplicate.

**Comment by laurenwigmore** [comment]
Closed. MERGED with 454.
