### ISSUE TITLE
Revised Q4 OKRs & Conscious Coliving Focus

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#875]
We created a plan for Q4 2023 in #814. After discussion 1 month in, we want to revise and refocus it quite a bit. This issue is about doing that.

## Job Story

When XXX I want to know what the Q4 OKRs are, what we are working on currently in this period, and what the progress is on each workstream so that ...

- I want to be able to find this information easily and clearly. 
- What are our OKRs?
  - Where can i find them?
  - Who needs to find this or use this?
- What is our plan of work?
  - Where can i find that?
  - Who needs to find this or use this?
- What is our budget?
- What is our progress at a given point in time?

# Acceptance

- [x] New Q4 Objectives and OKRs are concretely defined and documented in the Tao **✅2023-10-25 see https://github.com/life-itself/community/blob/main/content/tao/plan-2023.md and https://lifeitself.org/tao/plan-2023**
- [x] A plan of work for Q4 is created and documented in a roadmap board plus milestone, with any notes being cleaned and redirected to this document (e.g. If we have meeting notes in this issue, condense and articulate all this in the milestone document, cross out and link to the document)  **✅2023-10-25 see #880**
- [x] We are clear on how we will document, track progress and report on Q4 OKRs **✅2023-10-25 we will have a special issue for the Q4 Comms work and track in there for now.**
  - [x] OKR tracking in [LI Analytics Spreadsheet](https://docs.google.com/spreadsheets/d/1PLycC_qPr156OmGt35FpDsEwrxVZ5XIRrjdYOSaRToA/edit#gid=1004730985) **✅2023-10-25 ❌ we won't use this for now. But will use this for metrics ...**

Process point

- Screenshot taken of the board before and after each iteration to track progress and a report included with progress on OKRs

# Tasks

- [x] Create New issue for Revising Q4 2023 OKRs and focus on Conscious Coliving - https://github.com/life-itself/community/issues/875
- [x] Move relevant content below over - moved and rejigged to make sense based on pulling out summaries below
- [x] Pull out a summary of following **✅2023-10-25 in the notes below**
  - [x] OKRs for workstream
  - [x] OKRs for Q4 2023
  - [x] Strategy background 
- [ ] Brainstorm plan of work - **✅2023-10-25 see #880**
  - [x] Move current Q4 stuff into a new milestone e.g. "Milestone 2024"  **✅2023-10-25 Milestone created and text from current milstone copied over. https://github.com/life-itself/community/milestone/5** 
- [ ] https://github.com/life-itself/community/issues/814 - extract and document, then close 

Extras

- [ ] Remove recent OKRs blog post as no longer relevant
- [x] Decide how we want to document, track progress, etc on OKRs  ** ✅see in acceptance**

**Comment by rufuspollock** [comment]
FIXEd. All done.
