### ISSUE TITLE
Review Rufus recording from John Oliver and annotate (and then publish?)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#883]
Follows from #790. This is just about prepping and publishing Rufus' interview.

## Tasks

- [x] Look at Rufus and evaluate for quality/interest of content **2023-10-30 a lot of good content in it**
- [x] Create spreadsheet (or use descript comments) with start/end of relevant sections and comments plus recommendations for any clips **here is the [spreadsheet](https://docs.google.com/spreadsheets/d/1LiU0JLjOl1BGr_EUUi5Uda1khtqM80YxzD-RjlTjKd4/edit#gid=1887846893) with topic and times (which are also below**
- [x] Pick the top clips
- [x] turn them into at least one reel 
- [x] post it with engaging captions on Instagram, Twitter, Youtube and in WhatsApp groups **see [this sheet](https://docs.google.com/spreadsheets/d/1LiU0JLjOl1BGr_EUUi5Uda1khtqM80YxzD-RjlTjKd4/edit#gid=736105910) for stats and links**

## Updates 
2023-10-31 Using Descript, have added AI-generated markers on general topics of whole first video, and added specific comments to first 30 minutes; 
2023-11-15 have finished indexing first video; 
2023-11-16 both Rufus videos indexed and, see comments for suggested clips on Descript :https://web.descript.com/2fa9cce0-9181-43ba-b4c3-806e835dd773/323c1 and https://web.descript.com/379e8100-f5db-42b6-8836-f8115bf24988/323c1

you can view comments by clicking on the icon on top right of screen, see image:
<img width="1440" alt="Screen Shot 2023-11-21 at 12 44 10 PM" src="https://github.com/life-itself/community/assets/145260066/3f252ec0-4955-402d-bc6c-715f9f96f447">

## Remarkable clips 

Here are the top 15 clips from the 2 hour recording - most were selected to be around 1min30s in length in order to be shareable on social media. Bolded titles are those that seem most relevant to share, as intros to LI.
The descript links and clip titles & timestamps have also put in [this sheet](https://docs.google.com/spreadsheets/d/1LiU0JLjOl1BGr_EUUi5Uda1khtqM80YxzD-RjlTjKd4/edit#gid=1887846893), for easier access.

In [part 1](https://web.descript.com/2fa9cce0-9181-43ba-b4c3-806e835dd773/323c1):

- the role of understanding the mind in societal transformation (8:30-10:00)
- how parenting and education can help one transcend their original context and integrate it with new insight (13:01-14:19)
- on creating an inner development-oriented society and politics of being (16:53-18:17)
- how we need to come together to bring forth the second renaissance - caterpillar-butterfly metaphor (21:38-23:38)
- the suffering, imperfection and immense possibility of the moment we're in as a society (32:14-33:49)
- the dream: pragmatic utopia (38:14-39:54)
- making space for true leadership and healthy growth hierarchies (49:42-51:18)
- **what Life Itself is and does** (57:41-59:12)
- The Second Renaissance - spiritual and ecological aspects (59:45-1:02:03)
- The Second Renaissance - transcending rationality (1:02:06-1:03:29)
- **cleaning up root causes of society's problems - what Life Itself aims to do** (1:09:46-1:11:07) 

In [part 2](https://web.descript.com/379e8100-f5db-42b6-8836-f8115bf24988/323c1):
- the absence of political vision and inequality of our current system (10:09-11:46)
- cultivating being & development of culture as a conscious process in the Second Renaissance (24:28-25:44)
- reintegrating the spiritual in politics (26:44-28:19)
- on inclusion and preparing the interpersonal ground in order for transformational dialogue to happen (32:32-33:36)

**Comment by rufuspollock** [comment]
@alexianetcu how have you got on with this?

**Comment by alexianetcu** [comment]
Got halfway through the first video yesterday, aiming to finish it today.

**Comment by rufuspollock** [comment]
@alexianetcu what happened here? The aim was to complete last week - how did that go?

**Comment by alexianetcu** [comment]
@rufuspollock I just got around to finishing indexing and evaluating different segments of your first video this morning. I can get started on the second one within the next 24h if you think this is worthwhile. I definitely think there are many clips worth sharing on social media as introductions to LI or second renaissance etc. Let me know what you think about next steps in this process.

**Comment by rufuspollock** [comment]
@alexianetcu i can't see where your annotations are. Can you post a screenshot so i understand where to find them. Also can you make some kind of summary e.g. "10 clips that are particularly good" here is the list with rough subjects/titles for them and their length and link into the descript transcript and video for you ...

**Comment by alexianetcu** [comment]
@rufuspollock Hope the screenshot helps you find the comments. 
Unfortunately I cannot link a clip or its transcript directly from Descript, so you have to scroll to the comment that has the beginning timestamp written above in order to find the specific clip...
I am happy to create some social media content from some of the clips, so if you'd like that at some point, let me know which ones you'd prioritize.

**Comment by rufuspollock** [comment]
@alexianetcu if you can note the next steps we mentioned today in a comment and also add them to the task list above that would be great (and standard practice out of a call so we capture the info and don't forget it).

IIRC

- [ ] Pick the top 3 clips and turn them into social media clips and push them to IG, Facebook, Twitter and linkedin (? not so sure about linkedin but may as well i think ...)

**Comment by alexianetcu** [comment]
FIXED. Closing this as all indexing, publishing of first clip and stats gathering of Rufus' interview are done. For further reviews and clip creation, new issues will be opened.
