### ISSUE TITLE
November 2023 Newsletter

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#887]
## Acceptance
- [ ] Newsletter is sent 

## Tasks
- [ ] Write newsletter in Brevo
 - [ ] Info from Hub/Residencies received and included
 - [ ] Tenzo note published
- [ ] Test Newsletter
- [ ] Send Newsletter

## Notes
- [ ] Include sign up link to cc102

**Comment by laurenwigmore** [comment]
FIXED. Newsletter sent with all updates.
