### ISSUE TITLE
10 Eco Communities in Europe - Blog Post

### ISSUE THREAD

**Issue by moonimmisch** [life-itself/community#895]
## Acceptance
- [x] Blog post is live
- [x] All social media promo is completed

## Tasks
- [x] Blog Post Published with engaging image
- [x] Repositioned for LinkedIn post
- [x] Write Twitter thread use [Ship30for30](https://www.ship30for30.com/post/how-to-write-a-twitter-thread) for guidance of how to write a good thread
- [x] Post on IG
- [x] Linkedin 
- [x] Whatsapp

**Comment by moonimmisch** [comment]
Working document: https://docs.google.com/document/d/1OpW0jAwmMGJ8EM_-DPLsqhS2a0xI-ltH2fvk3YY5ilk/edit

**Comment by laurenwigmore** [comment]
@moonimmisch another task for Thursday would be to post part 2 of the socials and then close this issue, after updating the items.
Don't forget to tick things off as you go through so that we can see where things are at if you aren't around to update us 'in-person'.
