### ISSUE TITLE
CC201: Transforming Conflict in Conscious Coliving Email Course: Shipping

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#896]
Following on from #879 

This issue is for the shipping of the CC201: Transforming Conflict in Conscious Coliving course - 1 of 2 options selected as the follow up to the CC101 course.

- [Coggle diagram](https://coggle.it/diagram/ZUj97CcP9Medbsqw/t/cc201-transforming-in-conscious-coliving-title-tbc-v-01?utm_source=transaction&utm_medium=email&utm_campaign=retain)

# Acceptance
- [x] Coggle skeleton is fleshed out and signed off
- [x] [Full draft for the course completed by end of Nov](https://docs.google.com/document/d/1DwNsXspkdajMUvEpZnkFi0WExFXf4ZaugDHeXdUI8VM/edit)
- [x] Course in system and accessible online
 - [x] Brevo (takes approximately 30-45minutes per email as can use cc101 template already)
 - [x] Landing page for CC201 - https://lifeitself.org/transforming-conflict-in-conscious-coliving-course
- [x] Launch Strategy drawn up and issue created: #936
- [x] Launched

# Tasks
- [x] meeting to finalise skeleton and coggle
- [x] [v.01 drafted](https://docs.google.com/document/d/11e2q03l2ow97TAqh7SeltjpZ6U9qI_LuMyd0jer8hJQ/edit#heading=h.y1xoo0r1j4vq) & Sylvie asked to review in 1st instance
- [x] v.01 reviewed with comments/amendments
- [x] v.02 revised and redrafted and signed off
- [x] set up (pre-)registration sign up button
- [x] Add offer into website ✅ landing page created and intergrated into main CC landing page
- [x] Create image for landing page and course email headers - https://www.canva.com/design/DAF1Gc8DwWg/erz-Kie3nxEQ7Zv8Z2CzVg/edit @shiweiart @nathenf can you review please? 🚧 
 N.B. webpage doesn't allow/load image - will feature image on front page of YouTube video once done
- [x] Create promo video @moonimmisch _deadline 22nd - please update here once done_
  - [x] Write video script 🚧 Written just needs reviewing - [in this doc](https://docs.google.com/document/d/1IV16tHmFH-bSXChXuFj1Jc13MlSNqEz4kqa4x3Wuz0A/edit)
  - [x] [Record voiceover](https://drive.google.com/drive/folders/133CgSoydwWZlTagL6_mNfJGNhAsIsd1_) 
  - [x] Add voice over to overlay video 
  - [x] Publish on Youtube and add to the landing page 
- [ ] #964
- [ ] Market 
 - [x] Launch strategy decided
  - [x] Strategy added into it's own issue
 - [x] Launch date decided
 - [ ] Review idea of a conflict resolution masterclass as designed in day 6 - set up wait list

## Landing page

[Landing page text draft is now in this document](https://docs.google.com/document/d/1IV16tHmFH-bSXChXuFj1Jc13MlSNqEz4kqa4x3Wuz0A/edit)

**Comment by nathenf** [comment]
@laurenwigmore  started on this one as well, but probably worth you adding to this as you are more focussed on it.

**Comment by laurenwigmore** [comment]
> @laurenwigmore started on this one as well, but probably worth you adding to this as you are more focussed on it.

[Added the info for this in the same doc as well](https://docs.google.com/document/d/1IV16tHmFH-bSXChXuFj1Jc13MlSNqEz4kqa4x3Wuz0A/edit?usp=drive_link)

**Comment by laurenwigmore** [comment]
@nathenf @rufuspollock @shiweiart the [v.01 draft is available here for review and comment](https://docs.google.com/document/d/11e2q03l2ow97TAqh7SeltjpZ6U9qI_LuMyd0jer8hJQ/edit#heading=h.y1xoo0r1j4vq)

**Comment by rufuspollock** [comment]
@laurenwigmore awesome - could we update the issue descriptoin tasks (that's where i first look).

So we are clear on reviewing here could i suggest @shiweiart review in first place. @laurenwigmore i think you may need to ping her on whatsapp for this.

**Comment by laurenwigmore** [comment]
FIXED. Launched w/c 4th Dec 2023.
