### ISSUE TITLE
[epic] CC201: Conscious Coliving in Action: Practical Steps to Getting Started with Conscious Coliving

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#898]
Following on from #879 

- [Coggle diagram](https://coggle.it/diagram/ZVFjCScP9MedwVxb/t/practical-action)

## Acceptance

- [ ] Live and people are receiving it

```[tasklist]
### Subitems
- [x] Coggle skeleton is fleshed out and signed off
- [x] Full draft for the course completed by Mid of Dec [working on draft here](https://docs.google.com/document/d/1iU4RPF3t-Cmo90qJw18YGQmMRut8qQJ0nWL2YleqvZo/edit?usp=sharing)  **✅2024-01-16 and shared with @shiweiart for review**
- [x] Landing page for CC201 - https://lifeitself.org/practical-conscious-coliving-course
- [ ] #1065 
- [ ] BONUS: marketing
```

### Draft

- [x] meeting to finalise skeleton and coggle
- [x] v.01 drafted
- [x] v.01 reviewed with comments/amendments
- [x] ⏭️ [v.02 revised and redrafted](https://docs.google.com/document/d/1vKEWsy8pwVjHefLaSAYJt6ZsU5UtxxdfjVzSWma8eEU/edit?usp=sharing) **🚧2024-02-02  days 0-5 done, days 6&7 to re-structure and add to_  ⏲️2h** ✅ _2024-02-02 completed_
- [x] Shout out on CC whatsapp group for volunteers to do a read through
- [x] Volunteers sent the link

### Publish

- [x] set up (pre-)registration sign up button
- [x] Add offer into website
- [ ] ⏭️⏭️ Get into Brevo ⏲️6h
- [ ] Update system with live course

### Marketing

- [ ] Create Promo video
  - [ ] Write script 🚧 90% just needs reviewing - [in this doc](https://docs.google.com/document/d/1IV16tHmFH-bSXChXuFj1Jc13MlSNqEz4kqa4x3Wuz0A/edit)
  - [ ] Record voiceover and overlay clips
  - [ ] Publish on Youtube
  - [ ] Add into landing page
- [ ] Update cc101 to include a what's next - join cc201

## Landing page text

[Text for the landing page is drafted here](https://docs.google.com/document/d/1IV16tHmFH-bSXChXuFj1Jc13MlSNqEz4kqa4x3Wuz0A/edit)
 
## Feedback from the CC community volunteers review
I’ve just read it and thoroughly enjoyed it.  It’s well written and comprehensive.  I cannot fault it at all :-)

You put a great emphasis on ensuring that the article is well balanced - the importance of not considering co-living for the wrong reasons and in the wrong state of mind.   

One thing that I noticed is that you didn’t use word “adventure” to describe the initial impetus to consider co-living.  I’d personally be very excited about the unpredictability of what will happen in the community and all the potential of beautiful things arising from the interaction and the connectedness.  Emergence of creativity and new perceptions feeding into personal growth.  Maybe that’s the “rose tinted view”… 

Later in the article you wrote this: “If it is too easy to leave, it can create a real or implied disruption to its members which results in a fragile foundation. "   -  I read it just as I was thinking - what’s there to lose; you try and if it doesn’t work - you can always change your mind.  That made me realise what you were saying is correct.

**Comment by nathenf** [comment]
@laurenwigmore I've written the landing page copy for the course here, including a video script. Want to check it and make any corrections/improvements. I think we should aim to get both landing pages out by next week.

**Comment by laurenwigmore** [comment]
> @laurenwigmore I've written the landing page copy for the course here, including a video script. Want to check it and make any corrections/improvements. I think we should aim to get both landing pages out by next week.

[I've put this into a document and added a few suggestions](https://docs.google.com/document/d/1IV16tHmFH-bSXChXuFj1Jc13MlSNqEz4kqa4x3Wuz0A/edit)

**Comment by nathenf** [comment]
@laurenwigmore I've got to day 5 of writing the draft. I don't think I have extra time to complete the rest, but I'll set aside some time next week so we can have a handover call.

**Comment by laurenwigmore** [comment]
> @laurenwigmore I've got to day 5 of writing the draft. I don't think I have extra time to complete the rest, but I'll set aside some time next week so we can have a handover call.

That's great, thanks Nathen! I'll assign this to myself now. and we're in touch re the call.

**Comment by laurenwigmore** [comment]
FIXED. Course live. More promotion needed in future.
