### ISSUE TITLE
What is Life Itself about / up to from June 2020 (post for historical purposes and for onboarding)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#899]
This recording was from an onboarding in June 2020. Two parts:

- About integrity and our culture
- About what we are about (from 55m on)

Idea would be to post the latter on youtube publicly (removing any part that includes the team - just Rufus' part)

Other point would be to link the entire video (in drive) as part of onboarding.

## Tasks

- [ ] ➕2020-06-18 Make Otterai transcript of 'What is Life Itself up to?' meeting and evaluate whether to tidy ⏲️2 **💬2023-11-13  section on what life itself is about is from minute 55 on (first part is about integrity)**
  - [x] upload video to drive done - video here drive.google.com/drive/folders/1ACL1ztVfLoe79Akjc0mCx4QRkiMVCX8O
  - [x] save otterai transcript to same location done - transcript here: docs.google.com/document/d/19ANLS1iYIU4NoecNAh0QQ8twH9EX-P7WDO1HWRwlKuk/edit

**Comment by rufuspollock** [comment]
FIXED. Won't post for now.
