### ISSUE TITLE
ordinary people republish

### ISSUE THREAD

**Issue by shiweiart** [life-itself/community#903]
Key documents:

[A10](https://docs.google.com/document/d/1bF2lP2u8RfAMdlHdmvgzEUssCXHRu26VL-noKbmjcGI/edit?usp=drive_web&ouid=117157573293978592624)

 # Acceptance

- [x] all the pages and information across youtube; on website and spotify are consistant with the new title Ordinary people and the new blurb and content in the A10

# tasks

- [x] Update blog post (why do we have blog post *and* podcast page? seems like we always have duplication?)
- [x] Update podcast page with info  with blurb and content [](https://lifeitself.org/ordinary-people)
- [x] Update podcasts themselves with info @rufuspollock can you clarify what you mean by this? Is it when we actually record new podcast? is it any images on the podcast? 
- [x] Re-record the jingle (or just read that in future)
- [x] change the page title to Jamie Bristow :[]( https://lifeitself.org/podcast/jamie-bristow-sylvie-barbier-mindfulness-inner-development)
-  [ ] update image and title on spotify

**Comment by shiweiart** [comment]
- [ ] Update blog post (why do we have blog post *and* podcast page? seems like we always have duplication?)
- [ ] Update podcast page with info  with blurb and content [](https://lifeitself.org/ordinary-people)
- [ ] Update podcasts themselves with info @rufuspollock can you clarify what you mean by this? Is it when we actually record new podcast? is it any images on the podcast? 
- [ ] Re-record the jingle (or just read that in future)
- [ ] change the page title to Jamie Bristow :[]( https://lifeitself.org/podcast/jamie-bristow-sylvie-barbier-mindfulness-inner-development)

**Comment by rufuspollock** [comment]
@shiweiart to flag this is a duplicate of the points i had in the epic #669

**Comment by shiweiart** [comment]
I've updated the blog post: https://lifeitself.org/blog/ordinary-people-new-podcast-series
