### ISSUE TITLE
Community Call: James Baker 22/11/23

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#904]
James Baker | 22/11/2023 | Community Living: How to Grow to Handle Anything

## Acceptance

- [x] Community call hosted and recorded 
- [x] Uploaded to Youtube and blog post 

## Tasks

Pre-event

- [x] Confirm speaker
- [x] Confirm details with google form https://forms.gle/gfZfKEATSmusp5AW7
- [x]  Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [x]  Create Canva graphic using template 
- [x]  Create registration using Zoom
- [x]  Create the blog post  
  - [x] Include image, registration link, biography of speaker or description of the event
- [ ] Promotion
  - [ ] Emails
    - [ ] Initial announcement (main group) on if newsletter was more than a week ago 
    - [ ] Day before announcement (main group) only if initial announcement was more than a week ago
    - [ ] Email reminder (recipients)
    - [ ] Plus in newsletter (if applicable)
  - [ ] Whatsapp
    - [x] Initial announcement
    - [ ] 3 days before
    - [x] Day before
    - [ ] 1-2 hours 
  - [ ] Twitter
    - [x] Thread for initial announcement
    - [ ] 3 days
    - [ ] Day before
  - [ ] Instagram
    - [ ]  Stories
      - [x] Story template or resharing post
      - [ ] Initial
      - [ ] 3 days before
      - [x] Day before
  - [x] Post for initial announcement 
  - [x] Linkedin Event created 

### Post-event

- [x] Make the youtube video
- [x] Update original blog post with youtube video plus information 
- [x]  Title: Should include name of person, plus keywords/topic
- [x] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [x] Copy of zoom recording [saved here in its own folder](https://drive.google.com/drive/folders/1cKyu2A4FjTKMk-5YOuqhFpu9Er6o2jy4)
- [x] Update CRM with links etc. 
- [x] Let the speaker know and make it easily shareable

**Comment by laurenwigmore** [comment]
@moonimmisch can you look at doing the socials for instagram, twitter and setting up an event on linkedin please your next day in this week (likely Friday)

**Comment by moonimmisch** [comment]
> @moonimmisch can you look at doing the socials for instagram, twitter and setting up an event on linkedin please your next day in this week (likely Friday)

Thats all done now :D

**Comment by laurenwigmore** [comment]
@moonimmisch you can add the processing of the call (taking place on 22nd) as a task for Thursday 23rd Nov.
