### ISSUE TITLE
Community Call: Professor Luke Martell postponed

### ISSUE THREAD

**Issue by nathenf** [life-itself/community#905]
Professor Luke Martell | Postponed due to personal circumstances (originally 18/01/2024)| Building Utopia: Alternative Societies & Pluralist Socialism

**will reach out once circumstances change**

## Acceptance

- [ ] Community call hosted and recorded 
- [ ] Uploaded to Youtube and blog post 

## Tasks

Pre-event

- [x] Confirm speaker
- [ ] Confirm details with google form https://forms.gle/gfZfKEATSmusp5AW7
- [x]  Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [ ]  Create Canva graphic using template 
- [ ]  Create registration using Zoom
- [ ]  Create the blog post 
  - [ ] Include image, registration link, biography of speaker or description of the event
- [ ] Promotion
  - [ ] Emails
    - [ ] Initial announcement (main group) on if newsletter was more than a week ago 
    - [ ] Day before announcement (main group) only if initial announcement was more than a week ago
    - [ ] Email reminder (recipients)
    - [ ] Plus in newsletter (if applicable)
  - [ ] Whatsapp
    - [ ] Initial announcement
    - [ ] 3 days before
    - [ ] Day before
    - [ ] 1-2 hours 
  - [ ] Twitter
    - [ ] Thread for initial announcement
    - [ ] 3 days
    - [ ] Day before
  - [ ] Instagram
    - [ ]  Stories
      - [ ] Story template or resharing post
      - [ ] Initial
      - [ ] 3 days before
      - [ ] Day before
  - [ ] Post for initial announcement 

### Post-event

- [ ] Make the youtube video
- [ ] Update original blog post with youtube video plus information 
- [ ]  Title: Should include name of person, plus keywords/topic
- [ ] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [ ] Copy of zoom recording [saved here in its own folder](https://drive.google.com/drive/folders/1cKyu2A4FjTKMk-5YOuqhFpu9Er6o2jy4)
- [ ] Update CRM with links etc. 
- [ ] Let the speaker know and make it easily shareable

**Comment by rufuspollock** [comment]
WONTFIX / INVALID. Luke sends his apologies - he has retired now and not giving talks so much anymore.
