### ISSUE TITLE
Set up Page for 2024 Gathering

### ISSUE THREAD

**Issue by shiweiart** [life-itself/community#906]
Create landing page for the 2024 gathering! 🎉

## Acceptance

- [x] a webpage with all the key informations where people can apply **✅2024-07-02 https://lifeitself.org/blog/announcing-gathering-2024 launched last november**

## Tasks

- [x] write a blurb re what is the gathering: **✅2023-11-15 https://docs.google.com/document/d/13HZHYv5654I4rR785saXE187ncb89vVtH63taCZ4IZo/edit**
  - [x] someone reviews
- [ ] finalise on price: https://docs.google.com/spreadsheets/d/1B_FwocKTwEGZu-nw2ZA31iah2RDD8QkrR3hwOOGryz4/edit#gid=1842970437
- [x] create ti.to page
- [x] create an application form: https://docs.google.com/forms/d/1oGE-K81DEXtat22lMZ9UlKJyz-QGcN3oxGRXZH6OxjU/edit
- [x] publish page re the gathering in the residency section
- [x] create a term and condition page: https://docs.google.com/document/d/1FcNBtJ_OiW5Qyf0CgGl2yo3hxzECQ62e0TByam9FTAY/edit

## Notes

**Comment by rufuspollock** [comment]
FIXED.
