### ISSUE TITLE
Community Hangout Dec 2021

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#91]
Community hangout has happened and we've posted any updates / recordings if appropriate.

## Acceptance

* [x] Hangout setup
* [x] Hangout announced
* [x] All relevant people invited
* [x] Hangout has happened (on 12 Dec)
* [x] Any outputs are updated

## Tasks

* [x] Identify speaker **DONE. Esther Montmany**
* [x] Set up the hangout calendar invite
  * [x]  Zoom link
  * [x] Announce info
  * [x] Add Hangout invitees group
    * [x] Update group with latest subscribers plus those from last hangout who were specially added
  * [x] Add research group / salon call invitees
* [x] Add to hangouts page (or create blog post?)
  * [x] Add hangouts page to navbar
* [x] Outreach
  * [x] WhatsApp groups [Charley]
  * [x] Reach out to petro to see if she knows people who would like to come as esp relevant

**Comment by rufuspollock** [comment]
FIXED. This happened and posted here https://lifeitself.org/2021/11/30/community-hangout-december-2021/

**Comment by EilidhRoss1** [comment]
@rufuspollock there is a [recording](https://us02web.zoom.us/recording/detail?meeting_id=OV1Bi8s5TNq9HMogubSV4g%3D%3D). Will publish on youtube in January

**Comment by rufuspollock** [comment]
@EilidhRoss1 did this happen? And did we add it to the related blog post?

**Comment by EilidhRoss1** [comment]
@Rufus, yes it's published to [anchor](https://anchor.fm/life-itself/episodes/Esther-Montmany-on-Conscious-Parenting-and-Education-e1u947h) and [YouTube](https://youtu.be/FR_HnXUn_mc)(currently uplaoding on YT), it has it's [own page](https://lifeitself.org/podcast/esther-montmany-on-conscious-parenting-and-education) on the site and is in the [blog post](https://lifeitself.org/blog/2023/01/31/esther-montmany-on-conscious-parenting) with the other CP episodes.

**Comment by EilidhRoss1** [comment]
FIXED 
published to [anchor](https://anchor.fm/life-itself/episodes/Esther-Montmany-on-Conscious-Parenting-and-Education-e1u947h) and [YouTube](https://youtu.be/FR_HnXUn_mc)(currently uplaoding on YT), it has it's [own page](https://lifeitself.org/podcast/esther-montmany-on-conscious-parenting-and-education) on the site and is in the [blog post]
