### ISSUE TITLE
Ordinary People podcast: Publish Valerie

### ISSUE THREAD

**Issue by shiweiart** [life-itself/community#931]
## Acceptance

- [x] Episode live on Youtube
- [x] Episode live on Spotify
- [x] Podcast page on website done
- [ ] Announcement post live 

## Tasks

- [x] add video to clog
- [x] edit the video
- [x] add to Youtube
- [x] create canvas template
- [ ] create jingle
- [x] write short summary about this specific podcast and person
- [ ] upload on spotify and release
- [x] upload on youtube and release
- [x] Add to substack as a post and tagged as OP
- [ ] Episode page created and added to the website podcast page. 
- [x] Guest informed that the episode is out and has been sent the links.
- [x] The new episode has been announced on Twitter and other socials

**Comment by laurenwigmore** [comment]
@shiweiart what is the date you are planning to launch this episode?

**Comment by laurenwigmore** [comment]
FIXED.
