### ISSUE TITLE
Getting Stuff Done at Life Itself (revision Nov 2023)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#932]
Update our work planning and delivery process (iterations, OKR etc)

Requests for these things were also expressed:

- having a scrum leader (role could rotate)
- having the overall game clear (this is more per sprint) - a need for a scheduled individual teams/whole team sprint planning meeting.

These are to be discussed more at the core team meeting on Friday, Dec 1.

## Acceptance

- [x] Write a shaped proposal **✅2024-02-27 see https://github.com/life-itself/comms/blob/main/shaping/202404%20Revised%20getting%20stuff%20done%20and%20how%20we%20self-organise%20as%20a%20team.md**
- [x] Doc outlining step-by-step what our current work process will be- people can refer back to this to know how things work (e.g. new joiners). This would be updated "Getting stuff done" https://lifeitself.org/tao/getting-stuff-done 
  - [x] Best / recommended practices for how to budget for interrupts and trickling 
  - [x] What to do during under-runs
  - [x] How to deal with over-runs
- [x] Calendar invitations are in place (if required) **✅2024-02-29 ❌ will arrange in friday core meeting**
- [x] Doc where we capture experiences / learnings of the team with implementing this model, and can be used as basis for reviewing the process once we've had a go **✅2024-02-29 ❌ we can create this as we need it**

Misc

- [x] https://lifeitself.org/tao/working-with-us updated as appropriate **✅2024-02-29 in https://github.com/life-itself/community/commit/3d931d6c36f4794cac2f2b71cc5f99a92c88c6c4**
- [x] GSD linked from onboarding

## Tasks

- [x] Review https://lifeitself.org/tao/working-with-us and identify what we can remove and/or merge with GSD @elisapaka 
- [x] https://lifeitself.org/tao/getting-stuff-done - review and see if *anything* we want to keep @elisapaka 
- [x] Draft new Getting Stuff Done text
- [x] Put in a PR and have team quickly review **✅2024-02-29 ❌ did not do PR but here is the commit people can comment on https://github.com/life-itself/community/commit/3d931d6c36f4794cac2f2b71cc5f99a92c88c6c4**
- [x] Merge!

**Comment by rufuspollock** [comment]
Have completed a fully shaped proposal for this. About to start PR for revised GSD.

**Comment by elisapaka** [comment]
@rufuspollock I wasn't sure where to put our HackMD work from yesterday, so I moved it to my own Scratch for the time being and have made a small start on writing up the revised GSD page. https://hackmd.io/gL9eHMKnRtWNzejPqKQXOw

I'm also not sure where to move the meeting notes, so they are still in the Life Itself scratch.

**Comment by rufuspollock** [comment]
FIXED.
