### ISSUE TITLE
December 2023 Newsletter

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#935]
## Acceptance
 - [x] Newsletter is sent 2nd week of Jan - Thurs 11th
## Tasks
- [x] Write newsletter in Brevo
- [x] Info from Hub/Residencies received and included
- [x] Tenzo note published
- [x] Test Newsletter
- [x] Newsletter is scheduled

## Notes of items to include
- [x] The Gathering
- [x] Christmas wrap up
- [x] both cc201 courses
- [x] Jan community calls 🚧 only 1 #905 
- [ ] Masterclasses ❌ _not organised_
- [x] research item? 
-  [x] Where the wild things are workshop: https://lifeitself.org/where-the-wild-things-are

**Comment by laurenwigmore** [comment]
FIXED. Sent 11th Jan.
