### ISSUE TITLE
[epic] Conscious Parenting

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#94]
Create a conscious parenting course and/or resources online so that others may use them

Why: conscious parenting is one very concrete, very powerful area of application of "wiser" principles to day to day life.

How do we start?

- [ ] "Pilot" where we get some initial content (e.g. from interviews)
- [ ] Refine that material into an initial guide (e.g. pull out general principles, specific topics e.g. eating etc)
- [ ] Share

## Acceptance

- [ ] ➕2025-10-31 Do a shaping for this course

### Items

- [ ] #156 
- [ ] #1100
- [ ] Project page **✅2023-03-04 https://lifeitself.org/initiatives/conscious-parenting**

### Inbox

- [ ] Create people page for Esther on site using her bio and link her from project page

### Setup

* [ ] Introduction, definition, background on conscious parenting
  * [ ] Transcribe SCQH on conscious parenting (from Rufus notebook)

Admin

* [x] Create Conscious Parenting folder on drive
* [ ] Create A10

### Pilot

* [x] #156 
  * [x] Initial introductions to conscious parenting (recorded) **✅2022-09-26 initial recordings** 
  * [x] Process and publish Conscious Parenting interviews (structured) ~ 4.5h done 2022-08-24 and stored in zoom
  * [x] evaluate for use in our podcast series ✅ **podcasts are made and up**

Other potential material

* [ ] Esther recordings
  * [ ] Jan 2021 interviews at Bergerac Hub
    * [ ] Recording 1 (zoom) https://us02web.zoom.us/recording/detail?meeting_id=8pmKAAHDTC264Qrc7fkSzA%3D%3D
    * [ ] Recording 2 (22 Jan) https://us02web.zoom.us/recording/detail?meeting_id=8UqCMj21SY65sOrtc6gvUg%3D%3D
  * [ ] Collect existing Esther recordings on e.g. Rufus' phone
  * [ ] Evaluate which to transcribe / publish

### Misc content

* [x] Upload Esther conscious parenting community hangout recording (in zoom) to youtube https://lifeitself.us/2021/11/30/community-hangout-december-2021/ ✅ **see #315**
  * [x] and embed in the page for event
* [ ] 🔥 #tech list the related blog posts on the page

### Guide

- [ ] Review topics in the pilot recordings and make a list with a link to timestamps and/or embeds in the page e.g. "Eating", "Sleeping", "Conflicts" etc

## Notes

Topics to cover (potentially):

* [ ] What breakfast / food?
* [ ] How to start the day
* [ ] What if a child falls over
* [ ] What is the general approach re the nature of the child

First course

* [ ] Dates for course
* [ ] Write copy
* [ ] Agree pricing
* [ ] Course page
  * [ ] Info
  * [ ] Signup form
* [ ] Marketing

**Comment by rufuspollock** [comment]
Note: just refactored this quite a bit:

- added much more detail on acceptance. Specifically to clarify v1 goal is a "guide" of some kind.
- refactored tasks into sections and expanded

**Comment by nathenf** [comment]
@laurenwigmore let's link this into the beacons epic too

**Comment by rufuspollock** [comment]
@kanderson102 here is existing issue for conscious parenting course. Please can you move the shaping you did to a gdoc in the practicum folder in drive and list here against the shaping acceptance item with abrief note on its status e.g. how complete it is and what remains to be done.
