### ISSUE TITLE
Community Call: Isabela Granic 29/02/24

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#947]
Isabela Granic | 29/02/2024 | 630pm CET | Practicing Flexibility in Deliberately Developmental Spaces

## Acceptance

- [x] Community call hosted and recorded 
- [x] Uploaded to Youtube and blog post 

## Tasks

Pre-event

- [x] Confirm speaker
- [x] Confirm details with google form https://forms.gle/gfZfKEATSmusp5AW7
- [x]  Add to CRM [CRM + Network Database - Life Itself](https://docs.google.com/spreadsheets/d/1JDDIGIU9eluTRs0K5zvkNJKPyc4RWROK7q_ChJTxyT4/edit#gid=1440604079) 
- [x]  Create Canva graphic using template 
- [x]  Create registration using Zoom
- [x]  [Create the blog post](lifeitself.org/blog/practicing-flexibility-in-deliberately-developmental-spaces) 
  - [x] Include image, registration link, biography of speaker or description of the event
- [ ] Promotion
  - [ ] Emails
    - [ ] Initial announcement (main group) on if newsletter was more than a week ago 
    - [ ] Day before announcement (main group) only if initial announcement was more than a week ago
    - [ ] Email reminder (recipients)
    - [x] Plus in newsletter (if applicable)
  - [ ] Whatsapp
    - [x] Initial announcement
    - [ ] 3 days before
    - [x] Day before
    - [x] 1-2 hours 
  - [ ] Twitter
    - [x] Thread for initial announcement
    - [ ] 3 days
    - [ ] Day before
  - [ ] Instagram
    - [ ]  Stories
      - [ ] Story template or resharing post
      - [x] Initial
      - [ ] 3 days before
      - [ ] Day before
  - [x] Post for initial announcement 
  - [x] Linkedin Event created 

### Post-event

- [x] Make the youtube video
- [x] Update original blog post with youtube video plus information 
- [x]  Title: Should include name of person, plus keywords/topic
- [x] Announce recording on Whatsapp, Newsletter at end of month, Twitter and Instagram
- [x] Copy of zoom recording [saved here in its own folder](https://drive.google.com/drive/folders/1cKyu2A4FjTKMk-5YOuqhFpu9Er6o2jy4)
- [ ] Update CRM with links etc. 
- [x] Let the speaker know and make it easily shareable 

## Social Media Copy
Thursday February 29th 630pm CET is our next community call: Practicing Flexibility in Deliberately Developmental Spaces with Isabela Granic

Three years ago, Isabela, a tenured professor of developmental psychology resigned, confronted by the realization that their life's work in academia, aiming to improve young people's mental health and well-being, wasn't doing so. Frustrated by the disconnect between the "science of human flourishing" and its real-world application, Isabela joined forces with six co-founders. Together, over the past year, they translated research on youth mental health and combined it with practical philosophical practices from both Eastern and Western traditions. This synthesis birthed Liminal Learning, an immersive retreat-based program designed to propel young adults towards a purpose-driven life.

In our upcoming Community call, Isabela will be sharing the program's foundations, followed by engaging participants in two key social practices. These practices, successful in previous pilot gatherings, aim to build trust and help young adults explore the value tensions crucial to crafting personal meaning and collective purpose.

**Twitter**
📢Register now for our first Community Call of 2024!

Thurs 29th Feb 630pm CET 
[@PlayNiceInst](https://twitter.com/PlayNiceInst)
 will be joining us to share her journey from tenured professor of developmental psychology to co-creator of Liminal Learning.

Register here: [https://bit.ly/3OHBWkQ](https://t.co/bxrRVEXlGO)

Read more 👇

Tweet 2: Confronted by the realization that her life's work in academia, aiming to improve young people's mental health and well-being, wasn't doing so and by the frustration of the disconnect between the "science of human flourishing" & its real-world application . . .

Tweet 3: Isabela with six co-founders translated [#research](https://twitter.com/hashtag/research?src=hashtag_click) on youth [#mentalhealth](https://twitter.com/hashtag/mentalhealth?src=hashtag_click) & combined it with practical philosophical practices from East & West to birth Liminal Learning; an immersive retreat-based program to propel [#youngadults](https://twitter.com/hashtag/youngadults?src=hashtag_click) towards a [#purpose](https://twitter.com/hashtag/purpose?src=hashtag_click)-driven life.

**Comment by laurenwigmore** [comment]
FIXED.

**Comment by laurenwigmore** [comment]
FIXED.
