### ISSUE TITLE
Sympoiesis no 3 (Jan 2022) - Launch and share

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#95]
[Aside: Originally opened on 26 Oct ... - in another repo]

## Acceptance

* [x] Page on website for the event that we can link to
* [x] 20 people pinged
* [x] 8 people booked

## Tasks

* [x] Finalize draft of outline and put on website
  * [x] Finalize pricing
* [x] Send round to people from Emerge
* [x] Message relevant groups re the Jan workshop and others
* [x] Announce sunday 7 Nov event with Karl

**Comment by rufuspollock** [comment]
FIXED. Residency happened and was great. See https://lifeitself.org/sympoiesis/3-cultivating-conscious-community-jan-2022/
