### ISSUE TITLE
Pragmatic Utopianism Ep 1 with Stephen Diehl

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#954]
Recorded an episode here https://zoom.us/recording/detail?meeting_id=yhYfM%2FrsS26%2F3xHGsM13HQ%3D%3D (Saved here on shared drive: https://drive.google.com/drive/folders/16c5ETWTWtbxaAlUr_kE3EeBgF5iTh8wf)

Info: A Dialog on Pragmatic Utopianism - political philosophy for the second renaissance.

Background reading: https://lifeitself.org/blog/2020/12/21/pragmatic-utopianism

Intention: get this material out so that we can share and see what folks think (every content counts!), so stephen can share too, so we have more material in the "ontological politics" "bucket"

Ship it fast, ship it raw!

## Acceptance

- [x] Put on youtube
- [x] Cut off the first 1-2m (? need to check but there's a point we properly start) ✅ _trimmed a little off both but no real point of starting_
- [ ] Framing/Blurb (if any?)
- [x] ~~Blog post?~~ Just post on forum with same blurb 
  - [x] Post the transcript in the body of the discussion post
  - [x] BONUS: image
- [x] Post video to our general chat
- [x] Post a discussion thread: https://github.com/orgs/life-itself/discussions/1006
- [x]  Put transcript in discussion of Prag Utopianism
 
Bonus things we *could do* (but shouldn't 😉)

- [ ] Split into two (it's nearly 2h long or more)

### Analysis

- [ ] write out steps for getting videos out
  - which eliminate
  - which automate

## Acceptance

- [x] Episode is live on YouTube
- [x] Episode is live on Spotify
- [ ] Episode is live on LI podcast page

## Task

- [x] Create and publish Youtube video
- [x] Create Canva image
- [x] Publish audio on Anchor/Spotify
- [ ]  Create RSS link for our page
- [ ] Draft blurb for episode for podcast page 
  - [x] Adapt blurb for YouTube and Spotify
  - [ ] Add bio of Stephen Diehl

### RSS link creation

- Create a page for the episode on the [podcast page](https://lifeitself.org/podcast) of the website. 
- You can prep this before the podcast and YouTube video are published, however you will not be able to add the podcast link until the podcast is live.
- Add a new page in the vault/podcast section in the community repo. Use [Jeffery Martin episode page](https://lifeitself.org/podcast/a-scientific-approach-to-awakening-and-fundamental-wellbeing-podcast) as a guide. 
- Generate the links for the frontmatter: - this can only be done once the podcast has been published on spotify
- Note this is for the podcast page to embed with our branding
- Follow this link: https://rss2json.com/
- Paste this link in the box on the page (under the text that says Enter the URL to your RSS feed): https://anchor.fm/s/79b39934/podcast/rss
-  Find the podcast episode you are wanting to create the page for from the box underneath the API call
- (this will likely be the first episode listed under the line that says "items", but check the title
- Click the button with 4 arrows pointing outwards to make it full screen to ensure you don't copy only part of a link.
- Copy the link for "thumbnail" and paste it after "image:" in the frontmatter.
- For the src link, scroll down to where it says "enclosure" and copy the link that follows "link". Paste this after "src" in the frontmatter.
-  Fill out the rest of the frontmatter

**Comment by rufuspollock** [comment]
@laurenwigmore we discussed this as something to get up asap and as a practice for testing how we can streamline our publishing ...

**Comment by laurenwigmore** [comment]
Notes:
Small few second edits done on YouTube video (minimal time)
Same edits not done on Spotify podcast because it involves extra steps 
SRC link and LIpage to be updated once link is available on RSS site (takes a number of hours to sync)

Extra: To add a bio of Stephen Diehl

Number of hours to this point: 2.5

**Comment by rufuspollock** [comment]
@laurenwigmore confirming that this is pretty much done (just need to share to general chat with link to youtube plus the discussion forum).

![image](https://github.com/life-itself/community/assets/180658/bc0b7d35-2a3b-4918-8060-f5b57e8b7243)

**Comment by rufuspollock** [comment]
Forum post: First Dialog Exploring Pragmatic Utopianism and Political Philosophy by Rufus Pollock and Stephen Diehl

**Comment by rufuspollock** [comment]
Stephen sent me some context from his PoV that we could add as a note:

> If you want a text to contextualize a discussion, Martin Wolf’s new book ‘Crisis of Democratic Capitalism’ is a compelling defense of incremental reform compared to utopianism. Very close to my worldview.

![image](https://github.com/life-itself/community/assets/180658/32ac1b1b-087b-4c68-9ca5-546a55d41df5)

**Comment by laurenwigmore** [comment]
FIXED. All tasks done as per the meeting on 2024-01-16, and updated above. New context comment from Stephen also included.
