### ISSUE TITLE
Update cc101 to include a what's next - join Conflict and Practical Action Course

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#964]
## Acceptance
- [ ] CC101 brevo course updated and live
- [ ] CC101 landing page updated with a next step (join Conflict course and/or Practical Action course)

## Tasks
- [ ] Review content in Brevo
- [ ] Update all Brevo content 
- [ ] Update the CC101 landing page with a short sentence and links

**Comment by laurenwigmore** [comment]
Paused, as not a main focus at present, and Practical Action is not live yet.
