### ISSUE TITLE
Create a private posted version of the Second Renaissance 101 course 

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#965]
## Acceptance
- [x] Course is live by 22nd Dec ✔️ _ready to be shared_
- [ ] All participants contacted

## Tasks
- [x] Download and [save all episodes, video, audio and chat on the shared drive](https://drive.google.com/drive/folders/1bDjNrLbkXTUhuS7hpsD2ESRdpQ2rAu1D?usp=drive_link) 
- [x] Create new videos and edit episodes breakout rooms and endings in the private invite access folder (episode 2, 6 - endings) @moonimmisch _please start from ep 1 and I'll start from ep 6_
- [x] Saved edited episodes into a new folder for a private invite only posted version of the [SR 101 course on Gdrive](https://drive.google.com/drive/folders/1wIknywtrr9cfOtyPh1TYVEvtxUvEvDzl?usp=drive_link)
- [x] Episodes added to a private playlist on YouTube (https://www.youtube.com/playlist?list=PLg0Untv2MuxVyWb3Le34aASeQoCGr85o8)
- [ ] Identify who to share it with (Rufus to inform)
- [ ] Add their emails to the Gdrive folder
- [ ] Contact and invite them once course is live

## Links you will need
- [ ] Email blurb invite - https://docs.google.com/document/d/1ueXvjAxkNq024ebBWWina2LxMAbKgDXQLik3LLbx-qY/edit?usp=sharing
  - Includes link to playlist and feedback form

**Comment by rufuspollock** [comment]
Rufus share list

- Hannes
- Conscious Politics person
- Ma

**Comment by moonimmisch** [comment]
@laurenwigmore do you know where I could find the emails of the people rufus commented above so I can add them to the Gdrive? If not I can check with Rufus :)

**Comment by laurenwigmore** [comment]
> @laurenwigmore do you know where I could find the emails of the people rufus commented above so I can add them to the Gdrive? If not I can check with Rufus :)

For the time being it's OK not to add them to YouTube - @rufuspollock will do this himself for these 3 but thanks for checking

**Comment by laurenwigmore** [comment]
FIXED. Sign up available on web page, blurb and videos all completed.
