### ISSUE TITLE
Initiatives (Projects) list for Life Itself (created and on website)

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#97]
When sharing Life Itself's work i want an up to date list of current and past "initatives" (project, programs, streams, ...) with some info online on these (or at least the most important or currrently active ones) so that i can share this with people (and they can share with others)

When coming across Life Itself I want to know what you've been up to and what areas you are currently working on so that I have a sense of your capabilities, interests, competence etc

- Current / active
- Best / biggest
- Thematic

## Job Stories

- When I come to Life Itself website I want to know how Life Itself is delivering on their talk, so that I can see they are a legitimate organization walking the walk.
  - What are we delivering on? 
    - Transforming the narrative
    - Pioneering community living
- When I come to Life Itself website I want to know what they are up to right now so that I can be updated on relevant initiatives and explore more deeply.
- When X I want to explore all of Life Itself initiatives throughout time so that I can really get to know what they do and have done.
- When I find an interesting initiative I want to briefly learn more about it and the action steps I can take to get involved or learn even more so that I have a clear direction of next discovery.
- I want to see future ideas for initiatives so that I can invest/lead/get involved with them from the beginning

## Acceptance

- [x] Choose naming: initiatives, proejcts, ... ? **✅2023-02-02 choose ~~projects~~ initiatives 2023-03-30**
- [x] List of current sources for this info and where it is displayed (if anywhere) **✅ Listed below**
- [x] A spreadsheet (or similar structured list) that lists all Life Itself initiatives past and present ✅ 
- [ ] Individual projects on site at `/projects/{id}` e.g. `/initiatives/conscious-parenting` or `/initiatives/web3-guide/`. these pages can be pretty minimal. should have title, description, image?, ... **🚧2023-03-23 have done first 21 of highest priority** **✅2023-04-06 all done (actually 2w ago) plus nice layouts now e.g. https://lifeitself.org/initiatives/conscious-parenting or https://lifeitself.org/initiatives/hubs/**
- [x] Projects index page listing the project (in simplest way possible for now!) **🚧2023-03-29 see #397 deploy preview https://deploy-preview-397--zesty-liger-3a5c29.netlify.app/projects** **✅2023-04-06 fixed in #416 - see https://lifeitself.org/initiatives**
  - [x] 🏆 programmatic organization and/or explanation of our projects (how they connect to strategy etc) **✅2023-04-06 partially have this. see https://lifeitself.org/initiatives**
- [x] Featured projects identified **✅2023-03-16 labs, hubs, ecosystem (web3), (collective wisdom)**

### Create list of initiatives

- [x] Identify where we currently list initiatives **✅2022-12-15**
- [x] Create sheet for initiatives **✅2022-11-12 https://docs.google.com/spreadsheets/d/13RVMrZ02Rw6a1BtftIUO4v7R7rXt5_phQLR4rHa343M/edit#gid=513369262**
- [x] Collect initiatives from sources **✅2022-12-15 @rufuspollock unless you have anymore?**
	- [x] https://lifeitself.org/initiatives/ **✅ Been through 2022-12-15**
	- [x] Projects / Programs DB **✅ Been through 2022-12-15**
	- [x] Website **✅ Been through 2022-12-15**
	- [x] https://lifeitself.org/institute/ **✅ Been through 2022-12-15** 
- [x] Select top initiatives **✅2023-03-16 see above**
- [x] Create framework for description **✅2022-12-15 see below**

### Individual Project Page Templates @khalilcodes

- [x] Brainstorm (see below)
- [x] Create projects template (page structure) **✅2023-03-16 we have a project template**
  - [x] metadata **✅2023-03-16**
  - [x] what, why ... **✅2023-03-16** 
- [ ] Design layout **💬2023-03-16 Could use https://spotlight.tailwindui.com/about as initial template to tweak** **🚧2023-03-30 https://link.excalidraw.com/l/9u8crB2ZmUo/6jK2GWGLpBg** @khalilcodes 
- [ ] Implement

### Individual Projects Pages

- [x] [Conscious Parenting](https://lifeitself.org/projects/conscious-parenting)  #308 and #156 ✅
- [x] [Ecosystem Mapping](https://lifeitself.org/projects/ecosystem-mapping) ✅
- [x] [Making sense of Web3 & Crypto](https://lifeitself.org/projects/exploring-web3-and-crypto) ✅
- [x] [Life Itself Podcast](https://lifeitself.org/projects/podcast) ✅ 
- [x] [Hubs](https://lifeitself.org/projects/hubs) ✅ 
- [x] [Hub Berlin](https://lifeitself.org/projects/hub-berlin) ✅ 
- [x] [Hub Bergerac](https://lifeitself.org/projects/hub-bergerac) ✅ 
- [x] [Hub Petit Bois Martin](https://lifeitself.org/projects/hub-petit-bois-martin) ✅ 
- [x] [Ontological Politics](https://lifeitself.org/projects/ontological-politics) ✅ 
- [x] [Columinate](https://lifeitself.org/projects/columinate) ✅  **Missing: key resources and homepage**
- [x] [Wisdom Colloquia ](https://lifeitself.org/projects/wisdom-colloquia) ✅  **Missing: metadata, Description, key resources**
- [x] [Collective Wisdom](https://lifeitself.org/projects/collective-wisdom)  ✅ 
- [x] [Tao of Life Itself ](https://lifeitself.org/projects/tao-of-life-itself) ✅ 
- [x] [Residencies](https://lifeitself.org/projects/residencies) ✅ 
- [x] [Embodying Collective Transformation](https://lifeitself.org/projects/embodying-collective-transformation) ✅ 
- [x] [Institute / Labs](https://lifeitself.org/projects/labs) ✅ 
- [x] [Contemplative Activism](https://lifeitself.org/projects/contemplative-activism) ✅ 
- [x] [Sustainable Wellbeing](https://lifeitself.org/projects/sustainable-wellbeing) ✅ 
- [x] [Possibility Now](https://lifeitself.org/projects/possibility-now) ✅ 
- [x] [ Blind Spots ](https://lifeitself.org/projects/blind-spots-series) ✅ 
- [x] [Collective Intelligence](https://lifeitself.org/projects/collective-intelligence) ✅
- [ ] [Untitled Collaboration ](https://lifeitself.org/untitled-collaboration) 🚧**page not linked to original source, Missing: all info** ❌ WONT FIX - Not really a project

### Projects Index Page @khalilcodes 

🚧 #384 

- [x] Wireframe with any key copy **🚧  2022-12-26 working on copy below** **💬2023-03-16 copy is optional for first pass which is just a nice list**
- [ ] Design (?) ⏭️ @khalilcodes **💬2023-03-30 see https://spotlight.tailwindui.com/projects**
- [ ] Implement (integrating the list) @khalilcodes 

### Page Structure

- Title
- Tagline
- Meta (start/end, team) 
- Description
- Key Resources (links to articles via categoric sorting process) nb. if none hide title

## How they fit into a narrative

- Shifting the Cultural Narrative
- Pioneering a Wiser, Weller World
- Rigorous Sensemaking 

### Brainstorm

- Suggestion: Let us use Past, Present, Future to categorize initiatives so that we can also list initiatives set to launch or needing funding to move forward. 
- Regarding broader categorisation of pages and blog posts we should commit to assigning initiative titles as categories to enable us to list key resources and updates on initiative pages

### Rufus reflections 2023-02-16

- Labs or Hubs and e.g. web3 seem to be at different levels e.g. one is an entire area
- what do people want to know?
  - the more tangible and specific something is the easier it is to grasp. e.g. "labs" is quite general and is just a place to "do stuff" whereas e.g. "a sensemaking guide to web3" is quite clear
- Distinguishing question:
  - Is it something people could "consume / use / buy / visit" or is it a "domain / space / cluster". Let's call the former "projects" and the latter "domains" for now.
- Another approach would be to simply answer the question: What you done? e.g. Over the last 7 years we have:
  - We have created physical hubs in X places
  - Z people have attended our transformational residencies and programs
  - Mounted Y art exhibitions / performances
  - Run Z events
  - X white papers and thought pieces

#### Attempt at a quick list

Domains

- [Apps] Deliberately Dev Spaces and programs
  - Berlin Hub
  - Bergerac Hub
  - Plum Village Hub
  - Transformational/Sympoiesis residencies
- Labs
  - Guides / Deep Dives / Explorations
    - web3
    - conscious parenting
    - ?? ontological politics
 
---

## Main Page Copy

How do we bring about the shifts in being, culture and systems necessary to transform our social paradigm, and steer humanity and the planet into a flourishing future?

Here at Life Itself, we engage in many different projects. Some are experiments, others stand alone works, and others are ongoing explorations. All are designed to create a wiser, weller world. Our projects fall under two broad themes:

### Pioneering Community Living

At the core of what we do is the thesis that community living is key to embodying true transformation of ourselves and society. 

Why is community living so important? Because we need to combine inner transformation and outer development. This is difficult, but living in a conscious community makes it easier. You have mutual support, accountability, responsibility, connection. 

This is why we dedicate ourselves to creating pathways and providing tools for people to live in intentional communities. 

Examples: Co-living Hubs, Transformational Community Residencies 

### Transforming the Narrative

We are undergoing one of the greatest paradigm shifts in history. At it’s foundations this shift requires a new way of being and new ways of doing.

Our work brings inner transformation out of the domain of the purely spiritual, and seeks to cement it as a pillar of social change that works for all. We use rigorous enquiry and sensemaking to better understand how we can make this paradigm shift a positive transformation for society.

To stay up to date with our current and future initiatives sign up to our newsletter.

[sign-up embed]

## Projects 

Sort by: Current / Past / Theme   **default to: Chronological order by end date, with ongoing first**

[grid of project images with title and date] => click through to individual project pages

**Comment by rufuspollock** [comment]
@nathenf did some work on the initiatives list - would say 70% of the way there. Also had some thoughts on structure here https://next.lifeitself.org/notebook/projects/digital-garden-2022#2022-11-12---thoughts-on-structure

**Comment by rufuspollock** [comment]
@nathenf @EilidhRoss1 can you take a look at this? I think this is a key part of the site migration (in terms of helping structure) and very valuable in itself. (@nathenf this was the issue i mentioned last monday)

**Comment by EilidhRoss1** [comment]
@nathenf lets chat about this in our comms meeting this week

**Comment by nathenf** [comment]
> @nathenf did some work on the initiatives list - would say 70% of the way there. Also had some thoughts on structure here https://next.lifeitself.org/notebook/projects/digital-garden-2022#2022-11-12---thoughts-on-structure

@rufuspollock this link returns a 404, can you find this content and relink?

**Comment by nathenf** [comment]
@rufuspollock have been working on this so far this morning and have updated the issue task by task.

**Comment by rufuspollock** [comment]
@nathenf i think we can unblock this. i've updated acceptance a little to reflect sequence. my sense is immediate step is just to get a couple of projects pages up. my suggestion would be:

- conscious parenting
- ecosystem mapping
- web3 guide

I would do a minimal amount for each one first i.e. boot the markdown page with some common metadata, add featured image (just screenshot site or similar) and a short description. i wouldn't even worry about styling the pages - let's just get them up and see what they look like (you could manually show the image for example as well as have in frontmatter).

Basic rule is KISS and do the minimum and then we'll iterate.

**Comment by rufuspollock** [comment]
@nathenf this isn't complete is it - there are several acceptance not done and tasks - specifically the index page 😄

**Comment by nathenf** [comment]
@rufuspollock not sure how that happened I don't remember closing this... Of course it is not done

**Comment by rufuspollock** [comment]
> @rufuspollock not sure how that happened I don't remember closing this... Of course it is not done

@nathenf no problem - i see what happened now - you merged a commit where you said something like "fixes #97" and that auto closes things ... No big deal at all! I just got confused when i saw notification and looked at the issue!

<img width="869" alt="image" src="https://user-images.githubusercontent.com/180658/227086948-aac9b779-ea87-4e2e-b63e-2fd28503094d.png">

**Comment by nathenf** [comment]
@rufuspollock all pages up to priority 4 are now created. Do you want us to continue down the list and do all?

**Comment by rufuspollock** [comment]
> @rufuspollock all pages up to priority 4 are now created. Do you want us to continue down the list and do all?

Not for now, let's look at what we have.

**Comment by rufuspollock** [comment]
FIXED. All done - final fixes to have nice initiatives pages - individual and index in #416

**Comment by nathenf** [comment]
@rufuspollock it looks great! One thing that would be good to add is either breadcrumbs or a return to main initiatives page. These pages become a dead end if they want to view other initiatives.
