### ISSUE TITLE
First Steps After the Second Renaissance Pilot Course to allow sharing and signup

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#976]
Done 6 episode pilot Second Renaissance course in Dec 2023. Want to do minimal update webpage to reflect maturing info: https://lifeitself.org/second-renaissance and allow preliminary signups

## Acceptance

- [x] Second Renaissance Page is updated **✅2024-01-16 updated 2 weeks ago and good enough to try**
**✅2024-01-08: Website updated with intro blurb, intro to 2R course and pilot sign up, 2R book sign up left now at bottom** (Also have internal issue https://github.com/life-itself/comms/issues/69 with blurb and video links to invite to do the course as course not yet public)
  - [x] remaining: remove book signup and duplicate signup to the hero section.
- [x] 2R Announcement live [document draft](https://docs.google.com/document/d/13EMXZaammAD4XUSq9M6FoA1ZFrA2ZVlrxd912D3O96I/edit?usp=drive_link) **✅2024-01-16 ❌ we don't need a big announcement and we have blurbs for sharing internally to friends or whatsapp in https://github.com/life-itself/comms/issues/69**

![Image](https://github.com/life-itself/community/assets/180658/ac7bbab4-60c5-4753-a42d-638746853e2e)

## Tasks

- [ ] Review website and reference to Sec.Ren across the platform **🚧2024-01-16 [Working document](https://docs.google.com/document/d/1Re4SJkmHDrjwgcCNW-j0yPdsbN1kAUX94uNHGcH5W8U/edit?usp=sharing)**
- [x] Identify next steps
- [x] Next steps for page
  - [x] Intro blurb
  - [x] Add a captivating image
  - [x] Option to request access to the course (or will it remain invite only?) - to clarify
  - [x] Move book sign up down **💬2024-01-16  remove it entirely for now.**

### Blog ideas

Aim: Write 6 blogs to be released weekly from mid Jan-end Feb on aspects from the 6 episodes of the course, with the new category ‘second-renaissance’.
Intention: To provide the foundational information to introduce the ideas and topics of the Second Renaissance to a new audience.
	Secondary intention: for a later set of blog posts that expand on key ideas for a well-versed audience

Suggested topics for the first six:

- [ ] 1/ What IS the second renaissance - overview of term / time period / historical background and significance (aim: orientation of the topic)
- [ ] 2/ Setting scene of compass/feature and CRACKS in our territory  - overview of digging deeper to see the issues are foundational and setting map/compass metaphor centre stage (aim: to set the reality of the problem but provide hope with actions/solutions)
- [ ] 3/ What are views and values aka the water we swim in (aim: introduce the sense of blindness we all hold and to invite in self-inquiry/reflection). Could include a link to the Politics of Being talks around blindspots specifically
- [ ] 4/ Overview of the colors / eras / periods - main focus on features of modernity, post-modernity and meta modernity (I would pick 1 or 2 key ways max i.e. Wilber's colors and xxx) (aim: x)
- [ ] 5/ Awareness and self-awareness (ep 4) (aim: to expand on the importance, address why (self-)awareness is needed, and where it can sit in the colors / period)
- [ ] 6/ A story / personally reflective piece (I really felt the story and comparison between us, grandparents, children etc worked well but could be something else)

### Other blogs to link in

Website to be reviewed and links added here accordingly 

## First Draft of Website Text

_Intro Blurb/Holding Text_
“[Inspiring Quote]”

We exist during a period of great awakening, a new dawn for a new civilization moving from modernity into what comes next. The Second Renaissance is the time between these worlds, the bridge that is taking us through this transition period and birthing a new paradigm.

On this page, you can learn more about the Second Renaissance and the paradigmatic shift it is cultivating through our courses, articles, blogs, books and interviews.

**Introducing the Second Renaissance**
We recommend you start here to learn more about the Second Renaissance, and what it means for us individually and collectively.
[add short of Rufus intro video]

**FAQs**
_What is the Second Renaissance?_ A transition period facilitating a shift from one cultural paradigm to another. 

_What are these worlds, or paradigms, that we are between?_ We could look at our current paradigm as one that is the result of an oscillation between modernism and postmodernism, ultimately leading us (in)to meta-modernism. However, it isn’t quite that simple.

_Why not?_ Ultimately, we want to navigate to a wiser, weller world. This is what Life Itself is here for, and likely a want, need or an inkling you feel too. A sense that something has to change in quite a big way, something integral. What this means then is that we need a map. We also need to be able to locate ourselves on the map. To do this, we need to identify key features that allow us to locate ourselves correctly (to know what paradigm are we in), which is not so easy to do for cultural paradigms, for a variety of reasons, related to:

- a mis-identification of the sources of the problems 
- and therefore, the solutions
- blindspots and invisibility - we can’t know what we don’t know, yet there is a need for us to know it
- paradigms continuously overlap so a rigid labeling is complicated 

_How can I know more?_ Join us in the Second Renaissance course.

**Second Renaissance 101 online course**
Coming soon. Register your interest here [create form to embed]

What we will cover: [to write later]

**Sign up to the Second Renaissance Book**
Add link already on the page

**Recommended Reading (Books)**
[categorize from foundational to advanced]

**Recommended Blog Posts (Life Itself specific)**
[to be sourced/written]

**Comment by laurenwigmore** [comment]
@rufuspollock are you able to review the above First Draft of Website Text please (above), alternatively it's in the [Google doc here](https://docs.google.com/document/d/1Re4SJkmHDrjwgcCNW-j0yPdsbN1kAUX94uNHGcH5W8U/edit?usp=sharing). I can make this live over the next few days then, if you're happy with it, and we can continue to populate accordingly.

**Comment by rufuspollock** [comment]
I will try to look. Most important thing is can we get videos up on password protected or private URLs on YouTube. That is no 1 thing.

**Comment by laurenwigmore** [comment]
> I will try to look. Most important thing is can we get videos up on password protected or private URLs on YouTube. That is no 1 thing.

It's all been set up on the Gdrive in a separate folder, within the main Second Renaissance folder, which is set up that anyone with the link can view. This was updated on #965 before Christmas, so it's good to go.

**Comment by rufuspollock** [comment]
@laurenwigmore i would flag that i don't think a bunch of these tasks are necessary yet (perhaps we want to distinguish a brainstorm section of potential tasks from things we definitely want to do) e.g. think these two are not required right now ...


- [ ]  Write 6 new blogs (see below) and categorize as 'second renaissance'
- [ ] #977

**Comment by laurenwigmore** [comment]
FIXED. Update to page made. No further actions (as detailed here) to be taken at present (#977 updated to someday maybe)
