### ISSUE TITLE
Find blogs already written suitable to be added to 2R landing page

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#977]
When I visit the Second Renaissance landing page, I want to see a list of blogs or other writings to read. 

## Acceptance
- [ ] Blog list created
- [ ] Blogs listed on web-page

## Task
- [ ] Review blogs - identify suitable ones
- [ ] Add into a list
- [ ] Add to Second Renaissance page

**Comment by rufuspollock** [comment]
@laurenwigmore imo i would put this kind of stuff into a 2R shaping issue inbox and then we can analyse and decide to action.

i.e. move this to the inbox and then delete this issue.

**Comment by laurenwigmore** [comment]
> @laurenwigmore imo i would put this kind of stuff into a 2R shaping issue inbox and then we can analyse and decide to action.
> 
> i.e. move this to the inbox and then delete this issue.

I've moved this across to #993 but I'm unable to delete (I don't seem to have that option).
