### ISSUE TITLE
Blog post with the update about strategy and  re DDS and conscious coliving efforts 

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#978]
Matthew  post up write-up from the Dec meeting introducing the strategy and work around deliberately developmental spaces and conscious coliving (extract from zoom and excalidraw etc) ​​https://link.excalidraw.com/l/9u8crB2ZmUo/9TcEeLtYj8A 

## Acceptance

- [ ] Post is up setting out this update on strategy and outputs on DDS and CoCo and how it all fits together

## Tasks

- [ ] Check zoom recording to see if there is a nice chunk just explaining strategy and work
- [ ] If there is we can extract it ...
- [ ] Also could check october 30th call in same way
- [ ] Extract key images
- [ ] Write some text (build on transcript from call?)
- [ ] Post it all up with a short intro to give context

**Comment by rufuspollock** [comment]
@matthewmccarthy11 can you clarify *which* dec meeting (perhaps link to recording) and if possible listen to the recording and extract exact "quote" of request for issue *plus* timestamp of where we covered the strategy stuff.

**Comment by laurenwigmore** [comment]
Hi @matthewmccarthy11 where are you at / did you get with this?

**Comment by BoazBF** [comment]
Hey @matthewmccarthy11 
I'm curious to know how this task is going for you - would you kindly update me?
Thank you!
B
