### ISSUE TITLE
Publish Bjorkman SCQH

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#98]
## Acceptance

* [x] SCQH finalized into publishable form
* [x] Published online in an appropriate location **Published on https://www.whatisemerging.com/articles/cultivating-and-emerging-paradigm (https://lifeitself.us/2022/02/01/cultivating-an-emerging-paradigm/)**

## Tasks

* [x] Finalize (esp hypothesis section) **DONE. See https://docs.google.com/document/d/18ilUmX8fDIcIhiGSrNBxiB0CkuKBx9TtguTu0CJgQIo/edit#**
  * [x] Framing
* [x] Review from TB **He's happy**
* [x] Identify publication location(s) **WhatIsEmerging + Life Itself**
* [x] Publish **Published on https://www.whatisemerging.com/articles/cultivating-and-emerging-paradigm (https://lifeitself.us/2022/02/01/cultivating-an-emerging-paradigm/)**

**Comment by theo-cox** [comment]
Update: awaiting final review by @rufuspollock and Anna at Emerge then we are good to go live

**Comment by rufuspollock** [comment]
@theo-cox has this got x-published to Life Itself now? If not, can we back-publish to same date asap. Then we can close this 😄

**Comment by theo-cox** [comment]
Yes - https://lifeitself.us/2022/02/01/cultivating-an-emerging-paradigm/

**Comment by theo-cox** [comment]
FIXED. We cross-posted: https://lifeitself.us/2022/02/01/cultivating-an-emerging-paradigm/
