### ISSUE TITLE
Find login for medium and add to password system

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#99]
Identify our medium profiles and how to login and log that in our password system.

## Acceptance

- [ ] Comms team (and others) can login to the account
- [ ] We have one and only one medium profile

## Tasks

- [ ] Identify existing associated accounts **✅2023-03-02 see list below**
- [ ] Get access to them
  - [x] @lifeitself **✅2023-03-02 and stored info in password system**
  - [ ] https://medium.com/art-earth-tech 
- [ ] Update email for access so that comms team have access
  - [x] @lifeitself **✅2023-03-02**
  - [ ] https://medium.com/art-earth-tech 

### Medium Profiles

- [x] https://medium.com/@lifeitself **✅2023-03-02 see password system and updated for comms team access **
- https://medium.com/art-earth-tech 
- https://medium.com/open-revolution - this is more for diginomics etc.

### Miss

- seems that now the `@lifeitself` url is "old" and now should use subdomains https://help.medium.com/hc/en-us/articles/115004746707

<img width="928" alt="image" src="https://user-images.githubusercontent.com/180658/222480312-a8914f0c-c9dd-4837-93bf-26712ff01ab1.png">

- oddly, the @lifeitself account also has another url called medium.com/for-life-itself

![image](https://user-images.githubusercontent.com/180658/222481560-e4eb6edb-0892-4684-b0cd-f9b613a6e636.png)

**Comment by nathenf** [comment]
@rufuspollock @theo-cox  resurfacing this old issue. I will most likely do a write-up on medium for the guide launch

**Comment by theo-cox** [comment]
Sounds like a plan @nathenf although I sadly have never been on the medium so can't help with the password

**Comment by nathenf** [comment]
@theo-cox it seems that you only need email to access. I used accounts@lifeitself.org and we have an account there which has 7 followers. However there is another one with 12 followers and I not sure what other email to try, perhaps an old AET one?

**Comment by rufuspollock** [comment]
@nathenf can you point to the two accounts and i can see if i can dig this out. We also had https://medium.com/open-revolution (which we could converge with this).

**Comment by nathenf** [comment]
@rufuspollock  I linked them above

**Comment by rufuspollock** [comment]
@nathenf 

- First, checking the https://medium.com/art-earth-tech page all the branding is now life itself ... indeed the email at the bottom of that page can be used for sign in. I've added this info to password system.
- **However** that sign up link seems to be for: https://medium.com/@lifeitself (which confusing is also seemingly https://medium.com/for-life-itself)
- Trying again: with a bit of guessing i believe that art-earth-tech is owned by an old Life Itself / Art Earth Tech-er email (petronella at AET). I'm trying to get that forwarded to me so we can do login.

At that point, we probably want to consolidate art-earth-tech and lifeitself.

**Comment by rufuspollock** [comment]
FIXED / WONTFIX. We never use medium and only ever posted 2 articles there so let's forget about this.
