### ISSUE TITLE
[shape] Presenting our Strategy v3 (in its current form)

### ISSUE THREAD

**Issue by elisapaka** [life-itself/community#991]
Shape something around the topic "Present Strategy v3 as it is right now" by the 22nd of January expending no more than 3-4d of person-time.

## Acceptance

- [x] Proposal for what we will ship in terms of v3 strategy right now given an appetite of 4d **🚧2024-01-09 - did first pass. see below** **💬2024-02-13 worked on this much more and have 60% done in https://github.com/life-itself/comms/blob/main/shaping/202401%20Presenting%20our%20Strategy%20v3%20in%20its%20current%20form.md** **✅2024-02-14 it is complete!**
- [x] Bonus: SCQ for what we have right now i.e. what material we have, what we could do with it etc **✅2024-02-14 kind of.**
- [x] Bonus: roughly ordered list or tree of hypothesis (or questions) **✅2024-02-14 we have an issue tree there**
- [x] Bonus: close all of the existing strategy related issues **✅2024-02-14 ❌ does not make sense yet**

## Tasks

- [x] What is our appetite **✅2024-01-09 4d**
- [x] What is our goal
  - [x] What's our problem? Why do we want to do this?
- [x] What materials do we have? (with brief sentence or two about what it is and an evaluation of where it fits into things) **See inbox below, and map of existing materials (more complete than inbox) here: https://link.excalidraw.com/l/9u8crB2ZmUo/3EkbCxN8qBi**

### Questions

- [x] "Present Strategy v3 as it is right now": does this mean finishing the v3 Strategy as it was originally envisioned? (i.e. we won't be making any updates / revisions)
  - [x] What does present mean? **✅2024-02-14 have a consolidated version**
  - [x] What does "Strategy v3 as it right now" mean? **🔑 As Rufus presented yesterday (and/or is on discussion XXX)** (🍴❌ As it was originally envisioned back in 2021/2022? ❌; Something else? ❌)

---

# Meetings

# 2024-02-14 - re shape strategy publishing

Present: Rufus, Elisa

Type: joint coworking to finish shaping

Aspiration: finished shaping **✅2024-02-14 we did it!**

# 2024-02-13

Present: Rufus, Elisa

Otter transcript: https://otter.ai/u/VK1y5DmOCYJevDyWlbYQmGAs8mc?view=transcript

Type of call: focused coworking.

Intentions: have a shaped proposal for what the write-up is going to be.

- [x] Confirm appetite of 4d **✅2024-02-14 keeping that for now**
- [x] Ship proposal for write-up of LI Strategy v3 **🚧2024-02-14 we have 60% of shape up proposal after 2h of 2 person work**
- [x] Elisa is clear on how to prioritise the strategy write-up vs Labs work **✅2024-02-14 discussed prioritising this for this week**

Agenda

- [x] Meditation
- [x] Check-in
- [x] Review proposal
  - [x] Problem statement (SCQH)
  - [x] Brainstorm of elements
- [x] Review next actions
- [x] Check-out

# 2024-01-09 - Re Strategy

Present: Rufus, Elisa

- [x] Review actions from yesterday
- [x] ⏭️ Next actions
  - [x] Move these meeting notes to a meetings section of new shaping issue 

# 2024-01-08 - Re Strategy

Present: Rufus, Elisa

Intention: clarify next steps on writing up strategy work

- [ ] identify what material we want to prepare for the strategy (ie. what is definition of done for this effort)
- [ ] what are next steps

Agenda

- [x] Elisa first tasks
  - [x] Find strategy "write-up" epic issue in community repo **✅2024-01-08 https://github.com/life-itself/community/issues/196**
  - [x] Brainstorm some questions to ask Rufus
    - [x] What is an A10? **A project definition and README**
    - [x] Would it be helpful to have a review of 2021-23 strategy, and how it went? **2021-2023 is the period we have worked on the v3 strategy**
- [x] Discuss what we would ship with a strong time constraint
- [x] Do a first pass by interviewing Rufus 
- [x] Next actions
  - [x] Write up walkthrough in the recording **✅2024-01-09  [Meeting notes from Rufus & Elisa sync on 2024-01-08](https://docs.google.com/document/d/1_vjo2Jy8I4_lEeXp7p2jkN4KknjbEfR5MmrK8Sw0-jk/edit)**

**Comment by rufuspollock** [comment]
FIXED. All done. Follow up issue for implementation to be created by @elisapaka 

20h: 2x6h today. 2x2h yday. Plus time in Jan.
