### ISSUE TITLE
[shape] Second Renaissance - get more people into the movement (Jan 2024)

### ISSUE THREAD

**Issue by laurenwigmore** [life-itself/community#993]
Output from the shaping discussion on 2024-01-10 related to the Second Renaissance (2R) and building the 2R movement.

## Acceptance
- [ ] Announcement post detailing the 2R is live - [Announcement draft document](https://docs.google.com/document/d/13EMXZaammAD4XUSq9M6FoA1ZFrA2ZVlrxd912D3O96I/edit#heading=h.fdnfqn1d1e5d)
- [ ] The pilot course rerun 

### Tasks
- [x] Double check prompts to go into breakout rooms are still on all the 6 videos ✔️ *all in place*
- [ ] re-run course (& get people together in a group to do the discussions)
- [ ] Write an announcement post on 2R
  - [ ] Share post with ecosystem (to establish the term within the ecosystem)
  - [ ] Share post more broadly

# Proposal
General point:
- 🔮 **Marketing and getting more people "through the door" would be a good goal for all areas ...** both for DDS and 2R
  - Focus on that over producing more material ...

# [shape] Second Renaissance
Shape an intial set of work around building the movement for a second renaissance

Appetite: 6 person weeks x 2 people (= total of 3 person months)

 #### Summary of elements
- We want a landing page 
  -  people then sign up to go through the course 
     - and then into a forum to leave questions/comments (to help us distill more) 
  - and then offer them something to do (an action - i.e. volunteer, sign this, lead this etc)

https://app.excalidraw.com/l/9u8crB2ZmUo/5aGG8uxFdPH

![image](https://hackmd.io/_uploads/SyfC5M3d6.png)

Questions / Notes

- Lauren: suggest start with problem rather than just what we want
- [ ] ❓ What are the problems we are addressing?
    - ❓ What is "it"?
  - In the general ecosystem there's lots of conversations about related topics but called by different names
    - ❓ What are examples of that? ie. examples of these conversations ...
      - Game B, metacrisis, Moloch (? you mean slate star codex renaming of collective action problems?? Yes..), metamodern politics/listening society...
  - ❓ Who are we pitching the pilot to?
  - ❓ What is the overall call to action ...
- What do second renaissancers do?
  - They can do quite a few different things (politicians, artists, tech entrepreneurs,...) - people are active
  - What they believe, what their views are
  - An awareness of actively contributing to a second renaissance
- What is the 2R, and what are the views and values that you have?
  - interest in culturlal evolution and inner development, actively pursuing this in their work
- What is the credo / things that would distinguish people as actively contributing to the 2R?
  - Understanding this civilisation and dominant system is finished AND they also have a specific view of the 'solution'/direction
  - They believe in a different version of human beings which can take us to a weller, wiser world
  - Adopts pragmatic utopianism perspective and ontological development to address the next step of major issues 
  - Us evolving over tech is the biggest contribution to solving the collective action problem that we face

### Situation

- What's happening "out there"
  - In the general "ecosystem" there's lots of conversations about related topics e.g. metacrisis, Game B etc but called by different names
    - We have chosen "Second Renaissance" as *the* name we will run with for this "time between worlds" and as a good way to consolidate/cover/side-step the naming issue (is it metacrisis, is it metamodern)
      - we have a bunch of reasons for that btw that are worth writing out ...
      - our favorite term for the destination if we have to name it is "awakening society"
  - Is there a standard gateway for entry into this area? (what is "this area"?)
  - There is no second renaissance "movement" as such
- What we have
  - We have a lot of available content that isn't being shared, or is dispersed on the website. i.e. [Ordinary people podcast](https://www.youtube.com/watch?v=g40xTkyKLtE&list=PLg0Untv2MuxWWuj_i5e-fhdI8rEJ7d_qZ), ... [Sylvie on Blindspots](https://youtu.be/kB1g-enOurI?si=OZOzQGLDYbjw4NcC), 
  - We have just completed a 6 episode pilot "Introduction to the Second Renaissance" course and are sharing with invited individuals
  - We have a research collective interested in the second renaissance ... and the research collective does not have an overarching agenda to be contributing to or to frame research efforts. There is no process for facilitating research collective meetings
  - We have an ecosystem mapping project now in its 4th year ...
  - We have done work on the polycrisis, the metacrisis etc e.g. ORA work for commonwewal, re metacrisis that is just second renaissance by another name ...
- What we want?
  - We want to share information related to the Second Renaissance, to feed the 2R Movement.
  - We want our efforts to all funnel into the 'North Star' of the 2R - which is to awaken society to create a weller, wiser world
- How we operate
  - We sometimes work in isolation within our own areas and therefore can lack the understanding internally of how the areas all feed into the 2R.
- Meta stuff
  - We have ideas about field-building and movement building though this thesis isn't shared amongst team about how field-building will happen
    - we have not done much formal research about this ...
  -
  - We aren't always clear about building the broader "field" and building "Life Itself"
    - Though we do discuss this in our theory of change outline

Complication

- We have lots of content related to the second renaissance but it is not (as) well presented (as we would like) i.e. not findable, not coherent, not distilled, not consistently branded, not shaped into an overall direction/thesis ... this is bad because ...
  - people coming to life itself or coming to this space new ... they are confused/overwhelmed
    - they don't know where to start
  - it is not compelling to people
    - which means people don't get engaged with 2R or Life Itself
      - which means the movement doesn't get built and Life Itself can't play the role in that that it could ...
- We have diverse activities e.g. research collective, podcasts etc that don't really cohere like they could (or don't appear to do so) which results in duplication, wasted effort etc
- Lack of simple, consistent naming, narrative and access points get in the way of building a movement. Put crudely "there aren't many second renaissancers out there with a clear distinctive identity, shared mission and active collaborations ..."
  - There is a tower of babel aspect
    - Aside: Some tension re a "broad tent" vs a "strong vanguard" 
- Beneath that, there maybe an issue that there is a lack of agreement/clarity both within Life Itself ... and the broader community about what e.g. what is the second renaissance, what is a "second renaissancer" etc i.e. questions to ...
  - How are we envisaging 'second renaissancers'? 
  - How much agreement should there be on narrative, problem statement, solutions etc is there in this group?
    - And how much is there currently?

Summary complication

- We don't know/agree on what movement we want to build and how ...

### Elements

- Announcement post about 2R
- Have more people do the 2R course

## Brainstorm of possible actions

TODO: Process 

Extracted from #976 

  - [ ] Embed a short video (the short on YouTube initially as it is a quick win and/or a cut from the course…)
  - [ ] And/or a sign up to the next course with R&S
  - [x] #977
  - [ ] Link in useful blogs to webpage from available content (see below)
    - [ ] Add in the extra category of 'second renaissance' to these blogs 
  - [ ] Decide who will write the new blogs
  - [ ] Write 6 new blogs (see below) and categorize as 'second renaissance'
- [ ] Write the 2R announcement 

When I visit the Second Renaissance landing page, I want to see a list of blogs or other writings to read. (copied across from old issue now deleted #977)

## Acceptance
- [ ] Blog list created
- [ ] Blogs listed on web-page

## Task
- [ ] Review blogs - identify suitable ones
- [ ] Add into a list
- [ ] Add to Second Renaissance page

**Comment by rufuspollock** [comment]
INVALID (OBSOLETE). This got superseded by 2R launch work with much of this material ultimately done or integrated. This material was from brainstorm in Jan 2024.
