### ISSUE TITLE
Conflict Resolution Blogs 

### ISSUE THREAD

**Issue by moonimmisch** [life-itself/community#997]
## Acceptance
- [x] 2 blog post topics decided and added below
- [x] 2 blog posts fully drafted and stored on the shared drive

## Tasks
- [x] Brainstorm topics for  blog posts  
- [x] Agree on the topicss and add them below
  - [x] Topic 1: Navigating Conflict in Coliving: A Deep Dive into Resolution Processes
  - [x] Topic 2: Navigating Conflict in Coliving: The Three Main Myths of Conflict
- [x] Draft each blog in the CC Blog Folder on the shared drive
- [x] Ensure all are checks are done ready to publish

```[tasklist]
### Tasks
- [x] Write drafts for all posts
- [ ] Post 1 draft
- [ ] Post 2 draft
- [ ] Have Lauren proof read posts
- [x] Find images to accompany posts
```

**Comment by moonimmisch** [comment]
@laurenwigmore just tagging you in case you need to check anything!

**Comment by moonimmisch** [comment]
Blog link: Navigating Conflict in Coliving: A Deep Dive into Resolution Processes
- https://docs.google.com/document/d/1u96Ztv7zPT9RLVKfplKMUnutqflyeN-rhlHaLRkrHjU/edit
- this post has had a significant re-write, to include an in depth exploration of 3 processes & a cta to join the course as you suggested @laurenwigmore also moved into CC Blog Folder

**Comment by moonimmisch** [comment]
Blog Link: Navigating Conflict in Coliving: The Three Main Myths of Conflict
- https://docs.google.com/document/d/14Sl7TAO4p4PNnWX3L35Y8LSqIxV390VTOzZQdBNaIzI/edit
- Blog now in the correct folder & ready to go up on the site! (YAY)

**Comment by laurenwigmore** [comment]
@moonimmisch I've checked the Resolution Processes one - this can be posted this week as a blog.

**Comment by laurenwigmore** [comment]
FIXED. And have moved the publishing of these across to #1016 
Lauren has checked and tweaked blogs so they are sign off as good to publish.
