### ISSUE TITLE
Recap for 2023 for Life Itself Research / Labs 

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/community#998]
Write a recap of highlights of 2023

## Acceptance

- [ ] Blog post with "year in review" for labs/research in 2023

## Tasks

- [ ] Make an initial list with notes and links to blogposts
- [ ] Quickly check with @catherinet1  (and maybe @rufuspollock)
- [ ] Post it!
- [ ] Announce it on relevant channels

**Comment by rufuspollock** [comment]
@matthewmccarthy11 are you up for taking this on?
